### ISSUE TITLE
nwxc_input is not in this build of NWChem

### ISSUE THREAD

**Issue by xiongyan21** [nwchemgit/nwchem#10]
Dear All
   QA test tddft_he fails using NWCHEM6.8 with the following information

    ------------------------------------------------------------------------
 nwxc_input is not in this build of NWChem                   0
 ------------------------------------------------------------------------
 ------------------------------------------------------------------------
  current input line : 
    36:   xc new autodiff hfexch cpbe96
 ------------------------------------------------------------------------
 ------------------------------------------------------------------------
 A feature requested has not yet been implemented

 ------------------------------------------------------------------------

Thanks!
Very Best Regards!

**Comment by xiongyan21** [comment]
On NWCHEM6.8 built on Ubuntu17.10, the test also fails
... 
 NWChem Input Module
                                -------------------


 ------------------------------------------------------------------------
 nwxc_input is not in this build of NWChem                   0
 ------------------------------------------------------------------------
 ------------------------------------------------------------------------
  current input line : 
    36:   xc new autodiff hfexch cpbe96
 ------------------------------------------------------------------------
 ------------------------------------------------------------------------
 A feature requested has not yet been implemented

 ------------------------------------------------------------------------

**Comment by hjjvandam** [comment]
Hi Xiongyan,

I suppose you are getting these error messages on some of the QA test cases. You may either ignore these messages or add the nwxc module to the NWCHEM_MODULES environment variable. The nwxc module provides a second implementation of the density functionals offering 3rd order derivatives and adding 2nd order derivatives for many of the of the functionals. However, if you are not planning to use TDDFT gradients and not planning to use Hessians or infra-red spectroscopy for less common functionals you can probably just ignore these errors.

To run the examples without using nwxc simply remove the “new autodiff” part of the line xc directive.

Best wishes,

    Huub

________________________________
Hubertus van Dam
Brookhaven National Laboratory
Mon, Fri: ISB 114 (Bldg 734)
Tue–Thu: CSI 2-165 (Bldg 725)
Tel: 631-344-6020
hvandam@bnl.gov<mailto:hvandam@bnl.gov>
www.bnl.gov/compsci/people/staff.php?q=139<https://www.bnl.gov/compsci/people/staff.php?q=139>
www.linkedin.com/in/HuubVanDam<http://www.linkedin.com/in/HuubVanDam>
orcid.org/0000-0002-0876-3294<http://www.orcid.org/0000-0002-0876-3294>

**Comment by xiongyan21** [comment]
Dear Dr. Dam
   I have already exported NWCHEM_MODULES="all python" during the compilation of NWCHEM6.8 on Ubuntu17.10.  What is anything else required to be exported?
  Thanks a lot !
  Very Best Regards!

**Comment by hjjvandam** [comment]
Xiongyan,
I thought the nwxc module was not included in “all”. However, I have just checked and it is included. So now I am a bit confused as to why you are getting this error. I’ll have a look to see if I can find anything.
Best wishes,
Huub

________________________________
Hubertus van Dam
Brookhaven National Laboratory
Mon, Fri: ISB 114 (Bldg 734)
Tue–Thu: CSI 2-165 (Bldg 725)
Tel: 631-344-6020
hvandam@bnl.gov<mailto:hvandam@bnl.gov>
www.bnl.gov/compsci/people/staff.php?q=139<https://www.bnl.gov/compsci/people/staff.php?q=139>
www.linkedin.com/in/HuubVanDam<http://www.linkedin.com/in/HuubVanDam>
orcid.org/0000-0002-0876-3294<http://www.orcid.org/0000-0002-0876-3294>

**Comment by hjjvandam** [comment]
Xiongyan,

I have had another look. In the file nwchem/src/config/make_nwchem_config you will see that if you specify NWCHEM_MODULES=“all” then the nwxc module is filtered out from KNOWN_MODULE_SUBDIRS. So the nwxc module is not compiled. To get the nwxc module included in your build please set

NWCHEM_MODULES=“all nwxc python”

And run

cd nwchem/src
make nwchem_config
make

That should fix the problem.

Best wishes,

    Huub


________________________________
Hubertus van Dam
Brookhaven National Laboratory
Mon, Fri: ISB 114 (Bldg 734)
Tue–Thu: CSI 2-165 (Bldg 725)
Tel: 631-344-6020
hvandam@bnl.gov<mailto:hvandam@bnl.gov>
www.bnl.gov/compsci/people/staff.php?q=139<https://www.bnl.gov/compsci/people/staff.php?q=139>
www.linkedin.com/in/HuubVanDam<http://www.linkedin.com/in/HuubVanDam>
orcid.org/0000-0002-0876-3294<http://www.orcid.org/0000-0002-0876-3294>

**Comment by xiongyan21** [comment]
Dear Dr. Dam 
   Thanks  a lot for your time and expertise.
   It works!
  ...
----------------------------------------------------------------------------
  Root   1 triplet ag             0.931684999 a.u.               25.3524 eV 
  ----------------------------------------------------------------------------
     Transition Moments                    Spin forbidden
     Oscillator Strength                   Spin forbidden

     Occ.    1  ag  ---  Virt.    2  ag      -0.99634
     Occ.    1  ag  ---  Virt.    3  ag      -0.08546

              Target root =      1
          Target symmetry = none
      Ground state energy =     -2.903216575659
        Excitation energy =      0.931684998838
     Excited state energy =     -1.971531576822

  stored tddft:energy   -1.9715315768215178

**Comment by edoapra** [comment]
NWXC module excluded from NWCHEM_MODULES=all in 6.8 release
a04a5b30f570311ed1151aa9e14156fab0e2a4fb
