### ISSUE TITLE
TCE gives different energies compared to non-TCE CC calculations

### ISSUE THREAD

**Issue by stephenyuwono** [nwchemgit/nwchem#101]
Dear developers,

I have been trying to compile NWChem 6.8.1 (with the default GA 5.6.5) on my school's cluster. I was having issues with my coupled-cluster results not matching my earlier compilation (NWChem 6.6 with GA 5.6), even though the RHF energies match. The difference is in about tens of microhartree, despite the fact that I set the convergence threshold to be 1e-9.

I decided to take a look at the 'official' compilation on the cluster, and I obtained the same results. I then tested the non-TCE CCSD module and I was able to obtain my earlier number. The non-TCE CCSD module also give the same energies (within the convergence threshold) to calculations using GAMESS.

I noticed that there is a difference in the GA version, so I tried recompiling NWChem 6.6 with GA 5.6.5, and I get the same error. I am not sure if the error is due to compiler, TCE, or GA.

Attached are two different runs using the cluster's default installation of NWChem: one with TCE and the other using the standalone CCSD module.

Could you please advise?

Thank you,
Stephen

[Mg2_ATdZ_CCSDpT_3.9.log](https://github.com/nwchemgit/nwchem/files/2890708/Mg2_ATdZ_CCSDpT_3.9.log)

[Mg2_ATdZ_CCSDpT-nontce_3.9.log](https://github.com/nwchemgit/nwchem/files/2890709/Mg2_ATdZ_CCSDpT-nontce_3.9.log)

**Comment by edoapra** [comment]
Stephen
What value of ARMCI_NETWORK have you used in your compilations?

**Comment by jeffhammond** [comment]
The discrepancy is due to D2h symmetry in TCE.  If you disable symmetry in TCE, the numbers agree.

I do not have a good explanation for this so I can't say whether this is a bug, a numerical artifact, or something physical in how the CCSD equations are solved for Mg2.

Your numbers:
```
Mg2_ATdZ_CCSDpT_3.9.log: Total energy =    -399.255177
Mg2_ATdZ_CCSDpT_3.9.log: CCSD total energy / hartree       =      -399.294490135777835
Mg2_ATdZ_CCSDpT_3.9.log: CCSD[T] total energy / hartree       =      -399.295706515864424
Mg2_ATdZ_CCSDpT_3.9.log: CCSD(T) total energy / hartree       =      -399.295698086226196
Mg2_ATdZ_CCSDpT-nontce_3.9.log: Total CCSD energy:           -399.294523519209633
Mg2_ATdZ_CCSDpT-nontce_3.9.log: Total SCS-CCSD energy:                -399.313247938617906
Mg2_ATdZ_CCSDpT-nontce_3.9.log: Total CCSD+T(CCSD) energy:           -399.295744565703728
Mg2_ATdZ_CCSDpT-nontce_3.9.log: Total CCSD(T) energy:                -399.295735890586229
```
My numbers, running with one process on my Mac laptop.  This is an Intel toolchain build without ScaLAPACK enabled.

Symmetry on:
```
Mg2_ATdZ_CCSDpT_3.9.out.1: Total energy =    -399.255177
Mg2_ATdZ_CCSDpT_3.9.out.1: CCSD total energy / hartree       =      -399.294491270128276
Mg2_ATdZ_CCSDpT_3.9.out.1: CCSD[T] total energy / hartree       =      -399.295707855792045
Mg2_ATdZ_CCSDpT_3.9.out.1: CCSD(T) total energy / hartree       =      -399.295699434150265
```

Symmetry off:
```
Mg2_ATdZ_CCSDpT_3.9.out.3: Total energy =    -399.255177
Mg2_ATdZ_CCSDpT_3.9.out.3: CCSD total energy / hartree       =      -399.294523519140625
Mg2_ATdZ_CCSDpT_3.9.out.3: CCSD[T] total energy / hartree       =      -399.295744565634266
Mg2_ATdZ_CCSDpT_3.9.out.3: CCSD(T) total energy / hartree       =      -399.295735890516653
```

Non-TCE data, with symmetry on and off (which only affects the SCF because the CCSD(T) code is not symmetry-aware):
```
Mg2_ATdZ_CCSDpT-nontce_3.9.out.1: Total CCSD energy:           -399.294523519145457
Mg2_ATdZ_CCSDpT-nontce_3.9.out.1: Total SCS-CCSD energy:                -399.313247938554582
Mg2_ATdZ_CCSDpT-nontce_3.9.out.1: Total CCSD+T(CCSD) energy:           -399.295744565639609
Mg2_ATdZ_CCSDpT-nontce_3.9.out.1: Total CCSD(T) energy:                -399.295735890522053
Mg2_ATdZ_CCSDpT-nontce_3.9.out.2: Total CCSD energy:           -399.294523519204006
Mg2_ATdZ_CCSDpT-nontce_3.9.out.2: Total SCS-CCSD energy:                -399.313247938629559
Mg2_ATdZ_CCSDpT-nontce_3.9.out.2: Total CCSD+T(CCSD) energy:           -399.295744565699692
Mg2_ATdZ_CCSDpT-nontce_3.9.out.2: Total CCSD(T) energy:                -399.295735890582080
```

**Comment by stephenyuwono** [comment]
Hi Edoardo,

I used MPI-PR to build it. I attach my build script for your convenience.
[build.txt](https://github.com/nwchemgit/nwchem/files/2895504/build.txt)
Your advice is much appreciated on the build script. I am definitely still learning much on doing it properly.


Hi Jeff,

I tried turning off symmetry, but I still obtained the same results as with symmetry. Here is an output from my C1 run.
[Mg2_ATdZ_CCSDpT_3.9-nosym.log](https://github.com/nwchemgit/nwchem/files/2895516/Mg2_ATdZ_CCSDpT_3.9-nosym.log)

I can definitely say that I did not experience this issue before. I completed a project where I utilized symmetry with NWChem and I could reproduce CCSD, CCSDT, and CCSDTQ (= valence full CI for Mg2) energies from other software. Even active-space triples match what we had with another code. I attach example outputs from GAMESS and NWChem (old build) where the numbers match below.
[Mg2_fci_ATdZ_3.9.log](https://github.com/nwchemgit/nwchem/files/2895581/Mg2_fci_ATdZ_3.9.log)
[Mg2_ATdZ_CCSDTQ_3.9.log - OLD BUILD](https://github.com/nwchemgit/nwchem/files/2895582/Mg2_ATdZ_CCSDTQ_3.9.log)
[Mg2_ATdZ_CCSDTQ_3.9.log](https://github.com/nwchemgit/nwchem/files/2895586/Mg2_ATdZ_CCSDTQ_3.9.log)

From GAMESS:
CI EIGENSTATE   1 TOTAL ENERGY= -399.2961476639
From NWChem (old build):
CCSDTQ total energy / hartree = -399.296147663944396
From NWChem (current build):
CCSDTQ total energy / hartree = -399.296054855805153

So I think I might have messed up either the parallel/GA part. RHF energies seem fine, still.

Thank you again for your help.

**Comment by edoapra** [comment]
> Hi Edoardo,
> 
> I used MPI-PR to build it. I attach my build script for your convenience.
> [build.txt](https://github.com/nwchemgit/nwchem/files/2895504/build.txt)
> Your advice is much appreciated on the build script. I am definitely still learning much on doing it properly.
Are you really sure that the output named Mg2_ATdZ_CCSDpT_3.9.log was generated with a NWChem binary built setting ARMCI_NETWORK=MPI-PR?
I have spotted a warning message in that specific output that should be generated when ARMCI_NETWORK=MPI-PR
```
1: WARNING:armci_set_mem_offset: offset changed 192536911872 to 192540323840
```
It is more likely that the NWChem executable used for this run was compiled setting ARMCI_NETWORK=OPENIB (or ARMCI_NETWORK=SOCKETS).
Could you verify this hypotesis?

**Comment by stephenyuwono** [comment]
> > Hi Edoardo,
> > I used MPI-PR to build it. I attach my build script for your convenience.
> > [build.txt](https://github.com/nwchemgit/nwchem/files/2895504/build.txt)
> > Your advice is much appreciated on the build script. I am definitely still learning much on doing it properly.
> 
> Are you really sure that the output named Mg2_ATdZ_CCSDpT_3.9.log was generated with a NWChem binary built setting ARMCI_NETWORK=MPI-PR?
> I have spotted a warning message in that specific output that should NOT have been generated when ARMCI_NETWORK=MPI-PR
> 
> ```
> 1: WARNING:armci_set_mem_offset: offset changed 192536911872 to 192540323840
> ```
> It is more likely that the NWChem executable used for this run was compiled setting ARMCI_NETWORK=OPENIB (or ARMCI_NETWORK=SOCKETS).
> Could you verify this hypotesis?

I checked the build for that (default build in the cluster) and ARMCI_NETWORK is indeed set to OPENIB - sorry for the confusion there.

I did have the same problem when I was doing it with my own build which uses that script I sent earlier. I am trying to recompile it with that setting and get the corresponding output.

Hope this helps with the debugging.

**Comment by edoapra** [comment]
I would suggest you to use the 6.8.1 release, since it contains bug fixes

**Comment by xiongyan21** [comment]
It seems GAMESS cannot do CCSDT, let alone CCSDTQ.

**Comment by jeffhammond** [comment]
Very few codes support CCSDT and CCSDTQ. You can try CFOUR for CCSDT and CTF for CCSDT and CCSDTQ.  CFOUR’s NCC module has CCSDTQ.

**Comment by stephenyuwono** [comment]
> I would suggest you to use the 6.8.1 release, since it contains bug fixes

Hi Edoardo,

I finished running the test and here is the resulting log files with and without TCE. 
Please let me know if there is more that I can provide.

[Mg2_ATdZ_CCSDpT_3.9.log](https://github.com/nwchemgit/nwchem/files/2898130/Mg2_ATdZ_CCSDpT_3.9.log)
[Mg2_ATdZ_CCSDpT-nontce_3.9.log](https://github.com/nwchemgit/nwchem/files/2898131/Mg2_ATdZ_CCSDpT-nontce_3.9.log)
[build.txt](https://github.com/nwchemgit/nwchem/files/2898132/build.txt)

>I don't read your log files.
>It seems GAMESS cannot do CCSDT, let alone CCSDTQ, but may provide various faster and accurate approximations to CCSDT, etc., perhaps very useful.

Hi Xiong Yan,

The most recent version of GAMESS has an optional active-space CCSDt code built in (keyword: CCSD3A). By specifying all orbitals to be active, one obtains back the full CCSDT method. I also checked my calculations against this number and they still differ.

For the system that I was testing, the valence calculation correlates only four electrons, which means that I can do full CI and that would be equivalent to CCSDTQ. Again, I also did it with GAMESS and checked it.

**Comment by xiongyan21** [comment]
I introduced cc(t,3) in GAMESS 2018R2 on Aug. 8, 2018 and compared it using GAMESS 2018R3 with CCSDT in NWCHEM and that in an article for CH on Jan.16, 2019. Although The complete active space CCSDt might be a theoretical limit in GAMESS now, the existing old and new approximations of CCSDT might provide accurate results faster.

**Comment by stephenyuwono** [comment]
> The discrepancy is due to D2h symmetry in TCE. If you disable symmetry in TCE, the numbers agree.
> 
> I do not have a good explanation for this so I can't say whether this is a bug, a numerical artifact, or something physical in how the CCSD equations are solved for Mg2.

Hi Jeff,

I am not sure if symmetry is indeed the problem, since I still cannot reproduce my old number with the symmetry off. Also, I did not have this problem with the old compilation - I get the same energy with other codes when symmetry is turned on.

I am planning to use NWChem to calculate a much bigger system (an organic molecule), which cannot utilize symmetry anyway, at the CCSD/EOMCCSD level. Nevertheless, I want to make sure the numbers I get is right before proceeding on such costly calculation.

I will keep trying on my side and I will keep you guys posted if I find anything new. Thanks again for your prompt replies.

**Comment by edoapra** [comment]
> > I would suggest you to use the 6.8.1 release, since it contains bug fixes
> 
> Hi Edoardo,
> 
> I finished running the test and here is the resulting log files with and without TCE.
> Please let me know if there is more that I can provide.
> 
> [Mg2_ATdZ_CCSDpT_3.9.log](https://github.com/nwchemgit/nwchem/files/2898130/Mg2_ATdZ_CCSDpT_3.9.log)
> [Mg2_ATdZ_CCSDpT-nontce_3.9.log](https://github.com/nwchemgit/nwchem/files/2898131/Mg2_ATdZ_CCSDpT-nontce_3.9.log)
> [build.txt](https://github.com/nwchemgit/nwchem/files/2898132/build.txt)
> 
> > I don't read your log files.
> > It seems GAMESS cannot do CCSDT, let alone CCSDTQ, but may provide various faster and accurate approximations to CCSDT, etc., perhaps very useful.
> 
> Hi Xiong Yan,
> 
> The most recent version of GAMESS has an optional active-space CCSDt code built in (keyword: CCSD3A). By specifying all orbitals to be active, one obtains back the full CCSDT method. I also checked my calculations against this number and they still differ.
> 
> For the system that I was testing, the valence calculation correlates only four electrons, which means that I can do full CI and that would be equivalent to CCSDTQ. Again, I also did it with GAMESS and checked it.

Stephen
I have tried to reproduce your failure, but I was not able to do it.
I have spotted the following setting in your build environment
```
export FFLAGS="-i8 -I${MKLROOT}/include/intel64/ilp64 -I${MKLROOT}/include"
```
This is not a good choice, since it might replace definitions set in the makefile structure.
Could you try to unset it and  recompile from scratch?

**Comment by stephenyuwono** [comment]
> > > I would suggest you to use the 6.8.1 release, since it contains bug fixes
> > 
> > 
> > Hi Edoardo,
> > I finished running the test and here is the resulting log files with and without TCE.
> > Please let me know if there is more that I can provide.
> > [Mg2_ATdZ_CCSDpT_3.9.log](https://github.com/nwchemgit/nwchem/files/2898130/Mg2_ATdZ_CCSDpT_3.9.log)
> > [Mg2_ATdZ_CCSDpT-nontce_3.9.log](https://github.com/nwchemgit/nwchem/files/2898131/Mg2_ATdZ_CCSDpT-nontce_3.9.log)
> > [build.txt](https://github.com/nwchemgit/nwchem/files/2898132/build.txt)
> > > I don't read your log files.
> > > It seems GAMESS cannot do CCSDT, let alone CCSDTQ, but may provide various faster and accurate approximations to CCSDT, etc., perhaps very useful.
> > 
> > 
> > Hi Xiong Yan,
> > The most recent version of GAMESS has an optional active-space CCSDt code built in (keyword: CCSD3A). By specifying all orbitals to be active, one obtains back the full CCSDT method. I also checked my calculations against this number and they still differ.
> > For the system that I was testing, the valence calculation correlates only four electrons, which means that I can do full CI and that would be equivalent to CCSDTQ. Again, I also did it with GAMESS and checked it.
> 
> Stephen
> I have tried to reproduce your failure, but I was not able to do it.
> I have spotted the following setting in your build environment
> 
> ```
> export FFLAGS="-i8 -I${MKLROOT}/include/intel64/ilp64 -I${MKLROOT}/include"
> ```
> This is not a good choice, since it might replace definitions set in the makefile structure.
> Could you try to unset it and recompile from scratch?

Hi Edoardo,

I tried doing your suggestion, but I still have the same difference. I still think there is something with the parallel compilation part, so I will keep working on my end and I will keep you updated of any findings. Thank you very much for your help.

**Comment by edoapra** [comment]
@stephenyuwono This is likely to be affected by the same Intel compiler bug reported in https://github.com/nwchemgit/nwchem/issues/117 (at least, this what I have observed myself)
Please update your NWChem source with recent updates.

**Comment by edoapra** [comment]
Yet another manifestation of this same bug
http://www.nwchem-sw.org/index.php/Special:AWCforum/st/id3445

**Comment by srhhh** [comment]
Thank you @edoapra. Adding 2eorb did fix that bug. According to another comment from @jeffhammond, should I switch the default to 2eorb whenever RHF/ROHF are used whether TCE module is used?

I will also try to compile the most recent source and see if the bug still exists.

**Comment by jeffhammond** [comment]
> to another comment from @jeffhammond, should I switch the default to 2eorb whenever RHF/ROHF are used whether TCE module is used?

Yes, at least for CCSD-based methods. You have to use spin orbitals for CCSDT, for example. CCSDT+2eord should work but we broke it a while ago and we it hasn’t been a priority to fix, because 2eorb doesn’t make a big difference if one stores the triples amplitudes.

**Comment by stephenyuwono** [comment]
@edoapra @jeffhammond I have re-runned several tests with the newest source code and it works fine now. Thank you for solving this issue!
