### ISSUE TITLE
Dead URL in contrib/getfiles.nwchem for dftd3.tgz

### ISSUE THREAD

**Issue by yurivict** [nwchemgit/nwchem#1011]
[here](https://github.com/nwchemgit/nwchem/blob/master/contrib/getfiles.nwchem#L6C6-L6C83)

Why can't this repository can't be used: https://github.com/loriab/dftd3 ?
Or why this repository can't be used: https://github.com/loriab/dftd4 ?

**Comment by edoapra** [comment]
fixed in master and hotfix/release-7-2-0
