### ISSUE TITLE
0:autoz bonds: too many internals:Received an Error in Communication

### ISSUE THREAD

**Issue by divyavani01** [nwchemgit/nwchem#1022]
**MPI_ABORT was invoked on rank 0 in communicator MPI COMMUNICATOR 3 DUP FROM 0
with errorcode -1.**
**ERROR:**
   MPI_ABORT was invoked on rank 0 in communicator MPI COMMUNICATOR 3 DUP FROM 0
  with errorcode -1.
  NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
  You may or may not see output from other processes, depending on exactly when Open MPI kills them.
0:autoz bonds: too many internals:Received an Error in Communication

I am encountering an error while running a QM/MM optimization using NWChem. The following error is displayed:
i am pereparing my input using below python script and got the attached input file..can some one please help me out saying how an i fix  this and make it work and perform QM/MM optimization.
[protein_qm_inp_nwchem.txt](https://github.com/user-attachments/files/17253754/protein_qm_inp_nwchem.txt)
[nw_inp_prep.txt](https://github.com/user-attachments/files/17253755/nw_inp_prep.txt)

**Comment by edoapra** [comment]
Please read the paragraph below of FAQ section of the NWChem website to deal with this issue
https://nwchemgit.github.io/FAQ.html#input-problem-autoz-fails-to-generate-valid-internal-coordinates

If this is the information there is not enough, a better place to start a discussion is the NWChem users' forum  
https://groups.google.com/g/nwchem-forum/
