### ISSUE TITLE
Slow build

### ISSUE THREAD

**Issue by haampie** [nwchemgit/nwchem#1055]
**Describe the bug**
When building nwchem on a large machine, the load average during the build is about 4, which is not very impressive.

I haven't checked the build system, but it looks like directories are entered sequentially instead of in parallel, and that running sub-make is rather slow, so I expect there's a lot of overhead in executing a small makefiles for each subdir:

```
zgrep 'Entering directory' build-log.txt.gz | wc -l
1028
```

**To Reproduce**

`spack install nwchem`

**Expected behavior**
I would expect more parallelism from the build.

**Comment by jeffhammond** [comment]
NWChem has plenty of build parallelism.  I use `make -j$N` for large `N` all the time and it is useful, albeit not perfect.  It would be much better if we got rid of the recursive make pattern but that is not practical.  There is a lot of build customization happening inside of some directories, which is hard to replicate in a non-recursive make pattern.

**Comment by jeffhammond** [comment]
If you know how to parallelize over the directories, I can try to do that, but it has to be done carefully, because it's going to fork-bomb the system in `tce`, for example.

**Comment by haampie** [comment]
Yeah, there is enough build parallelism, but it looks like the makefiles are a sequential bottleneck.

Dunno how reliable this computation is, but if I do

```
$ cd src/pstat

$ time make  # measure executing the makefile without actually building anything
makefile error for lapack definition
please set LAPACK_LIB

../config/makefile.h:3419: *** .  Stop.

real	0m0.224s
user	0m0.069s
sys	0m0.181s

$ strace -fc make
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 76.92    0.503655        2722       185        46 wait4
  6.14    0.040211          32      1233      1045 execve
```

it looks like every sub-make spends ~220ms on executing the `../config/makefile.h` include (which spawns many sub-processes apparently). Multiply that with the `1028` "entering directory" I see in the logs, and you get 3:45 minutes spent on sequentially executing Makefile.

I guess moving a few of the dynamic bits of makefile.h into the configure script so that you can execute those subprocess once instead of a thousand times is better.

**Comment by jeffhammond** [comment]
Everything you say is true, and if NWChem had more than one paid developer working on it, it would be wise for someone to invest time on redesigning it.

When I started working on NWChem, it took 4 hours to build on an Itanium 2 workstation using the Intel compilers.  It's over a million lines of code (4MLOC the way I was configuring it then).  That the build takes less than 5 minutes nowadays is nothing short of a miracle to me.  Yes, it could be faster, but there is no behavior involving NWChem where the build time is the bottleneck.  Even as a rapid-fire developer, the incremental rebuilds are trivial, because they touch only one subdirectory.

I understand this is annoying for Spack's CI/CD system, but that's not really the use case for NWChem.  If you want to optimize this use case, perhaps Spack should use `NWCHEM_MODULES=smallqm` when testing, since that exercises most of the things that are changing in CI/CD.

**Comment by haampie** [comment]
OK, who knows someone will find this issue once and do something about it ;p

**Comment by haampie** [comment]
The upside of makefile/ninja file generators like cmake is that the dynamic bits are forced into the generator. I like this quote from https://neugierig.org/software/blog/2020/05/ninja.html:

> Ninja's closest relative is Make, which attempts to encompass all of this programmer-facing functionality (with globbing, variable expansions, substringing, functions, etc.) that resulted in a programming language that was too weak to express all the needed features (witness autotools) but still strong enough to let people write slow Makefiles.

**Comment by jeffhammond** [comment]
I am well aware of the merits if ninja.  Using it is literally the only thing good about CMake.

What very few people understand is that makefile.h encodes a tremendous amount of detail about broken compilers and other system oddities that NWChem has had to work around, and continues to need to work around, which will almost certainly be lost if anyone but one of the very few people who have spend a decade or more maintaining NWChem tries to rewrite the build system from scratch.

It would be possible to hoist a large portion of makefile.h out into a configure-like script that generates the results for makefile.h to cache but again, nobody is getting paid to do this and I am skeptical that anyone is going to donate the effort for it.
