### ISSUE TITLE
QA cases fail: verifying output ... failed

### ISSUE THREAD

**Issue by yurivict** [nwchemgit/nwchem#106]
This command: ```NWCHEM_TOP=/usr/local/ NWCHEM_TARGET= ./doqmtests.mpi``` fails:
```
 Running tests/h2o-camb3lyp-pol/h2o-camb3lyp-pol 
 
     cleaning scratch
     copying input and verified output files
     running nwchem (/usr/local//bin//nwchem)  with 1 processors 
 
     verifying output ... failed
 
Failed

 
 Running tests/h2o-cambeckehh/h2o-cambeckehh 
 
     cleaning scratch
     copying input and verified output files
     running nwchem (/usr/local//bin//nwchem)  with 1 processors 
 
     verifying output ... failed
 
Failed
```

Otherwise, nwchem works okay for individual other tasks.

master-oct22_2018-153-gb959e5ee0

**Comment by edoapra** [comment]
@yurivict Could you provide the following output files?
$NWCHEM_TOP/QA/testoutputs/h2o-camb3lyp-pol.out
$NWCHEM_TOP/QA/testoutputs/h2o-cambeckehh.out

**Comment by edoapra** [comment]
Commits  https://github.com/nwchemgit/nwchem/commit/f0a18b78d312041deb4ea18746b6facfc49e6440 through  c6db09ce9ddcc0a39d99065f88403afec599247d are (most likely) related to this issue

**Comment by yurivict** [comment]
Thank you.
