### ISSUE TITLE
QA test metagga_li4h4_0_m05_0.nw produces slightly different results using NWCHEM6.8 on Ubuntu18.04

### ISSUE THREAD

**Issue by xiongyan21** [nwchemgit/nwchem#107]
QA test metagga_li4h4_0_m05_0.nw produces slightly different results using NWCHEM6.8 on Ubuntu18.04.
The log file is attached.
[meta.log](https://github.com/nwchemgit/nwchem/files/3050104/meta.log)

**Comment by xiongyan21** [comment]
The log file of the input without direct is also attached.
[meta1.log](https://github.com/nwchemgit/nwchem/files/3050120/meta1.log)

**Comment by edoapra** [comment]
I see no reason to file this as a bug.

cd $NWCHEM_TOP/QA/testoutputs
perl $NWCHEM_TOP/QA/nwparse.pl meta1.log
diff metagga_li4h4_0_m05_0.out.nwparse meta.log.nwparse
1062c1062
< Frequency       -10         -1          6         43         43         43 
---
> Frequency       -11          1          6         43         43         43
