### ISSUE TITLE
QA tests metagga_li4h4_1_tpss_tpss.nw and metagga_li4h4_1_tpss_0.nw fail.

### ISSUE THREAD

**Issue by xiongyan21** [nwchemgit/nwchem#108]
QA test metagga_li4h4_1_tpss_tpss.nw fails.
The log files are attached.
[metatpss.log](https://github.com/nwchemgit/nwchem/files/3050173/metatpss.log)

with the following in the terminal
4:geom_binvr: ysyev failed:Received an Error in Communication
3:geom_binvr: ysyev failed:Received an Error in Communication
[hp-HP-Z2-Mini-G3-Workstation:02884] 1 more process has sent help message help-mpi-api.txt / mpi-abort
[hp-HP-Z2-Mini-G3-Workstation:02884] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages

[metatpss1.log](https://github.com/nwchemgit/nwchem/files/3050171/metatpss1.log)
2:geom_binvr: ysyev failed:Received an Error in Communication

It is not strange that some functional fail for some molecules, but the original QA tests produce results, thus, I do not know the reasons here.
Perhaps these tests are old and need to be reexamined.

**Comment by xiongyan21** [comment]
It is not strange that some functional fail for some molecules, but the original QA tests produce results, thus, I do not know the reasons here.
Perhaps these tests are old and need to be reexamined.

**Comment by edoapra** [comment]
@xiongyan21  I can see two different/separate problems in your output files.
metatpss.log is the result of a wrong NWChem installation

metapss1.log is the result of a bug. I am working on a fix

**Comment by xiongyan21** [comment]
I think there is no intsallation here. The last output is caused I do not save the later information.
I recalculate it and let it keep the error information.
The log file is attached.
Very Best Regards!
[metatpasserror.log](https://github.com/nwchemgit/nwchem/files/3057318/metatpasserror.log)

**Comment by edoapra** [comment]
> I think there is no wrong intsallation here. The previous output is caused by I do not save the later information.
> I recalculate it and let it keep the error information.
> The log file is attached.
> Very Best Regards!
> [metatpasserror.log](https://github.com/nwchemgit/nwchem/files/3057318/metatpasserror.log)

I see. Yes, the same numerical bug was causing the yevr problem. Yesterday's commit should address both problems

**Comment by jcpkato** [comment]
Hi edoarpa.
This is my output. I changed your correlation vertion but it didnt fixed my problem.
Hope you can help me.
Thanks for your time.
[tpss.txt](https://github.com/nwchemgit/nwchem/files/3065766/tpss.txt)

**Comment by edoapra** [comment]
@jcpkato could you please send me the input file?

**Comment by jcpkato** [comment]
This is my input.


[tpss.input.txt](https://github.com/nwchemgit/nwchem/files/3065782/tpss.input.txt)

**Comment by jcpkato** [comment]
Hi again.
I tried your last correlation, but the problem stills appearing.
This is the new output from the same input.

[tpss.txt](https://github.com/nwchemgit/nwchem/files/3066245/tpss.txt)

**Comment by edoapra** [comment]
@jcpkato 
Is this the same input or a new one?
The last commit fixes the problem for me

**Comment by jcpkato** [comment]
It is with the same input.

**Comment by edoapra** [comment]
@jcpkato 
Are you sure that you have been using the latest master branch? The header of your output does not confirm that.
Please recompile the code by executing
cd $NWCHEM_TOP/src/util
make clean;make
cd  ../nwdft/xc
make clean;make
cd ../..
make link

**Comment by jcpkato** [comment]
Hi edoapra.
Sorry for answering, but i have some health issues.
Im using 6.8 version and just rename it as 6.8.1. Or am I do not understanding you?
I tried your suggestion and in principle compiled but the problem persist, it seems that in some steps the optimizations beggins properly but then again it begin with the NaN issues.

Thanks again for your time

[tpss.txt](https://github.com/nwchemgit/nwchem/files/3070786/tpss.txt)

**Comment by edoapra** [comment]
@jcpkato the changes are all in the master branch and not in 6.8

**Comment by jcpkato** [comment]
Ok, thank you.
Ill download it and ill try your suggestions. Thanks for your time.

**Comment by jcpkato** [comment]
Thank you edoapra... your suggestion worked perfectly.
Thanks for your time.
