### ISSUE TITLE
QA test metagga_li4h4_1_m08hx_0.nw(mult 2)  needs a much longer  time to optimize  and gets different frequencies.

### ISSUE THREAD

**Issue by xiongyan21** [nwchemgit/nwchem#109]
QA test metagga_li4h4_1_m08hx_0.nw(mult 2) can finish, but needs a much longer

time to optimize  and gets different frequencies.'
The log file is attached.
[m08.log](https://github.com/nwchemgit/nwchem/files/3050202/m08.log)

Perhaps the formula of the functional or the code has been modified.

**Comment by xiongyan21** [comment]
The run with no direct gets results which perhaps can be called similar those with it, but different from those in QA test.
The log file is attached.
[m08nodirect.log](https://github.com/nwchemgit/nwchem/files/3057436/m08nodirect.log)

**Comment by edoapra** [comment]
Input and output files were updated
