### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by baerbock** [nwchemgit/nwchem#112]
During compilation nwchem frequently looks for `/usr/lib/python3.6/config*/libpython3.6.so`, which is not available anymore (Python 3.7).

How to make this no longer hardcoded?

**Comment by edoapra** [comment]
Did you set the env. variable PYTHONVERSION in your compilation?

**Comment by baerbock** [comment]
Thanks, this solves my issue. But there is another one: My `/usr/include/mpif-config.h` exists, but can't be found
```
Compiling Parallel-mpi.F...
/usr/include/mpif.h:56: Error: Can't open included file 'mpif-config.h'
make[4]: *** [../../../config/makefile.h:2998: ~/nwchem-git/src/nwchem/lib/LINUX64/libnwpwlib.a(Parallel-mpi.o)] Error 1
```

**Comment by edoapra** [comment]
Please report the output of the following commands

mpif90 -show
env | grep MPI
cd $NWCHEM_TOP/src/nwpwlib/Parallel ; make V=1

I am assuming you are using openmpi, am I right?

**Comment by edoapra** [comment]
Closed since not further feedback has been received
