### ISSUE TITLE
SCAN functional gives inaccurate interaction energies for benzene dimer

### ISSUE THREAD

**Issue by edoapra** [nwchemgit/nwchem#114]
The attached input files for the benzene dimer (using geometries from the S66x8 database) give an interaction energy inconsistent with what contained in the supporting information of the following articles

https://dx.doi.org/10.1103/PhysRevLett.115.036402
https://dx.doi.org/10.1063/1.4940734

[bdr1_scan.nw.txt](https://github.com/nwchemgit/nwchem/files/3143585/bdr1_scan.nw.txt)
[bdr2_scan.nw.txt](https://github.com/nwchemgit/nwchem/files/3143586/bdr2_scan.nw.txt)

E_bdr1=-463.914008
E_bdr2=-463.961191

This gives an interaction energy of 627.51*(-463.914008+463.961191)=29.6 Kcal/mol, while 
https://aip.scitation.org/doi/suppl/10.1063/1.4940734/suppl_file/scan6s.pdf
reports a value of -1.34kcal/mol

**Comment by dmejiar** [comment]
Edo, I think the issue is related to grid sensitivity and basis set superposition error, and not to a bug inside the code.

Using a fine grid, with the same def2-svp basis set, yields an interaction energy of 627.51*(-463.94091+463.94149)=0.36 kcal/mol, and a bsse corrected interaction energy of 627.51*(-463.93863+463.93669)=-1.22 kcal/mol.

The remaining difference to the reported value in the JCP paper might be accounted for by the difference between the basis sets. Note also that they did use BSSE corrections for the weakly bound systems.

**Comment by dmejiar** [comment]
I mixed results with different grid sizes in my previous comment. However, the conclusion remains. Here is a summary with the attached input and output files.

**No BSSE corrections**

| geom| medium | fine | xfine |
| ---     | ---          | ---   | ---     |
| bdr1  | -463.914010 | -463.935604 | -463.940914 |
| bdr2  | -463.961192 | -463.941493 | -463.935964 |
| Inter. (kcal/mol) | 29.61 | 3.70 | -3.11 |

**With BSSE corrections**

| geom| medium | fine | xfine |
| ---     | ---          | ---   | ---     |
| bdr1  | -463.922532 | -463.938166 | -463.938636 |
| bdr2  | -463.921122 | -463.936694 | -463.937217 |
| Inter. (kcal/mol) | -0.88 | -0.92 | -0.89 |


[bdr1_scan_default.log](https://github.com/nwchemgit/nwchem/files/3149622/bdr1_scan_default.log)
[bdr1_scan_fine.log](https://github.com/nwchemgit/nwchem/files/3149624/bdr1_scan_fine.log)
[bdr1_scan_xfine.log](https://github.com/nwchemgit/nwchem/files/3149625/bdr1_scan_xfine.log)
[bdr2_scan_default.log](https://github.com/nwchemgit/nwchem/files/3149626/bdr2_scan_default.log)
[bdr2_scan_fine.log](https://github.com/nwchemgit/nwchem/files/3149627/bdr2_scan_fine.log)
[bdr2_scan_xfine.log](https://github.com/nwchemgit/nwchem/files/3149628/bdr2_scan_xfine.log)

**Comment by edoapra** [comment]
@dmejiar thank you very much for the valuable feedback.
We probably need to add some text in the week about this and force the code to adapt xfine grid when metaGGAs are used
