### ISSUE TITLE
Can NWCHEM search MECP like GAMESS

### ISSUE THREAD

**Issue by xiongyan21** [nwchemgit/nwchem#115]
Can NWCHEM search MECP, perhaps regardless of spin and space symmetry difference and perhaps through MCSCF or TDDFT, which is necessary for PESes, which is a feature in GAMESS?
Can this point have imaginary frequencies?

**Comment by sibo** [comment]
I am also interested in finding Minimum Energy Crossing Points. Some utility programs have been written to read and write Gaussian calculations to find MECPs (see https://github.com/jaimergp/easymecp ). Does anyone know if any such MECP utilities exist for NWChem?
