### ISSUE TITLE
Consider removing the dependency on tcsh

### ISSUE THREAD

**Issue by marcindulak** [nwchemgit/nwchem#120]
FYI: In Fedora, tcsh is currently orphaned https://src.fedoraproject.org/rpms/tcsh after a maintainer left https://lists.pagure.io/archives/list/devel@lists.fedoraproject.org/thread/HLFI6YBUGVSSM63NEKJR4NYONDUJ3WLO/#JYV6PAJEDO5OXOLD3ZBXN3WEYGFMUJ76

The problem does not affect https://src.fedoraproject.org/rpms/nwchem, since I was able to remove the references to tcsh and still make the build succeed.

**Comment by jeffhammond** [comment]
NWChem has tried to support both BASH and TCSH for historical reasons but I think in most cases when we have scripts that use one, we have another script that supports the other.  I'm not sure everything can live without TCSH in all cases but it is likely that the common case that is relevant to Fedora doesn't need it.

In any case, I don't know where NWChem says it needs TCSH but a pull request to change that is certainly welcome.

**Comment by edoapra** [comment]
@marcindulak csh is used in the [64_to_32](https://github.com/nwchemgit/nwchem/blob/master/src/config/64_to_32)   scripts, therefore any build that makes use of the "make 64_to_32" command should fail. I seem to remember that Fedora's nwchem.spec contains a mention of `make 64_to_32`, therefore the build should not work unless a csh shell is present
https://src.fedoraproject.org/rpms/nwchem/blob/HEAD/f/nwchem.spec

**Comment by marcindulak** [comment]
@edoapra you are right: https://koji.fedoraproject.org/koji/buildinfo?buildID=1278923 lists (in https://kojipkgs.fedoraproject.org//packages/nwchem/6.8.1/9.fc30/data/logs/x86_64/root.log) tcsh as a dependency pulled during the build. I'll apply your https://github.com/nwchemgit/nwchem/commit/b85d2e8a074102d8fdb456a92c5295c5d04a7f91 as a patch in the spec file. There are other scripts under `src/config`, are they harmless, and can be removed?

**Comment by marcindulak** [comment]
But I think it may be better to keep the scripts for both shells, just give them file extensions, so one can choose what to execute.

**Comment by edoapra** [comment]
> But I think it may be better to keep the scripts for both shells, just give them file extensions, so one can choose what to execute.

Why? This decision would result in more scripts to maintain ...

**Comment by jeffhammond** [comment]
I’ll see how hard it is to convert to POSIX shell so it doesn’t matter whether it’s bash or tcsh.

**Comment by edoapra** [comment]
Conversion to bash seems done to me
