### ISSUE TITLE
NWChem on BlueGene/Q

### ISSUE THREAD

**Issue by chiensh** [nwchemgit/nwchem#123]
Just out of curiosity, is NWChem still supporting this old architecture?

I tried to compile the latest master build obtain on 11Jun2019, and with a self-built mpich3 and xlf 14.1 (with 64_to_32 conversion), but it was not successful when it compiles ccsd/ccsd_trpdrv_omp_mixprec.f due to a compiler internal error.  

**********
[chiensh@cumulus ~]$ mpixlf77_r -c -qintsize=8  -g -qEXTNAME -qxlf77=leadzero -qthreaded -qnosave  -g -O0 -qarch=qp -qtune=qp -qsimd=auto -qhot=level=1 -qprefetch -qunroll=yes  -qreport -qsource -qlistopt -qlist  ccsd_trpdrv_omp_mixprec.f
** ccsd_trpdrv_omp_mixprec   === End of Compilation 1 ===
1585-100  Internal compiler error -- please contact your service representative. For more information visit: http://www.ibm.com/support/docview.wss?uid=swg21110810
1501-511  Compilation failed for file ccsd_trpdrv_omp_mixprec.f
**********
i) I found that this code can only be compiled successfully when -qintsize=8  flag taken out. 
ii) I managed to narrow down the source of error to be the second loop between line 752 to 802(shown as follow): 
********************
750            do bb=1,nvir,chunking
751 #if 0
752              do cc=1,nvir,chunking
753                do b=bb,min(bb+chunking-1,nvir)
754                  do c=cc,min(cc+chunking-1,nvir)
...
800                  enddo
801                enddo
802              enddo
803 #endif
804            enddo

mpixlf77_r -c -qintsize=8   ccsd_trpdrv_omp_mixprec.F
** ccsd_trpdrv_omp_mixprec   === End of Compilation 1 ===
1501-510  Compilation successful for file ccsd_trpdrv_omp_mixprec.F
**********
750            do bb=1,nvir,chunking
751              do cc=1,nvir,chunking
752 #if 0
753                do b=bb,min(bb+chunking-1,nvir)
754                  do c=cc,min(cc+chunking-1,nvir)
...
800                  enddo
801                enddo
802 #endif
803              enddo
804            enddo

[chiensh@cumulus ~]$ mpixlf77_r -c -qintsize=8   ccsd_trpdrv_omp_mixprec.F
** ccsd_trpdrv_omp_mixprec   === End of Compilation 1 ===
1585-100  Internal compiler error -- please contact your service representative. For more information visit: http://www.ibm.com/support/docview.wss?uid=swg21110810
1501-511  Compilation failed for file ccsd_trpdrv_omp_mixprec.F
**********

Any idea how I can fix this? Thanks

~Dominic Chien

**Comment by jeffhammond** [comment]
I’ll disable that code on BGQ. Mixed precision has no value there.

**Comment by edoapra** [comment]
@chiensh could you try the update your tree with the commit https://github.com/nwchemgit/nwchem/commit/f24dce0661341add0e4cba9b31476e53c7d959a9 I have just pushed. 
You don't need to recompile the whole tree, just
cd $NWCHEM_TOP/src/ccsd
make

**Comment by edoapra** [comment]
No further feedback received
