### ISSUE TITLE
BLAS option qopenmp not parsed by GA

### ISSUE THREAD

**Issue by zerpiko** [nwchemgit/nwchem#127]
Hi
I'm trying to compile nwchem for a xeon gold 6148 following the instructions in https://github.com/nwchemgit/nwchem/wiki/Compiling-NWChem for Intel Xeon Phi (it says that they are applicable to other Xeon processors except for USE_FASTMEM option.

Regarding BLAS options I can see:

> When using MKL and Intel 16+, please use the following settings
> % setenv BLASOPT   "-mkl -qopenmp" 
> % setenv SCALAPACK "-mkl -qopenmp -lmkl_scalapack_ilp64 -lmkl_blacs_intelmpi_ilp64"

But GA 5.6.5 doesn't parse option "-qopenmp". In  nwchem-6.8.1/src/tools/ga-5.6.5/configure you can see the parsing options and the flag doesn't seem to be captured (and in fact I get the corresponding warning message).

> for arg in $with_blas ; do
>     case $arg in #(
>   yes) :
>      ;; #(
>   no) :
>      ;; #(
>   -l*) :
>     BLAS_LIBS="$BLAS_LIBS $arg" ;; #(
>   -L*) :
>     BLAS_LDFLAGS="$BLAS_LDFLAGS $arg" ;; #(
>   -WL*) :
>     BLAS_LDFLAGS="$BLAS_LDFLAGS $arg" ;; #(
>   -Wl*) :
>     BLAS_LDFLAGS="$BLAS_LDFLAGS $arg" ;; #(
>   -I*) :
>     BLAS_CPPFLAGS="$BLAS_CPPFLAGS $arg" ;; #(
>   *.a) :
>     BLAS_LIBS="$BLAS_LIBS $arg" ;; #(
>   *.so) :
>     BLAS_LIBS="$BLAS_LIBS $arg" ;; #(
>   *lib) :
>     if test -d $arg; then :
>   BLAS_LDFLAGS="$BLAS_LDFLAGS -L$arg"
> else
>   { $as_echo "$as_me:${as_lineno-$LINENO}: WARNING: $arg of with_blas not parsed" >&5
> $as_echo "$as_me: WARNING: $arg of with_blas not parsed" >&2;}
> fi ;; #(
>   *lib/) :
>     if test -d $arg; then :
>   BLAS_LDFLAGS="$BLAS_LDFLAGS -L$arg"
> else
>   { $as_echo "$as_me:${as_lineno-$LINENO}: WARNING: $arg of with_blas not parsed" >&5
> $as_echo "$as_me: WARNING: $arg of with_blas not parsed" >&2;}
> fi ;; #(
>   *lib64) :
>     if test -d $arg; then :
>   BLAS_LDFLAGS="$BLAS_LDFLAGS -L$arg"
> else
>   { $as_echo "$as_me:${as_lineno-$LINENO}: WARNING: $arg of with_blas not parsed" >&5
> $as_echo "$as_me: WARNING: $arg of with_blas not parsed" >&2;}
> fi ;; #(
>   *lib64/) :
>     if test -d $arg; then :
>   BLAS_LDFLAGS="$BLAS_LDFLAGS -L$arg"
> else
>   { $as_echo "$as_me:${as_lineno-$LINENO}: WARNING: $arg of with_blas not parsed" >&5
> $as_echo "$as_me: WARNING: $arg of with_blas not parsed" >&2;}
> fi ;; #(
>   *include) :
>     if test -d $arg; then :
>   BLAS_CPPFLAGS="$BLAS_CPPFLAGS -I$arg"
> else
>   { $as_echo "$as_me:${as_lineno-$LINENO}: WARNING: $arg of with_blas not parsed" >&5
> $as_echo "$as_me: WARNING: $arg of with_blas not parsed" >&2;}
> fi ;; #(
>   *include/) :
>     if test -d $arg; then :
>   BLAS_CPPFLAGS="$BLAS_CPPFLAGS -I$arg"
> else
>   { $as_echo "$as_me:${as_lineno-$LINENO}: WARNING: $arg of with_blas not parsed" >&5
> $as_echo "$as_me: WARNING: $arg of with_blas not parsed" >&2;}
> fi ;; #(
>   *include64) :
>     if test -d $arg; then :
>   BLAS_CPPFLAGS="$BLAS_CPPFLAGS -I$arg"
> else
>   { $as_echo "$as_me:${as_lineno-$LINENO}: WARNING: $arg of with_blas not parsed" >&5
> $as_echo "$as_me: WARNING: $arg of with_blas not parsed" >&2;}
> fi ;; #(
>   *include64/) :
>     if test -d $arg; then :
>   BLAS_CPPFLAGS="$BLAS_CPPFLAGS -I$arg"
> else
>   { $as_echo "$as_me:${as_lineno-$LINENO}: WARNING: $arg of with_blas not parsed" >&5
> $as_echo "$as_me: WARNING: $arg of with_blas not parsed" >&2;}
> fi ;; #(
>   -mkl*) :
>     BLAS_LIBS="$BLAS_LIBS $arg" ;; #(
>   *) :
>     ga_arg_parse_ok=no ;;
> esac
> # $arg didn't fit the most common cases
> # check for subdirectories e.g. lib,include
>     if test "x$ga_arg_parse_ok" = xno; then :
>   if test "x$ga_arg_parse_sizeof_voidp" = x8; then :
>   if test -d $arg/lib64; then :
>   BLAS_LDFLAGS="$BLAS_LDFLAGS -L$arg/lib64"; ga_arg_parse_ok=yes
> elif test -d $arg/lib; then :
>   BLAS_LDFLAGS="$BLAS_LDFLAGS -L$arg/lib"; ga_arg_parse_ok=yes
> fi
>              if test -d $arg/include64; then :
>   BLAS_CPPFLAGS="$BLAS_CPPFLAGS -I$arg/include64"; ga_arg_parse_ok=yes
> elif test -d $arg/include; then :
>   BLAS_CPPFLAGS="$BLAS_CPPFLAGS -I$arg/include"; ga_arg_parse_ok=yes
> fi
> else
>   if test -d $arg/lib; then :
>   BLAS_LDFLAGS="$BLAS_LDFLAGS -L$arg/lib"; ga_arg_parse_ok=yes
> fi
>              if test -d $arg/include; then :
>   BLAS_CPPFLAGS="$BLAS_CPPFLAGS -I$arg/include"; ga_arg_parse_ok=yes
> fi
> fi
> fi
> # $arg still unknown, look for "lib" and "include" anywhere...
>     if test "x$ga_arg_parse_ok" = xno; then :
>   case $arg in #(
>   *lib*) :
>     if test -d $arg; then :
>   BLAS_LDFLAGS="$BLAS_LDFLAGS -L$arg"; ga_arg_parse_ok=yes
> fi ;; #(
>   *include*) :
>     if test -d $arg; then :
>   BLAS_CPPFLAGS="$BLAS_CPPFLAGS -I$arg"; ga_arg_parse_ok=yes
> fi ;; #(
>   *) :
>      ;;
> esac
> fi
> # warn user that $arg fell through
>      if test "x$ga_arg_parse_ok" = xno; then :
>   { $as_echo "$as_me:${as_lineno-$LINENO}: WARNING: $arg of with_blas not parsed" >&5
> $as_echo "$as_me: WARNING: $arg of with_blas not parsed" >&2;}
> fi
> done

**Comment by edoapra** [comment]
@zerpiko I would recommend the following options to be set
```
BLASOPT="-mkl"
SCALAPACK "-mkl -lmkl_scalapack_ilp64 -lmkl_blacs_intelmpi_ilp64"
USE_OPENMP=1
```
Since USE_OPENMPI triggers -qopenmp, you would get the same effect.

Instead, if you prefer to stick to the previous options, you might want to file it as Global Arrays issue at
https://github.com/GlobalArrays/ga/issues

**Comment by jeffhammond** [comment]
@zerpiko FYI the `USE_FASTMEM` option is only applicable if you run in flat mode and want to use explicit MCDRAM allocation in the CCSD(T) code that supports it.  I did the `fastmem` work but nearly all HPC centers running KNL use cache mode, so I never spent any time testing it.
