### ISSUE TITLE
A little of erroneous QA tests (nwchem 6.8.1 gcc 7.4.0 openmpi 4.0.1 mkl 2019.4)

### ISSUE THREAD

**Issue by pistack** [nwchemgit/nwchem#131]
Dear All, 
when I compile nwchem 6.8.1(hotfix/release-6-8 branch) with gcc 7.4.0 elpa 2017 scalapack 2.0.2 mkl 2019.4 using this script (https://github.com/pistack/pistack-s-repository/blob/master/nwchem/build_nwchem.pbs) ,
I got a little of erroneous QA tests (https://github.com/pistack/pistack-s-repository/tree/master/nwchem/QA-test/err-tst) and numerically different tests. (https://github.com/pistack/pistack-s-repository/tree/master/nwchem/QA-test/failed-tst/very-diff). Could you suggest how to reduce these erroneous tests?

Thank you.

**Comment by edoapra** [comment]
@pistack You have plenty of variables (that might potentially lead into uncharted territory) involved in your build as listed in https://github.com/pistack/pistack-s-repository/blob/master/nwchem/build_nwchem.pbs. I have tried to reproduce some of your failures on my Ubuntu 18.04 with  limited success
My suggestion is to simplify your build by unsetting SCALAPACK, EXTERNAL_ARMCI_PATH, ELPA  and try the QA with these settings

**Comment by jeffhammond** [comment]
I’ll investigate the ARMCI-MPI dimension. I don’t test much with Open-MPI because RMA has been so buggy in the past (I know it’s better now but old habits die hard).

**Comment by jeffhammond** [comment]
I looked at the output files carefully and this really looks like a linear algebra issue.  Please try without ELPA.  If that doesn't fix it, try without ScaLAPACK.  If ARMCI-MPI was the problem, you'd see different failures (and a lot more them).

**Comment by pistack** [comment]
Although I disabled both elpa and scalpack, I could not reduce the number of erroneous QA tests (https://github.com/pistack/pistack-s-repository/tree/master/nwchem/QA-test/err-tst).
Does intel mkl or vectorization, such like avx2, cause  three test (h3_dirdyvtst,h3tr1,tropt-ch3nh2) execution fail?

Thank you.

**Comment by edoapra** [comment]
@pistack ELPA set or unset is got to have no effect since it needs an input line to be turned on.
A compiler problem might still be the root cause of it, but I would encourage you to try using the builtin GA/ARMCI first before further investigations

**Comment by edoapra** [comment]
No further feedback received
