### ISSUE TITLE
EOMCC run produced "there is a bug in the program" error from tce_eom_xguess.F

### ISSUE THREAD

**Issue by stephenyuwono** [nwchemgit/nwchem#132]
Dear All,

I was trying to run an EOMCCSDT calculation to reproduce some excitation energies reported in [this paper from 2001](https://doi.org/10.1016/S0009-2614(01)01010-7).

The step where TCE produces initial guess results in an error that says "there is a bug in the program", from the tce_eom_xguess.F routine. I am not sure about the meaning of the if statement preceding this output:

```
 if (nxtrials.lt.nroots_reduced)
1  call errquit('there is a bug in the program',0,UNKNOWN_ERR)
```

I am guessing that the nxtrials is related to the number of vectors with the symmetry corresponding to the excited state of interest. So, I have tried messing around with tce:maxeorb and tce:hbard, but I did not get any results.

Could anyone help? Thank you very much.

-Stephen

**Comment by edoapra** [comment]
@stephenyuwono Could you post the complete input file you have been using?

**Comment by jeffhammond** [comment]
@stephenyuwono You might look at https://github.com/nwchemgit/nwchem/blob/master/QA/tests/tce_cr_eom_t_ch_rohf/tce_cr_eom_t_ch_rohf.nw and change from `creomsd(t)` to `ccsdt`.

**Comment by stephenyuwono** [comment]
@edoapra please find the input file here:
[ch+_eomccsdt_a2_re.txt](https://github.com/nwchemgit/nwchem/files/3399360/ch%2B_eomccsdt_a2_re.txt)

@jeffhammond that file works for the b1 symmetry (same as ground state) and then stopped for b2. Please find the log file here.
[test.log](https://github.com/nwchemgit/nwchem/files/3399373/test.log)

**Comment by npbauman** [comment]
@stephenyuwono  Remove the maxeorb line. It is setting an energy window for the initial guess that is too small. If you remove it the calculation runs fine.

**Comment by stephenyuwono** [comment]
@npbauman I tried that as my initial run, but without setting maxeorb at all it has the same error. I was guessing I should actually increase the energy window, but not sure why it would be an issue. Here is my output, producing the same error, without setting tce:maxeorb or tce:hbard.
[ch+_eomccsdt_a2_re.log](https://github.com/nwchemgit/nwchem/files/3402372/ch%2B_eomccsdt_a2_re.log)

As a side question, how does NWChem set the window for the initial guess when no option is given?

**Comment by npbauman** [comment]
Interesting. When I run the same input it runs fine. I see no noticeable difference in out outputs besides the version of NWChem used. See the file below.
[test.log](https://github.com/nwchemgit/nwchem/files/3402619/test.log)

As a test, could you try setting maxeorb to a very large number (say 1.0d99).

Initial guesses are based on orbital energy differences between occupied and unoccupied orbitals. For x1 (or R_1 in standard CC notation) this is (e_a - e_i). The smallest of these values is the excitation from HOMO to LUMO. If you are using symmetry, then these are the lowest symmetry allowed orbitals energy differences. For x2 (or R_2 in standard CC notation) this is (e_a + e_b - e_i - e_j). The smallest possibility of these values is 2 times the differences between the HOMO and LUMO energies. If maxeorb is not set then for x1, the code ought to take the nroot number of excitations corresponding to the lowest orbital energy differences with essentially no limit for maxeorb (the default being 1.0d99). For x2, whether or not maxeorb is set, there is a hard coded value of 0.6 that the difference (e_a + e_b - e_i - e_j) must be below. 

Like I said, try setting the maxeorb values to a large value. We may have to look deeper as to the cause of the problem in your case.

**Comment by stephenyuwono** [comment]
@npbauman The fact that only the version differs between our calculation is interesting indeed. Could it be a compilation issue on my side?

In any case, I set maxeorb to 1.0d99 (should have thought of this earlier...) and now it works just fine, as seen in the output below. Thank you for your help!
[ch+_eomccsdt_a2_re_large-maxeorb.log](https://github.com/nwchemgit/nwchem/files/3402837/ch%2B_eomccsdt_a2_re_large-maxeorb.log)

**Comment by npbauman** [comment]
@stephenyuwono Could you 
1. `grep maxeorb ch+_eomccsdt_a2_re.db`(if you have not deleted it yet)
2. rerun the same calculation with no maxeorb line now that this has finished. Let me know if it finishes or not.
3. After you run it, whether it completes or fails, redo `grep maxeorb ch+_eomccsdt_a2_re.db `

**Comment by stephenyuwono** [comment]
@npbauman Apologies for the delay.

I followed your instructions:

1. `grep -a maxeorb ch+_eomccsdt_a2_re.db` results in `tce:maxeorb.▒▒▒▒B}T$!rtdb!task:status▒Wed Jul 17 12:13:55 2019` (not empty)
2. I reran the calculation without the maxeorb line. It crashed with the same error.
3. `grep -a maxeorb ch+_eomccsdt_a2_re_nomaxeorb.db` results in nothing.

For your checking, I am attaching the files below.
[testing.zip](https://github.com/nwchemgit/nwchem/files/3418127/testing.zip)

**Comment by edoapra** [comment]
@stephenyuwono What compiler (version included) have you been using?
Thanks

**Comment by edoapra** [comment]
@stephenyuwono Could you please try if switching to direct SCF makes any difference?
```
scf
 direct
end
```

**Comment by stephenyuwono** [comment]
@edoapra I used ifort version 2018.1.163 in the compilation.

Using direct scf does not seem to affect the result, either.

**Comment by edoapra** [comment]
@stephenyuwono We have uploaded files for the second beta of the upcoming 7.0.0 release
https://github.com/nwchemgit/nwchem/releases/tag/v7.0.0-beta2
The source code contains changes that should either address the bug you reported or at least help in diagnosing its behavior.
If you have time, could you try to compile and re-rerun your input?
Thanks

**Comment by edoapra** [comment]
No response received
