### ISSUE TITLE
NWCHEM_TOP and  64 characters

### ISSUE THREAD

**Issue by miroi** [nwchemgit/nwchem#133]
Hello, isn't there a way to fix this ? I prefer  longer  directory names....

~~~
The directory name chosen for NWCHEM_TOP is longer than 
the maximum allowed value of 64 characters
      current NWCHEM_TOP/src=/lustre/nyx/ukt/milias/work/software/nwchem/nwchem_intel17mkl/src equal to 66 characters
please chose a directory with a shorter name
~~~

**Comment by edoapra** [comment]
@miroi set the env. variable LONGNWTOP to y, e.g.
bash export LONGNWTOP=Y
csh/tcsh setenv LONGNWTOP Y

**Comment by edoapra** [comment]
> @miroi set the env. variable LONGNWTOP to y, e.g.
> bash export LONGNWTOP=Y
> csh/tcsh setenv LONGNWTOP Y

Sorry, wrong variable, the correct one is  NWCHEM_LONG_PATHS

**Comment by miroi** [comment]
Excellent ! Closing this issue.

**Comment by edoapra** [comment]
@miroi set the env. variable NWCHEM_LONG_PATHS to y, e.g.
bash export NWCHEM_LONG_PATHS=Y
csh/tcsh setenv NWCHEM_LONG_PATHS Y
