### ISSUE TITLE
String tutorial 1 in the NWCHEM gets stuck

### ISSUE THREAD

**Issue by xiongyan21** [nwchemgit/nwchem#135]
It seems String tutorial 1 in the NWCHEM manual gets stuck. The log file is attached.
[hcn-string.log](https://github.com/nwchemgit/nwchem/files/3497045/hcn-string.log)
NEB example H2O inversion can finish. The log file is attached.
[h2o-neb.log](https://github.com/nwchemgit/nwchem/files/3497079/h2o-neb.log)

**Comment by ebylaska** [comment]
Was able to reproduce the bug.  Looks like coords aren't being read in properly.  Likely due to some changes I made to NEB recently.  I'll put it on my list of things to do.

**Comment by ebylaska** [comment]
Looks like Edo's change fixes the problem

commit b53effe0dc0d83b83a7012bc990db4aa884aaa8f


[WE34304:~/Projects/NWChem/Bugs] bylaska% fgrep @ string.out
@zts
@zts String method.
@zts Temperature          =   0.00000
@zts Covergence Tolerance =   0.00010
@zts Step Size            =   0.10000
@zts Maximum Time Steps   =        10
@zts Number of replicas   =        10
@zts Number of histories  =        10
@zts algorithm            = 3 (QN Fixed Point - Damped Verlet)
@zts String Interpolator  =         1
@zts First Replica        = frozen
@zts Last Replica         = frozen
@zts
@zts  Step       xrms       xmax        E start       E middle          E end          E max      E average Walltime
@zts     1   0.138471   0.930526    -92.9066825    -63.5219551    -92.8817133    304.0417305    -47.4039526      6.4
@zts     2   0.049028   0.352686    -92.9066825    -53.3670684    -92.8817133     87.0638961    -68.2244359     12.6
@zts     3   0.040173   0.334328    -92.9066825    -49.4278200    -92.8817133     20.8118522    -74.5380028     15.7
@zts     4   0.022929   0.170377    -92.9066825    -53.2451728    -92.8817133     -8.8518573    -77.9688279     18.5
@zts     5   0.023857   0.147510    -92.9066825    -63.7025637    -92.8817133    -22.6431266    -80.4577382     21.6
@zts     6   0.026043   0.147530    -92.9066825    -71.9659927    -92.8817133    -37.0500973    -82.8322277     24.7
@zts     7   0.027473   0.154173    -92.9066825    -77.6935519    -92.8817133    -50.0230907    -84.7924537     27.8
@zts     8   0.030992   0.222044    -92.9066825    -81.4975323    -92.8817133    -60.9077479    -86.3654383     30.8
@zts     9   0.030617   0.249292    -92.9066825    -83.9185766    -92.8817133    -69.1353593    -87.5843024     33.8
@zts    10   0.033230   0.195935    -92.9066825    -85.7118773    -92.8817133    -74.9741782    -88.5284560     36.8
@zts The string calculation failed to converge
@zts Bead number    1  Potential Energy =     -92.906682492795
@zts Bead number    2  Potential Energy =     -92.383276304135
@zts Bead number    3  Potential Energy =     -89.060276944328
@zts Bead number    4  Potential Energy =     -80.264075646753
@zts Bead number    5  Potential Energy =     -74.974178191778
@zts Bead number    6  Potential Energy =     -85.711877338873
@zts Bead number    7  Potential Energy =     -91.472339038239
@zts Bead number    8  Potential Energy =     -92.754277876796
@zts Bead number    9  Potential Energy =     -92.875862765803
@zts Bead number   10  Potential Energy =     -92.881713271220
@zts
@zts String method.
@zts Temperature          =   0.00000
@zts Covergence Tolerance =   0.00010
@zts Step Size            =   0.10000
@zts Maximum Time Steps   =        20
@zts Number of replicas   =        20
@zts Number of histories  =        10
@zts algorithm            = 3 (QN Fixed Point - Damped Verlet)
@zts String Interpolator  =         1
@zts First Replica        = moves
@zts Last Replica         = moves
@zts
@zts  Step       xrms       xmax        E start       E middle          E end          E max      E average Walltime
@zts     1   0.040688   0.341381    -92.9066825    -87.9755301    -92.8824979    -87.5963699    -90.4739526     52.6
@zts     2   0.024806   0.152920    -92.9066825    -89.7632718    -92.8825460    -87.8528565    -90.7754466     59.9
@zts     3   0.041253   0.216763    -92.9066825    -90.8636887    -92.8827154    -88.1278865    -91.0662511     67.5
@zts     4   0.027424   0.187957    -92.9066825    -91.4005556    -92.8825638    -88.6473245    -91.3789906     74.9
@zts     5   0.041301   0.257075    -92.9066825    -91.8154778    -92.8825699    -89.1880385    -91.6758823     82.3
@zts     6   0.045893   0.365675    -92.9066825    -91.8292063    -92.8822979    -89.7702712    -91.9077348     89.6
@zts     7   0.044621   0.411084    -92.9066826    -92.1109131    -92.8824877    -90.2709223    -92.1061835     96.9
@zts     8   0.033541   0.258626    -92.9066826    -92.3247018    -92.8825244    -90.7645850    -92.2537379    104.1
@zts     9   0.057156   0.432684    -92.9066826    -92.2865978    -92.8825810    -91.2384835    -92.3508688    111.4
@zts    10   0.067926   0.860082    -92.9066826    -92.4259831    -92.8822761    -91.6133383    -92.4469613    118.6
@zts    11   0.046123   0.571285    -92.9066827    -92.4977091    -92.8825643    -91.8426035    -92.5245019    125.7
@zts    12   0.031546   0.356053    -92.9066827    -92.5185430    -92.8783126    -92.0371485    -92.5842990    132.6
@zts    13   0.031029   0.180800    -92.9066827    -92.5398132    -92.8793725    -92.2003138    -92.6344506    140.2
@zts    14   0.091251   0.478552    -92.9066827    -92.5664820    -92.8822876    -92.3389603    -92.6767735    147.4
@zts    15   0.074600   0.397557    -92.9066828    -92.6805970    -92.8725250    -92.4728008    -92.7304721    154.7
@zts    16   0.057396   0.274198    -92.9066828    -92.7420253    -92.8728530    -92.5883622    -92.7683709    161.6
@zts    17   0.142261   0.602960    -92.9066829    -92.7692739    -92.8764684    -92.6798875    -92.7943161    169.0
@zts    18   0.237757   1.107480    -92.9066829    -92.7568967    -92.8795152    -92.7516483    -92.8092854    176.4
@zts    19   1.044741   4.814708    -92.9066829    -92.7715358    -92.8810870    -92.7586689    -92.8255556    184.4
@zts    20   0.877617   5.115630    -92.9066830    -92.3369703    -92.7589673    -92.3369703    -92.6312936    202.0
@zts The string calculation failed to converge
@zts Bead number    1  Potential Energy =     -92.906682995977
@zts Bead number    2  Potential Energy =     -92.878047759649
@zts Bead number    3  Potential Energy =     -92.699050472350
@zts Bead number    4  Potential Energy =     -92.503711918780
@zts Bead number    5  Potential Energy =     -92.569491138873
@zts Bead number    6  Potential Energy =     -92.795117949420
@zts Bead number    7  Potential Energy =     -92.774573166695
@zts Bead number    8  Potential Energy =     -92.752659415474
@zts Bead number    9  Potential Energy =     -92.541884024564
@zts Bead number   10  Potential Energy =     -92.401676160869
@zts Bead number   11  Potential Energy =     -92.336970297894
@zts Bead number   12  Potential Energy =     -92.365928848913
@zts Bead number   13  Potential Energy =     -92.471587798609
@zts Bead number   14  Potential Energy =     -92.644720552576
@zts Bead number   15  Potential Energy =     -92.818493325325
@zts Bead number   16  Potential Energy =     -92.726902858427
@zts Bead number   17  Potential Energy =     -92.526753364619
@zts Bead number   18  Potential Energy =     -92.516886533300
@zts Bead number   19  Potential Energy =     -92.635765998926
@zts Bead number   20  Potential Energy =     -92.758967254699
