### ISSUE TITLE
More flexible Python installation settings

### ISSUE THREAD

**Issue by marcindulak** [nwchemgit/nwchem#136]
Needed by https://bugzilla.redhat.com/show_bug.cgi?id=1738065

From fedora 29 x86_64, site-packages are under `/usr/lib64/python3.7/site-packages` but includes (like `Python.h`) are under `/usr/include/python3.7m` - note the **m**.

With https://github.com/nwchemgit/nwchem/commit/33826b4cdd11dbcc97db25067bacfc219f1db892, neither setting 
```
PYTHONVERSION=3.7
```
nor
```
PYTHONVERSION=3.7m
```
allows the build to succeed, resulting respectively with

```
gcc -c -I. -I/usr/include/python3.7 -I/usr/include -I/usr/Include -I/usr -I/builddir/build/BUILD/nwchem-6.8.1/src/include -I/usr/include -I/usr/include/openmpi-x86_64 -I/usr/lib64/openmpi/lib -DMPICH_NO_ATTR_TYPE_TAGS -DGFORTRAN -DCHKUNDFLW -DGCC4 -DGCC46 -DEXT_INT -DLINUX -DLINUX64 -DSCALAPACK -DPARALLEL_DIAG  -m64 -Wall -O3 -funroll-loops -ffast-math  -g  -o task_python.o task_python.c
awk: cmd. line:1: warning: regexp escape sequence `\ ' is not a known regexp operator
task_python.c:4:10: fatal error: Python.h: No such file or directory
    4 | #include <Python.h>
      |          ^~~~~~~~~~
compilation terminated.
make[1]: *** [../config/makefile.h:2894: /builddir/build/BUILD/nwchem-6.8.1/lib/LINUX64/libnwpython.a(task_python.o)] Error 1
make[1]: Leaving directory '/builddir/build/BUILD/nwchem-6.8.1/src/python'
```

or

```
gfortran  -Wl,--export-dynamic  -L/builddir/build/BUILD/nwchem-6.8.1/lib/LINUX64 -L/usr/lib  -L/usr/lib64/openmpi/lib  -o /builddir/build/BUILD/nwchem-6.8.1/bin/LINUX64/nwchem nwchem.o stubs.o -lnwctask -lccsd -lmcscf -lselci -lmp2 -lmoints -lstepper -ldriver -loptim -lnwdft -lgradients -lcphf -lesp -lddscf -ldangchang -lguess -lhessian -lvib -lnwcutil -lrimp2 -lproperty -lsolvation -lnwints -lprepar -lnwmd -lnwpw -lofpw -lpaw -lpspw -lband -lnwpwlib -lcafe -lspace -lanalyze -lqhop -lpfft -ldplot -lnwpython -ldrdy -lvscf -lqmmm -lqmd -letrans -lpspw -ltce -lbq -lmm -lcons -lperfm -ldntmc -lccca -ldimqm -lnwcutil -lga -larmci -lpeigs -lperfm -lcons -lbq -lnwcutil /usr/lib64/python3.7m/config/libpython3.7m.so    -l64to32 -L/usr/lib64 -lopenblas     -L/usr/lib64/openmpi/lib -lmpi -lmpi_usempif08 -lmpi_mpifh   -libverbs  -lpthread  -lnwcutil -lpython3.7m -lcrypt -lpthread -ldl  -lutil -lm    
gfortran: error: /usr/lib64/python3.7m/config/libpython3.7m.so: No such file or directory
```

Moreover, despite existence of Python2 on the system we need to be able to select Python3, since distributions are in a transition period from Python2 to Python3.

**Comment by edoapra** [comment]
@marcindulak Did you try set 
```
USE_PYTHONCONFIG=y
```
?
The following settings seem to work for me under Fedora 29
```
PYTHONVERSION=3.7
PYTHONHOME=/usr
USE_PYTHONCONFIG=y
```

**Comment by edoapra** [comment]
@marcindulak 
I have pushed all the python3 changes from master to hotfix/release-6-8

**Comment by marcindulak** [comment]
I took master's https://github.com/nwchemgit/nwchem/commit/4003023d137fab610de2943e73ff4a6b535164ee, and eventually made the build work (https://koji.fedoraproject.org/koji/taskinfo?taskID=37086909),
but discovered the following problems:

1. `make USE64TO32=y` results in

```
config/makefile.h:2753: *** Please define LAPACK_LIB if you have defined BLASOPT or BLAS_LIB.  Stop.
```

Setting of this variable is not required according to https://github.com/nwchemgit/nwchem/wiki/Compiling-NWChem
and http://www.nwchem-sw.org/index.php/Compiling_NWChem

2. make clean is failing due to `For python you must define both PYTHONHOME and PYTHONVERSION`  https://koji.fedoraproject.org/koji/taskinfo?taskID=37073158

3. on fedora 32 there is a lot of lines https://koji.fedoraproject.org/koji/taskinfo?taskID=37067595

```
awk: cmd. line:1: warning: regexp escape sequence `\ ' is not a known regexp operator
```

4. tests fail with segmentation fault on fedora 32 https://koji.fedoraproject.org/koji/taskinfo?taskID=37086626

5. compilation fails on centos 6 i686 https://koji.fedoraproject.org/koji/taskinfo?taskID=37086785

```
Compiling util_mygop.F...
util_mygop.F:13.18:
      bigint = ((2**31)-1024)/
                  1
Error: Arithmetic overflow at (1)
util_mygop.F:50.18:
      bigint = ((2**31)-1024)/
                  1
Error: Arithmetic overflow at (1)
```

6. hotfix/release-6-8 https://github.com/nwchemgit/nwchem/commit/2272a644e10f34026ebcc0b1f393fe4a08d7a603 fails to build for me https://koji.fedoraproject.org/koji/taskinfo?taskID=37085052 - can you see why? It also looks like in this branch https://src.fedoraproject.org/rpms/nwchem/blob/master/f/b85d2e8a074102d8fdb456a92c5295c5d04a7f91.patch has not been applied.
If you branch off master for the next nwchem release maybe it's better I package master for fedora rawhide instead of the hotfix/release-6-8 branch, and I'll call it nwchem-6.8.2? When is a new release planned?

7. The following is not a problem, but a request. I'm using QA/tests/pyqa3 for testing python during the nwchem build for both python2 and python3.
Would it be possible to add pyga3 to https://github.com/nwchemgit/nwchem/blob/master/QA/doafewqmtests.mpi?
This is the set of quick tests I'm using. I think pyqa3 is compatible with modern python2 (>=2.6).

**Comment by edoapra** [comment]
@marcindulak I will reply here to item 4

> tests fail with segmentation fault on fedora 32 https://koji.fedoraproject.org/koji/taskinfo?taskID=37086626

As you can see from the log, these segmentation fault errors occur only with the mpich build.
The RPM used by Fedora are based on the MPICH 3.1.1 source.  I have verified that this segmentation fault problems occur on the vanilla  MPICH 3.1.1 (and 3.1.2) source code. When MPICh 3.1.3 or 3.1.4 are used, the segmentation fault crash is avoided. Moving Fedora to 3.1.4 for the MPICH RPMs seems the solution to me

**Comment by edoapra** [comment]
@marcindulak I will reply here to item 2

> make clean is failing due to For python you must define both PYTHONHOME and PYTHONVERSION https://koji.fedoraproject.org/koji/taskinfo?taskID=37073158

Not quite sure why we need to fix this one ... you can simply assign whatever value you want to PYTHONHOME and PYTHONVERSION and the make clean command will work

**Comment by edoapra** [comment]
@marcindulak I will reply here to item 6

I am having second thought about back porting changes from the master branch into hotfix/release-6-8.
It might be better to have a new release. We have not decided yet for the next release cycle

**Comment by marcindulak** [comment]
I'm still having problems on fedora 32, after updating to mpich-3.2.1. This time linking against python 3.8 (fedora 32 rawhide switched to python 3.8 in the meantime) fails https://koji.fedoraproject.org/koji/taskinfo?taskID=37301818

About point 2. - it was not necessary to set PYTHONHOME and PYTHONVERSION for make clean.

**Comment by marcindulak** [comment]
With https://github.com/nwchemgit/nwchem/commit/c18f9d28194b590da9efbc821e2b86df006252a8 I'm getting (both on fedora/centos) https://koji.fedoraproject.org/koji/taskinfo?taskID=37315810

```
...
Compiling tce_mo2e_disk_2eorb.F...
tce_mo2e_disk_2eorb.F:158:20:
  158 |       integer nxtask
      |                    1
Error: Symbol 'nxtask' at (1) already has basic type of INTEGER
tce_mo2e_disk_2eorb.F:159:21:
  159 |       external nxtask
      |                     1
Error: Duplicate EXTERNAL attribute specified at (1)
```

**Comment by marcindulak** [comment]
I see more commits came - do you think the current master is ready for rpm packaging?

**Comment by edoapra** [comment]
@marcindulak I have noticed that you have some builds on koji marked as 6.8.2. What patches have you applied to the source code? Would it make sense to sync these changes on hotfix/release-6-8 ?

**Comment by marcindulak** [comment]
I'm building those based off master, the hotfix/release-6-8 did not build for me. You can see the 7 characters of the git hash in the name of the tar.bz2 file on the top of the spec file.

**Comment by edoapra** [comment]
Got it. I could not quite figure out where the g4003023 tag comes from.

Do you think that it would still make sense backport the python changes to hotfix/release-6-8 or can you wait for a new release? A new release might still be two months from now.

**Comment by marcindulak** [comment]
I'll package master https://github.com/nwchemgit/nwchem/commit/03aaf4c85eecb8bf85b6f23783d650e6db1f4c43 as nwchem-6.8.2 for fedora 32 and 31 https://fedoraproject.org/wiki/Releases/31/Schedule, maybe also for epel7 if I ever find time to work on https://bugzilla.redhat.com/show_bug.cgi?id=1709933

I don't know what is the meaning of `133-ge032219` in https://github.com/nwchemgit/nwchem/releases/download/6.8.1-release/nwchem-6.8.1-release.revision-v6.8-133-ge032219-nonsrconly.2018-06-14.tar.bz2, so I've decided to use git hash.

**Comment by edoapra** [comment]
133-ge032219 is the output of
```
git describe
```

**Comment by edoapra** [comment]
> I'll package master [03aaf4c](https://github.com/nwchemgit/nwchem/commit/03aaf4c85eecb8bf85b6f23783d650e6db1f4c43) as nwchem-6.8.2 for fedora 32 and 31 https://fedoraproject.org/wiki/Releases/31/Schedule, maybe also for epel7 if I ever find time to work on https://bugzilla.redhat.com/show_bug.cgi?id=1709933
> 
I must confess I don't understand this bugzilla entry, do you?

**Comment by marcindulak** [comment]
I keep one nwchem.spec (and also one ga.spec) file for all releases of fedora and epel. It would take too much time to keep track of the separate spec files, while looking at them every few months, and trying to merge between different branches.

I understand that https://bugzilla.redhat.com/show_bug.cgi?id=1709933 asks for providing an additional subpackage of ga (and as a consequence of nwchem) using openmpi3 available in rhel7. The ga build is supposed to use `--with-mpi-pr` mentioned at https://github.com/GlobalArrays/ga

Adding this special subpackage for rhel7 means adding a couple of `%if 0%{?el7}` to the specs. The builds mentioned in bugzilla are here https://copr.fedorainfracloud.org/coprs/loveshack/livhpc/packages/: https://copr-be.cloud.fedoraproject.org/results/loveshack/livhpc/epel-7-x86_64/00978501-ga/ga.spec

**Comment by edoapra** [comment]
@marcindulak I have pushed a few more changes related to python to the tree.
Since I am planning to open a new release branch very soon, you might want to wait to update the RPMS sources until the branch is in place.

**Comment by edoapra** [comment]
@marcindulak We opened the 7.0.0 branch today.
I have updated nwchem.spec and sources at
https://github.com/edoapra/fedpkg/commit/ff60392a0fa7d4a06f854e859807e84b152256fd
ga 5.6.5 RPMs should be safe to use

**Comment by marcindulak** [comment]
epel6 still seems failing on python https://github.com/edoapra/fedpkg/pull/2

**Comment by edoapra** [comment]
> 
> 
> epel6 still seems failing on python [edoapra/fedpkg#2](https://github.com/edoapra/fedpkg/pull/2)

Copying here the same reply as in https://github.com/edoapra/fedpkg/pull/2

PYTHONHOME and USE_PYTHONCONFIG are gone
python3.?-devel should contain python-config or python3-config, am I right? 
This is what I get on a rhel6 box (is this the same as epel6?)
```
lsb_release -r
Release:	6.10
$ rpm -q -l python-devel|grep "python\-config"
/usr/bin/python-config
/usr/bin/python-config
rpm -q -l python34-devel|grep "python3\-config"
/usr/bin/python3-config
/usr/bin/python3-config
```
I would stick to the 5.6.5-3 requirement for ga (it contains an important bug fix).
What is blocking the epel rpms update to 5.6.5-3?

**Comment by marcindulak** [comment]
It looks like Python compile support is in a good state now.

Maybe it makes sense to print the built-in Python version in the Job information section?

Should I release https://github.com/nwchemgit/nwchem/commit/1c5f20f85040651743cc18e9672c87a6d11deb66 as 7.0.0 RPMS or are we waiting for the official release based on that branch?

**Comment by edoapra** [comment]
Yes, the python support seems more stable now.
Might print Python status in the output file in the future.

This is not a released version yet. Please wait a bit more.
