### ISSUE TITLE
libxc integration in NWChem?

### ISSUE THREAD

**Issue by susilehtola** [nwchemgit/nwchem#137]
Hi,

I was wondering if you have any plans to include a libxc interface in NWChem. As you may know, libxc implements hundreds of different functionals and is now used by 30 different codes. It is licensed under the Mozilla Public License, and should be compatible with NWChem's license. (libxc can also be linked statically and shipped with closed-source programs.)

**Comment by jeffhammond** [comment]
NWChem has its own XC library but I would certainly love to see someone add support for libxc (and funclib).

**Comment by hjjvandam** [comment]
Hi Susi,

I am not aware of plans around NWChem, however we are using LibXC for the functionals in NWChemEx. In relation to the latter one of the questions we have is how the LibXC developers feel about supporting GPUs. At the moment I have ported a version using OpenMP offloading, but I am also looking at a CUDA port as most of the rest of the NWChemEx GPU code is CUDA based. I am happy to work with LibXC to establish a way this can be provided as a feature of the library.

Best wishes,

     Huub

-----------------------------------------------------------------------------------------------------
Hubertus van Dam, 631-344-6020, hvandam@bnl.gov
Brookhaven National Laboratory

**Comment by susilehtola** [comment]
Hi Huub, this sounds interesting. I'm sure we'd be interested in adding support for it. Maybe you could file a ticket / pull request on our tracker with more information?

**Comment by dmejiar** [comment]
Hi @susilehtola, the pull request #401 was just merged into the master branch. It adds support for LibXC v5.1.5. Do you have an estimated date for v6.0 release?

**Comment by susilehtola** [comment]
Oh awesome @dmejiar ! I was just recently thinking again about how great it would be to have a libxc interface in NWChem.

There's no date for the 6.0 release; we want support for double hybrids but that's somewhat stagnated at the moment.

When will the interface be included in a stable release of NWChem?

**Comment by edoapra** [comment]
@susilehtola we should have a new release in the fall and the libxc interface is going to be part of it

**Comment by susilehtola** [comment]
Great.

Which features are implemented in the wrapper?

**Comment by susilehtola** [comment]
ping @dmejiar ?

**Comment by dmejiar** [comment]
@susilehtola , the wrapper works for v5.x and only for the Gaussian-basis-based DFT.  

`3D XC` functionals, including Laplacian-dependent metaGGAs, global and error-function-range-separated hybrids are supported. Yukawa and LCGau partitions are not implemented. 

DFT-D corrected functionals can also be used, although the user has to specify appropriate DFT-D parameters using `set` directives in the input file. The VV10 kernel is not implemented.

Up to 100 pure DFT `libxc` and `nwchem` XC functionals can be mixed together. This feature does not currently work  when mixing hybrid functionals.

NWChem can handle up to third-order derivatives for LDA and GGA functionals, but only first-order for metaGGAs.

There is currently no option to access the `set_ext_params` functions from the user side.

**Comment by susilehtola** [comment]
@dmejiar great to hear! Looks like you have a pretty good selection; I was mainly wondering about Laplacian dependent functionals as well as hybrids.

Since support is now included, I am closing this ticket.
