### ISSUE TITLE
Langevin thermostat for Gaussian basis AIMD equilibrates higher than target temperature

### ISSUE THREAD

**Issue by ngovind** [nwchemgit/nwchem#14]
Please see issue posted in the NWChem forum:
http://www.nwchem-sw.org/index.php/Special:AWCforum/st/id2509/#post_8774

**Comment by ngovind** [comment]
I have checked in a fix for this into the master and hotfix (6.8.1) branches.

**Comment by ngovind** [comment]
The commit ID for the hotfix (6.8.1) branch:

commit 78bac41361c6ac0029cc4b7e8f8b7eb79c0100a0

**Comment by edoapra** [comment]
Done.
