### ISSUE TITLE
Build failure and warnings on the i386 architecture

### ISSUE THREAD

**Issue by yurivict** [nwchemgit/nwchem#140]
See the log: http://beefy10.nyi.freebsd.org/data/112i386-default/509395/logs/nwchem-6.8.1.20190816.log

Some fairly recent changes broke the i386 compatibility. There are also quite a few warnings.

**Comment by edoapra** [comment]
@yurivict commit https://github.com/nwchemgit/nwchem/commit/ee61673fccd3b2b48f37fbab1b68c5b2664901b4 fixes this 32-bit integer bug

**Comment by edoapra** [comment]
No further feedback received

**Comment by yurivict** [comment]
The problem is gone, thanks!
