### ISSUE TITLE
Solution to build failure when including CCSDTQ

### ISSUE THREAD

**Issue by hernan3009** [nwchemgit/nwchem#142]
There is a bug that stops the building process on GNU/Debian and its derivatives (maybe in other cases) when including CCSDTQ module and 64 to 32 bits conversion.

This is produced in the 64_to_32 conversion part. The directory of CCSDTQ contains too many archives and the process returns:
` foreach: Too many arguments.`
I found that it is due a shortcoming in `csh` . A simple solution is to modify the file `/src/config/64_32` requiring the usage of `tcsh` instead of `csh` . (just add a 't').

This problem should not appear in Red Hat and other systems as they uses tsch in place of csh (see https://en.wikipedia.org/wiki/C_shell)

**Comment by edoapra** [comment]
@hernan3009 What version of NWChem are you referring to? 
We have recently replaced all the csh entries with bash in the master branch.
https://github.com/nwchemgit/nwchem/issues/120

**Comment by hernan3009** [comment]
@edoapra The one found in the latest Ubuntu (19.04) repositories. It is called: "nwchem-6.8+47+gitdf6c956".

I tried to compiled and also install the binaries supplied by Nwchem but I had not success in Ubuntu 19.04. There are broken dependencies.

**Comment by edoapra** [comment]
@hernan3009 Could you give precise detail about what you are trying to accomplish?
First, I was under the impression you were trying to compile the NWChem source code, while in your second post you are talking about Ubuntu packaged binaries. I am not sure what this issue is about.

**Comment by hernan3009** [comment]
@edoapra Yes, excuse me. My goal is installing Nwchem with support for CCSDTQ.
This morning I tried to compile Nwchem with the sources provided by Nwchem. I fail due to some version problem of ¿glibc?. After that I tried the binary from the Nwchem site packed in a .deb package. It fails due to packages dependencies.

So I am trying to install Nwchem using the files provided by Ubuntu. I cannot use the .deb provided by Ubuntu because I has not support for CCSDTQ and similar methods. Because of this I am trying to compile Nwchem from the sources provided by Ubuntu.

In this moment (right now!) I noticed that somehow my source repositories are those of Ubuntu 18.10. I update it and I will try with this version "6.8.1-5". Maybe this issue was solved. I'll tell you about it soon..

**Comment by edoapra** [comment]
@hernan3009 Unfortunately, I can only help you with the NWChem sources that you can download from github.

**Comment by hernan3009** [comment]
@edoapra I just wanted to comment the issue and a provide a fix for it as I didn't know that you recently replaced all the csh entries with bash.
Thank you.

**Comment by edoapra** [comment]
Anyhow, I prefer the following suggestion to the one you posted
```
sudo apt install
sudo update-alternatives  --set csh /bin/tcsh
```
