### ISSUE TITLE
QA test tce_hyperpolar_ccsd_small gets stuck when running paralelly

### ISSUE THREAD

**Issue by xiongyan21** [nwchemgit/nwchem#146]
QA test tce_hyperpolar_ccsd_small gets stuck when running paralely
Sequentially

[tce_hyperpolar_ccsd_small.log](https://github.com/nwchemgit/nwchem/files/3555910/tce_hyperpolar_ccsd_small.log)

Parallelly
[tce_hyperpolar_ccsd_small1.log](https://github.com/nwchemgit/nwchem/files/3555914/tce_hyperpolar_ccsd_small1.log)

By the way, I have tried QA test tce_helium_imaginary whose output is not provided, although I do not know the physical meaning of the calculation, also whether it is correct.
[tce_helium_imaginary.log](https://github.com/nwchemgit/nwchem/files/3556030/tce_helium_imaginary.log)

QA test tce_rohf_uccsd can pass, and when I modify it into ccsd(t), it also can  pass.
[tce_rohf_uccsd.log](https://github.com/nwchemgit/nwchem/files/3556256/tce_rohf_uccsd.log)

[tce_rohf_uccsd1.log](https://github.com/nwchemgit/nwchem/files/3556258/tce_rohf_uccsd1.log)

**Comment by edoapra** [comment]
@xiongyan21 
1) The small1 input file contains a memory line that does not make any sense, implying the file has been edited. Please don't do that
2) Please try the current master, since commit https://github.com/nwchemgit/nwchem/commit/635df8cd60bac564710ca96f6b7e86dca552ebe6 is likely to fix this. See
https://github.com/nwchemgit/nwchem/issues/143

**Comment by xiongyan21** [comment]
Thanks.
I run # 143 sequentially and find it successful.
[tce_c2_cc2.log](https://github.com/nwchemgit/nwchem/files/3560312/tce_c2_cc2.log)

**Comment by edoapra** [comment]
From the forum.log output, the following lines indicate that the 6.8 version was used and not the master branch. Please do try the master branch
```
    nwchem branch   = 6.8
    nwchem revision = v6.8-47-gdf6c956
    ga revision     = ga-5.6.3
```

**Comment by xiongyan21** [comment]
Repeated
[tce_c2_cc2_1.log](https://github.com/nwchemgit/nwchem/files/3562300/tce_c2_cc2_1.log)
[forum1.log](https://github.com/nwchemgit/nwchem/files/3562301/forum1.log)

**Comment by xiongyan21** [comment]
QA test tce_h2o_eomcc can give ocsillator strength, but when the ccsd block  with nroots 1 changed into 5 takes place of the tce block of forum, only that of the first root is provided. GAMESS has the capability to give the oscillator strength of each root requested, respectively.
[tce_h20_eomcc.log](https://github.com/nwchemgit/nwchem/files/3562554/tce_h20_eomcc.log)
[forum5.log](https://github.com/nwchemgit/nwchem/files/3562555/forum5.log)
