### ISSUE TITLE
Fail to compile on KNL node: tce_mrcc_ccsdpt_subg.F(103) 

### ISSUE THREAD

**Issue by chiensh** [nwchemgit/nwchem#153]
**I attempted to compile nwchem (the hotfix master download on 17 Sept 19) on a KNL node (cache mode), but I got the following errors:**

_Compiling tce_mrcc_q3fnt2_subg.F...
tce_mrcc_ccsdpt_subg.F(103): error #6404: This name does not have a type, and must have an explicit type.   [TRIPLESX_ALLOCED]
      triplesx_alloced=.false.
------^
...
compilation aborted for tce_mrcc_ccsdpt_subg.F (code 1)_

**Here is the environment I used for compilation**
_module load intel/18.2.199
module load impi/2018.2
export NWCHEM_TOP=/home/users/astar/ihpc/chiensh/nwchem-17Sept2019
export NWCHEM_TARGET=LINUX64
export ARMCI_NETWORK=OPENIB
export USE_MPI=y
export USE_MPIF=y
export USE_MPIF4=y
export LARGE_FILES=TRUE
export USE_NOIO=T
export USE_NOFSCHECK=T
export ENABLE_COMPONENT=yes
export LIB_DEFINES="-DDFLT_TOT_MEM=391422080"
export DISABLE_GAMIRROR=y
export USE_GAGITHUB=y
export MEMKIND_PATH=$HOME/apps/lib

export USE_OPENMP=y
export USE_KNL=T
export USE_F90_ALLOCATABLE=F
export USE_FASTMEM=F

export BLAS_SIZE=8
export BLASOPT="-mkl -qopenmp "
export LAPACK_LIB=$BLASOPT

export USE_SCALAPACK=yes
export SCALAPACK_SIZE=8
export SCALAPACK="$BLASOPT -lmkl_scalapack_ilp64 -lmkl_blacs_intelmpi_ilp64 "
export SCALAPACK_LIB=$SCALAPACK

export IB_HOME=/home/users/astar/ihpc/chiensh/apps/usr
export IB_INCLUDE=$IB_HOME/include/infiniband
export IB_LIB=$IB_HOME/lib64
export IB_LIB_NAME="-lrdmacm -libumad -libverbs -ldl -lpthread -lm "

export MPI_INCLUDE="-I/home/users/app/intel_psxe_2018_update2/compilers_and_libraries_2018.2.199/linux/mpi/intel64/include"
export LIBMPI="-L/home/users/app/intel_psxe_2018_update2/compilers_and_libraries_2018.2.199/linux/mpi/intel64/lib  -lmpifort  -lmpi_ilp64 -lmpi_mt -lmpi -lpthread"

export USE_PYTHON64=y
export PYTHONVERSION=2.7
export PYTHONHOME=/usr
export PYTHONLIBTYPE=so

export NWCHEM_MODULES="all"

export CCSDTQ=y
export CCSDTLR=y
export MRCC_METHODS=TRUE
#unset CCSDTQ
#unset CCSDTLR
#unset MRCC_METHODS

export CC=icc
export FC=ifort
export F77=ifort
export F90=ifort
export CXX=icpc_

Thanks for your advice!

~Dominic

**Comment by mjklemm** [comment]
I think one of my latest patches caused that problem.  I will have a look and provide a fix.
