### ISSUE TITLE
Has NWCHEM implemented analytical gradient in UHF TDDFT?

### ISSUE THREAD

**Issue by xiongyan21** [nwchemgit/nwchem#161]
I know TDDFT in NWCHEM can include triplet states vertical excitation energies, but has it implemented analytical gradient in UHF TDDFT?
In GAMESS analytical gradient can be used it with UHF TDDFT, UHF and ROHF SF-TDDFT, which greatly facilitates the geometry search of triplet states, MECIs, important in photochemistry, etc. I have tried the uhf-TDDFT gradient of triplet oxygen(2019 R1 Patch1) and SF-TDDFT geometry search of the triplet state of a petscide molecule.
According to an published article, SF-TDDFT, programmed in noncollinear instead, Tamm-Dancoff way , can correctly reproduce the branching plane of oxirane.

**Comment by hjjvandam** [comment]
Hi Xiongyan,

The TDDFT code I know in NWChem does not support spin unrestricted calculations. I know there have been discussions in the past about non-collinear approaches, but I don’t know if that was ever implemented.

Huub

-----------------------------------------------------------------------------------------------------
Hubertus van Dam, 631-344-6020, hvandam@bnl.gov<mailto:hvandam@bnl.gov>
Brookhaven National Laboratory

**Comment by xiongyan21** [comment]
QA test tddftgrad_phenoxy_radical is the calculation of TDDFT gradient with UHF.
The log file is attached.


I will try that of triplet oxygen with NWCHEM and compare the result with that from GAMESS.

**Comment by xiongyan21** [comment]
QA test tddftgrad_phenoxy_radical is the calculation of TDDFT gradient with UHF.
The log file is attached.


I will try that of triplet oxygen with NWCHEM and compare the result with that from GAMESS.
