### ISSUE TITLE
Segmentation Violation in nwchem

### ISSUE THREAD

**Issue by debuggercz** [nwchemgit/nwchem#163]
Hello.

I have instaled nwchem version 6.8.1 from repositories on CentOS 7 (yum install nwchem-mpich.x86_64 nwchem-openmpi.x86_64), but when I run "nwchem_openmpi wat.nw" I get:

0:Segmentation Violation error, status=: 11
(rank:0 hostname:hostname pid:11857):ARMCI DASSERT fail. src/common/signaltrap.c:SigSegvHandler():315 cond:0

`-bash-4.2$ nwchem_openmpi wat.nw_test 
--------------------------------------------------------------------------
[[27888,1],0]: A high-performance Open MPI point-to-point messaging module
was unable to find any relevant network interfaces:

Module: OpenFabrics (openib)
  Host: hostname

Another transport will be used instead, although this may result in
lower performance.
--------------------------------------------------------------------------
 argument  1 = wat.nw_test
                                         
                                         

              Northwest Computational Chemistry Package (NWChem) 6.8
              ------------------------------------------------------

                    Environmental Molecular Sciences Laboratory
                       Pacific Northwest National Laboratory
                                Richland, WA 99352

                              Copyright (c) 1994-2017
                       Pacific Northwest National Laboratory
                            Battelle Memorial Institute

             NWChem is an open-source computational chemistry package
                        distributed under the terms of the
                      Educational Community License (ECL) 2.0
             A copy of the license is included with this distribution
                              in the LICENSE.TXT file

                                  ACKNOWLEDGMENT
                                  --------------

            This software and its documentation were developed at the
            EMSL at Pacific Northwest National Laboratory, a multiprogram
            national laboratory, operated for the U.S. Department of Energy
            by Battelle under Contract Number DE-AC05-76RL01830. Support
            for this work was provided by the Department of Energy Office
            of Biological and Environmental Research, Office of Basic
            Energy Sciences, and the Office of Advanced Scientific Computing.

           Job information
           ---------------

    hostname        = hostname
    program         = nwchem_openmpi
    date            = Sat Nov  9 20:24:57 2019

    compiled        = Fri_May_17_19:46:39_2019
    source          = /builddir/build/BUILD/nwchem-6.8.1
    nwchem branch   = 6.8.1
    nwchem revision = v6.8-133-ge032219
    ga revision     = 
    use scalapack   = T
    input           = wat.nw_test
    prefix          = wat.
    data base       = /storage/home/user/wat/wat.db
    status          = startup
    nproc           =        1
    time left       =     -1s

           Memory information
           ------------------

    heap     =   65535996 doubles =    500.0 Mbytes
    stack    =   65536001 doubles =    500.0 Mbytes
    global   =  131072000 doubles =   1000.0 Mbytes (distinct from heap & stack)
    total    =  262143997 doubles =   2000.0 Mbytes
    verify   = no 
    hardfail = no 

           Directory information
           ---------------------

  0 permanent = /storage/home/user/wat
  0 scratch   = .

...
...

      Screening Tolerance Information
      -------------------------------
          Density screening/tol_rho:  1.00D-10
          AO Gaussian exp screening on grid/accAOfunc:  14
          CD Gaussian exp screening on grid/accCDfunc:  20
          XC Gaussian exp screening on grid/accXCfunc:  20
          Schwarz screening/accCoul:  1.00D-08

0:Segmentation Violation error, status=: 11
(rank:0 hostname:hostname pid:11857):ARMCI DASSERT fail. src/common/signaltrap.c:SigSegvHandler():315 cond:0
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI COMMUNICATOR 4 DUP FROM 0 
with errorcode 11.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------`

I did debugging of segmentation violation using valgrind. There is a problem
inside libraries which nwchem calls.

==23287==
==23287== HEAP SUMMARY:
==23287==     in use at exit: 1,109,678,422 bytes in 11,244 blocks
==23287==   total heap usage: 27,412 allocs, 16,168 frees, 1,134,320,673
bytes allocated
==23287==
==23287== LEAK SUMMARY:
==23287==    definitely lost: 13,838 bytes in 50 blocks
==23287==    indirectly lost: 903 bytes in 14 blocks
==23287==      possibly lost: 980 bytes in 21 blocks
==23287==    still reachable: 1,109,662,701 bytes in 11,159 blocks
==23287==         suppressed: 0 bytes in 0 blocks
==23287== Rerun with --leak-check=full to see details of leaked memory
==23287==
==23287== For counts of detected and suppressed errors, rerun with: -v
==23287== Use --track-origins=yes to see where uninitialised values come
from
==23287== ERROR SUMMARY: 8 errors from 8 contexts (suppressed: 0 from 0)

I have updated all libraries, checked possible mismatch arch (x64 vs
i386), tried several kernels ... nothing helped.

To set environment and PATH I am using:

source  /etc/profile.d/nwchem.sh
module load mpi/openmpi-x86_64
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib64/mpich/lib/

Can you help me with this, please?
Thank you

Michal

**Comment by edoapra** [comment]
@debuggercz  the following is not correct, but should be harmless
```
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib64/mpich/lib/
```
Can you try without it?
Could you please send me the output of the following commands, too
```
ldd `which nwchem_openmpi`
rpm -q -a | grep ga-
rpm -q -a | grep openmpi-
mpirun -np 2 --mca btl self,sm nwchem_openmpi wat.nw
```

**Comment by edoapra** [comment]
Could you also try the following
```
mpirun -n 1  --mca btl ^openib nwchem_openmpi wat.nw
```

**Comment by debuggercz** [comment]
Hello.

Thank you for you help.

> @debuggercz the following is not correct, but should be harmless
> 
> ```
> export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib64/mpich/lib/
> ```
> 
> Can you try without it?

If I don't use it, I get missing library error.

-bash-4.2$ cd /storage/home/user/wat/; nwchem_openmpi wat.nw
nwchem_openmpi: error while loading shared libraries: libscalapack.so.2: cannot open shared object file: No such file or directory

I also tried to copy missing library.

cp /usr/lib64/mpich/lib/libscalapack.so.2* /lib64/

Then I can run the program, but I get Segmentation Violation error like before.



> Could you please send me the output of the following commands, too
> 
> ```
> ldd `which nwchem_openmpi`

-bash-4.2$ ldd `which nwchem_openmpi`
        linux-vdso.so.1 =>  (0x00007ffdbf688000)
        libga.so.1 => /usr/lib64/openmpi/lib/libga.so.1 (0x00007f542fdd5000)
        libarmci.so.0 => /usr/lib64/openmpi/lib/libarmci.so.0 (0x00007f542faf4000)
        libpython2.7.so.1.0 => /lib64/libpython2.7.so.1.0 (0x00007f542f728000)
        libopenblas.so.0 => /lib64/libopenblas.so.0 (0x00007f542d234000)
        libmpi.so.12 => /usr/lib64/openmpi/lib/libmpi.so.12 (0x00007f542cf50000)
        libmpi_usempi.so.5 => /usr/lib64/openmpi/lib/libmpi_usempi.so.5 (0x00007f542cd4d000)
        libmpi_mpifh.so.12 => /usr/lib64/openmpi/lib/libmpi_mpifh.so.12 (0x00007f542caf8000)
        libibverbs.so.1 => /lib64/libibverbs.so.1 (0x00007f542c8df000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f542c6c3000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f542c4bf000)
        libutil.so.1 => /lib64/libutil.so.1 (0x00007f542c2bc000)
        libgfortran.so.3 => /lib64/libgfortran.so.3 (0x00007f542bf9a000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f542bc98000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f542ba82000)
        libquadmath.so.0 => /lib64/libquadmath.so.0 (0x00007f542b846000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f542b478000)
        libscalapack.so.2 => not found
        libscalapack.so.2 => not found
        libopen-rte.so.12 => /usr/lib64/openmpi/lib/libopen-rte.so.12 (0x00007f542b1fc000)
        libopen-pal.so.13 => /usr/lib64/openmpi/lib/libopen-pal.so.13 (0x00007f542af58000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f542ad50000)
        libhwloc.so.5 => /lib64/libhwloc.so.5 (0x00007f542ab13000)
        libnl-route-3.so.200 => /lib64/libnl-route-3.so.200 (0x00007f542a8a6000)
        libnl-3.so.200 => /lib64/libnl-3.so.200 (0x00007f542a685000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f5430243000)
        libnuma.so.1 => /lib64/libnuma.so.1 (0x00007f542a47a000)
        libltdl.so.7 => /lib64/libltdl.so.7 (0x00007f542a270000)



> rpm -q -a | grep ga-

-bash-4.2$ rpm -q -a | grep ga-
ga-common-5.6.5-6.el7.noarch
ga-openmpi-5.6.5-6.el7.x86_64
ga-mpich-5.6.5-6.el7.x86_64



> rpm -q -a | grep openmpi-

-bash-4.2$ rpm -q -a | grep openmpi-
openmpi-1.10.7-5.el7.x86_64
openmpi-devel-1.10.7-5.el7.x86_64
ga-openmpi-5.6.5-6.el7.x86_64
nwchem-openmpi-6.8.1-8.el7.x86_64


> mpirun -np 2 --mca btl self,sm nwchem_openmpi wat.nw
> ```

-bash-4.2$ mpirun -np 2 --mca btl self,sm nwchem_openmpi wat.nw
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
nwchem_openmpi: error while loading shared libraries: libscalapack.so.2: cannot open shared object file: No such file or directory


When I add necessary library and run it again ...

-bash-4.2$ export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib64/mpich/lib/
-bash-4.2$ mpirun -np 2 --mca btl self,sm nwchem_openmpi wat.nw
 argument  1 = wat.nw
                                         
                                         


              Northwest Computational Chemistry Package (NWChem) 6.8
              ------------------------------------------------------


                    Environmental Molecular Sciences Laboratory
                       Pacific Northwest National Laboratory
                                Richland, WA 99352

                              Copyright (c) 1994-2017
                       Pacific Northwest National Laboratory
                            Battelle Memorial Institute

             NWChem is an open-source computational chemistry package
                        distributed under the terms of the
                      Educational Community License (ECL) 2.0
             A copy of the license is included with this distribution
                              in the LICENSE.TXT file

                                  ACKNOWLEDGMENT
                                  --------------

            This software and its documentation were developed at the
            EMSL at Pacific Northwest National Laboratory, a multiprogram
            national laboratory, operated for the U.S. Department of Energy
            by Battelle under Contract Number DE-AC05-76RL01830. Support
            for this work was provided by the Department of Energy Office
            of Biological and Environmental Research, Office of Basic
            Energy Sciences, and the Office of Advanced Scientific Computing.


           Job information
           ---------------

    hostname        = hostname
    program         = nwchem_openmpi
    date            = Mon Nov 11 20:06:51 2019

    compiled        = Fri_May_17_19:46:39_2019
    source          = /builddir/build/BUILD/nwchem-6.8.1
    nwchem branch   = 6.8.1
    nwchem revision = v6.8-133-ge032219
    ga revision     = 
    use scalapack   = T
    input           = wat.nw
    prefix          = wat.
    data base       = /storage/home/user/wat/wat.db
    status          = startup
    nproc           =        2
    time left       =     -1s



           Memory information
           ------------------

    heap     =   13107198 doubles =    100.0 Mbytes
    stack    =   13107195 doubles =    100.0 Mbytes
    global   =   26214400 doubles =    200.0 Mbytes (distinct from heap & stack)
    total    =   52428793 doubles =    400.0 Mbytes
    verify   = yes
    hardfail = no 


           Directory information
           ---------------------

  0 permanent = /storage/home/user/wat
  0 scratch   = .


...
...

      Screening Tolerance Information
      -------------------------------
          Density screening/tol_rho:  1.00D-10
          AO Gaussian exp screening on grid/accAOfunc:  14
          CD Gaussian exp screening on grid/accCDfunc:  20
          XC Gaussian exp screening on grid/accXCfunc:  20
          Schwarz screening/accCoul:  1.00D-08

0:Segmentation Violation error, status=: 11
(rank:0 hostname:hostname pid:37347):ARMCI DASSERT fail. src/common/signaltrap.c:SigSegvHandler():315 cond:0
1:Segmentation Violation error, status=: 11
(rank:1 hostname:hostname pid:37348):ARMCI DASSERT fail. src/common/signaltrap.c:SigSegvHandler():315 cond:0
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI COMMUNICATOR 4 DUP FROM 0 
with errorcode 11.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------

Thank you
Michal

**Comment by debuggercz** [comment]
> Could you also try the following
> 
> ```
> mpirun -n 1  --mca btl ^openib nwchem_openmpi wat.nw
> ```

cp /usr/lib64/mpich/lib/libscalapack.so.2* /lib64/
-bash-4.2$ mpirun -n 1  --mca btl ^openib nwchem_openmpi wat.nw
 argument  1 = wat.nw
                                         
                                         


              Northwest Computational Chemistry Package (NWChem) 6.8
              ------------------------------------------------------


                    Environmental Molecular Sciences Laboratory
                       Pacific Northwest National Laboratory
                                Richland, WA 99352

                              Copyright (c) 1994-2017
                       Pacific Northwest National Laboratory
                            Battelle Memorial Institute

             NWChem is an open-source computational chemistry package
                        distributed under the terms of the
                      Educational Community License (ECL) 2.0
             A copy of the license is included with this distribution
                              in the LICENSE.TXT file

                                  ACKNOWLEDGMENT
                                  --------------

            This software and its documentation were developed at the
            EMSL at Pacific Northwest National Laboratory, a multiprogram
            national laboratory, operated for the U.S. Department of Energy
            by Battelle under Contract Number DE-AC05-76RL01830. Support
            for this work was provided by the Department of Energy Office
            of Biological and Environmental Research, Office of Basic
            Energy Sciences, and the Office of Advanced Scientific Computing.


           Job information
           ---------------

    hostname        = hostname
    program         = nwchem_openmpi
    date            = Mon Nov 11 20:10:41 2019

    compiled        = Fri_May_17_19:46:39_2019
    source          = /builddir/build/BUILD/nwchem-6.8.1
    nwchem branch   = 6.8.1
    nwchem revision = v6.8-133-ge032219
    ga revision     = 
    use scalapack   = T
    input           = wat.nw
    prefix          = wat.
    data base       = /storage/home/user/wat/wat.db
    status          = startup
    nproc           =        1
    time left       =     -1s



           Memory information
           ------------------

    heap     =   13107198 doubles =    100.0 Mbytes
    stack    =   13107195 doubles =    100.0 Mbytes
    global   =   26214400 doubles =    200.0 Mbytes (distinct from heap & stack)
    total    =   52428793 doubles =    400.0 Mbytes
    verify   = yes
    hardfail = no 


           Directory information
           ---------------------

  0 permanent = /storage/home/user/wat
  0 scratch   = .


...
...


--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI COMMUNICATOR 4 DUP FROM 0 
with errorcode 11.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
0:Segmentation Violation error, status=: 11
(rank:0 hostname:hostname pid:37517):ARMCI DASSERT fail. src/common/signaltrap.c:SigSegvHandler():315 cond:0
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[53290,1],0]
  Exit code:    11
--------------------------------------------------------------------------

**Comment by edoapra** [comment]
@debuggercz the scalapack library is likely to be the root cause of your segmentation fault.
You seem to have the mpich scalapack library installed, but you need the openmpi, instead.
Could you please unset LD_LIBRARY_PATH and install the openmpi scalapack library by typing
```
sudo yum install scalapack-openmpi
```

**Comment by debuggercz** [comment]
> @debuggercz the scalapack library is likely to be the root cause of your segmentation fault.
> You seem to have the mpich scalapack library installed, but you need the openmpi, instead.
> Could you please unset LD_LIBRARY_PATH and install the openmpi scalapack library by typing
> 
> ```
> sudo yum install scalapack-openmpi
> ```

You're right! When I used library from repository, everything works.

Thank you!
Michal
