### ISSUE TITLE
NWChem 7.0.0 beta 1 failed when the pool of memory is specified.

### ISSUE THREAD

**Issue by rangsimanketkaew** [nwchemgit/nwchem#164]
Hi,

I had run NWChem 7.0.0 beta 1 with specification of amount of pool of memory, e.g. global memory, like this

`memory total 450 global 200 mb`

but it failed with the following error:

```
[0] ARMCI Error: 0:inp_match: units missing:
Abort(-1) on node 0 (rank 0 in comm 496): application called MPI_Abort(comm=0x84000003, -1) - process 0
```

Have you found this issue and how to resolve it? Not sure if this a bug or a new feature of the upcoming v.7.0.0 so I just report it here.

Regards,
Rangsiman

**Comment by jeffhammond** [comment]
Use `memory total 450 mb global 200 mb` instead.

**Comment by rangsimanketkaew** [comment]
Sorry for late reply and nwchem works well with your suggested commands. :)
Thanks again.
