### ISSUE TITLE
Missing files to compile the `mrpt`  documentation

### ISSUE THREAD

**Issue by alejandrogallo** [nwchemgit/nwchem#167]
There are missing files in order to compile the TeX document found at
`
nwchem/src/mrpt/fci/doc/matrixelements.tex
`,
the files are `commands.tex` and `bibstuff.tex`.

**Comment by alejandrogallo** [comment]
I have a working version creating a pdf (instead of a postscript document), if it's useful I can submit a pull-request.

**Comment by edoapra** [comment]
File checked into master branch
