### ISSUE TITLE
dplot in nwchem-6.8

### ISSUE THREAD

**Issue by houzf** [nwchemgit/nwchem#168]
dplot_input.F:
78       if (.not. rtdb_cget(rtdb, 'task:theory', 1, theory))
 79      $     call errquit('dplot_inp: theory not specified',555,
 80      &       INPUT_ERR)
 81       if (.not. rtdb_cget(rtdb, theory(1:inp_strlen(theory))//
 82      A     ':output vectors', 1, file_vec)) then
 83          file_vec = ' '
 84       endif

This caused a failure for the examples (molecular orbital analysis of N2 molecule) in http://www.nwchem-sw.org/index.php/Release66:DPLOT :
dplot_inp: theory not specified                 555
 ------------------------------------------------------------------------
 ------------------------------------------------------------------------
  current input line :
    10:     dplot
 ------------------------------------------------------------------------
 ------------------------------------------------------------------------
 There is an error in the input file

**Comment by edoapra** [comment]
@houzf Thanks for reporting this bug.
The bug has been fixed with commit https://github.com/nwchemgit/nwchem/commit/51b62090a40aecb43698167a5e899865cfc9a51a
The bug fix is available in the master and release-7-0-0 branches.
Tar files are available for the first beta version for the upcoming 7.0.0 release at
https://github.com/nwchemgit/nwchem/releases/tag/v7.0.0-beta1

**Comment by edoapra** [comment]
No further feedback received in more than 10 days

**Comment by krarmd** [comment]
I'm getting this error as well, but I don't know if I can use NWchem 7.0. I downloaded Ubuntu 18.04 for WSL and installed NWchem 6.8 from this link as suggested at this support page.

Is there a way of implementing this fix for NWchem 6.8 running on a WSL Ubuntu 18.04 on Windows 10?

**Comment by edoapra** [comment]
No, you need to use NWChem 7.0.0
Fedora 32 will have RPMs available soon (in a matter of days)
You might want to install Fedora 32 under WSL and  then install NWChem

**Comment by edoapra** [comment]
@kramd I have good news for you. NWChem packages are now available for Ubuntu 18.
Here are the installation instructions
```
sudo apt -y install curl  python3-dev gfortran  mpi-default-bin mpi-default-dev libopenblas-dev ssh

curl -LJO https://github.com/nwchemgit/nwchem/releases/download/v7.0.0-release/nwchem-data_7.0.0-3_all.ubuntu_bionic.deb
curl -LJO https://github.com/nwchemgit/nwchem/releases/download/v7.0.0-release/nwchem_7.0.0-3_amd64.ubuntu_bionic.deb

sudo dpkg -i nwchem_7.0.0-3*.bionic.deb

```
