### ISSUE TITLE
  dft CPHF2 read: failed to open./qmd props.aoresp fiao f1

### ISSUE THREAD

**Issue by xiongyan21** [nwchemgit/nwchem#172]
Although I have repeated the test, in the log file, there is "dft_CPHF2_read: failed to open./qmd_props.aoresp_fiao_f1" and "dft_CPHF2_read: failed to open./qmd_props.aoresp_fiao_f2".
[qmd_props.log](https://github.com/nwchemgit/nwchem/files/4022881/qmd_props.log)

**Comment by xiongyan21** [comment]
The original output of the QA test also has
dft_CPHF2_read: failed to open./qmd_props.aoresp_fiao_f1
dft_CPHF2_read: failed to open./qmd_props.aoresp_fiao_f2

**Comment by UmutOzuguzel** [comment]
Let me know if you can fix this issue, I have the same problem on one of my models. The rest works fine.

**Comment by edoapra** [comment]
@UmutOzuguzel Please post input, output and error files. 
The following line is just a warning, the calculation should have been able to complete
```
dft_CPHF2_read: failed to open./qmd_props.aoresp_fiao_f1
```
Please let me know if your calculation did not proceed any further

**Comment by UmutOzuguzel** [comment]
[input&output.zip](https://github.com/nwchemgit/nwchem/files/4092985/input.output.zip)
@edoapra Thank you for your answer. I am trying to replicate the results from the supporting paper attached. I am using "recipe 3" for resonance Raman calculations, and I could successfully get results from most of my molecules. After checking the output file from my other calculations, I realized it was just a warning, however my calculation stops there.

You can find the input & output file for "recipe 3, step 2". I already provided the frequencies and optimized geometry from the previous calculation, though I did not post it here.

Also, if you are familiar with resonance Raman calculations on nwchem, please let me know.

Thank you,
Umut
[jp411039m_si_001.pdf](https://github.com/nwchemgit/nwchem/files/4093002/jp411039m_si_001.pdf)

**Comment by edoapra** [comment]
@UmutOzuguzel the jobs was killed with signal 9. This could be due to a variety of reasons (e.g. job running out of wall-time, out-of-memory conditions, etc ...) that might not be directly related to NWChem.
