### ISSUE TITLE
X + COSMO

### ISSUE THREAD

**Issue by amnikitin** [nwchemgit/nwchem#18]
Hi,

In the latest versions NWChem in the src\solvation\cosmo_def_radii.F file appeared next:

         if(.not.geom_tag_to_element(aname, symb, elem, atn)) 
     +     call errquit('cosmo def radii:cannot resolve tag'
     +                  //aname, 0,0)

This entry does not allow working with dummy points (X) in COSMO.
I deleted this entry. It seems to me that the program works correctly.
Could you fix it?

Example:

     charge 0
     
     set geom:dont_verify .true.
     
     geometry    # noautoz noautosym
      #symmetry d2h 
            O   4.00000000   1.00000000   0.00000000   
            H   4.00000000   1.78169000  -0.55244000   
            H   4.00000000   0.21831000  -0.55244000   
            X   4.00000000   1.00000000  -0.17500000   
     end 
     
     basis spherical
      * library def2-svpd
     end 
     
     scf 
      maxiter 200 
     end 
     
     dft 
      cgmin 
      xc pbe0
      disp vdw 3 
      grid fine 
      convergence energy 1d-7  density 1e-6  gradient 5e-5 
     end 
     
     esp 
      recalculate 
      probe   0.055
      range   0.35
      factor  1
      spacing 0.015
     end 
     
     property 
      nbofile  
      dipole 
      quadrupole 
      octupole 
     end 
     
     task DFT property
     task esp

**Comment by xiongyan21** [comment]
I have tried the inputs with and without X using NWCHEM6.8 unchanged on both Ubuntu17.10 and macOS High Sierra 10.13.3, and all the calculations can finish.
[cosmos.log](https://github.com/nwchemgit/nwchem/files/1738745/cosmos.log)
[cosmos1.log](https://github.com/nwchemgit/nwchem/files/1738748/cosmos1.log)

**Comment by amnikitin** [comment]
Sorry I missed cosmo.

    set geom:dont_verify .true.
    
    charge 0
    
    geometry    # noautoz noautosym
       O   4.00000000   1.00000000   0.00000000   # 1
       H   4.00000000   1.78169000  -0.55244000   # 2
       H   4.00000000   0.21831000  -0.55244000   # 3
       X   4.00000000   1.00000000  -0.17500000   # 4
    end 
    
    basis spherical
     * library def2-svpd
    end 
    
    dft 
     cgmin 
     xc pbe0
     disp vdw 3 
     grid fine 
    end 
    
    cosmo 
     dielec 78.4
    end 
    
    esp 
     recalculate 
     probe   0.055
     range   0.35
     factor  1
     spacing 0.02
    end 
    
    task DFT property
    task esp

I do not have 6.8, so it's 6.6.

result:

` cosmo def radii:cannot resolve tagX                                  0`

**Comment by xiongyan21** [comment]
Yes， you are right. When the cosmo group is added, the error can be reproduced with the entity X. Perhaps this is a little difficult to find a solution.
[cosmos6.log](https://github.com/nwchemgit/nwchem/files/1739761/cosmos6.log)
[cosmos5.log](https://github.com/nwchemgit/nwchem/files/1739763/cosmos5.log)

**Comment by amnikitin** [comment]
Here is the question. What is the X radius in COSMO and what is the X radius in ESP?
It seems to me that they should be zero both.
However, apparently it is not so.

**Comment by amnikitin** [comment]
Yet another related to the ESP thing.
Could you make user-defined radii for ESP?
Not by element, but by atom.
Such control is in COSMO, but not in ESP. This is very restrictive.

**Comment by edoapra** [comment]
Commit e125383773285096779bea9d3752a24d712ab29f  addresses the X dummy points in ESP
No need to input  user-defined radii for it
