### ISSUE TITLE
Fail to rebuild 6.8.1 with Homebrew on macOS due to OpenMPI 4 incompatibility

### ISSUE THREAD

**Issue by zbeekman** [nwchemgit/nwchem#181]
Hi, Homebrew maintainer here.

We're working to migrate our default BLAS/LAPACK implementation, OpenBLAS, to build with native macOS clang tooling rather than gcc-9 (Fortran still uses gfortran-9). During this process nwchem is failing to build due to incompatibilities with OpenMPI 4.0.2. In particular, were getting an error message about usage of a removed/deprecated MPI type/macro:

```
libtool: compile:  clang -DHAVE_CONFIG_H -I. -I../../ga-5.6.5/comex -I/usr/local/Cellar/open-mpi/4.0.2/include -I/usr/local/Cellar/open-mpi/4.0.2/lib -I../../ga-5.6.5/comex/src-common -I../../ga-5.6.5/comex/src-mpi -fPIC -DMPICH_NO_ATTR_TYPE_TAGS -MT src-armci/message.lo -MD -MP -MF src-armci/.deps/message.Tpo -c ../../ga-5.6.5/comex/src-armci/message.c -o src-armci/message.o
../../ga-5.6.5/comex/src-armci/message.c:265:9: error: static_assert failed "MPI_Type_struct was removed in MPI-3.0.  Use MPI_Type_create_struct instead."
        MPI_Type_struct(2, block, disp, type, &MPI_LONGLONG_INT);
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/Cellar/open-mpi/4.0.2/include/mpi.h:2850:31: note: expanded from macro 'MPI_Type_struct'
#define MPI_Type_struct(...)  THIS_SYMBOL_WAS_REMOVED_IN_MPI30(MPI_Type_struct, MPI_Type_create_struct)
                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/Cellar/open-mpi/4.0.2/include/mpi.h:322:57: note: expanded from macro 'THIS_SYMBOL_WAS_REMOVED_IN_MPI30'
#define THIS_SYMBOL_WAS_REMOVED_IN_MPI30(func, newfunc) _Static_assert(0, #func " was removed in MPI-3.0.  Use " #newfunc " instead.")
                                                        ^              ~
1 error generated.
```

I have attached the full build log. The error is near the bottom, and some additional information about the environment is at the very bottom.

[nwchem-failure.txt](https://github.com/nwchemgit/nwchem/files/4220618/nwchem-failure.txt)

Is this already resolved in the beta release? If so is there a patch I can back-port while we wait for nwchem 7.x?

Thanks!

CC: @jeffhammond if you have any thoughts on the matter

**Comment by edoapra** [comment]
@zbeekman Yes, this is fixed in ga 5.7.1 https://github.com/GlobalArrays/ga/pull/156/commits/0c6b0f7c0955af31589858938de1e2130518dd11 used by NWChem 7.0.0 
https://github.com/nwchemgit/nwchem/releases/tag/v7.0.0-beta2
 I don't see any reason to backport fix from 7.0.0 since we should be releasing 7.0.0  before the end of this month (and ga 5.7.1 should be out too https://github.com/GlobalArrays/ga/tree/hotfix/5.7.1)
A beta of 7.0.0 is available for download 
https://github.com/nwchemgit/nwchem/releases/tag/v7.0.0-beta2

**Comment by jeffhammond** [comment]
@zbeekman Is NWChem supported by Homebrew now?

**Comment by jeffhammond** [comment]
This was fixed by https://github.com/GlobalArrays/ga/pull/127 and https://github.com/GlobalArrays/ga/pull/131.

Per https://www.open-mpi.org/faq/?category=mpi-removed, you can support deleted symbols in Open-MPI via `--enable-mpi1-compatibility`, but I strongly discourage this for the reasons described on that page.

**Comment by zbeekman** [comment]
@jeffhammond it's been packaged by homebrew for a while now. (Since september 17 2018)

Thanks for the tip. I might just sit on the OpenBLAS migration to native Apple Clang for a week or two until nwchem 7.0 releases. If i'm feeling ambitious I'll see about a temporary hack like the one you mentioned, but CI takes 11 hours to rebuild all the packages downstream of OpenBLAS, so there's not much room for experimentation.

**Comment by jeffhammond** [comment]
@zbeekman Why don't you use Apple Accelerate?

**Comment by zbeekman** [comment]
Homebrew has had problems with it in the past, and it’s not actively
maintained and updated as OpenBLAS is. From what we’ve seen the quality of
implementation is as good or better in OpenBLAS. It also simplified
maintaining Homebrew on/for Linux.

**Comment by edoapra** [comment]
@zbeekman I am close at releasing NWChem 7.0.0. and creating a pull request on homebrew for the updated nwchem formula
https://github.com/edoapra/homebrew-core/blob/nwchem-7.0.0/Formula/nwchem.rb

**Comment by edoapra** [comment]
Pull request
https://github.com/Homebrew/homebrew-core/pull/50745
