### ISSUE TITLE
Python 3 support?

### ISSUE THREAD

**Issue by zbeekman** [nwchemgit/nwchem#182]
The installation instructions [reference extremely old and antiquated python versions.](https://github.com/nwchemgit/nwchem/blob/master/INSTALL#L366) Python 2 is now [past EOL](https://pythonclock.org/)

Will nwchem python support build against Python 3? Do we need to do anything differently to do so?

Thanks!

**Comment by edoapra** [comment]
@zbeekman Fixed in 7.0.0
See some details in
https://github.com/nwchemgit/nwchem/issues/136

**Comment by zbeekman** [comment]
I have a suspicion that the nwchem formula will need some serious love upon the 7.0 release. If any of you guys can guide us on what needs changing, your feedback is most welcome:

https://github.com/homebrew/homebrew-core/tree/master/Formula/nwchem.rb

**Comment by edoapra** [comment]
@zbeekman Since I was the original perpetrator of the homebrew nwchem formula, I will work on it

**Comment by zbeekman** [comment]
Ok, great, thanks so much!

**Comment by zbeekman** [comment]
I don't see a reason to keep this open so I'm closing this issue.
