### ISSUE TITLE
Executable file (without source?) fsplit.x in source

### ISSUE THREAD

**Issue by mbanck** [nwchemgit/nwchem#185]
Debian's lintian checker flags an error:

> E: nwchem source: source-is-missing src/tce/ccsdtq_alpha_offdiag/fsplit.x

Indeed, https://github.com/nwchemgit/nwchem/blob/master/src/tce/ccsdtq_alpha_offdiag/fsplit.x is part of the github repo, but due to size restrictions I can't check whether there is source code for it checked in as well.

In any case, I guess this file is not needed for building I guess, so could be removed.

**Comment by edoapra** [comment]
@mbanck thanks for pointing this out.
Would mind answering the question I have asked you on issue https://github.com/nwchemgit/nwchem/issues/184 ?

**Comment by jeffhammond** [comment]
I must have committed this file more than 10 years ago.  `fsplit.x` is compiled from a derivative of [fsplit.c](http://ftp.netbsd.org/pub/NetBSD/NetBSD-current/src/usr.bin/fsplit/fsplit.c).

In any case, this binary should be deleted from the repo.  No one needs it.
