### ISSUE TITLE
nwchem installation

### ISSUE THREAD

**Issue by varesh110** [nwchemgit/nwchem#186]
Hello everyone! 
I have to install nwchem on my notebook (linux-mint). I don't know how fix the resulting error!
here is my attempts:

export NWCHEM_TOP="/home/harir/nwchem-6.8.1-release"
export NWCHEM_MODULES="all"
export NWCHEM_TARGET="LINUX64"
export NWCHEM_LONG_PATHS="y"

export PYTHONHOME="/usr/bin"
export PYTHONVERSION="2.7"
export PYTHONLIBTYPE="so"
export USE_PYTHON64="y"

export USE_NOFSCHECK="y"
export TCGRSH="/usr/bin/ssh"
export LARGE_FILES="y"
export USE_MPI="y"
export USE_MPIF="y"
export USE_MPIF4="y"

export MPI_LOC="/usr/lib/x86_64-linux-gnu/openmpi"
export MPI_INCLUDE="/usr/lib/x86_64-linux-gnu/openmpi/include"
export MPI_LIB="/usr/lib/x86_64-linux-gnu/openmpi/lib"
export LIBMPI="-lmpi_usempif08 -lmpi_usempi_ignore_tkr -lmpi_mpifh -lmpi"
export USE_OPENMP="y"

export HAS_BLAS=yes
BLASOPT="-L/opt/openblas/lib -lopenblas -lopenblas_haswell-r0.3.9" 
############################################
please Note that my "/opt/openblas/lib" directory  includes:
cmake                          libopenblas_haswellp-r0.3.9.a   libopenblas.so.0
lib.grd                        libopenblas_haswellp-r0.3.9.so  pkgconfig
libopenblas.a                  libopenblas_haswell-r0.3.9.a
libopenblas_haswellp-r0.3.7.a  libopenblas.so
############################################
but after make, I faced with the following ERROR:
.....
inv_it3.c:(.text+0x273): undefined reference to `ycopy_'
inv_it3.c:(.text+0x29b): undefined reference to `ycopy_'
inv_it3.c:(.text+0x2e8): undefined reference to `ycopy_'
/home/harir/nwchem-6.8.1-release/lib/LINUX64/libpeigs.a(inv_it3.o):inv_it3.c:(.text+0x320): more undefined references to `ycopy_' follow
/home/harir/nwchem-6.8.1-release/lib/LINUX64/libpeigs.a(inv_it3.o): In function `inv_it3':
inv_it3.c:(.text+0x377): undefined reference to `ylagtf_'
inv_it3.c:(.text+0x3cc): undefined reference to `yasum_'
inv_it3.c:(.text+0x43e): undefined reference to `yscal_'
inv_it3.c:(.text+0x47b): undefined reference to `ylagts_'
inv_it3.c:(.text+0x48f): undefined reference to `iyamax_'
inv_it3.c:(.text+0x698): undefined reference to `ynrm2_'
inv_it3.c:(.text+0x6c6): undefined reference to `yscal_'
inv_it3.c:(.text+0x6f8): undefined reference to `ycopy_'
/home/harir/nwchem-6.8.1-release/lib/LINUX64/libpeigs.a(mgscs.o): In function `mgscs':
mgscs.c:(.text+0x5a5): undefined reference to `ynrm2_'
mgscs.c:(.text+0x5d5): undefined reference to `yscal_'
mgscs.c:(.text+0x5f2): undefined reference to `ycopy_'
mgscs.c:(.text+0x6a6): undefined reference to `ydot_'
mgscs.c:(.text+0x6d9): undefined reference to `yaxpy_'
collect2: error: ld returned 1 exit status
GNUmakefile:33: recipe for target 'all' failed
make: *** [all] Error 1

I will appreciate any help, comments, advice! help me guys... nobody answer me in  nwchem Forum... I have no idea... (╥﹏╥)

**Comment by edoapra** [comment]
@varesh110 
Shima
NWChem 7.0.0 is out.
Please do use 7.0.0 instead of 6.8.1

https://github.com/nwchemgit/nwchem/releases/tag/v7.0.0-release

Thanks

**Comment by varesh110** [comment]
Dear edoapra,
about nwchem7:
###################
export NWCHEM_TOP="/home/harir/nwchem-6.8.1-release"
export NWCHEM_MODULES="all"
export NWCHEM_TARGET="LINUX64"
export NWCHEM_LONG_PATHS="y"



export PYTHONHOME="/usr/bin"
export PYTHONVERSION="3.6"
export PYTHONLIBTYPE="so"
export USE_PYTHON64="y"


export USE_NOFSCHECK="y"
export TCGRSH="/usr/bin/ssh"
export LARGE_FILES="y"
export USE_MPI="y"
export USE_MPIF="y"
export USE_MPIF4="y"

export MPI_LOC="/usr/lib/x86_64-linux-gnu/openmpi"
export MPI_INCLUDE="/usr/lib/x86_64-linux-gnu/openmpi/include"
export MPI_LIB="/usr/lib/x86_64-linux-gnu/openmpi/lib"
export LIBMPI="-lmpi_usempif08 -lmpi_usempi_ignore_tkr -lmpi_mpifh -lmpi"
export USE_OPENMP="y"

export HAS_BLAS=yes
export BLASOPT="/opt/OpenBLAS/lib"
export LAPACK_LIB="/usr/lib/x86_64-linux-gnu/lapack"

export USE_SCALAPACK=y

export SCALAPACK="/usr/local/lib/libscalapack.a"

cd $NWCHEM_TOP
make clean
make 64_to_32
make FC="gfortran" CC="icc"
#######################
ar: creating /home/harir/nwchem-6.8.1-release/lib/LINUX64/lib64to32.a
echo /home/harir/nwchem-6.8.1-release/lib/LINUX64/lib64to32.a
/home/harir/nwchem-6.8.1-release/lib/LINUX64/lib64to32.a
make[2]: Leaving directory '/home/harir/nwchem-7.0.0/src/64to32blas'
make[1]: Leaving directory '/home/harir/nwchem-7.0.0/src/64to32blas'
make nwchem.o stubs.o
make[1]: Entering directory '/home/harir/nwchem-7.0.0/src'
gfortran -m64 -ffast-math  -Warray-bounds -fopenmp -fdefault-integer-8 -fno-tree-dominator-opts  -finline-functions -O2 -g -fno-aggressive-loop-optimizations -fno-tree-dominator-opts  -g -O   -I.  -I/home/harir/nwchem-6.8.1-release/src/include -I/home/harir/nwchem-6.8.1-release/src/tools/install/include -DGFORTRAN -DCHKUNDFLW -DGCC4 -DGCC46 -DUSE_OPENMP -DEXT_INT -DLINUX -DLINUX64 -DPARALLEL_DIAG -DCOMPILATION_DATE="'`date +%a_%b_%d_%H:%M:%S_%Y`'" -DCOMPILATION_DIR="'/home/harir/nwchem-6.8.1-release'" -DNWCHEM_BRANCH="'7.0.0'"  -c -o nwchem.o nwchem.F
make[1]: *** No rule to make target 'stubs.o'.  Stop.
make[1]: Leaving directory '/home/harir/nwchem-7.0.0/src'
GNUmakefile:33: recipe for target 'all' failed
make: *** [all] Error 2
