### ISSUE TITLE
Simint in NWChem

### ISSUE THREAD

**Issue by dmejiar** [nwchemgit/nwchem#187]
I have been trying to use Simint with the master branch (64f6135), but haven't been able to do so. I can compile and link NWChem with Simint, but when I include 

```
set int:cando_txs t
set int:cando_nw t
```
in the input file, I get the following error

```
  int_init: cando_nw set to always be  T
  int_init: cando_txs set to always be  T
  you are trying to turn an integral code on?
  sp   F
  nw   T
  txs  T
  hnd  F
  sim  F
------------------------------------------------------------------------
 int_init: logic error with user cando settings                 911
 ------------------------------------------------------------------------
```

I have used the script to download, generate and compile Simint by setting `USE_SIMINT=y`, `BUILD_SIMINT=y`, and `SIMINT_MAXAM=6`. As a side note, I changed `${NWCHEM_TOP}/src/NWints/simint/GNUMakefile` to replace `ifdef USE_SIMINT` for `ifdef BUILD_SIMINT` in order to be able to skip the generation and compilation of simint every time by unsetting `BUILD_SIMINT` but keeping  `USE_SIMINT=y`. 

Is there another flag I should be using?

**Comment by edoapra** [comment]
USE_SIMINT is the only one needed.
Could you please post the full input file?

Did you compile with USE_SIMINT=y from the beginning, from a clean source?

**Comment by dmejiar** [comment]
I had compiled a previous version without `USE_SIMINT=y`, but then I did 
```
cd ${NWCHEM_TOP}/src
make clean
export USE_SIMINT=y
export BUILD_SIMINT=y
export SIMINT_MAXAM=6
make nwchem_config
make -j 4
```

Should I try a `realclean` or a completely clean tree?

Anyway,  my input was very simple
```
echo
title "SIMINT TEST"
memory stack 2200 mb heap 300 mb global 1200 mb noverify
set grid:eaf_size_in_dbl 100000000
set lindep:n_dep 0
set int:cando_txs t
set int:cando_nw t
#
geometry noautosym
H 0.0 0.0 0.0
H 0.0 0.0 1.2
end
#
basis "ao basis" spherical
 * library pcseg-3
end
#
charge 0
#
dft
 grid fine nodisk
 xc pbe96
 direct
 noprint "final vectors analysis"
end
#
task dft
```
And the output is:
[simint.log](https://github.com/nwchemgit/nwchem/files/4326181/simint.log)

**Comment by edoapra** [comment]
I missed the real problem that you already reported in the first posting. The `set` directives should be set to `false` and not to `true`
```
set int:cando_txs f
set int:cando_nw f
```

**Comment by dmejiar** [comment]
Everything seems to be working now! I can see in the output 

```
  int_init: cando_nw set to always be  F
  int_init: cando_txs set to always be  F

  Using Simint Integral package
  num_der                     0
  simint: mem_2e4c                   1363304
  simint: memb_2e4c                  1499648
  simint: isz_2e4c                   170424
  simint: iszb_2e4c                  170424
  screen_method                      2
  screen_tol   1.000000000000000E-022
```

By the way, the file https://github.com/nwchemgit/nwchem/blob/master/src/NWints/simint/simint.txt says that the `set` directives should be set to `true`.

**Comment by edoapra** [comment]
@dmejiar thanks for reporting this. I have update the instructions. Let me know if things are more clear now

**Comment by dmejiar** [comment]
One more thing, the [release.notes.7.0.0](https://github.com/nwchemgit/nwchem/blob/af6f977/release.notes.7.0.0) mention that the `BUILD_SIMINT`environment variable triggers the download and compilation of simint, but only `USE_SIMINT` is looked for in the makefiles, isn't it?

About the performance, what settings do you recommend for simint? I noticed that the screening threshold seems too tight, does it have the same meaning as `tol2e`?

**Comment by edoapra** [comment]
@dmejiar thanks for pointing this. `USE_SIMINT` is the only variable needed. Mentioning `BUILD_SIMINT` was wrong. I have fixed the release notes accordingly https://github.com/nwchemgit/nwchem/commit/79d4dadce8328ea9f8b16b325aae0e1e27a388e4

What screening threshold are you referring to?

**Comment by dmejiar** [comment]
The one that can be modified by `int:smnt_screen_tol `. 

I have been doing some test calculations with the `pcseg-2` basis, and using simint with AVX-2 instructions is ~50% slower than using the standard integrals. Is that expected?

**Comment by edoapra** [comment]
`int:smnt_screen_tol` has a different meaning compared to `tol2e`, it is more similar to `int:acc_std`

While  tol2e is the threshold used by NWChem for Schwarz screening on the shell quartet integrals, `int:smnt_screen_tol` is used internally by Simint.
The default value of 1d-22 is pretty much on the safe side, based on strict numerical tests for correlated methods. For HF/DFT, you should be able to go to much lower values. 1d-16 might be a good starting point (or even lower https://aip.scitation.org/doi/full/10.1063/1.5129452)

I have not done any systematic benchmarking of Simint vs Texas, but 50% slowdown seems quite a lot to me (but I might be wrong)
