### ISSUE TITLE
6.8 on Windows

### ISSUE THREAD

**Issue by amnikitin** [nwchemgit/nwchem#19]
I try to compile with MinGW as usually. 

       gfortran  -c  -fno-tree-dominator-opts  -m32 -march=pentium4 -mtune=pentium4 -O2  -ffast-math               -Wuninitialized -fno-aggressive-loop-optimizations -fno-tree-dominator-opts  -O2 -ffast-math -Wuninitialized -I. -I/home/Layruoru/MPICH2/include -I/home/Layruoru/nwchem-6.8/src/include -I/home/Layruoru/nwchem-6.8/src/tools/install/include -DLINUX -DGFORTRAN -DGCC46 -DCHKUNDFLW -DGCC4 -DPARALLEL_DIAG  -DMPI -DMPI4  Dne_omp.F
       Dne_omp.F:29:9:
       
       USE omp_lib
         1
       Fatal Error: Can't open module file 'omp_lib.mod' for reading at (1): No such file or directory
       compilation terminated.
       make[4]: *** [/home/Layruoru/nwchem-6.8/lib/LINUX/libnwpwlib.a(Dne_omp.o)] Error 1
       make[3]: *** [optimized] Error 2
       make[2]: *** [subdirs] Error 1
       make[1]: *** [subdirs] Error 1
       make: *** [libraries] Error 1

What to do?

**Comment by jeffhammond** [comment]
What GCC version? Seems no OpenMP support so must be ancient or it’s a MinGW limit.

In any case, we should have build system or preprocessor guard around this code for non-OpenMP compilation.

**Comment by edoapra** [comment]
It's a MinGW limit
 [http://github.com/StephanTLavavej/mingw-distro/issues/32](https://github.com/StephanTLavavej/mingw-distro/issues/32)

**Comment by amnikitin** [comment]
gcc version 6.3.0 (MinGW.org GCC-6.3.0-1)

**Comment by ebylaska** [comment]
I'll work on fixing this....In principle OMP functions should never be called/compiled unless you explicitly compile with USE_OPENMP=y..

**Comment by edoapra** [comment]
I have verified that the change committed by @ebylaska  on master and hotfix/release-6-8 fixes the mingw compilation

https://github.com/nwchemgit/nwchem/commit/b8ff604a9d0931ac31ca1865ce173cff08988277
https://github.com/nwchemgit/nwchem/commit/474ad31c3c9d0d848dd0c09505d4d19f5f90257b

The upcoming maintenance release 6.8.1 will contain the fix

**Comment by A0094316** [comment]
I was trying to compile nwchem 6.8 also (following instructions from https://winmostar.com/en/nwchem4wm_en_win.html). But met the same problem (Use omp_lib Fatal Error: can't open module file 'omp_lib.mod' .....) as amnikitin had. I followed edoapra and copied the changes as in b8ff604 to my Dne_omp.F file. Unfortunately, the same error appeared! Problem was the same. Would anyone look into it further?

**Comment by amnikitin** [comment]
Nwchem compilation is always a nightmare.

**Comment by A0094316** [comment]
@amnikitin Did you eventually get nwchem run on your windows? I almost want to give up.

**Comment by amnikitin** [comment]
The latest version not.
Several previous ones managed to compile, it always took a long time.
If you just need a binary, the old, then there are several on the net. For
example in an Abalone package.

**Comment by edoapra** [comment]
A Win64 binary compiled with the MinGW environment is available from the 7.0.2 release page [https://github.com/nwchemgit/nwchem/releases/download/v7.0.2-release/nwchem-7.0.2_win64.zip](https://github.com/nwchemgit/nwchem/releases/download/v7.0.2-release/nwchem-7.0.2_win64.zip)
Based on my benchmark on a Windows Home Haswell system, this binary is much slower than running NWChem 7.0.2 under [WSL2](https://docs.microsoft.com/en-us/windows/wsl/install-win10) or using [Docker with the WSL2 backend](https://docs.docker.com/docker-for-windows/wsl/)
Based on these benchmark findings, I don't see any reason to work a native Windows build

**Comment by amnikitin** [comment]
> Based on my benchmark on a Windows Home Haswell system, this binary is
> much slower than running NWChem 7.0.2 under WSL2
> <https://docs.microsoft.com/en-us/windows/wsl/install-win10> or using Docker
> with the WSL2 backend <https://docs.docker.com/docker-for-windows/wsl/>
> Based on these benchmark findings, I don't see any reason to work a native
> Windows build
>
How much slower?

**Comment by edoapra** [comment]
3 times slower or worse ... if you are really interested I can run the benchmarks again
