### ISSUE TITLE
Python 3 compatibility of contrib/python/*py scripts

### ISSUE THREAD

**Issue by mdd31** [nwchemgit/nwchem#190]
I've been using the python API for calculations and I have been updating my workflows to python 3. I have been able to get NWChem 7.0.0+ to compile and work with python 3.

However I have found that the contrib/python/nwgeom.py was not updated to conform to the python 3 standard (this is something I make use of for calculations). I've updated this on my own [fork](https://github.com/mdd31/nwchem) and I was wanting to find out whether it would be possible to include these updates in the main source tree. What do I need to do to include these changes?

Did you want me to check the other scripts in the contrib/python folder for compatibility (I only use nwgeom in my scripts), and update those as well for inclusion at the same time?

**Comment by edoapra** [comment]
@mdd31 than you very much for updating `nwgeom.py`
I have created a pull request with your changes and I could merge it https://github.com/nwchemgit/nwchem/pull/191

Instead, if you prefer create the pull request yourself, please let me know

Cheers, Edo

**Comment by mdd31** [comment]
That's great. Thank you.

**Comment by edoapra** [comment]
I have merged the pull request.
Thanks for the contribution.
If you can spot and fix more files that need to be updated for python3 compatibility, please do it

**Comment by mdd31** [comment]
I've create a pull request (#192) for changes to the other contrib files.

**Comment by mdd31** [comment]
I found further issues which I believe I have been able to resolve with the pull request #222 .

**Comment by mdd31** [comment]
@edoapra Thank you for merging the related changes in #191, #192 and #222.

Is it possible to pull these changes into the hotfix 7-0-0 release branch? How would I go about doing this?
Best wishes,
Mark

**Comment by edoapra** [comment]
@mdd31 the changes are in hotfix/7-0-0
Could you tests them?

**Comment by mdd31** [comment]
Hi @edoapra  I've recompiled the hotfix branch and all works.

Thank you for your help.

I think it may be possible to close this issue, as the python scripts all seem to work now.

If I get chance in the future I may try to rewrite some of the functions- this would be more based on code style than function, to make better use of python 3 specific syntax.
