### ISSUE TITLE
-lmpif90 flag passed, ignoring OpenMPIv4 in $PATH

### ISSUE THREAD

**Issue by diracs-delta** [nwchemgit/nwchem#193]
I am trying to compile NWChem 7.0 (git) on an older machine. I have had to install the latest release (v4.3) of OpenMPI manually. This version of OpenMPI does not install a library named `libmpi_f90`. When I compile NWChem, I am met with the following error.

```
/share/apps/gcc/gcc-9.2.0/bin/gfortran   -L/home/davidlq2/Repositories/nwchem-7.0.0/lib/LINUX64 -L/home/davidlq2/Repositories/nwchem-7.0.0/src/tools/install/lib   -o /home/davidlq2/Repositories/nwchem-7.0.0/bin/LINUX64/nwchem nwchem.o stubs.o -lnwctask -lccsd -lmcscf -lselci -lmp2 -lmoints -lstepper -ldriver -loptim -lnwdft -lgradients -lcphf -lesp -lddscf -ldangchang -lguess -lhessian -lvib -lnwcutil -lrimp2 -lproperty -lsolvation -lnwints -lprepar -lnwmd -lnwpw -lofpw -lpaw -lpspw -lband -lnwpwlib -lcafe -lspace -lanalyze -lqhop -lpfft -ldplot -ldrdy -lvscf -lqmmm -lqmd -letrans -lpspw -ltce -lbq -lmm -lcons -lperfm -ldntmc -lccca -ldimqm -lnwcutil -lga -larmci -lpeigs -lperfm -lcons -lbq -lnwcutil    -l64to32 -L/home/davidlq2/.local/lib -lopenblas  -lopenblas -lnwcblas   -L/home/davidlq2/.local/lib -lmpi_usempif08 -lmpi_usempi_ignore_tkr -lmpi_mpifh -lmpi    -lcomex -lmpi_f90 -lmpi_f77 -lmpi -libverbs -ldat -lrt -lnsl -lutil -lm -ldl -lm -lrt -lnsl -lutil -lm -ldl -lopenblas -lrt -lm -lpthread
/usr/bin/ld: cannot find -lmpi_f90
collect2: error: ld returned 1 exit status
make: *** [all] Error 1
```

This is strange because it seems that NWChem is passing the `-lmpi_f90` flag despite me correctly specifying the OpenMPI library directory (located in `$HOME/.local/lib` for me). On the NWChem wiki, it states that NWChem automatically adds linker flags based on the `mpif90` in my `PATH`. However, I've already correctly specified my `PATH` to include my updated user-installed `mpif90`. I checked this by running:

```
 $ which mpif90
~/.local/bin/mpif90
```

which shows the binary I installed into `~/.local`.

I ran the compilation in the following environment:

```
#!/bin/bash

source $HOME/.bashrc

export NWCHEM_TOP=/home/davidlq2/Repositories/nwchem-7.0.0
export NWCHEM_TARGET=LINUX64
export NWCHEM_MODULES="all"
export USE_NOFSCHECK=TRUE
export USE_NOIO=TRUE

export ARMCI_NETWORK=MPI-PR
export USE_MPI=y
# export USE_MPIF=y
# export USE_MPIF4=y

export LIBMPI="-lmpi_usempif08 -lmpi_usempi_ignore_tkr -lmpi_mpifh -lmpi"
export MPI_LOC=/home/davidlq2/.local
export MPI_LIB="/home/davidlq2/.local/lib"
export MPI_INCLUDE="/home/davidlq2/.local/include"

export BLASOPT="-L$HOME/.local/lib -lopenblas"
export LAPACK_LIB=-lopenblas

export BLAS_SIZE=4

cd $NWCHEM_TOP/src
make -j 8 nwchem_config |& tee make_nwchem_config.log
make -j 8 64_to_32 |& tee make_64_to_32.log
make -j 8 |& tee make.log
``` 

I also repeated the compilation by un-commenting the above commented lines, which gave me the same error.

Does anybody know how why NWChem is passing the `-lmpi_f90` flag and other flags corresponding to old OpenMPI libraries to the linker, despite the environmental variables I set? Thank you for spending your time to help me!

**Comment by edoapra** [comment]
My recommendation is to unset MPI_LIB, LIBMPI and MPI_INCLUDE and let NWChem do the guessing for you.
https://github.com/nwchemgit/nwchem/wiki/Compiling-NWChem#mpi-variables

If the problem still persists, could you send the output  of 
```
mpif90 -show
```

**Comment by edoapra** [comment]
One more piece of information needed. Could you please also send (attach) the following file
```
/home/davidlq2/Repositories/nwchem-7.0.0/src/tools/build/config.log
```

**Comment by diracs-delta** [comment]
@edoapra Thank you for the suggestion, but unsetting the MPI environmental variables doesn't help NWChem figure out that it should use the libraries in `~/.local/lib`. Here's the output of `mpif90 -show`:

```
$ mpif90 -show
/share/apps/gcc/gcc-9.2.0/bin/gfortran -I/home/davidlq2/.local/include -pthread -I/home/davidlq2/.local/lib -Wl,-rpath -Wl,/home/davidlq2/.local/lib -Wl,--enable-new-dtags -L/home/davidlq2/.local/lib -lmpi_usempif08 -lmpi_usempi_ignore_tkr -lmpi_mpifh -lmpi
```

As you can see from the above, `mpif90` correctly sources the libraries in `~/.local/include` and does not include the `libmpi_f90` library passed to the linker by NWChem. I've also attached the log [here](https://github.com/diracs-delta/logs/blob/master/config.log). 

Thank you for letting me know the location of the log file. The first few pertinent lines are as follows.

```
  $ ../ga-5.7.1/configure --prefix=/home/davidlq2/Repositories/nwchem-7.0.0/src/tools/install --with-tcgmsg --with-mpi=-I/opt/openmpi/include -I/opt/openmpi/lib -L/opt/openmpi/lib -lmpi_f90 -lmpi_f77 -lmpi -libverbs -ldat -lrt -lnsl -lutil -lm -ldl -lm -lrt -lnsl -lutil -lm -ldl --enable-peigs --enable-underscoring --disable-mpi-tests --without-scalapack --with-lapack=-lopenblas --with-blas4=-L/home/davidlq2/.local/lib -lopenblas --with-mpi-pr CC=/share/apps/gcc/gcc-9.2.0/bin/gcc CXX=/share/apps/gcc/gcc-9.2.0/bin/g++ F77=/share/apps/gcc/gcc-9.2.0/bin/gfortran ARMCI_DEFAULT_SHMMAX_UBOUND=131072

## --------- ##
## Platform. ##
## --------- ##

hostname = gellmann.scs.illinois.edu
uname -m = x86_64
uname -r = 2.6.32-504.16.2.el6.x86_64
uname -s = Linux
uname -v = #1 SMP Wed Apr 22 06:48:29 UTC 2015

/usr/bin/uname -p = unknown
/bin/uname -X     = unknown

/bin/arch              = x86_64
/usr/bin/arch -k       = unknown
/usr/convex/getsysinfo = unknown
/usr/bin/hostinfo      = unknown
/bin/machine           = unknown
/usr/bin/oslevel       = unknown
/bin/universe          = unknown

PATH: /opt/openmpi/bin
PATH: /usr/lib64/qt-3.3/bin
PATH: /usr/local/bin
PATH: /bin
PATH: /usr/bin
PATH: /usr/local/sbin
PATH: /usr/sbin
PATH: /sbin
PATH: /opt/ganglia/bin
PATH: /opt/ganglia/sbin
PATH: /usr/java/latest/bin
PATH: /opt/pdsh/bin
PATH: /opt/rocks/bin
PATH: /opt/rocks/sbin
PATH: /opt/gridengine/bin/linux-x64
PATH: /home/davidlq2/.scripts
PATH: /home/davidlq2/.cargo/bin
PATH: /home/davidlq2/Repositories/bin
PATH: /home/davidlq2/.local/bin
PATH: /home/davidlq2/bin
```

What's interesting is that the outdated libraries are being passed to `configure`. Do you know what might be causing this? Is there a more detailed source available on NWChem's build process so that I can help you debug more?

Thank you!

**Comment by edoapra** [comment]
@diracs-delta as you can see from the log you posted, mpif90 out of `/opt/openmpi/bin`  is selected, instead of the one out of `~/.local/bin`. On top of it, the situation for `LD_LIBRARY_PATH` might be messy, too.
My suggestion is to start from a clean environment when only one MPI installation is used.

**Comment by diracs-delta** [comment]
@edoapra Thanks for the advice. I don't have root privileges on this machine though, so I'll keep looking around for an alternative solution and update this issue if I find anything.

**Comment by edoapra** [comment]
@diracs-delta why don't you try the following, using bash shell
```
unset LD_LIBRARY_PATH
export PATH=/home/davidlq2/.local/bin:/share/apps/gcc/gcc-9.2.0/bin:/usr/bin:/bin:/usr/sbin:/sbin
cd $NWCHEM_TOP/src
rm -rf tools/build
make
```
If this still fails, please send me the same top part of tools/build/config.log

**Comment by diracs-delta** [comment]
@edoapra Thank you for the advice, but I have already resolved the issue. I'm unsure of exactly how this solved it, but I simply rebuilt the entire repository from scratch by deleting NWChem-7.0 and re-cloning it from git. I think this implies that some build files are cached, even after running `make clean`. Completely re-building the repository allowed NWChem-7.0 to find and link to my manually-installed OpenMPI libraries. Thank you for your help!

**Comment by diracs-delta** [comment]
Also, I just looked at the Makefile in `src`. It seems that there is a definition for `realclean` in there, so running

```
make realclean
```

might fix NWChem using old binary and library paths, without having to completely re-clone and re-build the NWChem repository.
