### ISSUE TITLE
Possibly outdated --enable-peigs flag used for external ga-config

### ISSUE THREAD

**Issue by Micket** [nwchemgit/nwchem#196]
Compiling against an external GA, i got stuck on the use of --enable-peigs in
https://github.com/nwchemgit/nwchem/blob/0a8e84593611261a5bb175287b88f60b0c1407a5/src/config/makefile.h#L112

With GA 5.7.2, this parameter is `--use_peigs` and returns 1 or 0.
```makefile
 GA_HAS_PEIGS = $(shell ${EXTERNAL_GA_PATH}/bin/ga-config --use_peigs | awk '/1/ {print "Y"}') 
```

```bash
$ ga-config --help
Usage: ga-config [OPTIONS]...

With the exception of --version and --help, all other options can be combined
or run exclusively.  Output is echoed to stdout.

Options:

  --f77
  --cc
  --cppflags
  --cflags
  --fflags
  --fint
  --blas_size
  --scalapack_size
  --use_blas
  --use_lapack
  --use_scalapack
  --use_peigs
  --use_elpa
  --use_elpa_2015
  --use_elpa_2016
  --ldflags
  --libs
  --flibs
  --network_ldflags
  --network_libs
  --network_cppflags
  --enable-f77
  --version
  --help
```

**Comment by edoapra** [comment]
@Micket I have just pushed a fix for the incorrect detection of Peigs support.
Could you provide more details about the actual problem you were encountering?
Thanks

**Comment by Micket** [comment]
@edoapra Well, when trying to compile, it simply didn't detect that that my external GA had been built with Peigs support, and gave me the error message `NWChem requires Global Arrays built with either Peigs or Scalapack support`.

**Comment by Micket** [comment]
Fix looks good to me

**Comment by edoapra** [comment]
> 
> 
> @edoapra Well, when trying to compile, it simply didn't detect that that my external GA had been built with Peigs support, and gave me the error message `NWChem requires Global Arrays built with either Peigs or Scalapack support`.

@Micket thank you very much for this bug report. I have never tested that particular case you were dealing with, therefore I was not able to detect the buggy makefile line
