### ISSUE TITLE
Can't build nwchem-7.0.0 because it requires ga with the SCALAPACK option, and this option is only available in ga-5.7.2 when it is built with cmake, which breaks

### ISSUE THREAD

**Issue by yurivict** [nwchemgit/nwchem#197]
ga-5.7.2 breaks when built with cmake: https://github.com/GlobalArrays/ga/issues/158

Any idea how can I build nwchem-7.0.0?

I can't update the FreeBSD port from 7.0.0-beta1 to 7.0.0-release for this reason.

**Comment by edoapra** [comment]
@yurivict Why is this a NWChem issue? Either you stick to autoconf or you continue the issue already open for  CMake use in GA. Please explain. You can use autoconf  to build GA with ScaLapack

**Comment by yurivict** [comment]
I was able to build nwchem-7.0.0.

I found the workaround for the ga autoconf build problem, it required the libscalapack.so library to be forced manually. It first looked like a blocker, and ga is unmaintained.

Sorry for the disturbance!
