### ISSUE TITLE
Sporadic crashes while computing the energy

### ISSUE THREAD

**Issue by yurivict** [nwchemgit/nwchem#198]
I run simple energy computation processes like this:
```
title "todo-title"
echo
geometry units angstroms
 load m.xyz
 symmetry c1
end
basis
 C library 3-21G
 H library 3-21G
 N library 3-21G
 O library 3-21G
end
scf
  thresh 0.01
end
task scf energy
```
through MPI on the same host ans some processes crash with a low probability, ~6 out of 1000 exit on a signal.

OS: FreeBSD 12.1
Architecture: amd64
Version: nwchem-7.0.0

**Comment by edoapra** [comment]
@yurivict Could you provide more details about these crashes?
What kind of signal terminates these runs? Have tried to run these processes under a debugger?

**Comment by yurivict** [comment]
I'll try to catch the crash with a debugger, and would post it here.

**Comment by yurivict** [comment]
```nwchem``` processes are being killed by the process ```hydra_pmi_proxy``` from ```mpich```. ```hydra_pmi_proxy``` sends ```nwchem``` ```SIGKILL``` (9).

Do you know why can this be happening?

**Comment by edoapra** [comment]
@yurivict the bug report still does not provide enough information to understand what's  happening/
Why is `hydra_mpi_proxy` sending a SIGKILL? However, you might get better answer filing your report on the mpich mailing list.


NWChem uses threads only in some part of the code. GA (that uses MPI to spawn processes) remains the main approach for parallelization

**Comment by yurivict** [comment]
I am trying to ask on the mpich mailing list.

I am also trying to use OpenMPI as an alternative to mpich.

**Comment by edoapra** [comment]
Closed after lack of further feedbacj
