### ISSUE TITLE
Fails to build with OpenMPI: unrecognized command line option '-i8'; did you mean '-k8'?

### ISSUE THREAD

**Issue by yurivict** [nwchemgit/nwchem#199]
I am trying to use a standard way to build NWChem with OpenMPI by defining ```CC```, ```MPICC```,  ```CXX```,  ```MPICXX```, ```F77```,  ```MPIF77```,  ```FC```, ```MPIFC``` make arguments to point to corresponding executables defined by OpenMPI.

The build fails:
```
gfortran9: error: unrecognized command line option '-i8'; did you mean '-k8'?
```

Before NWChem was built successfully with MPICH w/out using its compiler executables. MPICH is installed in a default location. OpenMPI is installed into a special location that requires special compilation/link flags.

MPI programs are supposed to be built with substitute compiler commands provided by MPI implementations.

OS: FreeBSD 12.1
openmpi-4.0.3
nwchem-7.0.0

**Comment by jeffhammond** [comment]
NWChem build system detects compilers by the value of `FC`.  Yes, this is not ideal.  The solution here is likely to set `_FC=gfortran`, but I don't know if that will do what it should.  If it doesn't, use `FC=gfortran CC=gcc CXX=g++`.  NWChem should figure out the MPI settings from `MPICC` and friends.

**Comment by yurivict** [comment]
When I added ```_FC=gfortran``` it failed in a different way:
```
/usr/local/mpi/openmpi/bin/mpif90 -m64 -ffast-math  -Warray-bounds -std=legacy -fdefault-integer-8 -O2 -g -fno-aggressive-loop-optimizations  -L/usr/local/mpi/openmpi/lib -Wl,-rpath,/usr/local/mpi/openmpi/lib  -o /usr/ports/science/nwchem/work/nwchem-7.0.0-release/src/../bin/LINUX64/nwchem nwchem.o stubs.o -lnwctask -lccsd -lmcscf -lselci -lmp2 -lmoints -lstepper -ldriver -loptim -lnwdft -lgradients -lcphf -lesp -lddscf -ldangchang -lguess -lhessian -lvib -lnwcutil -lrimp2 -lproperty -lsolvation -lnwints -lprepar -lnwmd -lnwpw -lofpw -lpaw -lpspw -lband -lnwpwlib -lcafe -lspace -lanalyze -lqhop -lpfft -ldplot -ldrdy -lvscf -lqmmm -lqmd -letrans -lpspw -ltce -lbq -lmm -lcons -lperfm -ldntmc -lccca -ldimqm -lnwcutil -lga -larmci -lpeigs -lperfm -lcons -lbq -lnwcutil    -l64to32 -lnwclapack  -lnwcblas  -L/usr/local/lib/gcc9 -L/usr/local/lib -lmpifort -lmpi    -lcomex -lblas -lm -L/usr/local/lib -lpthread   
/usr/local/bin/ld: cannot find -lnwctask
/usr/local/bin/ld: cannot find -lccsd
/usr/local/bin/ld: cannot find -lmcscf
/usr/local/bin/ld: cannot find -lselci
/usr/local/bin/ld: cannot find -lmp2
/usr/local/bin/ld: cannot find -lmoints
/usr/local/bin/ld: cannot find -lstepper
/usr/local/bin/ld: cannot find -ldriver
/usr/local/bin/ld: cannot find -loptim
/usr/local/bin/ld: cannot find -lnwdft
/usr/local/bin/ld: cannot find -lgradients
/usr/local/bin/ld: cannot find -lcphf
/usr/local/bin/ld: cannot find -lesp
/usr/local/bin/ld: cannot find -lddscf
/usr/local/bin/ld: cannot find -ldangchang
/usr/local/bin/ld: cannot find -lguess
/usr/local/bin/ld: cannot find -lhessian
/usr/local/bin/ld: cannot find -lvib
/usr/local/bin/ld: cannot find -lnwcutil
/usr/local/bin/ld: cannot find -lrimp2
/usr/local/bin/ld: cannot find -lproperty
/usr/local/bin/ld: cannot find -lsolvation
/usr/local/bin/ld: cannot find -lnwints
/usr/local/bin/ld: cannot find -lprepar
/usr/local/bin/ld: cannot find -lnwmd
/usr/local/bin/ld: cannot find -lnwpw
/usr/local/bin/ld: cannot find -lofpw
/usr/local/bin/ld: cannot find -lpaw
/usr/local/bin/ld: cannot find -lpspw
/usr/local/bin/ld: cannot find -lband
/usr/local/bin/ld: cannot find -lnwpwlib
/usr/local/bin/ld: cannot find -lcafe
/usr/local/bin/ld: cannot find -lspace
/usr/local/bin/ld: cannot find -lanalyze
/usr/local/bin/ld: cannot find -lqhop
/usr/local/bin/ld: cannot find -lpfft
/usr/local/bin/ld: cannot find -ldplot
/usr/local/bin/ld: cannot find -ldrdy
/usr/local/bin/ld: cannot find -lvscf
/usr/local/bin/ld: cannot find -lqmmm
/usr/local/bin/ld: cannot find -lqmd
/usr/local/bin/ld: cannot find -letrans
/usr/local/bin/ld: cannot find -lpspw
/usr/local/bin/ld: cannot find -ltce
/usr/local/bin/ld: cannot find -lbq
/usr/local/bin/ld: cannot find -lmm
/usr/local/bin/ld: cannot find -lcons
/usr/local/bin/ld: cannot find -lperfm
/usr/local/bin/ld: cannot find -ldntmc
/usr/local/bin/ld: cannot find -lccca
/usr/local/bin/ld: cannot find -ldimqm
/usr/local/bin/ld: cannot find -lnwcutil
/usr/local/bin/ld: cannot find -lpeigs
/usr/local/bin/ld: cannot find -lperfm
/usr/local/bin/ld: cannot find -lcons
/usr/local/bin/ld: cannot find -lbq
/usr/local/bin/ld: cannot find -lnwcutil
/usr/local/bin/ld: cannot find -l64to32
/usr/local/bin/ld: cannot find -lnwclapack
/usr/local/bin/ld: cannot find -lnwcblas
collect2: error: ld returned 1 exit status
gmake[2]: *** [GNUmakefile:35: all] Error 1
gmake[2]: Leaving directory '/usr/ports/science/nwchem/work/nwchem-7.0.0-release/src'
===> Compilation failed unexpectedly.
```

Libraries are in ```lib/LINUX64```:
```
$ find . -name "*nwclapack*"
./work/nwchem-7.0.0-release/lib/LINUX64/libnwclapack.a
```
but there is no corresponding ```-L``` statement in the link line.

**Comment by edoapra** [comment]
@yurivict I would suggest the following settings
* change the PATH env. variable to point to the location of the desired mpif90.  In your case, it should be
```
export PATH=usr/local/mpi/openmpi/bin/:$PATH
```
* do not set any of the over compiler or MPI related env. variables, since the makefile structure will detect them (there could be issues with gcc 10, but there are patches available in master and hotftix/release-7-0-0). E.g.
```
unset FC
unset _FC
unset CC
unset CXX
unset MPICC
...
```
If this still fails, please file a detailed bug report that includes all the env. variables that you have set all the makefile logs, incuding $NWCHEM_TOP/src/tools/build.log

**Comment by yurivict** [comment]
@edoapra  Just setting paths wouldn't help because CFLAGS/CXXFLAGS/LDFLAGS are also needed to ensure that the right MPI implementation is used (OpenMPI and not MPICH).

**Comment by edoapra** [comment]
> 
> 
> @edoapra Just setting paths wouldn't work because CFLAGS/CXXFLAGS/LDFLAGS are also needed to ensure that the right MPI implementation is used (OpenMPI and not MPICH).

I asked you for a detailed bug report, would you mind doing that?
Please file a detailed bug report that includes all the env. variables that you have set all the makefile logs, including $NWCHEM_TOP/src/tools/build.log

**Comment by yurivict** [comment]
While running with only the PATH setting as you suggested I observe the errors:
```
/bin/sh: /usr/ports/science/nwchem/work/nwchem-7.0.0-release/src/../src/tools/install/bin/ga-config: not found
```

```bin/ga-config``` is in a regular location:
```
$ which ga-config
/usr/local/bin/ga-config
```

**Comment by yurivict** [comment]
While trying to build in a way how the MPI spec suggests (using compiler wrappers) with an additional ```_FC=gfortran``` setting and with a correction of internal static library paths - it runs to the link phase and it creates a faulty executable because it links with the libmpifort library that isn't installed by OpenMPI. libmpifort.so that it links comes from MPICH which is wrong.

**Comment by edoapra** [comment]
One more try: could you please report all the env. variables you are using?
Second: all the makefile logs I have asked you.

If you do not provide  all the information I have asked, there is not much use of continuing this issue.

**Comment by jeffhammond** [comment]
Regarding
> While trying to build in a way how the MPI spec suggests (using compiler wrappers)

MPI 3.1 Section 17.1.7 says
> _Advice to users._ Users must take appropriate steps to ensure that proper options are specified to compilers. MPI libraries must document these options. Some MPI libraries are shipped together with special compilation scripts (e.g., mpif90, mpicc) that set these options automatically. (End of advice to users.)

Thus, the MPI standard does not suggest using compiler wrappers.  It only says users need do the right thing (and in non-normative text, no less).  It is certainly the case that the convenience scripts are widely available but they are optional and in some cases less helpful.

For historical reasons, the NWChem build system was designed to not rely on MPI wrapper scripts but rather the equally valid method of specifying preprocessor and linker flags explicitly and the method for doing this is documented.  We can't force you to follow the directions, but neither can you force us to debug problems resulting from a failure to follow the directions.

**Comment by yurivict** [comment]
> One more try: could you please report all the env. variables you are using?

Build with only the PATH variable set to include executables from OpenMPI. Relevant executable paths are:
```
        /usr/local/mpi/openmpi/bin/mpic++
        /usr/local/mpi/openmpi/bin/mpicc
        /usr/local/mpi/openmpi/bin/mpicxx
        /usr/local/mpi/openmpi/bin/mpiexec
        /usr/local/mpi/openmpi/bin/mpif77
        /usr/local/mpi/openmpi/bin/mpif90
        /usr/local/mpi/openmpi/bin/mpifort
        /usr/local/mpi/openmpi/bin/mpirun
```

The environment:
```
BSD_INSTALL_MAN=install  -m 444
BSD_INSTALL_DATA=install  -m 0644
BSD_INSTALL_SCRIPT=install  -m 555
BSD_INSTALL_LIB=install  -s -m 0644
BSD_INSTALL_PROGRAM=install  -s -m 555
MANPREFIX=/usr/local
LIBS=
LDFLAGS= -Wl,-rpath=/usr/local/lib/gcc9  -L/usr/local/lib/gcc9 -B/usr/local/bin -fstack-protector-strong 
LOCALBASE=/usr/local
PREFIX=/usr/local
STRINGS=/usr/local/bin/strings
SIZE=/usr/local/bin/size
READELF=/usr/local/bin/readelf
RANLIB=/usr/local/bin/ranlib
OBJDUMP=/usr/local/bin/objdump
OBJCOPY=/usr/local/bin/objcopy
NM=/usr/local/bin/nm
LD=/usr/local/bin/ld
GPROF=/usr/local/bin/gprof
CPPFILT=/usr/local/bin/c++filt
AS=/usr/local/bin/as
AR=/usr/local/bin/ar
ADDR2LINE=/usr/local/bin/addr2line
NO_LINT=YES
MK_KERNEL_SYMBOLS=no
MK_DEBUG_FILES=no
NO_PIE=yes
HOME=/usr/ports/science/nwchem/work
XDG_CONFIG_HOME=/usr/ports/science/nwchem/work
XDG_DATA_HOME=/usr/ports/science/nwchem/work
PERL_USE_UNSAFE_INC=1
PATH=/usr/local/mpi/openmpi/bin:/usr/ports/science/nwchem/work/.bin:/home/yuri/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin
USE_64TO32=y
BLAS_SIZE=4
EXTERNAL_GA_PATH=/usr/local
USE_INTERNALBLAS=Y
USE_MPI=Y
NWCHEM_TARGET=LINUX64
NWCHEM_LONG_PATHS=Y
NWCHEM_MODULES=all
NWCHEM_TOP=/usr/ports/science/nwchem/work/nwchem-7.0.0-release/src/..
OPSYS=FreeBSD
ARCH=amd64
GTK_IM_MODULE=ibus
LOGNAME=yuri
LC_CTYPE=en_US.UTF-8
LANG=C
MAKELEVEL=2
CONFIG_DONE_NWCHEM=1
XDG_MENU_PREFIX=xfce-
DESKTOP_SESSION=xfce
XDG_DATA_DIRS=/usr/local/share:/usr/share
XAUTHORITY=/home/yuri/.Xauthority
CLICOLOR=1
XFCE4_SESSION_WITH_CK=1
MAIL=/var/mail/yuri
META_MODE=normal
MAKEFLAGS= .MAKE.LEVEL.ENV=MAKELEVEL ARCH=amd64 CONFIG_DONE_NWCHEM=1 HAVE_COMPAT_IA32_KERN=YES\  OPSYS=FreeBSD OSREL=12.1 OSVERSION=1201512 _OSRELEASE=12.1-STABLE _PERL5_FROM_BIN=5.30.2 _PKG_CHECKED=1 _SMP_CPUS=8
_PERL5_FROM_BIN=5.30.2
EDITOR=vim
XDG_RUNTIME_DIR=/var/run/user/1001
SVN_EDITOR=vim
OSREL=12.1
SESSION_MANAGER=local/yv.noip.me:/tmp/.ICE-unix/2965
_OSRELEASE=12.1-STABLE
.MAKE.LEVEL.ENV=MAKELEVEL
SSH_AUTH_SOCK=/tmp/ssh-qnBsAtjsAuqn/agent.2951
DISPLAY=unix:0.0
OLDPWD=/usr/ports/science/nwchem
_SMP_CPUS=8
PWD=/usr/ports/science/nwchem/work/nwchem-7.0.0-release/src
HAVE_COMPAT_IA32_KERN=YES 
_=/usr/bin/make
XDG_CURRENT_DESKTOP=XFCE
MYVIMRC=/usr/home/yuri/.vimrc
VTE_VERSION=5202
TERM=xterm-256color
VIM=/usr/local/share/vim
DBUS_SESSION_BUS_ADDRESS=unix:path=/tmp/dbus-qxs9OutcBK,guid=3fb0008862058e90fefa273e5ea783a6
XMODIFIERS=@im=ibus
USER=yuri
VIMRUNTIME=/usr/local/share/vim/vim82
CVSROOT=/usr/home/cvs
_PKG_CHECKED=1
SHELL=/bin/sh
COLORTERM=truecolor
PANEL_GDK_CORE_DEVICE_EVENTS=0
LC_ALL=C
WINDOWID=60817411
XDG_CONFIG_DIRS=/etc/xdg:/usr/local/etc/xdg
SSH_AGENT_PID=2952
XDG_SESSION_COOKIE=yv.noip.me-1588036518.39673-328996907
OSVERSION=1201512
SHLVL=1
QT_IM_MODULE=ibus
```

Full build log: https://people.freebsd.org/~yuri/nwchem-7.0.0-withPATH-only.log

Outcome:
The build didn't use any of the OpenMPI compilers. The build is wrong because it didn't link to OpenMPI at all.

**Comment by edoapra** [comment]
The log seems to indicate that you might have two different version of OpenMPI,
one providing `libmpi.so.40` and a second one providing `libmpi.so.12`
What causes the failure is the fact that while the current compilation seems to be pointing to `libmpi.so.12`, the Global Arrays library you are using seem to be built against  `/usr/local/mpi/openmpi/lib/libmpi.so.40`
```
gfortran -m64 -ffast-math  -Warray-bounds -std=legacy -fdefault-integer-8 -O2 -g -fno-aggressive-loop-optimizations  -I/usr/local/mpi/openmpi/include  -L/usr/ports/science/nwchem/work/nwchem-7.0.0-release/src/../lib/LINUX64 -L/usr/local/lib  -L/usr/local/mpi/openmpi/lib  -o /usr/ports/science/nwchem/work/nwchem-7.0.0-release/src/../bin/LINUX64/nwchem nwchem.o stubs.o -lnwctask -lccsd -lmcscf -lselci -lmp2 -lmoints -lstepper -ldriver -loptim -lnwdft -lgradients -lcphf -lesp -lddscf -ldangchang -lguess -lhessian -lvib -lnwcutil -lrimp2 -lproperty -lsolvation -lnwints -lprepar -lnwmd -lnwpw -lofpw -lpaw -lpspw -lband -lnwpwlib -lcafe -lspace -lanalyze -lqhop -lpfft -ldplot -ldrdy -lvscf -lqmmm -lqmd -letrans -lpspw -ltce -lbq -lmm -lcons -lperfm -ldntmc -lccca -ldimqm -lnwcutil -lga -larmci -lpeigs -lperfm -lcons -lbq -lnwcutil    -l64to32 -lnwclapack  -lnwcblas  -L/usr/local/mpi/openmpi/lib -lmpi_usempi -lmpi_mpifh -lmpi    -lcomex -lblas -lm -L/usr/local/lib -lpthread   
/usr/local/bin/ld: warning: libmpi.so.40, needed by /usr/local/lib/libga.so, may conflict with libmpi.so.12
/usr/local/bin/ld: /usr/ports/science/nwchem/work/nwchem-7.0.0-release/src/../lib/LINUX64/libnwcutil.a(util_mygabcast.o): undefined reference to symbol 'ompi_mpi_dblprec'
/usr/local/bin/ld: /usr/local/mpi/openmpi/lib/libmpi.so.40: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```

**Comment by yurivict** [comment]
/usr/local/mpi/openmpi/lib/libmpi.so.40 is installed by OpenMPI, /usr/local/lib/libmpi.so.12 is installed by MPICH. I am trying to build against OpenMPI and MPICH should be ignored.

You suggested to just use a PATH to OpenMPI executables, but this didn't work.

If only OpenMPI-provided compiler wrappers are be used via environment variables - correct headers/libraries are used. Doing this and adding ```_FC=gfortran``` causes nwchem to link to OpenMPI properly except it links to libmpifort.so from MPICH.

**Comment by edoapra** [comment]
Thanks for mpich/openmpi update
We need to verify the ga-config output, since the link line you reported has `-L/usr/local/lib` before `-L/usr/local/mpi/openmpi/lib' and this causes the linker to pick libmpi out of mpich
Please report the output of the command
```
ga-config --ldflags
```

**Comment by yurivict** [comment]
```
$ ga-config --ldflags
-L/usr/local/lib
```
The above is correct because the library is installed in the default location ```/usr/local/lib/libga.so```.

```ga``` and ```scalapack``` are correctly linked to the libmpi.so from OpenMPI:
```
$ ldd -a /usr/local/lib/libga.so 
/usr/local/lib/libga.so:
	libmpi.so.40 => /usr/local/mpi/openmpi/lib/libmpi.so.40 (0x801275000)
	libscalapack.so => /usr/local/lib/libscalapack.so (0x801600000)
...
$ ldd -a /usr/local/lib/libscalapack.so
/usr/local/lib/libscalapack.so:
	libmpi.so.40 => /usr/local/mpi/openmpi/lib/libmpi.so.40 (0x801598000)
...
```

I am trying to achieve the same for the nwchem executable itself.

The required compilation/link flags are normally provided by OpenMPI's compiler wrappers when they are used, but can also be provided manually.

**Comment by edoapra** [comment]
@yurivict I have no solution for this problem. The root cause is clear.

**Comment by edoapra** [comment]
Closed for lack of activity
