### ISSUE TITLE
ABS deviation %

### ISSUE THREAD

**Issue by amnikitin** [nwchemgit/nwchem#20]
Hi,

When calculating partial charges on atoms, I need a measure of the quality of the fit to the quantum calculated electrostatic potential. I assume that this measure is a string
` ABS deviation %                              198.348743`
in output.

I do not know what the program means by ABS deviation % (it would be desirable to document this), but this sounds strange, insofar as this value always of hundreds and thousands percent. Whatever the measure was, it is unlikely that thousands of percent sound reasonable. I suspect there's a mistake here. Could you clarify?

**Comment by edoapra** [comment]
@amnikitin Could you provide the input and output files corresponding to this issue?

**Comment by amnikitin** [comment]
Hi,

Methane:
 ABS deviation %                              142.021790

Maybe it's 1,42 percent?
Input and output are attached.

**Comment by amnikitin** [comment]
[!task.nw.zip](https://github.com/nwchemgit/nwchem/files/2403818/task.nw.zip)

**Comment by edoapra** [comment]
Replaced ABS deviation % with RRMS (Relative Root Mean Square Fit) from [Besler, B. H., Merz, K. M. and Kollman, P. A. (1990), Atomic charges derived from semiempirical methods. J. Comput. Chem., 11: 431-439. doi:10.1002/jcc.540110404](https://doi.org/10.1002/jcc.540110404)
8b11702cce1f3b7499f6595488806b62cf4b9ea0
