### ISSUE TITLE
User manual

### ISSUE THREAD

**Issue by antoscha** [nwchemgit/nwchem#203]
Dear Developers,

Is there any user manual? The one obtained by `make pdf` in `doc/` is quite outdated.

Thanks in advance,
Anton K.

**Comment by edoapra** [comment]
The user manual is now provided online in wiki format

https://github.com/nwchemgit/nwchem/wiki

On 6/1/20 12:37 AM, antoscha wrote:

Dear Developers,

Is there any user manual? The one obtained by make pdf in doc/ is quite outdated.

Thanks in advance,
Anton K.

**Comment by antoscha** [comment]
Ok, thanks.
