### ISSUE TITLE
possible semantics error with geom_input.F

### ISSUE THREAD

**Issue by naromero77** [nwchemgit/nwchem#208]
Hi, 

I work with the DOE ECP Flang project and I am tasked with compiling Office of Science codes with the new LLVM Flang front-end. (Note that this is different from the "classic" Flang compiler which is already supported by the NWChem build system)

**Describe the bug**
The Flang front-end cannot compile this file due to semantics error:
https://github.com/nwchemgit/nwchem/blob/master/src/geom/geom_input.F

What I find odd about this file is that in multiple places there are a bunch of `+` signs -- almost like the ones you would see in a patch file. I don't think `+` is an official Fortran line continuation sentinel, but I could be mistaken.

Here is the compile-time error from LLVM Flang.
```
Compiling geom_input.F...
geom_input.F:960:35: error: No explicit type declared for 'ns'
       +                            ns, 
                                    ^^
geom_input.F:1072:35: error: No explicit type declared for 'ns'
       +                            ns, 
                                    ^^
/nfs/gce/projects/naromero-workspace/llvm-master/bin/f18: semantic errors in geom_input.F
```

**Describe settings used**
LLVM Flang front-end built on Linux x86

**Attach log files**
[comex_config.log](https://github.com/nwchemgit/nwchem/files/4766741/comex_config.log)
[config.log](https://github.com/nwchemgit/nwchem/files/4766742/config.log)

**To Reproduce**
Build LLVM Flang. I can provide a script if necessary.

Here is the NWChem build script.
[build.sh.txt](https://github.com/nwchemgit/nwchem/files/4766750/build.sh.txt)

**Expected behavior**
It should just build without any semantics. However, if this is legit Fortran code, I will file a bug/feature request with the LLVM Flang bugzilla.

**Comment by hjjvandam** [comment]
Hi Romero,

The compiler isn’t complaining about the “+” signs, but about the variable “ns” being undefined. Does that complain go away if you replace the “+” with a more conventional character for a continuation line? It seems to me that the “+” sign might not be the problem.

Best wishes,

    Huub

-----------------------------------------------------------------------------------------------------
Hubertus van Dam, 631-344-6020, hvandam@bnl.gov<mailto:hvandam@bnl.gov>
Brookhaven National Laboratory

**Comment by jeffhammond** [comment]
@naromero77 
Try this MCVE:
```fortran
jrhammon-mac02:geom jrhammon$ gfortran -c bug.F && echo "SUCCESS"
SUCCESS
jrhammon-mac02:geom jrhammon$ ifort -c bug.F && echo "SUCCESS"
SUCCESS
jrhammon-mac02:geom jrhammon$ cat bug.F 
      subroutine geom_read_file_xyz(filename,
     +                            ifr, 
     +                            ns, 
     +                            asel, 
     +                            isel,
     +                            n,
     +                            nmax,
     +                            tags,
     +                             c)
      implicit none
      character*(*) filename
      integer  ifr
      character*(*) asel(ns)
      integer ns
      integer isel(2*ns)
      integer n
      integer nmax
      character*16 tags(nmax)
      double precision c(3,nmax)
      end subroutine
```

**Comment by jeffhammond** [comment]
I suspect the problem is that `ns` is used before it is declared.  Reordering these two lines may resolve the issue.  Please let me know if that's the case and I'll commit the fix.
```fortran
      character*(*) asel(ns)
      integer ns
```

**Comment by naromero77** [comment]
@jeffhammond 

That was tremendously helpful. At least for the reduced test case, it seems to fix the issue with flang. I think there might be something more complicated going on with the big file or there are multiple instances of it the same problem that I have not found.

**Comment by naromero77** [comment]
@jeffhammond OK, here is the diff that will allow it to compile. Can you commit the change?

```
diff --git a/src/geom/geom_input.F b/src/geom/geom_input.F
index 7f8689202..364f28208 100644
--- a/src/geom/geom_input.F
+++ b/src/geom/geom_input.F
@@ -972,8 +972,8 @@ c
 #include "util.fh"
       character*(*) filename
       integer  ifr
-      character*(*) asel(ns)
       integer ns
+      character*(*) asel(ns)
       integer isel(2*ns)
       integer n
       integer nmax
@@ -1084,8 +1084,8 @@ c       process selections here
 #include "util.fh"
       character*(*) filename
       integer  ifr
-      character*(*) asel(ns)
       integer ns
+      character*(*) asel(ns)
       integer isel(2*ns)
       integer n
       integer nmax
```

**Comment by edoapra** [comment]
@naromero77 Nick, I have just committed the change to the master branch. I will committed to hotfix/release-7-0-0, too

**Comment by naromero77** [comment]
@edoapra @jeffhammond Thanks guys. 

I will close the issue, but expect a few more from me in the following days.
