### ISSUE TITLE
dfloat -> dble

### ISSUE THREAD

**Issue by naromero77** [nwchemgit/nwchem#210]
Many Office of Science codes use dfloat(n) where n is some integer to convert to double precision. Unfortunately, this is not a standard Fortran intrinsic procedure. It appears to be some extension that is supported by GCC and Intel (which probably covers well over 80% of the everyday Fortran compiler usage)

The correct way to do this is using dble(n). More info here:
https://github.com/flang-compiler/f18/issues/1077

I grepped through the NWChem source code and there way too many places where dfloat is used, e.g. TCE, DFT, etc., to fix this manually. Maybe there is some macro magic that can handle this or I can push the Flang developers to implement it, but it will probably end up low on their priority list.

I don't expect you guys to switch over to dble(n), but mostly making you aware of the issue. But if you do want to switch over, I am willing to make the PR for it :)

**Comment by jeffhammond** [comment]
I would like to fix this globally. DBLE is standard since Fortran 77 so we should be able to use it unconditionally.  We can do this with sed.

**Comment by jeffhammond** [comment]
Please test the linked pull request @naromero77.  The good news is that DBLE is shorter than DFLOAT, so we won't run into 72-column problems :-)
