### ISSUE TITLE
PGI's C compiler does not like zero-size array in util_mygabcast.c

### ISSUE THREAD

**Issue by naromero77** [nwchemgit/nwchem#213]
Note that this has nothing to do with flang.

PGI's C compiler has a fatal error on `util_mygabcast.c` because because `nodeid` is a zero size array. I don't think one is allowed a zero-size array in C. I think this easiest fix is to make it size 1.
```
diff --git a/src/util/util_mygabcast.c b/src/util/util_mygabcast.c
index 4c8a3e8d5..c234fbe9d 100644
--- a/src/util/util_mygabcast.c
+++ b/src/util/util_mygabcast.c
@@ -102,7 +102,7 @@ Integer FATR util_mynodeid_(void)
 #include <mpi.h>
 {
   int myid;
-  Integer nodeid[0];
+  Integer nodeid[1];
   MPI_Comm_rank(MPI_COMM_WORLD,&myid);
   *nodeid = (Integer) myid;
   return  *nodeid;
```

But why not make `nodeid` just a single integer instead of an array of integers with size 1?

**Comment by edoapra** [comment]
Why should we support pgcc?
clang and gcc are enough for the needs of a Fortran code

**Comment by jeffhammond** [comment]
I may end up using C in semidirect CCSD(T) OpenMP for GPU for various reasons, in which case we would want PGI or Cray compilers for Perlmutter.

We can mix C compilers if necessary but it’s easier to support PGI C in spite of its well-known problems.
