### ISSUE TITLE
lshift -> shiftl ; rshift -> shiftr in util_pack.F

### ISSUE THREAD

**Issue by naromero77** [nwchemgit/nwchem#214]
New flang does not understand `lshift/rshift` as intrinsic procedures. I could not find much information about it, except that this page for the IBM XL compiler suggests that `lshift/rshift` are extensions and the correct naming convention is `shiftl/shiftr`.
https://www.ibm.com/support/knowledgecenter/SSAT4T_15.1.5/com.ibm.xlf1515.lelinux.doc/language_ref/intrinsicprocs.html

**Comment by jeffhammond** [comment]
@edoapra I'm not sure if this is caused by the shift intrinsic change but it seems unpack is having trouble (this is the nwchem.nw input in src/).

```
 Starting SCF solution at       0.1s

                    20                     0                    19
                    14                   141               1310739
  6.203396434416891E-003
 ------------------------------------------------------------------------
 int2e_buf_cntr_unpack: invalid count                  20
 ------------------------------------------------------------------------
 ------------------------------------------------------------------------
  current input line : 
    26: task scf optimize
 ------------------------------------------------------------------------
 ------------------------------------------------------------------------
 This error has not yet been assigned to a category
 ------------------------------------------------------------------------
 For more information see the NWChem manual at 
 https://github.com/nwchemgit/nwchem/wiki


 For further details see manual section: 
 No section for this category                                                   
                                                                                
                                                                                
                   
0:int2e_buf_cntr_unpack: invalid count:Received an Error in Communication
Abort(20) on node 0 (rank 0 in comm 496): application called MPI_Abort(comm=0x84000002, 20) - process 0
```

**Comment by hjjvandam** [comment]
Hi Nick,

Bit operations have been standardized in Fortran 90. This page claims to list the standard operations: https://rosettacode.org/wiki/Bitwise_operations#Fortran. Lshift and rshift are versions of ishft or ishftc with a different sign for j.

Huub

-----------------------------------------------------------------------------------------------------
Hubertus van Dam, 631-344-6020, hvandam@bnl.gov<mailto:hvandam@bnl.gov>
Brookhaven National Laboratory

**Comment by edoapra** [comment]
@jeffhammond Yes, it is very likely it is the result of my `ishft` changes. I wonder why the travis ci  tests did not catch it. Let me have a look

**Comment by edoapra** [comment]
@jeffhammond are you running direct (e.g. compiled with `USE_NOIO=y` ) or conventional SCF?

**Comment by jeffhammond** [comment]
I am running src/nwchem.nw without modification, but I used IFX.  I will try again with IFORT.

**Comment by edoapra** [comment]
@jeffhammond I have just manage to reproduce the  problemwith the simplest setup with GNU compilers.
Thanks

**Comment by edoapra** [comment]
@jeffhammond Commit https://github.com/nwchemgit/nwchem/commit/3593b92e59d088a18e01f154ac88803be639d451 should address  the `int2e_buf_cntr_unpack` bug

**Comment by naromero77** [comment]
There are still instances of `lshift` and `rshift` in https://github.com/nwchemgit/nwchem/blob/master/src/util/util_pack.F

Was the plan to change those to `ishft` as well?

**Comment by edoapra** [comment]
@naromero77 all rshift/lshift calls should have been converted to ishft

**Comment by naromero77** [comment]
@edoapra The last commit had a typo. It is `ishft` not `ishift` -- easy to get those mixed up.

**Comment by edoapra** [comment]
> 
> 
> @edoapra The last commit had a typo. It is `ishft` not `ishift` -- easy to get those mixed up.

I am assuming you are referring to commit 37ce9315b00e77da419f86eebcc42e6d4b848a5b, right?
I am checking since it is the penultimate commit at this point in time

**Comment by naromero77** [comment]
Many thanks
