### ISSUE TITLE
cleanup SELCI popcount

### ISSUE THREAD

**Issue by jeffhammond** [nwchemgit/nwchem#216]
The SELCI module contains a bunch of 20 year-old code to compute POPCOUNT, all of which look awful except for the Cray T3E case that uses the Fortran 2008 intrinsic (before it was standard, of course).

We should considering removing all the Fortran stuff and just wrap `__builtin_popcount` that exists in C compilers (and maps to hardware when available), and fall back on the simple C implementation from Wikipedia:
```c
int popcount64d(uint64_t x)
{
    int count;
    for (count=0; x; count++)
        x &= x - 1;
    return count;
}
```

Or we can use what we already have in https://github.com/nwchemgit/nwchem/blob/master/src/util/util_intrsc2008.F.

@hjjvandam Why don't we have an option to use Fortran 2008 POPCOUNT when it is available?

**Comment by hjjvandam** [comment]
Hi Jeff,

Why we don’t have an option to use popcount when it is available is a good question. I don’t have an answer to that question other than that popcount is not used in so many places. It is mostly used in selected CI where the electron configurations are managed with bit patterns.

The story of POPCOUNT and LEADZ in Fortran is actually really interesting. The operations were introduced by CDC in the 1960s. They were implemented as hardware instructions, and apparently they were helpful in cryptography (although evidence of that is hard to come by). The surprising thing is that it look so long for these functions to be standardized in Fortran. Admittedly these functions are not that heavily used in most number crunching codes. Nevertheless these functions have been around unchanged for a long time, so why couldn’t these definitions simply be labeled a standard?

Best wishes,

    Huub

-----------------------------------------------------------------------------------------------------
Hubertus van Dam, 631-344-6020, hvandam@bnl.gov<mailto:hvandam@bnl.gov>
Brookhaven National Laboratory

**Comment by jeffhammond** [comment]
I think the following data from https://vaibhavsagar.com/blog/2019/09/08/popcount/ explains why the POPCOUNT intrinsic didn't end up in ISO Fortran until 2008:
```
1961: IBM Stretch
1964: CDC 6000
1975: Cray-1
2005: SPARC
2005: ARM NEON
2007: AMD K10
2008: Intel Nehalem
```
