### ISSUE TITLE
RE: 6.8 on Windows

### ISSUE THREAD

**Issue by amnikitin** [nwchemgit/nwchem#22]
Hi,

I tried to use a new  Dne_omp.F file.
https://github.com/nwchemgit/nwchem/commit/b8ff604a9d0931ac31ca1865ce173cff08988277
Result:

       gfortran  -c  -fno-tree-dominator-opts  -m32 -march=pentium4 -mtune=pentium4 -O2  -ffast-math -Wuninitialized -fno-aggressive-loop-optimizations -fno-tree-dominator-opts  -O2 -ffast-math -Wuninitialized -I. -I../include -I/home/Layruoru/nwchem-6.8/src/include -I/home/Layruoru/nwchem-6.8/src/tools/install/include -DLINUX -DGFORTRAN -DGCC46 -DCHKUNDFLW -DGCC4 -DPARALLEL_DIAG   nwpw_timing.F
       nwpw_timing.F:107:9:

       USE omp_lib
         1
       Fatal Error: Can't open module file 'omp_lib.mod' for reading at (1): No such file or directory
       compilation terminated.

Could you help with this?

**Comment by edoapra** [comment]
@amnikitin the error indicates that USE_OPENMP was on. Please unset it when compiling on MinGW

**Comment by amnikitin** [comment]
I used 0716046 file.

With _run2.sh

    export NWCHEM_TOP=~/nwchem-6.8
    export NWCHEM_TARGET=LINUX
    export USE_MPI=y
    export MPI_LOC=~/MPICH2
    export MPI_INCLUDE=$MPI_LOC/include
    export MPI_LIB=$MPI_LOC/lib
    export LIBMPI="-lfmpich2g -lmpi"
    export NWCHEM_MODULES=all
    export DEPEND_CC=gcc
    export USE_INTERNALBLAS=y
    export USE_OPENMP=n
    
    cd $NWCHEM_TOP/src
    
    make CC=gcc FC=gfortran 

I have

    $ _run2.sh
    cat: /home/Layruoru/nwchem-6.8/src/tools/build/config.h: No such file or directory
    
    MinGW environment does not support OpenMP
    Please unset USE_OPENMP

**Comment by edoapra** [comment]
@amnikitin 
This is the expected behavior
you do have 
USE_OPENMP=n
Please execute the command

unset USE_OPENMP

**Comment by amnikitin** [comment]
@edoapra 
I unpacked the archive, rewrote two new files and consistently executed two scripts.

    export NWCHEM_TOP=~/nwchem-6.8
    export NWCHEM_TARGET=LINUX
    export USE_MPI=y
    export MPI_LOC=~/MPICH2
    export MPI_INCLUDE=$MPI_LOC/include
    export MPI_LIB=$MPI_LOC/lib
    export LIBMPI="-lfmpich2g -lmpi"
    export NWCHEM_MODULES=all
    export DEPEND_CC=gcc
    export USE_INTERNALBLAS=y
    unset USE_OPENMP
    
    cd $NWCHEM_TOP/src
    
    make nwchem_config

and

    export NWCHEM_TOP=~/nwchem-6.8
    export NWCHEM_TARGET=LINUX
    export USE_MPI=y
    export MPI_LOC=~/MPICH2
    export MPI_INCLUDE=$MPI_LOC/include
    export MPI_LIB=$MPI_LOC/lib
    export LIBMPI="-lfmpich2g -lmpi"
    export NWCHEM_MODULES=all
    export DEPEND_CC=gcc
    export USE_INTERNALBLAS=y
    unset USE_OPENMP

    cd $NWCHEM_TOP/src
    
    make CC=gcc FC=gfortran 

Result:

    make[4]: *** [/home/Layruoru/nwchem-6.8/bin/LINUX/depend.x] Error 127
    ( cd /home/Layruoru/nwchem-6.8/src/config; make /home/Layruoru/nwchem-6.8/bin/LINUX/depend.x ; )
    /usr/bin/gcc  -g -o /home/Layruoru/nwchem-6.8/bin/LINUX/depend.x depend.c
    /bin/sh: /usr/bin/gcc: No such file or directory
    make[5]: *** [/home/Layruoru/nwchem-6.8/bin/LINUX/depend.x] Error 127
    Compiling nwpw_timing.F...
    nwpw_timing.F:107:9:
    
       USE omp_lib
         1
    Fatal Error: Can't open module file 'omp_lib.mod' for reading at (1): No such file or directory
    compilation terminated.
    make[4]: *** [/home/Layruoru/nwchem-6.8/lib/LINUX/libnwpwlib.a(nwpw_timing.o)] Error 1
    make[3]: *** [optimized] Error 2
    make[2]: *** [subdirs] Error 1
    make[1]: *** [subdirs] Error 1
    make: *** [libraries] Error 1

**Comment by edoapra** [comment]
Please use the hotfix/release-6-8 branch that contains the appropriate fix and that I have tested under MinGW

To checkout
git clone -b hotfix/release-6-8 https://github.com/nwchemgit/nwchem.git nwchem-6.8.1

export NWCHEM_TOP=....../nwchem-6.8.1

**Comment by amnikitin** [comment]
I have not tried to compile 6.8.1, however, I see a string
nwpw_timing.F line 107

`      USE omp_lib
`

My MinGW stops at such things.

**Comment by amnikitin** [comment]
I removed all links on the **USE omp_lib** from the program.
Now stop at **psi_lmbda_omp.F**.
I would suggest that such a file should not be part of the MinGW project.

**Comment by edoapra** [comment]
@amnikitin Unfortunately  I am not able to reproduce your failure
