### ISSUE TITLE
NWCHEM_TARGET value is case sensitive

### ISSUE THREAD

**Issue by naromero77** [nwchemgit/nwchem#220]
I think this is unrelated to the use of `f18`. IIRC, PEIGS, is the parallel eigensolver. But I am compiling NWChem without MPI -- so I would think that PEIGS would not be compiled.

Here is the error message:
```
Making libraries in peigs
make[1]: Entering directory '/nfs/gce/projects/naromero-workspace/FLANG/nwchem-7.0.0/src/peigs'
(make lib ) || exit 1
make[2]: Entering directory '/nfs/gce/projects/naromero-workspace/FLANG/nwchem-7.0.0/src/peigs'
(cd ./src/c; make)
make[3]: Entering directory '/nfs/gce/projects/naromero-workspace/FLANG/nwchem-7.0.0/src/peigs/src/c'
Compiling clustrfix.c...
pgcc-Error-Switch -D expects an argument
-D<macro>           Define a preprocessor macro
GNUmakefile:281: recipe for target 'clustrfix.o' failed
make[3]: *** [clustrfix.o] Error 1
make[3]: Leaving directory '/nfs/gce/projects/naromero-workspace/FLANG/nwchem-7.0.0/src/peigs/src/c'
GNUmakefile:63: recipe for target 'lib' failed
make[2]: *** [lib] Error 2
```

Here is my build script:
```
#!/bin/bash
module load pgi/19.7
GCE=/nfs/gce/projects/naromero-workspace
export PATH=${GCE}/llvm-master/bin:$PATH
export NWCHEM_TOP=${GCE}/FLANG/nwchem-7.0.0
export NWCHEM_TARGET=linux64
export USE_MPI=n
export USE_INTERNALBLAS=y
export NWCHEM_MODULES=all
export CC=pgcc
export FC=flang

cd ${NWCHEM_TOP}/src
make nwchem_conf
make
```

**Comment by jeffhammond** [comment]
I don’t know that compiling NWChem without MPI is possible anymore, but if it is, you’ll get ARMCI over TCP/IP and PeIGS will use TCGMSG over TCP/IP for message passing ala 1993.

If you want to disable PeIGS, you have to use ScaLAPACK. 

If you absolutely can’t have MPI or PeIGS, then I can probably hack GA to make it work but I don’t think it is the right way to solve any problem.

**Comment by naromero77** [comment]
I was trying to avoid using MPI because mpif90 with f18 is a serious hack right now -- though it appears to mostly work. I will recompile NWChem with MPI later this week.

**Comment by jeffhammond** [comment]
You don’t need and shouldn’t use MPI compiler scripts. Just set the environment variables properly and it will build with f18 directly. I will send you my setup later.

**Comment by naromero77** [comment]
I am still getting this error. Here is my new build script with MPI:
```
#!/bin/bash
module load pgi/19.7
GCE=/nfs/gce/projects/naromero-workspace
export PATH=${GCE}/llvm-master/bin:$PATH
export NWCHEM_TOP=${GCE}/FLANG/nwchem-7.0.0
export NWCHEM_TARGET=linux64
export USE_MPI=y
export LIBMPI="-lmpifort -lmpi"
export MPI_LIB=/home/naromero/mpich-3.3.2-test/lib
export MPI_INCLUDE=/home/naromero/mpich-3.3.2-test/include
export USE_INTERNALBLAS=y
export NWCHEM_MODULES=all
export CC=pgcc
export FC=flang

cd ${NWCHEM_TOP}/src
make nwchem_conf
make
```

**Comment by hjjvandam** [comment]
Hi Nick,

I noticed two things with your environment variables:

  1.  I am not sure whether the NWCHEM_TARGET setting is case sensitive. I would try setting NWCHEM_TARGET=LINUX64
  2.  You haven’t set ARMCI_NETWORK. I don’t know if that is still required or not, historically this could be set to either MPI or TCGMSG. Apparently you should be able to set ARMCI_NETWORK=SOCKETS which is probably what you want (see issue #105 on Github)

Best wishes,

    Huub

-----------------------------------------------------------------------------------------------------
Hubertus van Dam, 631-344-6020, hvandam@bnl.gov<mailto:hvandam@bnl.gov>
Brookhaven National Laboratory

**Comment by edoapra** [comment]
> I am still getting this error. Here is my new build script with MPI:
> 
> ```
> #!/bin/bash
> module load pgi/19.7
> GCE=/nfs/gce/projects/naromero-workspace
> export PATH=${GCE}/llvm-master/bin:$PATH
> export NWCHEM_TOP=${GCE}/FLANG/nwchem-7.0.0
> export NWCHEM_TARGET=linux64
> export USE_MPI=y
> export LIBMPI="-lmpifort -lmpi"
> export MPI_LIB=/home/naromero/mpich-3.3.2-test/lib
> export MPI_INCLUDE=/home/naromero/mpich-3.3.2-test/include
> export USE_INTERNALBLAS=y
> export NWCHEM_MODULES=all
> export CC=pgcc
> export FC=flang
> 
> cd ${NWCHEM_TOP}/src
> make nwchem_conf
> make
> ```

Nick,
Are you getting a failure in the tools compilation or in the peigs compilation?
If you are getting a failure in peigs, could you please send me the output of the following command
```
make FC=f18 CC=pgcc NWCHEM_TARGET=LINUX64 V=1
```

**Comment by naromero77** [comment]
Edo, sorry been in a meetings most of the day.

It seems to be working now and really the only thing I changed is:
`linux64` -> `LINUX64`

So perhaps, it is like @hjjvandam suggested. The value of `NWCHEM_TARGET` is case sensitive

**Comment by naromero77** [comment]
I suppose this issue can be fixed with a little documentation or make the value of `NWCHEM_TARGET` case insensitive. Its also OK to do nothing, but I will leave the issue open until early next week, after which I will just close it.

**Comment by edoapra** [comment]
commit 92ac3cc65d4ff6cd2f8423c2b2d6a2681da0175c will make the compilation if NWCHEM_TARGET is not recognized.
This is a better fix, since it avoid creative user choices, too
