### ISSUE TITLE
f18 compile-time issue with `equivalence` in moints

### ISSUE THREAD

**Issue by naromero77** [nwchemgit/nwchem#224]
Here are some more compile-time issues with f18. As I offered before, I am willing to push on supporting this use case of `equivalence`, but it will not happen right away. Recommended replace for `equivalence` is the `transfer` intrinsic function.

```
flang  -c -i8 -Mdalign -Mllalign -Kieee  -Mcache_align   -g -O2  -I.  -I/nfs/gce/projects/naromero-workspace/FLANG/nwchem-7.0.0/src/include -I/nfs/gce/projects/naromero-workspace/FLANG/nwchem-7.0.0/src/tools/install/include -DEXT_INT -DLINUX -DLINUX64 -DCHKUNDFLW -DPGLINUX -DCHKUNDFLW -DPGLINUX -DPARALLEL_DIAG -DDEBUG_PRINT  sifs1.F
sifs1.F:2498:26: error: Equivalence set cannot contain 'longw' that is numeric sequence type and 'shortw' that is not
        equivalence (longw,shortw)
                           ^^^^^^
sifs1.F:2589:26: error: Equivalence set cannot contain 'longw' that is numeric sequence type and 'shortw' that is not
        equivalence (longw,shortw)
                           ^^^^^^
sifs1.F:2659:26: error: Equivalence set cannot contain 'longw' that is numeric sequence type and 'shortw' that is not
        equivalence (longw,shortw)
                           ^^^^^^
sifs1.F:2719:26: error: Equivalence set cannot contain 'longw' that is numeric sequence type and 'shortw' that is not
        equivalence (longw,shortw)
                           ^^^^^^
sifs1.F:2784:26: error: Equivalence set cannot contain 'longw' that is numeric sequence type and 'shortw' that is not
        equivalence (longw,shortw)
                           ^^^^^^
sifs1.F:2843:26: error: Equivalence set cannot contain 'longw' that is numeric sequence type and 'shortw' that is not
        equivalence (longw,shortw)
                           ^^^^^^
sifs1.F:2958:27: error: Equivalence set cannot contain 'local1' that is numeric sequence type and 'llocl1' that is not
        equivalence (llocl1,local1),(llocl2,local2)
                            ^^^^^^
sifs1.F:2958:43: error: Equivalence set cannot contain 'local2' that is numeric sequence type and 'llocl2' that is not
        equivalence (llocl1,local1),(llocl2,local2)
                                            ^^^^^^
sifs1.F:2959:27: error: Equivalence set cannot contain 'local3' that is numeric sequence type and 'llocl3' that is not
        equivalence (llocl3,local3),(llocl4,local4)
                            ^^^^^^
sifs1.F:2959:43: error: Equivalence set cannot contain 'local4' that is numeric sequence type and 'llocl4' that is not
        equivalence (llocl3,local3),(llocl4,local4)
                                            ^^^^^^
sifs1.F:2965:26: error: Equivalence set cannot contain 'longw' that is numeric sequence type and 'shortw' that is not
        equivalence (longw,shortw)
                           ^^^^^^
sifs1.F:3154:27: error: Equivalence set cannot contain 'local1' that is numeric sequence type and 'llocl1' that is not
        equivalence (llocl1,local1),(llocl2,local2)
                            ^^^^^^
sifs1.F:3154:43: error: Equivalence set cannot contain 'local2' that is numeric sequence type and 'llocl2' that is not
        equivalence (llocl1,local1),(llocl2,local2)
                                            ^^^^^^
sifs1.F:3155:27: error: Equivalence set cannot contain 'local3' that is numeric sequence type and 'llocl3' that is not
        equivalence (llocl3,local3),(llocl4,local4)
                            ^^^^^^
sifs1.F:3155:43: error: Equivalence set cannot contain 'local4' that is numeric sequence type and 'llocl4' that is not
        equivalence (llocl3,local3),(llocl4,local4)
                                            ^^^^^^
sifs1.F:3161:26: error: Equivalence set cannot contain 'longw' that is numeric sequence type and 'shortw' that is not
        equivalence (longw,shortw)
```

**Comment by naromero77** [comment]
Doing a recursive grep in NWChem: There are over two dozen files that contain the `equivalence` statements, but I am not sure that all would need to be replaced since it appears that **some** support for `equivalence` is available in `f18`

**Comment by naromero77** [comment]
I took a bit of hiatus from compiling NWChem with `f18`, but I would like to follow-up. I have two questions:

1. Given the number of `equivalence` statements in NWChem. How important do you think it is to have `f18` support for the use cases in the code? For example, if you plan to get rid of it in the future, I will not push the issue with the f18 developers. However, if this something that requires substantial re-work or the developer is no longer around -- I will push for support of equivalence for the NWChem use cases. 

2. I would still like to attempt to compile the rest of NWChem with `f18`, by avoiding components/modules that use `equivalence`. However, it is not obvious to me that use of `equivalence` is localized to a few modules and it also present in some header files. I may just give it the old-college try, but it would be helpful if anyone could provide some additional insight.

**Comment by hjjvandam** [comment]
Hi Nick,

As far as I can see all these equivalence statements are related to packing integers. For example if you have a two-electron integral (ij|kl) then you can store a single 8-byte integer to refer to that integral. However, at some point you will need to know i, j, k, and l separately. Of course you can use masks and bit shifts, or integer mod and divides, but a really simple and cheap way is to simply change the way you view this single 8-byte integer. If you use an equivalence to view this integer as 4 2-byte integers than you can extract i, j, k and l directly out of the 8-byte integer (apart from the big-endian vs little-endian issue).

So yes, it is possible to reimplement this stuff, but care is needed for at least two reasons:

  1.  One needs to understand the code in detail to ensure that the packing is done right (a lot of stuff will break badly if there are coding errors)
  2.  One needs to understand how compilers translate alternative codes to ensure that the packing and unpacking is done efficiently. Depending on the functionality where this is used the packing/unpacking can take something like 10% of the computer time. Doing this in a stupid way can have a larger impact on performance.
Of course the last issue is that addressing this is a rather thankless task. At best no one will ever know about the work that went into it, as worst you will get major hassle for breaking the code.

As for additional insights I think moints is used in a number of cases. There are just a few configurations that avoid using this module (tinyqmpw, and the classical molecular dynamics modules). In any case, I am not in a position to commit resources to fixing this (although I would be willing to help).

Best wishes,

    Huub

-----------------------------------------------------------------------------------------------------
Hubertus van Dam, 631-344-6020, hvandam@bnl.gov<mailto:hvandam@bnl.gov>
Brookhaven National Laboratory

**Comment by edoapra** [comment]
FYI
https://github.com/nwchemgit/nwchem/commit/9dbe5d476727a032c1d32a31302446c9225e0d03
https://github.com/nwchemgit/nwchem/commit/76482efa53b078cd32b481d8ba3ae5a12345a1b9
https://github.com/nwchemgit/nwchem/commit/3841c556331f1bec586fac1d7a82a3dd280b3a4a

**Comment by naromero77** [comment]
@hjjvandam Thanks for explaining the code. Yes, these types of tasks can be tedious and thankless.
