### ISSUE TITLE
COMPILATION_DATE and NWCHEM_BRANCH substitutions misformatted by makefile 

### ISSUE THREAD

**Issue by levik85** [nwchemgit/nwchem#226]
When compiling the code (commit c9099c8623ad15d0ca784efb47995e2d4a477d54)

> mpiifort -i8 -g  -I.  -I/l/nwchem/src/include -I/l/nwchem/src/tools/install/include -DEXT_INT -DLINUX -DLINUX64 -DSCALAPACK  -DPARALLEL_DIAG -DCOMPILATION_DATE="'`date +%a_%b_%d_%H:%M:%S_%Y`'" -DCOMPILATION_DIR="'/l/nwchem'"  -DNWCHEM_BRANCH="'7.0.0'"  -c -o nwchem.o nwchem.F
> nwchem.F(508): error #5082: Syntax error, found ':' when expecting one of: <END-OF-STATEMENT> ;
>      & Fri_Jul_03_12:23:09_2020
> --------------------^
> nwchem.F(508): error #5082: Syntax error, found END-OF-STATEMENT when expecting one of: ) ,
>      & Fri_Jul_03_12:23:09_2020
> -------------------------------^
> nwchem.F(512): error #5082: Syntax error, found REAL_CONSTANT '.0' when expecting one of: :: ) , : * <END-OF-STATEMENT> ; . (/ + - ] /) ' ** > PRIVATE / // ...
>      & 7.0.0   
> ----------^
> nwchem.F(508): error #6404: This name does not have a type, and must have an explicit type.   [FRI_JUL_03_12]
>      & Fri_Jul_03_12:23:09_2020
> -------^
> nwchem.F(508): error #6514: Substring or array slice notation requires CHARACTER type or array.   [FRI_JUL_03_12]
>      & Fri_Jul_03_12:23:09_2020
> -------^
> nwchem.F(507): error #6200: A colon (:) is not valid in this context.
>       compiled =
> ^
> nwchem.F(508): error #6684: This is an incorrect value for a kind type parameter in this context.   [2020]
>      & Fri_Jul_03_12:23:09_2020
> ---------------------------^
> nwchem.F(512): error #6054: A CHARACTER data type is required in this context.
>      & 7.0.0   
> ----------^
> compilation aborted for nwchem.F (code 1)
> <builtin>: recipe for target 'nwchem.o' failed

I manually entered the compilation date and version information on the relevant lines (508 and 512) and compiled just fine.

The formatting of these substitutions by the shell is apparently not as expected. The shell is:

GNU bash, version 4.3.48(1)-release (x86_64-pc-linux-gnu)

**Comment by edoapra** [comment]
Please don't set FC=mpifort. Instead, add the location of mpif90 to your PATH env. variable and set FC to the name of the Fortran compiler you are using

**Comment by edoapra** [comment]
No further feedback received. Closing this requeste
