### ISSUE TITLE
Can NWCHEM calculate oscillator strengths?

### ISSUE THREAD

**Issue by xiongyan21** [nwchemgit/nwchem#230]
Can NWCHEM calculate oscillator strengths, e.g., with TDDFT or EOMCCSD?

Very Best Regards!

**Comment by jeffhammond** [comment]
EOMCC methods compute 0->n oscillator strengths but not m->n. It could do the latter but the code isn’t there.

**Comment by ngovind** [comment]
If you run TDDFT calculations, the oscillator strengths are calculated and
printed in the output.

Best,
-Niri

**Comment by xiongyan21** [comment]
Dear Dr. Hammond and Govind
I have found that from TDDFT output,  but got the following  instead of oscillator strength in the QA test tce_uracil_creomact
 Target symmetry : a"  
      Symmetry restriction : on 
   Dipole & oscillator str : off
                I/O scheme : Global Array Library

Very Best Regards!

**Comment by jeffhammond** [comment]
To get dipole and oscillator strengths, you need to add the `dipole` keyword (http://www.nwchem-sw.org/index.php/Release66:TCE#DIPOLE_--_the_ground-_and_excited-state_dipole_moments) so TCE solves the EOM left eigenvectors.

When you run a perturbative method like CR-EOM-CCSD(T) or similar, the perturbative corrections only apply to the energies, so your dipoles and oscillator strengths will be computed at the EOM-CCSD level of theory.

If you want more accurate dipoles and oscillator strengths, you'll need to use active-space iterative triples EOM-CCSDt,  However, I confess that it has been a long time since I ran that code and I don't know if everything is implemented and validated.  Karol or someone who has worked on TCE in the 10 years will know better than me.

**Comment by xiongyan21** [comment]
Dear Dr. Hammond
Thanks a lot.
The addition of dipole into TCE requires much more GA, but the parallel run is much slower.

Very Best Regards!

**Comment by jeffhammond** [comment]
Okay.  Sorry about that.  I don't remember all the details.  I thought EOM-CCSD was fully memory-optimized now, although it is certainly the case that you have to solve more equations.  I wouldn't expect that the CCSD-Lambda and EOM-CCSD-Left would increase the memory requirements by more than double.  Post your input file and maybe I can run it somewhere.  I have computers with stupid amounts of memory :-D

**Comment by xiongyan21** [comment]
Dear Hammond
The input is from  QA test test tce_uracil_creomact with  the addition of dipole into TCE, but the sto-3g and 3-21G gives the following mistake
 Memory Information
            ------------------
          Available GA space size is     524281600 doubles
          Available MA space size is     144152556 doubles

 Maximum block size supplied by input
 Maximum block size        15 doubles
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 1 in communicator MPI COMMUNICATOR 3 DUP FROM 0
with errorcode -1000.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------

Very Best regards!

**Comment by jeffhammond** [comment]
You can increase memory as shown below:
```
title "uracil-6-31-Gs-eomccsd"
echo
start uracil-6-31-Gs-eomccsd

memory stack 2000 mb heap 100 mb global 2000 mb noverify # per process memory settings

geometry units angstrom
N            .034130    -.986909     .000000
N          -1.173397     .981920     .000000
C          -1.218805    -.408164     .000000
C           -.007302    1.702153     .000000
C           1.196200    1.107045     .000000
C           1.289085    -.345905     .000000
O           2.310232    -.996874     .000000
O          -2.257041   -1.026495     .000000
H            .049329   -1.997961     .000000
H          -2.070598    1.437050     .000000
H           -.125651    2.776484     .000000
H           2.111671    1.674079     .000000
end

basis cartesian
* library 6-31G*
end

scf
thresh 1.0e-10
singlet
rhf
end

tce
# frozen core approximation
freeze atomic
# CCSD level of theory
ccsd
# EOM wtih one root - the one with a' symmetry
nroots 1
symmetry 
targetsym a'
# dipole and oscillator strengths
dipole
# convergence criteria
thresh 1.0d-5
# for CCSD, this can be 30-40, but for (T) it must be ~20
tilesize 32
# spin-free two-electron integrals
2eorb
# the fastest spin-free four-index transformation algorithm
2emet 13
end

task tce energy
```

**Comment by xiongyan21** [comment]
Dear Hammond
Thanks a lot for your telling me the addition of dipole will get oscillator strength with coupled cluster methods using NWCHEM7.0.0, but I will not actually repeat  the QA test  again, thus I will not try your input.

Very Best Regards!
