### ISSUE TITLE
Tests are failing due to SEGFAULT

### ISSUE THREAD

**Issue by antoscha** [nwchemgit/nwchem#245]
Hi,

I have found many tests failed because of various segmentation faults and precision losses. Please consider the attached output.
NWChem was configured as follows:
```
export CC=gcc
export CXX=g++
export FC=gfortran
export F77=gfortran

export USE_MPI=yes

export MPI_LOC=/usr
export MPI_LIB=$MPI_LOC/lib/openmpi
export MPI_INCLUDE=$MPI_LOC/include
export LIBMPI="-lmpi_usempif08 -lmpi_usempi_ignore_tkr -lmpi_mpifh -lmpi"

export USE_64TO32=y

export HAS_BLAS=yes
export BLASOPT="-lblas"
export BLAS_SIZE=4

export USE_SCALAPACK=y
export SCALAPACK_SIZE=4
export SCALAPACK="-lscalapack"

export LAPACK_SIZE=4
export LAPACK_LIB="-llapack"

export NWCHEM_TARGET=LINUX64
export NWCHEM_MODULES="all nwxc python"
export NWCHEM_TOP=$(pwd)

export USE_PYTHONCONFIG=y
export PYTHONHOME=/usr
export PYTHONVERSION=3.8
export PYTHONLIBTYPE=so

export LARGE_FILES=TRUE
export USE_NOFSCHECK=TRUE

export MRCC_METHODS=y
export CCSDTQ=y
export CCSDTLR=y
export IPCCSD=y
export EACCSD=y
```

[few_tests.log](https://github.com/nwchemgit/nwchem/files/5136138/few_tests.log)

**Comment by edoapra** [comment]
Could you provide more details on this issue?
For example, do you get the same failure at smaller. processor counts (you seem to be using 28)?
What are the details of the computer(s) you are using? Is it a single node with 28 core? Is multi-threading on or not?
Did you execute `make 64_to_32` in the compilation process

**Comment by antoscha** [comment]
Yes, it's a single-node computer without hyperthreading, here is the sequence of compilation commands:
```
cd src
make nwchem_config
make 64_to_32
make
../contrib/getmem.nwchem
cd util
make version
make
cd ..
make link
```
Testing results with the use of fewer cores I'll report later.

**Comment by antoscha** [comment]
Well, it's much better when only 4 cores are employed. I run the script `doqmtests.mpi` and there are still similar errors. Could you please look into the attached file?
[fast_tests.txt](https://github.com/nwchemgit/nwchem/files/5138873/fast_tests.txt)

**Comment by edoapra** [comment]
It's better, but there are still unexpected segvs
Could you post the following files
$NWCHEM_TOP/QA/testoutputs/dft_li2freq.out
$NWCHEM_TOP/QA/testoutputs/hess_nh3_ub3lyp.out

If these files don't help much, you should probably recompiled the `tools` directory, after

- unsettting all the MPI variables (MPI_LIB, MPI_INCLUDE and LIBMPI)
- setting ARMCI_NETWORK=MPI-PR 

e.g.
```
cd tools
unset MPI_LIB
unset MPI_INCLUDE
unset LIBMPI
export ARMCI_NETWORK=MPI-PR 
make clean
make
cd ..
make link
```

**Comment by sparerib2019** [comment]
Thanks, Edoardo,
I am in prior surveys with the customers precise requirements.
Let me look into those folks before get back to you.

Kind Regards,
Tomoya Ito

ソフテックアイオーティー株式会社
（ソフテック代表）
一般社団法人大阪府産業支援型NPO協議会 IoTアドバイザー
非営利公益団体各種
伊藤 智哉 / Tomoya Ito
空気圧技能士１級、NI準公認 / NI Assistant Developer
5330033 大阪市東淀川区東中島1-17-5 ステュディオ新大阪520
(電話&FAX)+81 (0)6 6195 8007 (携帯)+81 (0)90-9543-6637
メール(mail)： mailto:tomoya.ito@softech.mobi
Web：                        https://service-dmc.wixsite.com/mysite-1293

https://softechiotenglish.wordpress.com/
Facebook：  https://goo.gl/pLTXFx


2020年8月28日(金) 6:39 Edoardo Aprà <notifications@github.com>:

**Comment by antoscha** [comment]
Alright, segfaults are gone with the use of `ARCMI_NETWORK=MPI-PR`. But there is still a lot of precision losses, please check in the attachment.
[qmtests.txt](https://github.com/nwchemgit/nwchem/files/5175858/qmtests.txt)

**Comment by edoapra** [comment]
The numerical discrepancies in the QA log you sent us are acceptable (some are due to the parsers not being smart enough to catch a different output order). The QA log shows that your NWChem installation is working correctly.

**Comment by antoscha** [comment]
Thank you very much!
