### ISSUE TITLE
Create (and distribute) a Flatpak (or a SNAP) so any Linux distro can have NWChem working properly

### ISSUE THREAD

**Issue by HenriqueCSJ** [nwchemgit/nwchem#25]
Currently, Universal Linux Packages like Flatpak[1] and Snap[2] are turning into the easiest way to distribute software under Linux. It is nice because it eliminates the hard packaging process that has to be done by each Linux distro and the upstream (you) can be the direct provider of s single universal package.

Today, to provide NWChem is hard for the distros because packaging guidelines are too restrictive and dependencies are constantly breaking the software (so we got to be stuck with a version that "works" for most softwares) but with Universal Linux Packages, each software has the possibility to satisfy its own dependencies and work as intended.

Thank you for the great software

[1] - https://flatpak.org/
[2] - https://www.ubuntu.com/desktop/snappy

**Comment by edoapra** [comment]
@HenriqueCSJ you make a good point.
What about [AppImage](https://appimage.org/) or [Spack](https://spack.io/)(that has already a NWChem 6.6 module)?
I am not quite sure which one of this packages is the best match for NWChem.
I have done a  bit of experimentation myself with Docker, but I am not sure if a container is better or worse than Universal Linux Packages https://github.com/edoapra/docker-file

**Comment by HenriqueCSJ** [comment]
Let me add that Flatpak improved the package distribution: https://flathub.org/apps

**Comment by edoapra** [comment]
@HenriqueCSJ since NWChem 6.8.1 is now available in the Fedora/EPEL RPMs, I would like to close this issue.
I have experimented a bit with Flatpak and Snap, but they don't seem to be designed to match the build requirements of NWChem

**Comment by edoapra** [comment]
The only other package manager I had any success with is spack

**Comment by HenriqueCSJ** [comment]
@edoapra Thank you for taking a look at this. Let's hope that Flatpak evolves to suit NWChem's needs soon and I believe that if in the future packaging using all guidelines become prohibitive, maybe, a COPR RPM can do the job.

I'll keep an eye on Flatpack and SNAP.
