### ISSUE TITLE
MPI run on NWChem 7.0.0

### ISSUE THREAD

**Issue by 80nph1r3** [nwchemgit/nwchem#252]
Hello,

I installed NWChem 7.0.0 on Ubuntu 18.04.5 with following commands:

sudo apt -y install curl  python3-dev gfortran  mpi-default-bin mpi-default-dev libopenblas-dev ssh

curl -LJO https://github.com/nwchemgit/nwchem/releases/download/v7.0.0-release/nwchem-data_7.0.0-3_all.ubuntu_bionic.deb
curl -LJO https://github.com/nwchemgit/nwchem/releases/download/v7.0.0-release/nwchem_7.0.0-3_amd64.ubuntu_bionic.deb

sudo dpkg -i nwchem-data_7.0.0-3*_bionic.deb nwchem_7.0.0-3*_bionic.deb

It can perform a single-thread calculation, but if I try to start an MPI run with the command

mpirun -n 2 nwchem ./h2o_freq.nw >& h2o_freq.out &

I get the warning:

[[62635,1],0]: A high-performance Open MPI point-to-point messaging module
was unable to find any relevant network interfaces:

Module: OpenFabrics (openib)
  Host: hpnode0601

Another transport will be used instead, although this may result in
lower performance.

MPI run cannot start and is aborted. Input and output files are attached. 

What should I do?

[h2o_freq-inp.txt](https://github.com/nwchemgit/nwchem/files/5247144/h2o_freq-inp.txt)
[h2o_freq-out.txt](https://github.com/nwchemgit/nwchem/files/5247145/h2o_freq-out.txt)

**Comment by edoapra** [comment]
The network interface warning can be ignored.
If you are curious about it, you can find more details with a google search.
The real error is another one and it seems to indicate that you are trying to perform I/O (write a file) in a directory where you don't have write permission
 ```
./h2o_freq.db: Permission denied
hdbm_open: open of ./h2o_freq.db failed
rtdb_seq_open: hdbm failed to open file ./h2o_freq.db
 ------------------------------------------------------------------------
 start: rtdb_open empty failed                    0
 ------------------------------------------------------------------------
 start: rtdb_open empty failed                    0
 ------------------------------------------------------------------------
 ------------------------------------------------------------------------
  current input line : 
 ------------------------------------------------------------------------
  current input line : 
```

**Comment by 80nph1r3** [comment]
Thank you very much for the response
