### ISSUE TITLE
Does NWChem support AMD GPUs? If yes, is there anything I need to know to install NWChem correctly?

### ISSUE THREAD

**Issue by danny305** [nwchemgit/nwchem#253]
AMD has just donated some fat servers to UT with each server having 8GPUs. I am trying to get NWChem installed on these servers but can't find anything on the internet on how to install NWChem so it can take advantage of the AMD GPUs. Since its AMD, it does not utilize CUDA but instead has ROCm. Is NWChem compatible?

Danny

**Comment by edoapra** [comment]
@danny305 
Here are some links you might find useful
https://github.com/nwchemgit/nwchem/issues/70
https://blog.csdn.net/jslove1997/article/details/104566464
https://blog.csdn.net/jslove1997/article/details/104377425

**Comment by jeffhammond** [comment]
The NWChem CUDA C kernels in TCE were converted to use HIP.  There is also some OpenMP target offload support.  Have you tested OpenMP target in ROCm AOCC to see if it is working well?
