### ISSUE TITLE
C Preprocessor error with Intel Compilers

### ISSUE THREAD

**Issue by roguephysicist** [nwchemgit/nwchem#255]
I get the following error when using the Intel compiler suite (2018 and 2020):
```console
checking how to run the C preprocessor... fpp -P 
configure: error: in `$NWCHEM_TOP/src/tools/build':
configure: error: C preprocessor "fpp -P " fails sanity check
```

**Describe settings used**

Environment Variables:

export NWCHEM_TOP="$RESEARCHPATH/src/nwchem-7.0.0"
export NWCHEM_TARGET=LINUX64
export NWCHEM_MODULES="all python"
export USE_MPI=y
export USE_MPIF=y
export USE_MPIF4=y
export USE_INTERNALBLAS=y

Operating system: Red Hat Enterprise Linux 7

**Attach log files**
[config.log](https://github.com/nwchemgit/nwchem/files/5271580/config.log)

**To Reproduce**
```console
make nwchem_config && make
```

**Expected behavior**
Running the following command separetely,
```console
cd $NWCHEM_TOP/src/tools/build/
../ga-5.7.1/configure --prefix=$NWCHEM_TOP/src/tools/install SCOREP_WRAPPER=OFF --with-tcgmsg --with-mpi="-I$MPIHOME/include -I$MPIHOME/lib -L$MPIHOME/lib -lmpi_usempif08 -lmpi_usempi_ignore_tkr -lmpi_mpifh -lmpi" --enable-peigs --enable-underscoring --disable-mpi-tests --without-scalapack --without-lapack --without-blas --with-mpi-ts CC=icc CXX=icpc F77=ifort ARMCI_DEFAULT_SHMMAX_UBOUND=131072
```
correctly detects my C preprocessor as either `icc -E` or `icpc -E`. This problem does not occur at all with the GNU compilers.

**Additional context**
I load my compilers, MPI, etc. from modulefiles. They are properly configured; I have compiled hundreds of programs with them. This error is also reproducible from within Spack.

**Comment by edoapra** [comment]
@roguephysicist  Did you set the env. variable CPP?

What is the output of the command
```
  env | grep CPP
```
and of the command
```
  env | grep fpp
```

**Comment by roguephysicist** [comment]
Yes, it is set automatically from my modulefile:

```console
$ env | grep CPP
$ env | grep fpp
$ module load compilers/intel/2018 
$ env | grep CPP
CPP=icc -E
$ env | grep fpp
$
```

**Comment by edoapra** [comment]
Please unset CPP

**Comment by roguephysicist** [comment]
I did, got the same error.

**Comment by edoapra** [comment]
Could you submit 
$NWCHEM_TOP/src/tools/build/comex.log

**Comment by roguephysicist** [comment]
It doesn't get that far; this occurs during the very first part. The only the file that is generated is `$NWCHEM_TOP/src/tools/build/config.log`, which I attached above.

**Comment by edoapra** [comment]
What is output of 
```
ls -l $NWCHEM_TOP/src/tools/build/
ls -l $NWCHEM_TOP/src/tools/build/comex
```

**Comment by roguephysicist** [comment]
```
$ ls -l $NWCHEM_TOP/src/tools/build/
total 20
-rw-rw-r--. 1 user user 19563 Sep 23 16:24 config.log
$ ls -l $NWCHEM_TOP/src/tools/build/comex
ls: cannot access $NWCHEM_TOP/src/nwchem-7.0.0/src/tools/build/comex: No such file or directory
```

**Comment by edoapra** [comment]
Very strange
According to config.log
```
configure:45864: === configuring in comex (/data.local1/milias/software/nwchem/nwchem_master/src/tools/build/comex)
```
I see a discrepancy, config.log that was submitted does not seem to correspond to 7.0.0, while your latest error log does correspond to 7.0.0.
Could you post this newer config.log?

**Comment by edoapra** [comment]
Sorry, please ignore the latest posting. I was looking at the wrong file!

**Comment by roguephysicist** [comment]
No problem! Thanks for working on this with me.

**Comment by edoapra** [comment]
Thanks!
Anyhow, the config.log file seems shorter than expected.
The last test reported in config.log is not the pre-processor check
Could you please report its size with
```
ls -l config.log
```

**Comment by edoapra** [comment]
the config.log that was uploaded seem the result of an execution stopped with `CTRL+C` a.k.a `SIGINT`
```
configure: caught signal 2
configure: exit 1
```

**Comment by roguephysicist** [comment]
I ran it all again for consistency. Attached is the `config.log` and what was printed to stdout.

```
-rw-rw-r--. 1 user user 19437 Sep 23 17:51 nwchem-7.0.0/src/tools/build/config.log
```

[config.log](https://github.com/nwchemgit/nwchem/files/5272111/config.log)
[stdout.txt](https://github.com/nwchemgit/nwchem/files/5272112/stdout.txt)

**Comment by edoapra** [comment]
According to this new config.log, `CPP` was set equal to `fpp -P`
```
$ grep ac_cv_env_CPP_ config.log
c_cv_env_CPP_set=set
ac_cv_env_CPP_value='fpp -P '
```

**Comment by roguephysicist** [comment]
That was definitely not set by me -- I did find these lines within the source:

```
src/config/makefile.h
1979:           CPP=fpp -P 

src/config/makefile-legacy.h
1979:           CPP=fpp -P 

src/config/makefile.h.orig
1977:           CPP=fpp -P 
```

**Comment by edoapra** [comment]
makefile.h is the only one that could potentially be sourced.
Not sure why this happens in your case and not when I try to reproduce your problem.
Anyhow, could you try 
```
cd $NWCHEM_TOP/src/tools
make FC=ifort CPP="gcc -E"
```
Please send me stdout and config.log

**Comment by edoapra** [comment]
Could you also delete line 1979 from `src/config/makefile.h` and re-try with the same env. you first used?
Thanks

**Comment by roguephysicist** [comment]
The first thing you suggested worked, now trying the second.
[config.log](https://github.com/nwchemgit/nwchem/files/5272365/config.log)
[stdout.txt](https://github.com/nwchemgit/nwchem/files/5272366/stdout.txt)

**Comment by roguephysicist** [comment]
Yeah, deleting line 1979 worked as well:
[config.log](https://github.com/nwchemgit/nwchem/files/5272462/config.log)
[stdout.txt](https://github.com/nwchemgit/nwchem/files/5272463/stdout.txt)

**Comment by edoapra** [comment]
I guess you have found a solution of the problem, isn't it?
Inspection of the latest config.log shows `CPP='icc -E'`
I have removed the definition of `CPP` for `FC=ifort` since it was related to a part of code that is no longer in use. I am testing these changes in the master branch and, if the tests are successful, I will commit the changes to the  [hotfix/release-7-0-0](https://github.com/nwchemgit/nwchem/tree/hotfix/release-7-0-0) branch, too.

**Comment by roguephysicist** [comment]
Awesome, thanks @edoapra. Hopefully these changes will also propagate soon to Spack. I will start building now with the modified makefile.

**Comment by edoapra** [comment]
NWChem 7.0.2 is out and it just got into spack
[https://github.com/spack/spack/pull/19297#event-3874587087](https://github.com/spack/spack/pull/19297#event-3874587087)

> Awesome, thanks @edoapra. Hopefully these changes will also propagate soon to Spack. I will start building now with the modified makefile.
