### ISSUE TITLE
Understand the src

### ISSUE THREAD

**Issue by ysy1111** [nwchemgit/nwchem#256]
Having a rough idea about how do the source codes work is quiet time-consuming and difficult only with the comments in codes. I am working on designing some new xc functionals. Understanding the code is the first step. Do you have any doc to help me studying the source code? Your help is really appraciated!

**Comment by hjjvandam** [comment]
Hi Ysy1111,

There is a technical report that talks about the implementation of density functionals: https://www.bnl.gov/isd/documents/93143.pdf. Admittedly, this report mainly discusses the various techniques for generating code for higher order derivatives, and not so much about how the code is designed. However, there are a few comments in this report about the structure of the code. Also, there were some slides on the code structure on the old NWChem website at www.nwchem-sw.org<http://www.nwchem-sw.org>, but website has been retired and no longer exists. Maybe Karol can comment on whether the material that was on the website is still available somewhere.

Another thing that I have used in the past is http://www.cse.scitech.ac.uk/ccg/software/gprof2tree/. This is a little tool that takes the output from the performance profiler gprof and turns it into a textual call tree. While this is certainly not the greatest thing it is a way of relatively quickly getting a call tree of the piece functionality that you are interested in.

I hope this helps.

Best wishes,

     Huub

-----------------------------------------------------------------------------------------------------
Hubertus van Dam, 631-344-6020, hvandam@bnl.gov<mailto:hvandam@bnl.gov>
Brookhaven National Laboratory

**Comment by edoapra** [comment]
Here is the link to the NWChem architecture
https://nwchemgit.github.io/NWChem-Architecture.html

**Comment by edoapra** [comment]
@ysy1111 the following directory contains the LaTeX source of the programmer's manual
https://github.com/nwchemgit/nwchem/tree/master/doc/prog
This was written several years ago and some of its content might no longer be valid.
Another issue that there is very little content on the gaussian DFT module
A partial flow-chart for  the DFT code is 
https://github.com/nwchemgit/nwchem/blob/master/src/nwdft/grid/flow.txt

**Comment by ysy1111** [comment]
@hjjvandam Thank you very much. It seems gprof2tree is quite useful. After reading its instruction, I understand how it works on a single Fortran program (like the example they gave). But how does it work for a large scale software like NWChem? Sorry, I am literally a newbie at Linux.

**Comment by ysy1111** [comment]
@edoapra Thank you!

**Comment by jeffhammond** [comment]
I haven't used it but gprof2tree should work with multi-object binaries the same as it does with one source file.  Just read up on how to use gprof and make sure to compile NWChem with `USE_GPROF=y` in your environment.

You can also try Intel Vtune to make call graphs [1] which you can get for free via [2] or [3], where the latter supports Apt and Yum [4].  (I work for Intel and must disclose this when recommending Intel products.)

1. https://software.intel.com/content/www/us/en/develop/articles/making-visual-call-graphs-from-intel-vtune-amplifier-output.html
2. https://software.intel.com/content/www/us/en/develop/tools/vtune-profiler/choose-download.html
3. https://software.intel.com/content/www/us/en/develop/tools/oneapi/base-toolkit.html
4. https://software.intel.com/content/www/us/en/develop/articles/oneapi-repo-instructions.html

**Comment by hjjvandam** [comment]
Hi Ysy1111,

In nwchem/src/config/makefile.h there is a variable USE_GPROF that adds the relevant compiler flags. I think you can turn this on simply by setting the environment variable

                export USE_GPROF=yes

After that you will need to recompile the code as the compiler has to instrument it. I am sorry that this is a bit tedious but it should save you having to extract the call stack by hand.

Best wishes,

    Huub

-----------------------------------------------------------------------------------------------------
Hubertus van Dam, 631-344-6020, hvandam@bnl.gov<mailto:hvandam@bnl.gov>
Brookhaven National Laboratory

**Comment by jeffhammond** [comment]
One of the advantages of Vtune is that it doesn't need the `-pg` flag, but obviously it has other limitations.

https://software.intel.com/content/www/us/en/develop/documentation/vtune-help/top/set-up-analysis-target/linux-targets/compiler-switches-for-performance-analysis-on-linux-targets.html
