### ISSUE TITLE
SIMINT

### ISSUE THREAD

**Issue by heully** [nwchemgit/nwchem#26]
I have a library with simint, it was linked into nwchem6.8 but how to tell nwchem to use this library rather than texas or hondo ?
thank you very much
jean-louis

**Comment by edoapra** [comment]
Jean-Louis
The Simint interface is only present in the master branch and not in the 6.8 branch.
Some preliminary/rough notes about the Siminit NWChem interface are in
https://github.com/nwchemgit/nwchem/blob/master/src/NWints/simint/simint.txt

**Comment by heully** [comment]
I have problem with the int_init subroutine. As soon as you say true for a particular int code I get:
logic error with user cando settings. In fact I do not understand the logic of int_init. Anaway I tried different setting for cando_txs, nw and sim but nothing works! could you give me more information on
how to tell nwchem to use simint. thank you very much

**Comment by edoapra** [comment]
@heully The cando_txs/cand_nw errors you are the expected behavior when Simint is not linked against NWChem.
Are you using the current master branch from NWChem? What env. variables did you set?

**Comment by heully** [comment]
Hello !
Well, i am not very sur now. I put the following lines:
export SIMINT_HOME=/usr/local
export USE_SIMINT=y
but the meaning of SIMINT_HOME is not clear because when I installed simint it put things in /usr/local/include and /usr/local/lib. I thought that nwchem needs both and will search itself what it is needed. By the way it is a simint.a and not a simint.so I am using so I cannot see by a ldd if simint is inside nwchem.
However, looking at int_init.F I got the impression that one can only put false to a set int:cando_ ?
OK, I will produce a simint.so so I can verify that it is seen by nwchem.
Could you answer me to the meaning of simint_home ?
thank you very much
jean-louis

**Comment by edoapra** [comment]
@heully If you do ls -l $SIMINT_HOME, you should have (at least) the lib the include directories.
Could you please send me the output of the following commands?
```
cd $NWCHEM_TOP/src/NWints/simint
make clean
make
```

**Comment by heully** [comment]
hello, I tried what you said but  it was only crasy so I started from the veru beginning and:
I got the following, so now I do not understant what I did before:
make[4] : on entre dans le répertoire « /home/jean-louis/PROG/nwexp/nwchem/src/NWints/simint/module »
Compiling nwcsim_module.F...
nwcsim_module.F:3:9:

       use SimintFortran
         1
Fatal Error: Can't open module file ‘simintfortran.mod’ for reading at (1): Aucun fichier ou dossier de ce type
compilation terminated.
Am I missing something in my mwint ?

here is my compilation instruction in attached
[build_nwchem.txt](https://github.com/nwchemgit/nwchem/files/1816805/build_nwchem.txt)

**Comment by edoapra** [comment]
I believe that your build is failing since your Simint library does not contain the Fortran interface.
I completely forgot that the simint library currently distributed does not contain the Fortran interface.
You can either ask the Simint developers to update their library tarball or you can produce it yourself from the simint generator https://github.com/simint-chem/simint-generator

**Comment by edoapra** [comment]
Close after lack of feedback
