### ISSUE TITLE
NWChem problems with MPI

### ISSUE THREAD

**Issue by fjhermoso** [nwchemgit/nwchem#266]
Hi all,

I've been running NWChem recently and when I run it in console, I recieve this message: 
```
No protocol specified
[0] ARMCI Error: 0:nwchem: failed to open the input file:
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI COMMUNICATOR 3 DUP FROM 0
with errorcode -1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
```
Created .nwlog from that is completly clear and it does not contain any information. I contacted my boss but he made me come here because we don't know what's the problem. 

Thank you all,

**Comment by jeffhammond** [comment]
“nwchem: failed to open the input file” seems like the important part here.

How did you invoke NWChem and is your input file present?
-- 
Jeff Hammond
jeff.science@gmail.com
http://jeffhammond.github.io/

**Comment by fjhermoso** [comment]
Thanks for asking, Jeff!

I am located in a directory which I have called "NWCHEM", and there are all .nw files I have to run. Used command is:

nwchem_<_inputfile.nw_>_outputfile.nwlog_&

, where "_" represents a space. My input file starts with a blanck line, followed by "echo".

Thank you all,

**Comment by jeffhammond** [comment]
Do not pipe NWChem input files to the binary.  It will not work.  The command structure is:
```
# no MPI
$NWCHEM_TOP/bin/$NWCHEM_TARGET/nwchem input.nw 1> out.log 2> err.log
# MPI
mpirun -n 10 $NWCHEM_TOP/bin/$NWCHEM_TARGET/nwchem input.nw 1> out.log 2> err.log
```
