### ISSUE TITLE
python-3.10 build support

### ISSUE THREAD

**Issue by marcindulak** [nwchemgit/nwchem#271]
**Describe the bug**

nwchem https://github.com/nwchemgit/nwchem/commit/55e74b08d431e19b762c088ae19ec3d3be5a4efe fails to build python support

https://bugzilla.redhat.com/show_bug.cgi?id=1900680

```
make[1]: Entering directory '/builddir/build/BUILD/nwchem-5d4a0e84c8f8d9656a0ac37e796a9a4eff8c5ad9/src/python'
/bin/sh: python3.1-config: command not found
Compiling python_input.F...
/bin/sh: python3.1-config: command not found
Compiling task_python.c...
task_python.c:4:10: fatal error: Python.h: No such file or directory
    4 | #include <Python.h>
      |          ^~~~~~~~~~
compilation terminated.
```

This is due to cutting off the digits of python release in

https://github.com/nwchemgit/nwchem/blob/55e74b08d431e19b762c088ae19ec3d3be5a4efe/src/config/makefile.h#L2618-L2625

**Describe settings used**

Preparation for python 3.10 on fedora https://fedoraproject.org/wiki/Changes/Python3.10

**To Reproduce**

Requires fedora mock setup https://copr.fedorainfracloud.org/coprs/g/python/python3.10/

**Expected behavior**

`PYTHONVERSION` is set such that it corresponds to `python$PYTHONVERSION-config`.

**Screenshots**

**Additional context**

An example solution may consist of taking one more character (11 instead of 10), however I'm not sure whether the behavior of `cut` is defined in this case.

```
v=$(echo "Python 3.9" 2>&1 |cut -c 8-11); echo ${v}end
3.9end
v=$(echo "Python 3.10" 2>&1 |cut -c 8-11); echo ${v}end
3.10end
```

I'm also not sure how python development releases, like https://www.python.org/downloads/release/python-390a6/ will behave wrt to python-config.

**Comment by edoapra** [comment]
I think the only problem is for 3.10 and later (two digits for minor version). I will try to fix that
Development releases work for me. Here is what 3.9.0a6 does for me
```
curl -LJO https://www.python.org/ftp/python/3.9.0/Python-3.9.0a6.tgz
tar xzf Python-3.9.0a6.tgz
cd Python-3.9.0a6
./configure --prefix=$HOME/python390a6
make
make test
make install
export PATH=$HOME/python390a6/bin:$PATH
cd $NWCHEM_TOP/src/python
make clean ; make PYTHONVERSION=3.9
cd ..
make  PYTHONVERSION=3.9 link
cd ../QA
/runtests.unix pyqa3

 Running tests/pyqa3/pyqa3

     cleaning scratch
     copying input and verified output files
     running nwchem (/home/edo/nwchem/nwchem.oct//bin/LINUX64/nwchem)
          verifying output ... OK

OK
```

**Comment by edoapra** [comment]
The combination of commits https://github.com/nwchemgit/nwchem/commit/638401361c6f294164a4f820ff867a62ac836fd5 and https://github.com/nwchemgit/nwchem/commit/cd0496c6bdd58cf2f1004e32cb39499a14c4c677 addresses this issue. 
The combined patch can be found in https://github.com/edoapra/fedpkg/commit/608566800dd6c1aaac0a1d143b2d646b6e030883
