### ISSUE TITLE
NWCHEM7.0.2 compilation fails on Ubuntu18.04

### ISSUE THREAD

**Issue by xiongyan21** [nwchemgit/nwchem#280]
The following error appears at the last step
gfortran: error: lopenblas: there is no such file or clip
GNUmakefile:33: recipe for target 'all' failed
make: *** [all] Error 1

Very Best Regards!

**Comment by edoapra** [comment]
This is not a bug report. Please correctly use the template if you do want to report a bug.
If you are struggling to install NWChem on Ubuntu, you might consider install the precompiled packages
https://github.com/nwchemgit/nwchem/releases/tag/v7.0.2-release
```
sudo apt -y install  python3-dev gfortran  mpi-default-bin mpi-default-dev ssh

curl -LJO https://github.com/nwchemgit/nwchem/releases/download/v7.0.2-release/nwchem-data_7.0.2-1_all.ubuntu_bionic.deb
curl -LJO https://github.com/nwchemgit/nwchem/releases/download/v7.0.2-release/nwchem_7.0.2-1_amd64.ubuntu_bionic.deb
sudo dpkg -i nwchem*7.0.2*bionic*.deb
```

**Comment by xiongyan21** [comment]
Thanks, anyway. 
The source code compilation is successful after carefully reading the document.

Very Best Regards!
