### ISSUE TITLE
Unexpected contention from child thread using Intel MPI

### ISSUE THREAD

**Issue by glowthrower** [nwchemgit/nwchem#281]
**Describe the bug**

When compiled against a modern version of Intel MPI and launched using `mpirun` or `mpiexec`, NWChem consumes more CPU resources than I would naively expect. Specifically, each individual MPI process contains two threads (one parent and one child), both of which generate concurrent load. The end result is that a single MPI process produces up to 200% CPU load. Equivalently, if the machine has N cores, then running `mpirun -np <N> nwchem <input.nw>` produces such strong contention that the job barely proceeds. The following `htop` screenshot illustrates a case where two MPI processes are producing a combined load around 400%:

![nwchem_screenshot](https://user-images.githubusercontent.com/20861344/101544862-acb79980-39a6-11eb-877c-8cc0e3405884.png)

Note in particular that there should NOT be any OpenMP parallelism here, either in NWChem or in e.g. an external BLAS library such as MKL. This is deliberate -- I do see this behaviour in both these cases, but for the purposes of this bug report, I am using a "standard" build using the internal netlib BLAS (which isn't multithread AFAIK).

If I run NWChem in a way that enforces core binding or affinity, then both threads can wind up bound to the same core. This naturally also results in heavy contention, with each thread seemingly starving the other. If they're allowed to float free, then performance seems "OK" until the number of threads passes the number of available cores, at which point it rapidly degrades (for example, the case `mpirun -np 4` on an 8-core node is fine, `mpirun -np 5` is not).

If this is intended/expected behaviour, then please correct me. But it definitely seems unexpected, given that it doesn't match the behaviour I see when using the nwchem build available through apt on Ubuntu, for example, where performance scales nicely up through `mpirun -np <n>` until n reaches the number of available cores. (The various `nwchem` processes do spawn children, but they seem to play better with each other.)

One final comment: I wondered if this might be due to a busy wait somewhere on an MPI routine, so I have experimented with the `I_MPI_WAIT_MODE=1` environment variable. This seems to improve performance somewhat, but I don't think it "fixes" the issue so much as suppresses the symptoms.

**Describe settings used**

I am building and executing NWChem on Linux machines. I can reproduce this consistently both on a desktop running Ubuntu 18.04 LTS, and on various nodes of an HPC cluster running CentOS 7. In the latter case, the issue is seen consistently -- both on compute nodes inside slurm allocations, and on head nodes when executing directly with `mpirun` or `mpiexec`.

I'm building NWChem 7.0.2 with GCC 9.3.0, with `mpicc` etc. as provided by Intel MPI 2019 Update 8 (i.e. that from Parallel Studio 2020 Update 3). I can also reproduce this behaviour using other versions of GCC and/or Intel MPI, although I haven't exhaustively checked the various combinations.

For the purposes of this bug report, the build is performed using the environment variables specified by the following script:

```shell
#! /bin/bash

export NWCHEM_TOP=/home/<me>/nwchem-7.0.2
export NWCHEM_TARGET=LINUX64
export USE_MPI=y
export USE_MPIF=y
export USE_MPIF4=y

export ARMCI_NETWORK=MPI-MT

export USE_INTERNALBLAS=y

export NWCHEM_MODULES="all"
```

**To Reproduce**
1. Steps to reproduce the behavior:

 - Obtain and install a recent version of Intel Parallel Studio.
 
 - Build nwchem using either GCC or the Intel compilers, with the
   Intel MPI `mpicc` and `mpif90` etc. on path.

 - Launch an nwchem job using `mpirun nwchem`. Look at htop etc.

2. Attach all the input files required to run.

 This behaviour occurs regardless of input, but for the sake of completeness, here is an NWChem job file that I use for testing:
```
echo
start

scratch_dir /home/<me>/scratch
permanent_dir /home/<me>/scratch

memory total 5 gb stack 1 gb heap 1 gb

geometry units angstrom
 C  -0.3069   -0.4340    0.0000
 C   1.2434   -0.4888   -0.0000
 C  -0.8753    1.0093    0.0000
 C   1.8316   -1.9228   -0.0000
 C  -2.4233    1.0859   -0.0000
 C   3.3758   -1.9602   -0.0000
 C  -2.9733    2.5293   -0.0000
 H  -0.6801   -0.9618    0.8823
 H  -0.6801   -0.9618   -0.8823
 H   1.6135    0.0411   -0.8823
 H   1.6135    0.0411    0.8823
 H  -0.4990    1.5350   -0.8823
 H  -0.4990    1.5350    0.8823
 H   1.4749   -2.4616   -0.8820
 H   1.4749   -2.4616    0.8820
 H  -2.8124    0.5700   -0.8820
 H  -2.8124    0.5700    0.8820
 H   3.7271   -2.9936    0.0000
 H   3.7751   -1.4644    0.8870
 H   3.7751   -1.4644   -0.8870
 H  -4.0648    2.5161   -0.0000
 H  -2.6390    3.0710   -0.8870
 H  -2.6390    3.0710    0.8870
end

basis spherical
  * library cc-pvdz
end

set lindep:tol 2.0e-05

scf
  thresh 1.0e-8
end
task scf energy

unset tce:*
tce
  ccsd
  thresh 1.0e-8
  maxiter 1000
  lshift 0.7
  2eorb
  2emet 15
end
set tce:nts T
task tce energy
```

**Expected behavior**

Executing `mpirun -np <n> nwchem <input.nw>` should generate system load up to n * 100%. Instead, it generates system load up to n * 200%, where permitted by the number of available cores, and heavy contention past that point.

**Screenshots**

See above.

**Additional context**

**Comment by edoapra** [comment]
`ARMCI_NETWORK=MPI-MT` is not a setting I would recommend.
https://nwchemgit.github.io/ARMCI.html
Did you see the same behavior with `ARMCI_NETWORK=MPI-PR`?

Please keep in mind that Intel MPI 2019 (and later) works  reliably only when it uses UCX
https://software.intel.com/content/www/us/en/develop/articles/improve-performance-and-stability-with-intel-mpi-library-on-infiniband.html

**Comment by glowthrower** [comment]
Ah, the `ARMCI_NETWORK=MPI-MT` setting is a hangover from my original (i.e. not stripped-down) build attempt -- I'm ultimately trying to build NWChem with OpenMP enabled, and so I figured that the multi-threaded MPI library would be the most sensible. Is there any particular reason that you would recommend against it, or it just known to be flaky? (Maybe a better question: is there any reason it would be needed by an OpenMP-enabled build?)

I think I tried `ARMCI_NETWORK=MPI-PR` during the many(!) builds I've performed trying to narrow this down, but I will explicitly do so again to make sure.

Re: UCX. Thanks for the link! I will have to double-check precisely what's going on with the interconnect on the cluster and the various fabric options -- I think it's using OmniPath rather than Mellanox-flavour Infiniband, actually -- but from a quick check, adding `FI_PROVIDER=mlx` doesn't appear to make any difference to the behaviour as described above.

**Comment by glowthrower** [comment]
Actually, why do you say "Intel MPI 2019 (and later) works reliably **only** when it uses UCX"? Maybe I'm missing it, but I can't see that implied in your linked article. Do you mean with NWChem specifically, or in general? (I've had no problems with other large-scale MPI codes in the past using Intel MPI 2019, but maybe I've just been lucky...)

**Comment by edoapra** [comment]
My own experience is based on using NWChem and `ARMCI_NETWORK=MPI-PR` or `ARMCI_NETWORK=OPENIB` on a Infiniband network

**Comment by glowthrower** [comment]
> Because ARMCI drives progress itself (with MPI-MT at least) you don’t want the Intel MPI build that also does this.

Just to check that I've understood you correctly (and maybe for future reference for anyone else who finds this), do you mean here that with `ARMCI_NETWORK=MPI-MT`, the correct Intel MPI library to link/load against would be the non-multithreaded one? (On my install, the two libraries are given as `release` and `release_mt`, so the former.) In the course of working on this, I tried both, to no visible effect.

**Comment by glowthrower** [comment]
OK, thanks to all for the tips. 

The issue is indeed linked to the choice of `ARMCI_NETWORK`. It occurs consistently for `MPI-MT`, and also for `MPI-TS`. The latter is noteworthy because it is the default choice made by the build process when `ARMCI_NETWORK` is not given, at least on all systems I've experimented on. The behaviour does NOT occur with `ARMCI_NETWORK=MPI-PR`, so that seems to be a resolution (I guess I didn't try this correctly earlier).

In retrospect, this makes sense -- I've also seen the same behaviour in builds of NWChem produced using the various Intel compiler/MPI backed easybuild configs, as the GlobalArrays configs that they depend on [explicitly set MPI-TS via `--with-mpi-ts`](https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/g/GlobalArrays/GlobalArrays-5.8-intel-2020a.eb).

As such, may I politely suggest that a couple of lines be added to the documentation to warn people who might want to use Intel MPI? It seems like it would be a common use case and I guess I'm not the only person who's ended up with a buggy/non-performant NWChem as a result of the default. :smile:

Finally, @jeffhammond : since your name pops up all through the documentation regarding ARMCI-MPI, are the various instructions for building ARMCI-MPI still valid for NWChem 7.0.2? It seems sensible to experiment with that for performance testing, but at least one of the linked pages on Casper seems to have been intentionally blanked, which makes me wonder if anything has changed in the meantime..?

**Comment by jeffhammond** [comment]
`ARMCI_NETWORK=MPI-TS` is the default because it is the most likely to function, and allows sequential (single-process) execution.  It's definitely not the highest performing back-end, but NWChem has always required customization to get the highest performing builds (the previous ARMCI default was `ARMCI_NETWORK=SOCKETS`).

`ARMCI_NETWORK=MPI-PR` is a portable, high-performance back-end, but it does not allow sequential execution.  One must run use >1 processes, which will confuse some users, and it annoys others that just want to run sequentially or who are running NWPW, which doesn't use ARMCI.  That's why it is not the default.

ARMCI-MPI is as portable and performance as MPI-3 RMA.  ARMCI-MPI performs well without Casper _if_ the MPI library does a good job with RMA, especially asynchronous progress.  Sadly, most MPI libraries are bad at this, although Intel MPI with the helper thread may be an exception to this (I haven't tested).  When used with [Casper](https://github.com/pmodels/casper), it behaves a lot like MPI-PR, although it still allows sequential usage.

Sadly, most people who run into this issue don't read the documentation, so adding something there only helps in cases like yours.  A better method for us is to auto-detect bad configurations and warn about them.  I will try to do that but I'm not sure when.

The way to install ARMCI-MPI is use [$NWCHEM_TOP/src/tools/install-armci-mpi](https://github.com/nwchemgit/nwchem/blob/master/src/tools/install-armci-mpi), which will look for `mpicc` if `MPICC=...` is not set.  I use that all the time.  If it doesn't work, then please report a bug to https://github.com/pmodels/armci-mpi.

As for the blank docs, I assume that is on https://wiki.mpich.org/armci-mpi/index.php/Main_Page.  I haven't maintained that page in many years, so I guess I should delete the site and redirect to documentation on GitHub, which I can create if necessary.

**Comment by glowthrower** [comment]
Thanks for the comment, that all makes perfect sense and clears everything up. 

Anyway, now that I've had the chance to test it out a bit, an OpenMP- and MKL-enabled build using `FC=ifort` and `ARMCI_NETWORK=MPI-PR` performs excellently and scales easily into the thousands of cores. 😄

I'll close this now. Thanks again for the swift help!

**Comment by jeffhammond** [comment]
That's great news.  MPI-PR is indeed the right way to go for scaling NWChem.  Edo ran NWChem semidirect CCSD(T) on half a million cores (NERSC Cori KNL) that way.  I recall he used some special options to get multiple process ranks but that shouldn't be necessary for common usage, even on thousands of cores.

**Comment by glowthrower** [comment]
The bottleneck for me now (running CCSD and CCSD(T) calculations with large basis sets) is memory and I/O rather than core count, so I think that increasing process ranks shouldn't be necessary anyway. I can see how it might be needed for big KNL systems though.

Anecdotally, I have noticed that the process ranks consume quite a lot of RAM. Running the test script I posted above with cc-pVQZ rather than cc-pVDZ, I observed the process ranks using about 30GB of memory each during the amplitude initialisations, which is significantly more than the per-core RAM budget on the cluster I'm using. But this is manageable, I think.

**Comment by jeffhammond** [comment]
Are you running the semidirect module (`task ccsd(t) energy`) or TCE (`task tce energy`)?

The semidirect code has very good OpenMP in (T) - most of it is in MKL but the `tengy` part threads properly too.  The CCSD OpenMP is mediocre and I'm not sure it's worth enabling in most cases.  If you compile with `USE_OPENMP`, you can enable them independently (see https://github.com/NWChem/input-generator/blob/master/make_nwchem_input.py#L2074 for details).

I've found that even on a Haswell workstation that OpenMP helps CCSD(T) because kernel serialization makes the I/O inefficient with e.g. 36 processes per node.  High process count per node is also a reason to use MPI-PR, because ARMCI-MPI hits a bottleneck in the way that MPI libraries implement `MPI_Accumulate` ([details](https://github.com/pmodels/mpich/issues/3831)).

TCE threading is inside of each kernel so one needs to use huge tilesizes for it to be efficient.  I wrote OpenMP threaded transposes but haven't tested them extensively.  Whether threading overhead pays off in terms of performance depends on whether a single thread per process can saturate the available bandwidth, and how efficient your OpenMP implementation is (Blue Gene/Q's is very good, Intel's is good, and GCC's is not good).

**Comment by glowthrower** [comment]
I'm using `tce` exclusively -- I experimented a couple of years ago and found that it performed better than the "standard" `ccsd` and `ccsd(t)` in pretty much every way, including scalability. Nothing in the changelogs suggests that this has changed..?

Actually, your comment about threading being inside MKL raises another question I've been wondering about: whether it makes more sense to link against the serial or multithreaded MKL. With OpenMP disabled and one process per core, it seems pretty obvious that serial would be better. With OpenMP enabled, I figure it would depend on whether BLAS/LAPACK calls are being made inside the OpenMP regions. I assume they're probably not, so went for the multithreaded version and made a note to test it for performance at some point, but I'm open to suggestions.

The choice of tilesize is also pretty opaque to me. The documentation is honestly a bit unclear on how best to choose sizes, not to mention the balance between `attilesize` and `tilesize`. I assumed that increasing them would allow better threading performance, but most of the time I feel like I need to prioritise large global memory allocations to give space for the amplitudes and MOs, and I think(?) tilesize impacts only local usage?

**Comment by edoapra** [comment]
I am still puzzled by the fact that `ARMCI_NETWORK=MPI_TS` exhibits this performance degrading behavior. I would like to reproduce this behavior for further analysis of the factors that trigger is. Does this problem show up on a single node Ubuntu desktop run with ARMCI_NETWORK=MPI_TS`?
When does the 200% CPU load start to occur? Is it early in the run or only when the tce/CCSD part starts?
Thanks

**Comment by glowthrower** [comment]
> Does this problem show up on a single node Ubuntu desktop run with `ARMCI_NETWORK=MPI-TS`?

I only tested it quickly to confirm my suspicions about the easybuild versions (where I have very definitely seen this behaviour), but yes, I believe so. I will carefully double-check it to confirm some time in the next 24 hours. (I've run so many builds that they're all getting mixed up in my head at this point, and I wouldn't want to send you off on a wild goose chase.)

> When does the 200% CPU load start to occur? Is it early in the run or only when the tce/CCSD part starts?

More or less immediately after launch. (My guess is, as soon as MPI communication starts being used.) Using my above script, you should be able to observe it both in the run-up to and during `task scf energy`  -- you can get rid of the `tce` task completely if you prefer.

> Thanks

No problems, let me know if there's anything else I can help you do to reproduce this.

**Comment by edoapra** [comment]
I have just noticed that you mentioned easybuild ... has any of these 200% CPU slowdown surfaced when building NWChem without easybuild?

**Comment by glowthrower** [comment]
Apologies, I guess I've been unclear on that point.

I generally don't use easybuild, so pretty much everything I've written about here relates to standard builds from release tarballs that I've downloaded and unpacked by hand.

The cluster I'm working on does have a bunch of easybuild packages available, and when I was trying to troubleshoot my own builds, I experimented with the NWChem versions there to see if things were different. They weren't, but I didn't want to rip through the config files etc., so I made a mental note of it and went back to my own builds. 

Once you pointed out that `MPI-MT` might be the issue, and I was able to correct it with `MPI-PR`, I went back and investigated the easybuild config files to see what was happening there. When I saw they used `MPI-TS`, I tried that myself in a standard build, and observed the same behaviour again.

Does that clarify things?

**Comment by edoapra** [comment]
Sure, it does clarify things. I simply wanted to have a reproducer with the smallest number  of moving parts.
I will try the following 7.0.2 build (without easybuild)
- Desktop Ubuntu 18.04 
- `ARMCI_NETWORK=MPI-TS` 
- gnu compilers 
- Intel MPI 2019 
- `USE_INTERNALBLAS=y`

Let me know if these are the same conditions that triggered the 200% CPU behavior for you?
Could you also post the output of `/usr/bin/lscpu` of your Ubuntu desktop computer?

**Comment by jeffhammond** [comment]
> I'm using `tce` exclusively -- I experimented a couple of years ago and found that it performed better than the "standard" `ccsd` and `ccsd(t)` in pretty much every way, including scalability.

The semidirect code uses a very different algorithm that uses much less memory, but is limited in that it does not support point-group symmetry and is limited to RHF references.  If your molecules have point-group symmetry, TCE may win on that basis.  For example, C2v is going to be worth a huge reduction in compute and memory in TCE.  However, TCE stores the 3- and 4-virtual 2-electron integrals, whereas semidirect does not, which means that TCE is a memory hog if you use a large basis set.  The semidirect triples is dominated by DGEMM, whereas TCE triples are bandwidth-limited, so the semidirect code may perform better on newer hardware where FMA throughput is growing faster than memory bandwidth.

In any case, it would be worth testing again if you have time. 

> Nothing in the changelogs suggests that this has changed..?

I am a slacker and never contribute to release notes but the OpenMP was added in 2016-2017, but not documented explicitly, so you likely wouldn't have tried that.  The OpenMP changes also include a thread-agnostic optimization in TENGY that improves that by ~2x, but the wall time of TENGY is an order-of-magnitude smaller than DGEMM in that code, so the overall impact is small. 

> Actually, your comment about threading being inside MKL raises another question I've been wondering about: whether it makes more sense to link against the serial or multithreaded MKL. With OpenMP disabled and one process per core, it seems pretty obvious that serial would be better. With OpenMP enabled, I figure it would depend on whether BLAS/LAPACK calls are being made inside the OpenMP regions. I assume they're probably not, so went for the multithreaded version and made a note to test it for performance at some point, but I'm open to suggestions.

You want to set `MKL_NUM_THREADS` or `OMP_NUM_THREADS` to limit MKL parallelism with MPI, in the case where the affinity mask set by `mpirun` won't tell MKL not to use all the hardware threads, which is its default when the threaded library is used.  This leads to oversubscription, which is bad.

By default, MKL will use only one thread when called inside of an OpenMP region.

> The choice of tilesize is also pretty opaque to me.

I wrote https://nwchemgit.github.io/TCE.html#maximizing-performance in an attempt to be useful but I know it's not perfect.

Using a tilesize greater than ~30 blows up the local memory requirements in (T).  For CCSD, you can go up to 60 or so.  Karol implemented some multi-level tiling stuff that allows one to get the best of both worlds but I never figured out how to use it.

The other issue is that huge tiles reduce task parallelism, which can impede scaling because of load-imbalance.  `set tce:nts T` will mitigate this.

> The documentation is honestly a bit unclear on how best to choose sizes, not to mention the balance between `attilesize` and `tilesize`.

`attilesize` is used only in the four-index transformation.  You can make it larger than `tilesize` but I haven't tested much with values large than 50.

> I assumed that increasing them would allow better threading performance, but most of the time I feel like I need to prioritise large global memory allocations to give space for the amplitudes and MOs, and I think(?) tilesize impacts only local usage. EDIT: The implication is that I might not be able to choose large enough tilesizes to really give the threads room to play, so the OpenMP might only be useful for corner cases where I have to "coalesce" processes together in order to expose more global memory.

This is a good intuition.

**Comment by edoapra** [comment]
I could not reproduce the 200% CPU usage problem.  I have run a job with the input posted here and the execution went as expected using around 100% CPU load on each available core. Here is what I did
- downloaded https://github.com/nwchemgit/nwchem/releases/download/v7.0.2-release/nwchem-7.0.2-release.revision-b9985dfa-srconly.2020-10-12.tar.bz2
- compiled with the following settings
```
source /opt/intel/compilers_and_libraries_2020.2.254/linux/mpi/intel64/bin/mpivars.sh
export USE_MPI=y
export USE_MPIF=y
export USE_MPIF4=y
export ARMCI_NETWORK=MPI-TS
export USE_INTERNALBLAS=y
export NWCHEM_MODULES="all"
export FC=gfortran-9
export CC=gcc-9
```
compile command:
```
make
```
- using 4 processes on a 4-core system (details below) the job ended in less than 10 minutes (563 seconds).
- snippet of tools log from  $NWCHEM_TOP/src/tools/build/config.log
```
  $ ../ga-5.7.2/configure --prefix=/data/edo/nwchem/nwchem-7.0.2/src/tools/install --with-tcgmsg --with-mpi=-I/data/opt/intel/compilers_and_libraries_2020.2.254/linux/mpi/intel64/include/gfortran/7.1.0 -I/data/opt/intel/compilers_and_libraries_2020.2.254/linux/mpi/intel64/include -L/data/opt/intel/compilers_and_libraries_2020.2.254/linux/mpi/intel64/lib/release -L/data/opt/intel/compilers_and_libraries_2020.2.254/linux/mpi/intel64/lib -lmpifort -lmpi -lrt -lpthread -ldl --enable-peigs --enable-underscoring --disable-mpi-tests --without-scalapack --without-lapack --without-blas --with-mpi-ts CC=gcc-9 CXX=g++ F77=gfortran-9 FFLAGS=-fno-aggressive-loop-optimizations -std=legacy ARMCI_DEFAULT_SHMMAX_UBOUND=13107
```
- `lscpu` output
```
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  1
Core(s) per socket:  4
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               85
Model name:          Intel(R) Xeon(R) W-2102 CPU @ 2.90GHz
Stepping:            4
CPU MHz:             1200.091
CPU max MHz:         2900.0000
CPU min MHz:         1200.0000
BogoMIPS:            5799.77
Virtualization:      VT-x
L1d cache:           32K
L1i cache:           32K
L2 cache:            1024K
L3 cache:            8448K
NUMA node0 CPU(s):   0-3
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single pti intel_ppin ssbd mba ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req md_clear flush_l1d
```
- `lsb_release -a`
```
LSB Version:	core-9.20170808ubuntu1-noarch:printing-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic
```
- `mpirun -genv I_MPI_DEBUG=2` shows
```
[0] MPI startup(): Intel(R) MPI Library, Version 2019 Update 8  Build 20200624 (id: 4f16ad915)
[0] MPI startup(): Copyright (C) 2003-2020 Intel Corporation.  All rights reserved.
[0] MPI startup(): library kind: release
[0] MPI startup(): libfabric version: 1.10.1-impi
[0] MPI startup(): libfabric provider: tcp;ofi_rxm
```

**Comment by glowthrower** [comment]
Sorry for the slow response. I tried to reproduce it myself as well. Your settings mostly match mine (only difference is the GCC version -- mine is 7.5.0) and what I saw matches what you see -- expected behaviour with no problems. 

:thinking: 

I'm still fairly sure that I didn't imagine this, but I need to carefully investigate it again. I will try and retrace my steps tomorrow and see if I can either reproduce it, or persuade myself that I made a mistake. Hopefully I haven't wasted your time/effort.

**Comment by glowthrower** [comment]
I've gone back to this and I'm unable to consistently reproduce problems with `ARMCI_NETWORK=MPI-TS`. I have no idea how I got to that conclusion originally. Sorry for the confusion.

I can consistently reproduce them with `MPI-MT`, but I guess that's much less surprising/concerning.

I guess this can stay closed for now. If I do manage to find a solid reproduction case, I will report it back here. Thanks again.

**Comment by edoapra** [comment]
I have tried myself `MPI-MT`, but I am getting 100% CPU load for the main process and 50% load for the thread. I wonder if some env. variables and/or hardware factors are the cause of your 20% CPU load

**Comment by glowthrower** [comment]
Are you seeing that (100%/50%) with a fully-loaded machine? By that I mean, for example, on an N-core desktop, running `mpirun -np 4 nwchem ...`?

I ask because that's what I see in that case. It's only when I leave enough room for each process to hit 200% -- i.e. on my 8-core desktop, `mpirun -np 4 nwchem`. The behaviour doesn't go away for `-np 8`, performance still suffers, it's just less visible through `htop` etc.

**Comment by edoapra** [comment]
I see 100%/50% on a fully-loaded machine
I see the 200% behavior on a half-loaded machine.
Performance is decent (not great, `MPI-PR` is much better) in both cases, albeit half-loaded is faster than full-loaded (but It is a desktop machine with a bunch of competing processes)
Your experience seem a motivation for discouraging users from using `MPI-MT`
