### ISSUE TITLE
RODFT with fractional occupations

### ISSUE THREAD

**Issue by miroi** [nwchemgit/nwchem#283]
Hello,

based on[https://groups.google.com/g/nwchem-forum/c/Hj_jLUMKjrk/m/5RGj44pZAAAJ]( https://groups.google.com/g/nwchem-forum/c/Hj_jLUMKjrk/m/5RGj44pZAAAJ  ) 

"RODFT does not have the same functionality as the default Unrestricted DFT code. FON is one of them.
The code should have stopped with a more meaningful error message"

would be good to have input check in RODFT and FON , then printout message about non existing functionality.

**Comment by edoapra** [comment]
Fix committed https://github.com/nwchemgit/nwchem/commit/a1d5ac21745cd912bb5235422d368074782fc15c
