### ISSUE TITLE
Medium-scale MPI-PR jobs crash due to exceeding PSM2_MQ_RECVREQS_MAX

### ISSUE THREAD

**Issue by glowthrower** [nwchemgit/nwchem#284]
**Describe the bug**

After successfully building NWChem against `ARMCI_NETWORK=MPI-PR` as described/discussed [here](https://github.com/nwchemgit/nwchem/issues/281), I have begun seeing crashes that seem to be related to the number of MPI Irecvs in flight. These crashes occur for numbers of running processes past approximately 150, give or take. (On the cluster I'm using, that's about five or six nodes, each with 32 cores.) 

These don't seem to be tightly connected to any particular task or configuration size, although some task types are more prone than others (I see them often in the semidirect `ccsd` task, but rarely/never in `tce` tasks, for example). An example snippet of output looks like:

```
                   Four-Index Transformation
                   -------------------------
          Number of basis functions:            142
          Number of shells:                     102
          Number of occupied orbitals:           81
          Number of occ. correlated orbitals:    81
          Block length:                          16
          Superscript MO index range:      1 -   81
          Subscript MO index range:        1 -  142
          MO coefficients read from:  /home/my-username/scratch/ccs
          Number of operator matrices in core: 6642
          Half-transformed integrals produced

    0 shell      1 out of    102 in             2.12 secs
    0 shell      2 out of    102 in             2.12 secs
    0 shell      3 out of    102 in             2.12 secs
    0 shell      4 out of    102 in             2.12 secs
    0 shell      5 out of    102 in             2.12 secs
    0 shell      6 out of    102 in             2.12 secs
    0 shell      7 out of    102 in             7.68 secs
    0 shell      8 out of    102 in             7.68 secs
    0 shell      9 out of    102 in             7.68 secs
    0 shell     10 out of    102 in             7.68 secs
    0 shell     11 out of    102 in             7.68 secs
    0 shell     12 out of    102 in             7.68 secs
    0 shell     13 out of    102 in             7.68 secs
    0 shell     14 out of    102 in             7.68 secs
    0 shell     15 out of    102 in             7.68 secs
    0 shell     16 out of    102 in             7.68 secs
    0 shell     17 out of    102 in             7.68 secs
    0 shell     18 out of    102 in             7.68 secs
    0 shell     19 out of    102 in             7.68 secs
    0 shell     20 out of    102 in             7.68 secs
    0 shell     21 out of    102 in             7.68 secs
    0 shell     22 out of    102 in             7.68 secs
    0 shell     23 out of    102 in             7.68 secs
    0 shell     24 out of    102 in             7.68 secs
    0 shell     25 out of    102 in             7.68 secs
    0 shell     26 out of    102 in             7.68 secs
    0 shell     27 out of    102 in            10.85 secs
    0 shell     28 out of    102 in            10.85 secs
    0 shell     29 out of    102 in            10.85 secs
    0 shell     30 out of    102 in            10.85 secs
    0 shell     31 out of    102 in            10.85 secs
    0 shell     32 out of    102 in            10.85 secs
    0 shell     33 out of    102 in            10.85 secs
    0 shell     34 out of    102 in            17.85 secs
    0 shell     35 out of    102 in            17.85 secs
    0 shell     36 out of    102 in            17.85 secs
    0 shell     37 out of    102 in            17.85 secs
    0 shell     38 out of    102 in            17.85 secs
    0 shell     39 out of    102 in            17.85 secs
    0 shell     40 out of    102 in            17.85 secs
    0 shell     41 out of    102 in            17.85 secs
    0 shell     42 out of    102 in            17.85 secs
    0 shell     43 out of    102 in            17.85 secs
    0 shell     44 out of    102 in            21.33 secs
    0 shell     45 out of    102 in            21.33 secs
    0 shell     46 out of    102 in            21.33 secs
    0 shell     47 out of    102 in            21.33 secs
    0 shell     48 out of    102 in            26.35 secs
    0 shell     49 out of    102 in            26.35 secs
    0 shell     50 out of    102 in            26.35 secs
    0 shell     51 out of    102 in            26.35 secs
    0 shell     52 out of    102 in            26.35 secs
    0 shell     53 out of    102 in            26.35 secs
    0 shell     54 out of    102 in            26.35 secs
    0 shell     55 out of    102 in            31.76 secs
    0 shell     56 out of    102 in            31.76 secs
    0 shell     57 out of    102 in            31.76 secs
    0 shell     58 out of    102 in            31.76 secs
    0 shell     59 out of    102 in            31.76 secs
    0 shell     60 out of    102 in            31.76 secs
    0 shell     61 out of    102 in            31.76 secs
    0 shell     62 out of    102 in            31.76 secs
    0 shell     63 out of    102 in            31.76 secs
<node>133.10024Exhausted 1048576 MQ irecv request descriptors, which usually indicates a user program error or insufficient request descriptors (PSM2_MQ_RECVREQS_MAX=1048576)
srun: error: <node>133: task 63: Exited with exit code 255
```
A quick search finds [similar reported issues](https://community.intel.com/t5/Intel-oneAPI-HPC-Toolkit/PSM2-MQ-RECVREQS-MAX-limit-reached/td-p/1087818), although I haven't been able to find any directly related to NWChem. (I tried the `I_MPI_ADJUST_GATHERV=3` workaround mentioned in that thread, to no avail.)

Assuming that the error is telling the truth, and that the number specifies in-flight irecvs *per process* or *per node*, the number seems excessively high. If it's overall, then maybe it's a bit more sane (~6500 per process). I should be able to increase the PSM2_MQ_RECVREQS_MAX limit, but I'd like to know that it's an expected load before I do.

I know there are a lot of possibilities for the cause of this, mostly not to do with NWChem itself (maybe GlobalArrays?). Nevertheless, I was wondering if anybody has seen a similar issue before, or could suggest further debug steps, a resolution, or a sensible workaround.

**Describe settings used**

The target environment is a relatively modern HPC cluster with an OmniPath interconnect, using Intel MPI 2019 and the `libfabric` and `psm2` that came along with it. Job management is handled by slurm, with MPI processes managed by `pmi2`. Nodes have access to a shared filesystem and local scratch storage -- the shared filesystem often struggles to keep up with load, which may be related to this.

Environment variables used for build are:
```shell
#! /bin/bash

export NWCHEM_TOP=/path/to/build/dir/nwchem-7.0.2
export NWCHEM_TARGET=LINUX64
export USE_MPI=y
export USE_MPIF=y
export USE_MPIF4=y

export ARMCI_NETWORK=MPI-PR

export HAS_BLAS=y
export BLAS_SIZE=8
export BLASOPT="-L${MKLROOT}/lib/intel64 -lmkl_intel_ilp64 -lmkl_intel_thread -lmkl_core -liomp5 -lpthread -lm -ldl"

export HAS_LAPACK=y
export USE_LAPACK=y
export LAPACK_SIZE=8
export LAPACK_LIB="$BLASOPT"
export LAPACK_LIBS="$BLASOPT"
export LAPACKOPT="$BLASOPT"

export HAS_SCALAPACK=y
export USE_SCALAPACK=y
export SCALAPACK_SIZE=8
export SCALAPACK=" -L${MKLROOT}/lib/intel64 -lmkl_scalapack_ilp64 -lmkl_blacs_intelmpi_ilp64"
export SCALAPACK_LIB="$SCALAPACK"
export SCALAPACK_LIBS="$SCALAPACK"

export NWCHEM_MODULES="all python"
export CCSDTQ=y

export USE_OPENMP=y

export USE_PYTHONCONFIG=y
export PYTHONHOME=/path/to/pythonhome/python-3.6.9/
export PYTHONVERSION=3
```

A sample (slurm) job start command would be:
```
srun --time=2:0:0 --nodes=5 --tasks-per-node=32 --cpus-per-task=1 --cpu_bind=core --mpi=pmi2 nwchem ./input.nw
```

Some output obtained with `I_MPI_DEBUG=3` to confirm the fabric configuration:
```
[0] MPI startup(): libfabric version: 1.10.1-impi
[0] MPI startup(): libfabric provider: psm2
```

**Comment by edoapra** [comment]
Let me repeat once more that I would not  recommend use of Intel MPI 2019 for NWChem use unless UCX is used instead of libfabric https://github.com/nwchemgit/nwchem/issues/281#issuecomment-741125241.
However, I have no direct experience with the `psm2` provider. You can find some reports on the web that seems to hint that `PSM2_MQ_RECVREQS_MAX` could be increased from the user side. For example, setting `PSM2_MQ_RECVREQS_MAX=2097152` seem to fix some Global Arrays failures as reported in https://ccportal.ims.ac.jp/en/node/2795
Having said that the following env. variable settings might alleviate the network contention you are reporting
```
COMEX_MAX_NB_OUTSTANDING=6
``` 
You might even try values lower than 6 up to 1.

**Comment by jeffhammond** [comment]
PSM2 is for Omni Path, not Mellanox, so if Intel MPI is using that, the network must be Omni Path.  PSM2 supports no other networks, and I don't think `libfabric` will work at all if MPI tries to use it on Mellanox, and I don't know how that would happen, since Intel MPI and libfabric should detect the network properly.

In any case, I have seen this before and the job run time environment variable `PSM2_MEMORY=large` was the solution then, but it's possible the defaults have changed.  You might find that `PSM2_MQ_RECVREQS_MAX=$((1024*1024*N))` for `N>1` works better.

**Comment by glowthrower** [comment]
> Let me repeat once more that I would not recommend use of Intel MPI 2019 for NWChem use unless UCX is used instead of libfabric [#281 (comment)](https://github.com/nwchemgit/nwchem/issues/281#issuecomment-741125241).

I definitely heard you the first time. :smile: Although I'm certainly willing to trust your experience, I would also very much like to see a concrete reason why I should be suspicious of the combination of libfabric and Intel MPI, especially in an Omni-Path setting. I hope I don't seem stubborn, because I'm not trying to be -- I've got plenty of experience writing MPI code but I'm far from being an expert on the hardware/implementation side of things, and I'm always keen to understand things better.

From what I can see -- and please do correct me if I'm wrong -- UCX seems to be a "full-stack" kind of solution for Mellanox gear, as opposed to libfabric + whatever. I've just gone back and reread the Intel page you linked to originally. To me, it reads like a how-to on using a new libfabric provider that interfaces sideways with the UCX stack somehow. But I can't find anything in there suggesting that MPI 2019 and libfabric should be considered unreliable..? It certainly seems (from Intel's marketing material anyway) that PSM2 is [supported by Intel MPI 2019](https://software.intel.com/content/www/us/en/develop/articles/intel-mpi-library-2019-over-libfabric.html), and indeed the only fabric provider available for that hardware -- given that Omni-Path has Intel's name attached to it, I'd find it both concerning and surprising if they had prioritised tuning their MPI implementation for Mellanox hardware. I'm not saying I wouldn't believe it though...

But it sounds like you've had concrete experiences where NWChem either performs poorly or (much worse) delivers incorrect results using libfabric? If so, were they only on Infiniband?

Anecdotally, I've had significantly more problems using OpenMPI on the cluster I'm working with, and Intel MPI performance seems to be at worst comparable, and generally quite a lot better. Since I don't have the option to switch out the interconnect, I'm mostly interested in making the best I can with what I've got...

> However, I have no direct experience with the `psm2` provider. You can find some reports on the web that seems to hint that `PSM2_MQ_RECVREQS_MAX` could be increased from the user side. For example, setting `PSM2_MQ_RECVREQS_MAX=2097152` seem to fix some Global Arrays failures as reported in https://ccportal.ims.ac.jp/en/node/2795

Cranking up the `PSM2_MQ_RECVREQS_MAX` setting does appear to make the errors go away, at least from an initial quick check. @jeffhammond -- your suggestion of `PSM2_MEMORY=large` also seems to work, and might be preferable due to the lack of magic numbers. :smile: I'll test a bit more thoroughly over the weekend. As I said, I was mostly interested to know if the errors I was getting could be symptomatic of a bigger issue or inefficiency.

> Having said that the following env. variable settings might alleviate the network contention you are reporting
> 
> ```
> COMEX_MAX_NB_OUTSTANDING=6
> ```
> 
> You might even try values lower than 6 up to 1.

This is also interesting. It doesn't seem to alleviate the crashes on its own, but changing this seems to have a small but noticeable impact on runtime. Do you happen to know the default value for this?

**Comment by edoapra** [comment]
> This is also interesting. It doesn't seem to alleviate the crashes on its own, but changing this seems to have a small but noticeable impact on runtime. Do you happen to know the default value for this?

It should have  default value of 8. You can check it with the following command

```
grep COMEX_MAX_NB_OUTSTANDING $NWCHEM_TOP/src/tools/ga-5.7.2/comex/src-mpi-pr/*h
```

**Comment by jeffhammond** [comment]
If PSM2 controls change behavior, you must be using OPA. Do you have a pointer to system details?

**Comment by glowthrower** [comment]
Yes, it's definitely OPA. I thought I said that explicitly in the first post above, but maybe it wasn't clear.

**Comment by glowthrower** [comment]
It seems from further testing that `PSM2_MEMORY=large` is an easy fix for this, and I haven't observed any noticeable impacts on performance/scaleability. Thanks for the help!
