### ISSUE TITLE
Looking for AMD EPYC build optimization settings recommendations

### ISSUE THREAD

**Issue by gcstoianowski** [nwchemgit/nwchem#287]
I built NWChem from nwchem-7.0.0-release.revision-2c9a1c7c-srconly.2020-02-26.tar.bz2 separately for Intel SKL 6148 and AMD EPYC 7742 processors using Intel 2020.4.304 compilers and Open MPI 4.0, to be run on clusters with InfiniBand interconnects.  I used ARMCI_NETWORK=MPI-PR.  I tried the resulting executables with https://github.com/NREL/ESIFHPC3/blob/master/NWChem/dft.nw.   The final Delta E on the SKL processors is -8.4D-04; while on the EPYC processors it's -1.1D-03, insufficient for validation.  FOPTIMIZE on SKL included -axCORE-AVX512; on EPYC it included -march=core-avx2.  It would appear that compiler optimization may need curtailing on the EPYC build.  Unfortunately, https://nwchemgit.github.io/Compiling-NWChem.html doesn't provide guidance on building NWChem for AMD EPYC processors.

Any pointers from developers or users who have dealt with this would be most welcome.

**Comment by edoapra** [comment]
Gerardo
I must confess I have never used Intel compiler on AMD Epyc.
I have been using the AMD AOCC compiler suite, instead
https://developer.amd.com/amd-aocc/
The other option is to use the GNU compilers, but AOCC gives better performances.
Once you have installed AOCC, the compiler will be recognized by NWChem with the command
```
make FC=flang
```

**Comment by gcstoianowski** [comment]
Edo,

You wrote:
> I must confess I have never used Intel compiler on AMD Epyc.
> I have been using the AMD AOCC compiler suite, instead
> [...] 
>
> make FC=flang

Thanks!  We have those, too.  I'll give it a try.

Saludos,

Gerardo

**Comment by gcstoianowski** [comment]
Edo,

I regret to report that a build with FC=flang using AOCC 2.3 failed to pass validation; Delta E is still to large.

Saludos,
Gerardo

**Comment by edoapra** [comment]
What are you using for BLASOPT/LAPACK_LIB and SCALAPACK?

**Comment by gcstoianowski** [comment]
For the build with Intel compilers, I was using MKL; I also tried with the internal libraries, with similar results.
For the build with AOCC, I did not have external BLAS, etc., libraries, so I used the internal libraries.  Just now AMD's optimized libraries were made availablem so I plan on trying those next.
If you have specific suggestions for the libraries and related environment variables, those would be appreciated.

**Comment by jeffhammond** [comment]
I would with GCC and OpenBLAS on AMD.  That should validate.  Once you have something that works, you can figure out if other compilers or libraries perform better.  Given how the DFT code works, I don't see a lot of opportunity for compiler optimization.

**Comment by gcstoianowski** [comment]
Thanks, Jeff.  I don't have OpenBLAS; I'd have to install and build it.  (BTW, I'm using gcc together with either ifort or flang, depending on the build.  I'm not using either icc or clang.)

**Comment by edoapra** [comment]
Gerardo
Are you getting the same wrong results with Intel and AOCC compilers, that is the same
 DeltaE?

**Comment by gcstoianowski** [comment]
Yes, about the same DeltaE: between -1.0D-03 and -1.3D-03; best was -9.9D-04 with two nodes, but that also failed to validate.

**Comment by edoapra** [comment]
Gerardo, I was able to pass the test validation of the `get_result.bash` script on a AMD Epyc box using AOCC 2.1.0 and OpenMPI 4.0.x
I have built OpenBLAS directly from NWChem using the BUILD_OPENBLAS env. variable. Here are my settings
```
export USE_MPI=y
export USE_64TO32=y
export BLAS_SIZE=4
export SCALAPACK_SIZE=4
export BUILD_SCALAPACK=1
export BUILD_OPENBLAS=1
export ARMCI_NETWORK=MPI-PR
export USE_NOIO=1
```

**Comment by gcstoianowski** [comment]
Edo,
Thank you very much.  I'll try this next, since I've been unable to complete a build using the ARM optimized libraries (libblis, etc.).

**Comment by edoapra** [comment]
> ... since I've been unable to complete a build using the ARM optimized libraries (libblis, etc.).
I would recommend use of OpenBLAS based on my limited experience

**Comment by gcstoianowski** [comment]
Edo,

I tried OpenBLAS with the settings you suggested. The build almost completed, except for missing symbols at the final link step:

`flang   -L/global/home/users/gerardo/nwchem/lib/LINUX64 -L/global/home/users/gerardo/nwchem/src/tools/install/lib  -o /global/home/users/gerardo/nwchem/bin/LINUX64/nwchem nwchem.o stubs.o -lnwctask -lccsd -lmcscf -lmp2 -lmoints -lstepper -ldriver -loptim -lnwdft -lgradients -lcphf -lesp -lddscf -lguess -lhessian -lvib -lnwcutil -lrimp2 -lproperty -lsolvation -lnwints -ldplot -lvscf -letrans -ltce -lbq -lcons -ldimqm -lnwcutil -lga -larmci -lpeigs -lperfm -lcons -lbq -lnwcutil  -L/global/home/users/gerardo/nwchem/src/libext/lib -lscalapack  -l64to32 -L/global/home/users/gerardo/nwchem/src/libext/lib -lopenblas  -L/global/home/users/gerardo/nwchem/src/libext/lib -lopenblas       -lnwcblas   -L/global/software/centos-7/modules/aocc/2.3.0/hpcx/2.7.0/ompi/lib -lmpi_usempif08 -lmpi_usempi_ignore_tkr -lmpi_mpifh -lmpi    -lcomex -lmpi_usempif08 -lmpi_usempi_ignore_tkr -lmpi_mpifh -lmpi -lopenblas -lrt -lpthread -lm -lpthread  -lm  
ld.lld: error: undefined symbol: dlamch_
>>> referenced by lbfgs-b.F:473
>>>               lbfgs-b.o:(mainlb_) in archive /global/home/users/gerardo/nwchem/lib/LINUX64/libdriver.a
>>> referenced by geom_input.F:4533
>>>               geom_input.o:(hnd_molops_) in archive /global/home/users/gerardo/nwchem/lib/LINUX64/libnwcutil.a
>>> referenced by stpr_sjacobi.F:37
>>>               stpr_sjacobi.o:(stpr_sjacobi_) in archive /global/home/users/gerardo/nwchem/lib/LINUX64/libnwcutil.a
>>> referenced 27 more times
>>> did you mean: pdlamch_
>>> defined in: /global/home/users/gerardo/nwchem/src/libext/lib/libscalapack.a(pdlamch.f.o)
`
(and several more errors like the one above).

My complete environment was as follows:

`module load aocc/2.3.0 hpcx/2.7.0
module load cmake/3.16.4

export NWCHEM_TOP=/global/home/users/gerardo/nwchem
export NWCHEM_TARGET=LINUX64
export ARMCI_NETWORK=MPI-PR
export USE_MPI=y
export NWCHEM_MODULES=qm
export BLAS_SIZE=4
export USE_64TO32=y
export SCALAPACK_SIZE=4
export BUILD_SCALAPACK=1
export BUILD_OPENBLAS=1
export USE_NOIO=1
export FC=flang
`

My sources came from nwchem-7.0.0-release.revision-2c9a1c7c-srconly.2020-02-26.tar.bz2, which come with USE_64TO32=y by default in src/config/makefile.h

**Comment by edoapra** [comment]
I am afraid you might have stumbled in a few bugs/glitches for the BUILD_OPENBLAS integration that have been fixed after 7.0.0 has been released.
If you cannot use 7.0.2 or master, let's what you we can do to fix the problem, short of suggesting you to download and compiler OpenBLAS yourself.

* Do you still have `USE_INTERNALBLAS=y`? If you do, please unset it. Then, please try 
 `cd $NWCHEM_TOP/src; make FC=flang link `
* What is the output of `ls -l $NWCHEM_TOP/src/libext/lib`
* What is the output of `ar t $NWCHEM_TOP/src/libext/lib/lib*op*.a | grep -i dlamch `
* What is the output of `nm $NWCHEM_TOP/src/libext/lib/lib*op*.a | grep -i dlamch | sort | uniq `
* could you post (attachment) the full output of `make FC=flang link` if it still fails

**Comment by gcstoianowski** [comment]
Edo,

Here is the output of the commands you suggested I run:

[gerardo@rome001 src]$ ls -l $NWCHEM_TOP/src/libext/lib
total 36877
-rw-rw-r-- 1 gerardo hpcperf  5624224 Dec 21 06:16 libopenblas.a
-rw-rw-r-- 1 gerardo hpcperf  5624224 Dec 21 06:16 libopenblas_zen-r0.3.7.a
-rw-rw-r-- 1 gerardo hpcperf 27457484 Dec 21 06:18 libscalapack.a
[gerardo@rome001 src]$ ar t $NWCHEM_TOP/src/libext/lib/lib*op*.a | grep -i dlamch
no entry /global/home/users/gerardo/nwchem/src/libext/lib/libopenblas_zen-r0.3.7.a in archive
[gerardo@rome001 src]$ ar t $NWCHEM_TOP/src/libext/lib/libopenblas.a | grep -i dlamch
[gerardo@rome001 src]$ ar t $NWCHEM_TOP/src/libext/lib/libopenblas_zen-r0.3.7.a | grep -i dlamch
[gerardo@rome001 src]$ nm $NWCHEM_TOP/src/libext/lib/libopenblas.a | grep -i dlamch | sort | uniq
[gerardo@rome001 src]$ nm $NWCHEM_TOP/src/libext/lib/libopenblas_zen-r0.3.7.a | grep -i dlamch | sort | uniq

and here is the full output from the 'make link' command
[make_link_a230h270mpipr.log](https://github.com/nwchemgit/nwchem/files/5725010/make_link_a230h270mpipr.log)

**Comment by gcstoianowski** [comment]
Edo,

For completeness, here is the log from the full make:
[make_a230h270mpipr.log](https://github.com/nwchemgit/nwchem/files/5725038/make_a230h270mpipr.log)

**Comment by edoapra** [comment]
Gerardo
the following lines in the log are the root cause of your lapack link problem
```
F90-S-0126-Name etime is not an intrinsic function (../INSTALL/second_INT_ETIME.f: 53)
  0 inform,   0 warnings,   1 severes, 0 fatal for second
```
In order to fix your linking problem, please 
* Copy the attached file to he computer  were you are installing NWChem in the `$NWCHEM_TOP` directory [openblas.patch.txt](https://github.com/nwchemgit/nwchem/files/5725971/openblas.patch.txt)
*  `cd $NWCHEM_TOP`
*  `patch -p1 < openblas.patch.txt`
*  `cd src/libext/openblas`
* `rm -rf OpenBLAS* ../lib/lib*openbl*`
* ` make FC=flang `
* `cd $NWCHEM_TOP/src`
* `make FC=flang link`


PS Sorry for using you as a guinea pig. Your feedback is very much appreciated

**Comment by gcstoianowski** [comment]
Edo,

I don't mind helping out.  The patch didn't quite work.  I still got the following from the make inside src/libext/openblas:

F90-S-0126-Name etime is not an intrinsic function (../INSTALL/second_INT_ETIME.f: 53)
  0 inform,   0 warnings,   1 severes, 0 fatal for second
make[3]: *** [../INSTALL/second_INT_ETIME.o] Error 1
make[3]: *** Waiting for unfinished jobs....

In addition, I got a lot of warnings such as the following:
clang-11: warning: argument unused during compilation: '-frecursive' [-Wunused-command-line-argument]

**Comment by edoapra** [comment]
Gerardo,
Thanks for the feedback and for noticing the warnings about compiler options.
The compiler was not properly detected.
I have generated a new patch 
[openblas2.patch.txt](https://github.com/nwchemgit/nwchem/files/5726263/openblas2.patch.txt)
that need to be applied after removing the previous one
* Copy the attached file to he computer  were you are installing NWChem in the `$NWCHEM_TOP` directory [openblas2.patch.txt](https://github.com/nwchemgit/nwchem/files/5726263/openblas2.patch.txt)
*  `cd $NWCHEM_TOP`
* `patch -p1 -R < openblas.patch.txt`
*  `patch -p1 < openblas2.patch.txt`
*  `cd src/libext/openblas`
* `rm -rf OpenBLAS* ../lib/lib*openbl*`
* ` make FC=flang `
* `cd $NWCHEM_TOP/src`
* `make FC=flang link`

Please let me know if this addresses both the compiler warnings and the `ETIME` compilation failure

**Comment by gcstoianowski** [comment]
I got the following warnings:

F90-W-0130-Floating point underflow. Check constants and constant expressions (../INSTALL/dlamch.f: 114)
  0 inform,   1 warnings,   0 severes, 0 fatal for dlamch
. . .
F90-W-0130-Floating point underflow. Check constants and constant expressions (../INSTALL/slamch.f: 114)
  0 inform,   1 warnings,   0 severes, 0 fatal for slamch
. . .
F90-W-0130-Floating point underflow. Check constants and constant expressions (../ga-5.7.1/LinAlg/lapack+blas/gal_dlamch.f: 113)
  0 inform,   1 warnings,   0 severes, 0 fatal for gal_dlamch

but I suspect those might be expected.

The build completed, but I regret to report that the test case didn't run any faster and the output failed validation

**Comment by edoapra** [comment]
if that's the case, I would guess that the issue is likely to be related to parallelization. How many nodes are you using? More than one? Does the error show up when using just a singled node?
Could you try to re-run with the following line before the `task dft` line
`set dft:xcreplicated f`
Could you also post the full output file, too?

**Comment by gcstoianowski** [comment]
1.  I've used 1, 2, 4 and 8 nodes, each having two EPYC Rome processors (128 cores/node).  The error shows up in all cases, using MKL internal (Netlib) BLAS, and now with OpenBLAS.
2.  I added 'set dft:replicated f' as directed, but the 4-node job again failed to validate; Delta E remains at 1.3D-03
3.  I downloaded 7.0.2, but the build with flang failed with essentially the same ETIME error message.  I think a patch similar to your openblas2 patch above is needed.  (The one you provided for 7.0.0 won't work, though.)

**Comment by edoapra** [comment]
>     3. I downloaded 7.0.2, but the build with flang failed with essentially the same ETIME error message.  I think a patch similar to your openblas2 patch above is needed.  (The one you provided for 7.0.0 won't work, though.)
You can copy `$NWCHEM_TOP/src/libext/openblas/build_openblas.sh` from your 7.0.0 tree to your 7.0.2 tree.

**Comment by gcstoianowski** [comment]
Edo,

- Copying the build_openblas.sh script from 7.0.0 to 7.0.2 worked.
- I was still getting failure to validate from 7.0.2, when I noticed "Load of old vectors failed.   Forcing atomic density guess" in my output logs.  I added "rm -f test.drv.hess test.db test.movecs" to my Slurm script and I now got four 8-node/1024-MPI-rank jobs to validate, using either 7.0.0 or 7.0.2, and running with or without  'set dft:xcreplicated f' in the input file.

Thanks for all your help and sorry for not noticing the lack of cleanup before.

**Comment by gcstoianowski** [comment]
Edo,

One more question.  The dft.nw job (including the reference log) ends in 'dft optimize failed', followed by MPI_Abort.  What can be done to ignore the failure and avoid the undesirable MPI_Abort?

Saludos,
Gerardo

**Comment by edoapra** [comment]
> One more question. The dft.nw job (including the reference log) ends in 'dft optimize failed', followed by MPI_Abort. What can be done to ignore the failure and avoid the undesirable MPI_Abort?
> 
change 
```
task dft optimize
```
to
```
task dft optimize ignore
```

**Comment by edoapra** [comment]
> (BTW: Do you mind if I post your openblas2.patch.txt to the NREL ESIF-HPC-3 GitHub page for NWChem?)

Sure, no problem.
