### ISSUE TITLE
nwchem 6.8.1 on Centos 7:  unrecognized argument pmi_args

### ISSUE THREAD

**Issue by FredericBrochu** [nwchemgit/nwchem#298]
I have installed nwchem 6.8.1 on a Centos 7 cluster. Compilation succeeded with a few warnings, but when using it with the Nitrogen example (n2.nw):
nwchem n2.nw
fails with:
[mpiexec@login-a-1] match_arg (utils/args/args.c:159): unrecognized argument pmi_args
[mpiexec@login-a-1] HYDU_parse_array (utils/args/args.c:174): argument matching returned error
[mpiexec@login-a-1] parse_args (ui/mpich/utils.c:1596): error parsing input array
[mpiexec@login-a-1] HYD_uii_mpx_get_parameters (ui/mpich/utils.c:1648): unable to parse user arguments
[mpiexec@login-a-1] main (ui/mpich/mpiexec.c:153): error parsing parameters
then hangs forever

The alternative:
mpiexec -np 8 nwchem n2.nw
hangs directly with no error message.

The installation was done with the following modules:
module list
Currently Loaded Modulefiles:
  1) dot                                 5) gcc-7.3.0-gcc-4.8.5-tex4qcx
  2) slurm                               6) openblas-0.2.20-gcc-7.3.0-tq4e7cr
  3) centos7/global                      7) python-3.6.5-gcc-7.3.0-cklmfze
  4) centos7/default-basic               8) mpich-3.2-gcc-7.3.0-rsmlpyl

and with the following command lines:
module purge
cd $INSTALL_AREA
wget https://github.com/nwchemgit/nwchem/archive/6.8.1-release.tar.gz
tar xzf 6.8.1-release.tar.gz
cd nwchem-6.8.1-release/

module load mpich-3.2-gcc-7.3.0-rsmlpyl # this points to gcc7.3.0... Alternative is openmpi-3.0.0-gcc-4.8.5-n2hvjgm
module load gcc-7.3.0-gcc-4.8.5-tex4qcx
# using shipped BLAS.
export USE_INTERNALBLAS=y
export NWCHEM_TARGET="LINUX64"
export USE_MPI="y"
export MPI_LOC="/usr/local/software/spack/current/opt/spack/linux-centos7-x86_64/gcc-7.3.0/mpich-3.2-rsmlpyl7to6ntrau2tufursoxlun4q7n"
export MPI_LIB="-L/usr/local/software/spack/current/opt/spack/linux-centos7-x86_64/gcc-7.3.0/mpich-3.2-rsmlpyl7to6ntrau2tufursoxlun4q7n/lib"
export MPI_INCLUDE=$MPI_LOC/include
export NWCHEM_TOP=$PWD
export LIBMPI="-lmpifort -Wl,-rpath -Wl,/usr/local/software/spack/current/opt/spack/linux-centos7-x86_64/gcc-7.3.0/mpich-3.2-rsmlpyl7to6ntrau2tufursoxlun4q7n/lib -lmpi"

cd $NWCHEM_TOP/src
make nwchem_config NWCHEM_MODULES=all
make

Apart from a few warnings, the installation seemed successful.
Is there anything I missed?

                   Best regards,

                                                   Frederic

**Comment by FredericBrochu** [comment]
* Tried 7.0.2, I unfortunately ended up with the same issue
*  running nwchem binary straightaway (with no -np flag) leads to the error messages
[mpiexec@login-a-1] match_arg (utils/args/args.c:159): unrecognized argument pmi_args
[mpiexec@login-a-1] HYDU_parse_array (utils/args/args.c:174): argument matching returned error
[mpiexec@login-a-1] parse_args (ui/mpich/utils.c:1596): error parsing input array
[mpiexec@login-a-1] HYD_uii_mpx_get_parameters (ui/mpich/utils.c:1648): unable to parse user arguments
[mpiexec@login-a-1] main (ui/mpich/mpiexec.c:153): error parsing parameters
then hangs forever

*  ldd nwchem 's output is the following:
        linux-vdso.so.1 =>  (0x00007ffe6bddd000)
        libmpifort.so.12 => /usr/local/software/spack/current/opt/spack/linux-centos7-x86_64/gcc-7.3.0/mpich-3.2-rsmlpyl7to6ntrau2tufursoxlun4q7n/lib/libmpifort.so.12 (0x00007f12afd63000)
        libmpi.so.12 => /usr/local/software/spack/current/opt/spack/linux-centos7-x86_64/gcc-7.3.0/mpich-3.2-rsmlpyl7to6ntrau2tufursoxlun4q7n/lib/libmpi.so.12 (0x00007f12af8d2000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f12af6ca000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f12af4ae000)
        libgfortran.so.4 => /usr/local/software/spack/current/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-7.3.0-tex4qcxfmj2ny4phn5bkoqu5c4q2kbse/lib64/libgfortran.so.4 (0x00007f12af0db000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f12aedd9000)
        libgcc_s.so.1 => /usr/local/software/spack/current/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-7.3.0-tex4qcxfmj2ny4phn5bkoqu5c4q2kbse/lib64/libgcc_s.so.1 (0x00007f12aebc2000)
        libquadmath.so.0 => /usr/local/software/spack/current/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-7.3.0-tex4qcxfmj2ny4phn5bkoqu5c4q2kbse/lib64/libquadmath.so.0 (0x00007f12ae983000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f12ae5b6000)
        libfabric.so.1 => /usr/local/software/spack/current/opt/spack/linux-centos7-x86_64/gcc-7.3.0/libfabric-1.5.0-m7md7iopkwgrbeoi6ilgk4n3xoljb5fp/lib/libfabric.so.1 (0x00007f12ae369000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f12aff9b000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f12ae165000)

I will have a look at the RPMs.

Many thanks for your help.

                     Frederic

**Comment by edoapra** [comment]
>     * running nwchem binary straightaway (with no -np flag) leads to the error messages
>       [mpiexec@login-a-1] match_arg (utils/args/args.c:159): unrecognized argument pmi_args
>       [mpiexec@login-a-1] HYDU_parse_array (utils/args/args.c:174): argument matching returned error
>       [mpiexec@login-a-1] parse_args (ui/mpich/utils.c:1596): error parsing input array
>       [mpiexec@login-a-1] HYD_uii_mpx_get_parameters (ui/mpich/utils.c:1648): unable to parse user arguments
>       [mpiexec@login-a-1] main (ui/mpich/mpiexec.c:153): error parsing parameters
>       then hangs forever
> 
>    

Is this with or without mpiexec/mpirun?   
What I was suggesting to try is just
```
$NWCHEM_TOP/bin/LINUX64/nwchem "input file name"
```

**Comment by edoapra** [comment]
What is the output of the following commands
```
which mpirun
which mpiexec
```

**Comment by FredericBrochu** [comment]
Yes, the result of $NWCHEM_TOP/bin/LINUX64/nwchem n2.nw
are the following error messages:
[mpiexec@login-a-1] match_arg (utils/args/args.c:159): unrecognized argument pmi_args
  [mpiexec@login-a-1] HYDU_parse_array (utils/args/args.c:174): argument matching returned error
  [mpiexec@login-a-1] parse_args (ui/mpich/utils.c:1596): error parsing input array
  [mpiexec@login-a-1] HYD_uii_mpx_get_parameters (ui/mpich/utils.c:1648): unable to parse user arguments
  [mpiexec@login-a-1] main (ui/mpich/mpiexec.c:153): error parsing parameters

which mpirun returns:
/usr/local/software/spack/current/opt/spack/linux-centos7-x86_64/gcc-7.3.0/mpich-3.2-rsmlpyl7to6ntrau2tufursoxlun4q7n/bin/mpirun
which mpiexec returns:
/usr/local/software/spack/current/opt/spack/linux-centos7-x86_64/gcc-7.3.0/mpich-3.2-rsmlpyl7to6ntrau2tufursoxlun4q7n/bin/mpiexec

**Comment by edoapra** [comment]
Could you try the following and report what happens
```
wget http://cagt.bu.edu/w/images/c/c3/Mpi.c
mpicc  -o mpitest.x Mpi.c
mpiexec -np 2 ./mpitest.x
```

**Comment by FredericBrochu** [comment]
mpicc  -o mpitest.x Mpi.c
mpiexec -np 2 ./mpitest.x
Process 1 on login-a-1
Process 0 on login-a-1
pi is approximately 3.1416009869231241, Error is 0.0000083333333309
wall clock time = 0.000102

**Comment by edoapra** [comment]
What is the output of 
```
ldd ./mpitest.x
mpiexec -info
```

**Comment by edoapra** [comment]
I must correct my previous request. I am interested in the output of
```
mpiexec.hydra -info
mpiexec.hydra -np 1 $NWCHEM_TOP/bin/LINUX64/nwchem
```

**Comment by FredericBrochu** [comment]
**ldd ./mpitest.x**
        linux-vdso.so.1 =>  (0x00007fffdd948000)
        libmpi.so.12 => /usr/local/software/spack/current/opt/spack/linux-centos7-x86_64/gcc-7.3.0/mpich-3.2-rsmlpyl7to6ntrau2tufursoxlun4q7n/lib/libmpi.so.12 (0x00007fb92ed9f000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fb92e9d2000)
        libfabric.so.1 => /usr/local/software/spack/current/opt/spack/linux-centos7-x86_64/gcc-7.3.0/libfabric-1.5.0-m7md7iopkwgrbeoi6ilgk4n3xoljb5fp/lib/libfabric.so.1 (0x00007fb92e785000)
        librt.so.1 => /lib64/librt.so.1 (0x00007fb92e57d000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fb92e361000)
        libgfortran.so.4 => /usr/local/software/spack/current/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-7.3.0-tex4qcxfmj2ny4phn5bkoqu5c4q2kbse/lib64/libgfortran.so.4 (0x00007fb92df8e000)
        libm.so.6 => /lib64/libm.so.6 (0x00007fb92dc8c000)
        libgcc_s.so.1 => /usr/local/software/spack/current/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-7.3.0-tex4qcxfmj2ny4phn5bkoqu5c4q2kbse/lib64/libgcc_s.so.1 (0x00007fb92da75000)
        libquadmath.so.0 => /usr/local/software/spack/current/opt/spack/linux-centos7-x86_64/gcc-4.8.5/gcc-7.3.0-tex4qcxfmj2ny4phn5bkoqu5c4q2kbse/lib64/libquadmath.so.0 (0x00007fb92d836000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fb92f230000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007fb92d632000)

**mpiexec.hydra -info**
HYDRA build details:
    Version:                                 3.2
    Release Date:                            Wed Nov 11 22:06:48 CST 2015
    CC:                              /usr/local/software/spack/v0.11.2/lib/spack/env/gcc/gcc
    CXX:                             /usr/local/software/spack/v0.11.2/lib/spack/env/gcc/g++
    F77:                             /usr/local/software/spack/v0.11.2/lib/spack/env/gcc/gfortran
    F90:                             /usr/local/software/spack/v0.11.2/lib/spack/env/gcc/gfortran
    Configure options:                       '--disable-option-checking' '--prefix=/usr/local/software/spack/current/opt/spack/linux-centos7-x86_64/gcc-7.3.0/mpich-3.2-rsmlpyl7to6ntrau2tufursoxlun4q7n' '--enable-shared' '--with-pm=hydra' '--with-pmi=yes' '--enable-romio' '--without-ibverbs' '--with-device=ch3:nemesis:ofi' 'CC=/usr/local/software/spack/v0.11.2/lib/spack/env/gcc/gcc' 'CXX=/usr/local/software/spack/v0.11.2/lib/spack/env/gcc/g++' 'FC=/usr/local/software/spack/v0.11.2/lib/spack/env/gcc/gfortran' 'F77=/usr/local/software/spack/v0.11.2/lib/spack/env/gcc/gfortran' '--cache-file=/dev/null' '--srcdir=/usr/local/software/spack/v0.11.2/var/spack/stage/mpich-3.2-rsmlpyl7to6ntrau2tufursoxlun4q7n/mpich-3.2/src/pm/hydra' 'CFLAGS= -O2' 'LDFLAGS=' 'LIBS=-lpthread ' 'CPPFLAGS= -I/tmp/sjr20/spack-stage/spack-stage-GsOyco/mpich-3.2/src/mpl/include -I/usr/local/software/spack/v0.11.2/var/spack/stage/mpich-3.2-rsmlpyl7to6ntrau2tufursoxlun4q7n/mpich-3.2/src/mpl/include -I/usr/local/software/spack/v0.11.2/var/spack/stage/mpich-3.2-rsmlpyl7to6ntrau2tufursoxlun4q7n/mpich-3.2/src/openpa/src -I/tmp/sjr20/spack-stage/spack-stage-GsOyco/mpich-3.2/src/openpa/src -D_REENTRANT -I/tmp/sjr20/spack-stage/spack-stage-GsOyco/mpich-3.2/src/mpi/romio/include'
    Process Manager:                         pmi
    Launchers available:                     ssh rsh fork slurm ll lsf sge manual persist
    Topology libraries available:            hwloc
    Resource management kernels available:   user slurm ll lsf sge pbs cobalt
    Checkpointing libraries available:
    Demux engines available:                 poll select

**mpiexec.hydra -np 1 $NWCHEM_TOP/bin/LINUX64/nwchem**

just hangs with no output.

**Comment by edoapra** [comment]
I must confess I have no idea of what is going on in this case.
One perplexing aspect if that a serial execution seems to require mpiexec https://github.com/nwchemgit/nwchem/issues/298#issuecomment-755447954
Since I have no way to reproduce your problem, the only suggestions I have is to use the EPEL rpms or to switch from mpich to openmpi (that gives better performances anyway)

**Comment by FredericBrochu** [comment]
Good news: recompiling with openmpi 3.0.0 solved my problem. There must be something wrong with our installation of MPICH as I got the same kind of error with another application (GAMESS). 
In the mean time, I close this issue as it clearly has nothing to do with NWCHEM itself. 
Many thanks for your time and support. 

               Frederic
