### ISSUE TITLE
densities at positions of nuclei returned as zero

### ISSUE THREAD

**Issue by moritz-braun** [nwchemgit/nwchem#323]
**Describe the bug**
When making use of the 
WHERE g+n option 
in the
DPLOT
directive the
densities are returned as zeros.
**Describe settings used**
Report all the environment variables used.
No nwchem specifc ones used when calling nwchem
Report what operating system and distribution you are using.
OS: Linux
Distribution:Red Hat Enterprise Linux Server release 7.9 (Maipo)
**Attach log files**
Attach as many log files as possible.
* stdout/stderr of the NWChem execution
* stdout attached as OUT.txt
[OUT.txt](https://github.com/nwchemgit/nwchem/files/5973760/OUT.txt)
* complete makefile log NA
* $NWCHEM_TOP/src/tools/build/config.log NA
* $NWCHEM_TOP/src/tools/build/comex/config.log NA
* debugging stack NA
No need to debug, since execution does not fail!
**To Reproduce**
1. Steps to reproduce the behavior:
run nwchem with input files as per 2
2. Attach all the input files required to run.
a) carbondioxide.xyz 
b) carbondioxide.nw
these files are attached 
**Expected behavior**
Non-zero values of densities at the
three positions of the nuclei should
be returned to STDOUT 

**Screenshots**

**Additional context**

[co2.zip](https://github.com/nwchemgit/nwchem/files/5973739/co2.zip)
This zip file contains the two files as listed under 2.!

**Comment by edoapra** [comment]
@moritz-braun Thanks for reporting this bug.
A fix has been committed to the master and hotfix/release-7-0-0 branches
3feb4f0784d5ea066d3b2a6b5eb758707f245de4
378e38c291a1ff975524a3772229af17f96a96be
