### ISSUE TITLE
QA test pspw_qmmm fails 

### ISSUE THREAD

**Issue by xiongyan21** [nwchemgit/nwchem#325]
QA test pspw_qmmm fails. What is wrong in the input?
[pspw_qmmm.log](https://github.com/nwchemgit/nwchem/files/5977002/pspw_qmmm.log)

It seems the results of  test pspw_stress are changing.

[pspw_stress.log](https://github.com/nwchemgit/nwchem/files/5976998/pspw_stress.log)

Test pspw_polarizability reproduces the original results.

Test pspw_SiC also changes the results.
[pspw_SiC.log](https://github.com/nwchemgit/nwchem/files/5977044/pspw_SiC.log)

And what restart file is requred to run qmmm_grad0?

Very Best Regards!

**Comment by edoapra** [comment]
Please use the template to report issues.
This issue will be closed for not following the provided template
