### ISSUE TITLE
The results of QA quantum computation test be_6-31g_fci agrees very well with that of Gamess Aldet FCI

### ISSUE THREAD

**Issue by xiongyan21** [nwchemgit/nwchem#327]
The results of QA quantum coputation test be_6-31g_fci agrees very well with that of Gamess Aldet FCI, with the negnigible difference of the two kinds of FCIs, i.e., difference occurring in eight decimal points, where the energy of Aldet is lower,  when using the same number of active orbitals as well as active electrons, and the same basis set.

[be_6-31g_fci.log](https://github.com/nwchemgit/nwchem/files/5979348/be_6-31g_fci.log)

I have repeated the first and tried the latter.

Very Best Regards!

**Comment by xiongyan21** [comment]
Can NWchem do second order FCI?

Very Best Regards!

**Comment by edoapra** [comment]
Please use the template to report issues.
This issue will be closed for not following the provided template

**Comment by xiongyan21** [comment]
Generally,  examples in chem_library_tests don't do quantum calculations.

Very Best Regard!
