### ISSUE TITLE
"task dft" is tedious in QA test ch3radical_rot_mp

### ISSUE THREAD

**Issue by xiongyan21** [nwchemgit/nwchem#328]
For the paramagnetic NMR calculation using odft QA test ch3radical_rot_mp including ZORA and mcp ,  the same results will be got with or without " task dft" by NWChem7.0.0 and NWCHEM7.0.2.
 If odft is changed into dft for a closed shell compound, error will appear, perhaps the model is no longer useful.

Very Best Regards!

[ch3radical_rot_mp.log](https://github.com/nwchemgit/nwchem/files/5995159/ch3radical_rot_mp.log)
[ch3radical_rot_mp1.log](https://github.com/nwchemgit/nwchem/files/5995163/ch3radical_rot_mp1.log)
[ch3radical_rot_mp2.log](https://github.com/nwchemgit/nwchem/files/5995165/ch3radical_rot_mp2.log)
[ch3radical_rot_mp3.log](https://github.com/nwchemgit/nwchem/files/5995172/ch3radical_rot_mp3.log)

**Comment by edoapra** [comment]
Please use the template to report issues.
This issue will be closed for not following the provided template
