### ISSUE TITLE
CC2 calculations are not working and run CCSD instead

### ISSUE THREAD

**Issue by chjacob-tubs** [nwchemgit/nwchem#337]
With the most recent version, CC2 calculations are not possible anymore. 

The problem can be reproduced with the test tce_cc2_c2.nw, for which the output then shows
```
 Iterations converged
 CCSD correlation energy / hartree =        -0.312647997365604
 CCSD total energy / hartree       =       -75.700612067459403
```
(with version 6.8.1 that I used previously I get CC2 instead of CCSD here, the numbers also change).

I traced this problem to lines 834-836 in `src/tce/tce_energy.F`, where `ccsd_var` is set to `ic` (should be `cc2`). 
```
       if (.not.rtdb_get(rtdb,'tce:nts',mt_log,1,res_log)) 
     c      res_log=.true.
       if(res_log) ccsd_var='ic'
```

I dont know what this code is supposed to do, so I cannot suggest a fix. But commenting out these lines gives me back the old behavior.

**Comment by edoapra** [comment]
@chjacob-tubs Could you attach to this issue the complete input and output files?

**Comment by edoapra** [comment]
A fix for this bug has been committed to the `master` and the `hotfix/release-7-0-0` branches.
The fix has been validated by the tce_cc2_c2 QA test (e.g. [https://github.com/nwchemgit/nwchem/runs/2034470592?check_suite_focus=true](https://github.com/nwchemgit/nwchem/runs/2034470592?check_suite_focus=true)
