### ISSUE TITLE
"too many open files in system" error

### ISSUE THREAD

**Issue by jerrypgreenberg** [nwchemgit/nwchem#338]
Hi

One of our users on our expanse cluster at SDSC ( https://www.sdsc.edu/support/user_guides/expanse ) was running a qmmm optimization and he found that if he uses more then 32 cores on a single node (the nodes have 128 cores), he gets the following error:

_shm_attach: shm_open: Too many open files in system
[14] Received an Error in Communication: (-1) _shm_attach: shm_open
Abort(-1) on node 14 (rank 14 in comm 496): application called MPI_Abort(comm=0x84000002, -1)

He compiled nwchem 6.6 himself with intel/intelmpi 19.1.1.217

I uploaded the input files (appended with ".txt") the the log file

Also, ulimit -n gives:

131072

Jerry

[vnb32s.nw.log](https://github.com/nwchemgit/nwchem/files/6105597/vnb32s.nw.log)

[vnb32s.nw.txt](https://github.com/nwchemgit/nwchem/files/6105514/vnb32s.nw.txt)
[vnb32s-F.pdb.txt](https://github.com/nwchemgit/nwchem/files/6105515/vnb32s-F.pdb.txt)

**Comment by edoapra** [comment]
This issue does not contain any information on how NWChem was compiled.
What value of `ARMCI_NETWORK` was used?
NWChem 6.6 is more than five years old.  I would recommend using the latest 7.0.2 version before filing a bug report

**Comment by mjklemm** [comment]
I have seen this error in the context of Open MPI and `ARMCI_NETWORK=MPI-PR`.  In that case, a large number of shared-memory segments have to be created to do the intra-node communication between the compute processes and the communication process.

You need to increase the max number of open file descriptors for the system.  You can do this by running the following command as root user for each of the compute nodes:

`echo xyz > /proc/sys/fs/file-max`

Please replace xyz in the above command with an actual number in the range of 512000.

Can you confirm you're using MPI-PR and that the above works for you?

**Comment by jerrypgreenberg** [comment]
Thanks!

We increased our file limit to 548000 and now the user reports that she can go up to 103 cores on a 128 node.

Before we increase this further, our system administrators would like to know if there is some recommended number of open files per core that we should be using?

**Comment by mjklemm** [comment]
For my tests, I just put a large number, which I guess is fine for testing, but nothing you'd on a production system. 

I will conduct a few tests on my systems and see what the minimum number of file descriptors is.  I'll come back with an answer soon.

**Comment by mjklemm** [comment]
I was able to run on 12 nodes with 128 MPI process per node when setting the max number of open files to 375000:

`echo 375000 > /proc/sys/fs/file-max`

Hope that helps!

**Comment by jerrypgreenberg** [comment]
Hi Michael,

Any news?

Thanks,

Jerry

From: Michael Klemm ***@***.***>
Date: Thursday, March 11, 2021 at 11:40 PM
To: nwchemgit/nwchem ***@***.***>
Cc: Greenberg, Jerry ***@***.***>, Author ***@***.***>
Subject: Re: [nwchemgit/nwchem] "too many open files in system" error (#338)

For my tests, I just put a large number, which I guess is fine for testing, but nothing you'd on a production system.

I will conduct a few tests on my systems and see what the minimum number of file descriptors is. I'll come back with an answer soon.

**Comment by edoapra** [comment]
@jerrypgreenberg 
Michael has replied 21 days ago.
> I was able to run on 12 nodes with 128 MPI process per node when setting the max number of open files to 375000:
> 
> `echo 375000 > /proc/sys/fs/file-max`
> 
> Hope that helps!

**Comment by jerrypgreenberg** [comment]
Thanks,

Sorry I missed that.

Jerry

From: Edoardo Aprà ***@***.***>
Date: Wednesday, April 7, 2021 at 1:53 PM
To: nwchemgit/nwchem ***@***.***>
Cc: Greenberg, Jerry ***@***.***>, Mention ***@***.***>
Subject: Re: [nwchemgit/nwchem] "too many open files in system" error (#338)

@jerrypgreenberg<https://urldefense.com/v3/__https:/github.com/jerrypgreenberg__;!!Mih3wA!Um4EveSfXedetIVdxkR9PGZPrq84D4HURLz1fJinNxw2j5yUSEo_L42PcbcM$>
Michael has replied 21 days ago.

I was able to run on 12 nodes with 128 MPI process per node when setting the max number of open files to 375000:

echo 375000 > /proc/sys/fs/file-max

Hope that helps!
