### ISSUE TITLE
NWCHEM Does Not Give Electronic  Entropy and Gives Completely Different Rotational Entropy

### ISSUE THREAD

**Issue by xiongyan21** [nwchemgit/nwchem#34]
NWCHEM does dot provide the value of electronic  entropy value and gives a completely different one of rotational entropy. 
It seems GAMESS cannot optimize the initial structure(any geometry) using mp2 and fails when using b3lyp. GAMESS only can do when mult=2.
The results from GAMESS
mp2 
...
NSERCH=  0     ENERGY=      -0.4998212

                                 -----------------------
                                 GRADIENT (HARTREE/BOHR)
                                 -----------------------
        ATOM     ZNUC       DE/DX         DE/DY         DE/DZ
 --------------------------------------------------------------
    1  C            0.0     0.0000000     0.0000000     0.0000000
    2  H            1.0     0.0000000     0.0000000     0.0000000

          MAXIMUM GRADIENT = 0.0000000    RMS GRADIENT = 0.0000000

 NSERCH:   0  E=       -0.4998211760  GRAD. MAX=  0.0000000  R.M.S.=  0.0000000

      ***** EQUILIBRIUM GEOMETRY LOCATED *****
 COORDINATES OF ALL ATOMS ARE (ANGS)
   ATOM   CHARGE       X              Y              Z
 ------------------------------------------------------------
 C           0.0   0.0000000000   0.0000000000   0.0000000000
 H           1.0   0.5714200000   0.0000000000   0.0000000000
...
E         H         G         CV        CP        S
KJ/MOL    KJ/MOL    KJ/MOL   J/MOL-K   J/MOL-K   J/MOL-K
 ELEC.      0.000     0.000    -1.718     0.000     0.000     5.763
 TRANS.     3.718     6.197   -26.254    12.472    20.786   108.842
 ROT.       2.479     2.479  Infinity     8.314     8.314 -Infinity
 VIB.       0.000     0.000     0.000     0.000     0.000     0.000
 TOTAL      6.197     8.676  Infinity    20.786    29.100 -Infinity
 VIB. THERMAL CORRECTION E(T)-E(0) = H(T)-H(0) =     0.000 J/MOL
B3LYP
...ITER EX      TOTAL ENERGY        E CHANGE  DENSITY CHANGE    DIIS ERROR
   1  0       -0.4700490884    -0.4700490884   0.061014893   0.000000000
   2  1       -0.4960793402    -0.0260302518   0.033531066   0.000000000
   3  2       -0.4992807775    -0.0032014373   0.016429551   0.000000000
   4  3       -0.4997392689    -0.0004584914   0.006995024   0.000000000
   5  0       -0.4998085602    -0.0000692913   0.004695234   0.000000000
 CONVERGED TO SWOFF, SO DFT CALCULATION IS NOW SWITCHED ON.
   6  1       -0.4985075467     0.0013010135   0.028938710   0.000000000
   7  2       -0.4988712812    -0.0003637345   0.002327072   0.000000000
   8  3       -0.4988747068    -0.0000034256   0.000203816   0.000000000
 DFT CODE IS SWITCHING BACK TO THE FINE GRID
   9  4                 NaN              NaN   0.000000000   0.000000000
  10  5                 NaN              NaN   0.000000000   0.000000000

NWCHEM6.8 gives 
mult 2
Total Entropy                    =   40.905 cal/mol-K
   - Translational                =   33.623 cal/mol-K (mol. weight =  13.0078)
   - Rotational                   =    7.282 cal/mol-K (symmetry #  =        1)
   - Vibrational                  =    0.000 cal/mol-K

 Cv (constant volume heat capacity) =    4.966 cal/mol-K
   - Translational                  =    2.979 cal/mol-K
   - Rotational                     =    1.986 cal/mol-K
   - Vibrational                    =    0.000 cal/mol-K
mult 4
Total Entropy                    =   40.802 cal/mol-K
   - Translational                =   33.623 cal/mol-K (mol. weight =  13.0078)
   - Rotational                   =    7.178 cal/mol-K (symmetry #  =        1)
   - Vibrational                  =    0.000 cal/mol-K

 Cv (constant volume heat capacity) =    4.966 cal/mol-K
   - Translational                  =    2.979 cal/mol-K
   - Rotational                     =    1.986 cal/mol-K
   - Vibrational                    =    0.000 cal/mol-K
The log files of  the repeated calculations are attached 
[chquartet2.log](https://github.com/nwchemgit/nwchem/files/1875114/chquartet2.log)
[chdoublet2.log](https://github.com/nwchemgit/nwchem/files/1875117/chdoublet2.log)

It seems the possible problem from GAMESS is from the very beginning, i.e., the charge of carbon atom is zero.

**Comment by ebylaska** [comment]
Electronic entropy for mult=2
R*ln(2) = 8.314 J/mol-K * ln(2)  = 5.76282565918 J/mol-K
The rotational difference is probably because in one case you're using
symmetry and the other you're not

**Comment by xiongyan21** [comment]
CH  mp2 optimization is successful using GAMESS 2018 R3 binary.
...
  E         H         G         CV        CP        S
           KJ/MOL    KJ/MOL    KJ/MOL   J/MOL-K   J/MOL-K   J/MOL-K
 ELEC.      0.000     0.000    -1.718     0.000     0.000     5.763
 TRANS.     3.718     6.197   -35.765    12.472    20.786   140.742
 ROT.       2.479     2.479    -6.565     8.314     8.314    30.332
 VIB.      17.632    17.632    17.632     0.001     0.001     0.000
 TOTAL     23.830    26.309   -26.415    20.787    29.102   176.837
 VIB. THERMAL CORRECTION E(T)-E(0) = H(T)-H(0) =         ...
...
Very Best Regards!
