### ISSUE TITLE
NVIDIA Fortran issues with backlash

### ISSUE THREAD

**Issue by jeffhammond** [nwchemgit/nwchem#340]
This is a repeat of https://github.com/nwchemgit/nwchem/issues/176 for NVIDIA (formerly PGI) Fortran.

The solution is `-Mbackslash` although I am waiting to see if there is a programmatic solution ala XLF so that we can avoid more compiler flags.  However, the following is sufficient.

```
$ pwd
~/NWCHEM/arm/src/nwpw/nwpwlib/nwpwxc
$ nvfortran  -c -i8 -Mcache_align   -mp -Minfo=mp -fast -O3 -Mvect=simd  -Munroll -Minfo=loop  -I.  -I~/NWCHEM/arm/src/include -I~/NWCHEM/arm/src/tools/install/include -DEXT_INT -DLINUX -DLINUX64 -DCHKUNDFLW -DPGLINUX -DUSE_OPENMP -DPARALLEL_DIAG -DINTERNALBLAS nwpwxc_vdw3c.F
NVFORTRAN-S-0026-Unmatched quote (nwpwxc_vdw3c.F: 3181)
  0 inform,   0 warnings,   1 severes, 0 fatal for nwpwxc_split
NVFORTRAN-S-0026-Unmatched quote (nwpwxc_vdw3c.F: 3244)
  0 inform,   0 warnings,   1 severes, 0 fatal for nwpwxc_removebksl
```

# Potential fix
```patch
diff --git a/src/config/makefile.h b/src/config/makefile.h
index 74360ba058..91bb999b02 100644
--- a/src/config/makefile.h
+++ b/src/config/makefile.h
@@ -2475,6 +2475,7 @@ ifeq ($(_CPU),$(findstring $(_CPU), ppc64 ppc64le))
     endif # end of ppc64 arch
       ifeq ($(_FC),pgf90)
         FOPTIONS   += -Mcache_align  # -Kieee 
+        FOPTIONS   +=  -Mbackslash
 #        FOPTIMIZE   = -O3  -Mnounroll -Minfo=loop -Mipa=fast
         FOPTIMIZE   =  -fast -O3 -Mvect=simd  -Munroll -Minfo=loop # -Mipa=fast
         FVECTORIZE   = -fast    -O3   #-Mipa=fast
```

# Compiler version
```
$ nvfortran --version

nvfortran 21.2-0 linuxarm64 target on aarch64 Linux 
NVIDIA Compilers and Tools
Copyright (c) 2020, NVIDIA CORPORATION.  All rights reserved.
```

**Comment by edoapra** [comment]
What `FC` are you using? `nvfortran`?

**Comment by jeffhammond** [comment]
Yeah, `nvfortran` from https://developer.nvidia.com/nvidia-hpc-sdk-downloads.

**Comment by edoapra** [comment]
Is this in the same nwpw directory as https://github.com/nwchemgit/nwchem/issues/176 ?

**Comment by jeffhammond** [comment]
Yeah, sorry, it's `nwpwxc_vdw3c.F` just like before.  My initial bug report is not high-quality 😞

**Comment by edoapra** [comment]
I have just realized that your are using `aarch64` (that's why I was surprised I did not stumbled myself with nvfortran on x86_64 earlier)
You need the same fix that was pushed for `nvfortran/x86_64` with 
https://github.com/nwchemgit/nwchem/commit/bd8b4e7cf17b5723c396f0991e681120a1c2f673

**Comment by jeffhammond** [comment]
Ah, okay, that's good.  I am indeed on AArch64.  I should have mentioned that too.

**Comment by edoapra** [comment]
It seems that we have two different pgf90 sections (one starts at line 2167 and one at line 2476) that we should probably consolidate in one. 
Your result seems to indicate that the 2476 section is x86_64 specific (but this needs to be verified)

**Comment by edoapra** [comment]
Could you test the commit I pushed on `aarch64`? It seems to work by using the trick `_CPU=aarch64`, but I was still using the x86_64 nvfortran

**Comment by jeffhammond** [comment]
Yeah I wonder at what point we should clean up the Linux build stuff. There's a lot of obsolete support there.  I'll take a crack at consolidating PGI/NV at least.

**Comment by edoapra** [comment]
Fix tested.
https://github.com/nwchemgit/nwchem/runs/2496243076?check_suite_focus=true
