### ISSUE TITLE
QA test pspw_SiC cannot get the same result with the same input as the original input

### ISSUE THREAD

**Issue by xiongyan21** [nwchemgit/nwchem#341]
QA test pspw_SiC cannot get the same result withe the same input  as the original test
[pspw.log](https://github.com/nwchemgit/nwchem/files/6147014/pspw.log)
original:

[pspw_SiC_original.log](https://github.com/nwchemgit/nwchem/files/6147058/pspw_SiC_original.log)

Very Best Regard!

**Comment by edoapra** [comment]
Please use the issue template

**Comment by xiongyan21** [comment]
I surely can reproduce your results with you inputs.
