### ISSUE TITLE
Help Compile NWchem parallel.

### ISSUE THREAD

**Issue by shinhyuna159** [nwchemgit/nwchem#346]
Hello. I am a student in theoretical quantum chemistry lab. I failed to compile the NWchem.
I don't want installation the NWchem in yum. I want to compile the NWchem version 7.0.2. (ex. Using make and make install)
I have to compile the NWchem source code because I want to study the NWchem source code in parallel. (Actually, I am a beginner to compilation. So, I desperately need help. :'( ) 

My server OS is CentOS 7, GCC version is 7.3.1, Make version is 4.2.1. And I configure Nwchem with Intel MKL, OpenMPI (v 3.1.6), Pyhton2.7.5 and GA (v 5.8)

My .bashrc file is 
'''
export NWCHEM_TOP=/opt/nwchem
export NWCHEM_TARGET=LINUX64
export ARMCI_NETWORK=MPI-PR
export NWCHEM_MODULES=all
export USE_NOFSCHECK=TRUE
export USE_NOIO=TRUE
export MRCC_METHODS=TRUE
export CCSDTQ=TRUE
export PYTHONVERSION=2.7
export BLASOPT="-L/opt/intel/mkl/lib/intel64"
export LAPACK_LIB="-L/opt/intel/mkl/lib/intel64"
export LIBMPI="-L$MPI_LIB -lmpi_mpifh -lmpi_usempif08 -lmpi -lmpi_usempi_ignore_tkr"
export FC=gfortran
export CC=gcc
export CXX=g++
export NWCHEM_MPIF_WRAP=/opt/mpi/bin/mpifort
export NWCHEM_MPIC_WRAP=/opt/mpi/bin/mpicc
export NWCHEM_MPICXX_WRAP=/opt/mpi/bin/mpicxx
export USE_MPI=y
export USE_MPIF=y
export USE_MPIF4=y
export MPI_LOC=/opt/mpi
export MPI_LIB=/opt/mpi/lib
export MPI_INCLUDE=/opt/mpi/include
export PATH=$NWCHEM_TOP/bin/$NWCHEM_TARGET:$PATH
export LD_LIBRARY_PATH=$NWCHEM_TOP/lib/$NWCHEM_TARGET:$LD_LIBRARY_PATH
'''

I saw and followed it on this site https://nwchemgit.github.io/Compiling-NWChem.html

And do ` cd /opt/nwchem/src` , `make nwchem_config`, `make -j6 2> error`

An error occurred here. 

[error.txt](https://github.com/nwchemgit/nwchem/files/6178966/error.txt)

I don't know why the error occurs. Please help me compile the Nwchem. I am willing to give you additional information you need. Please help me.

(I have asked this question before, but I am not fully informed on how to compile it, so I am posting it again.)

**Comment by shinhyuna159** [comment]
Oh my god... Everything I wrote is gone.....

**Comment by edoapra** [comment]
Please post this to the google group since this is not a bug report
https://groups.google.com/forum/#!forum/nwchem-forum
