### ISSUE TITLE
NWCHEM6.8 Prints Different Degenerate Excitation Energy Orders on Ubuntu17.10.2 with Openmpi from Those out of  QA Output and  on MAC with Mpich 

### ISSUE THREAD

**Issue by xiongyan21** [nwchemgit/nwchem#35]
For QA test tddft_n2+, NWCHEM6.8 prints different degenerate excitation energy orders on Ubuntu17.10.2 with Openmpi from those out of  QA output and  on MAC with mpich, the latter two 
of which are also not identical.
The log files of the calculations repeated are attached. Of course, the OSes are different.
MAC with mpich
[tddft_n2+.log](https://github.com/nwchemgit/nwchem/files/1886016/tddft_n2.log)
[tddft_n2+2.log](https://github.com/nwchemgit/nwchem/files/1886017/tddft_n2.2.log)
Ubuntu with openmpi
[tddft_n2+.log](https://github.com/nwchemgit/nwchem/files/1886008/tddft_n2.log)
[tddft_n2+2.log](https://github.com/nwchemgit/nwchem/files/1886010/tddft_n2.2.log)
Very Best Regards!

**Comment by jeffhammond** [comment]
I don't see an actual problem.  Degenerate systems tend to do things like this.  What specific numerical results concern you?

**Comment by xiongyan21** [comment]
Dear Dr. Hammond
   I just wonder why running on  different operating systems can give different orders, although they are degenerate.
  Very Best Regards!

**Comment by jeffhammond** [comment]
I doubt it has anything to do with the OS but rather has to do with the non-determinism of certain linear algebra operations.  Have you tried running the same job on the same machine multiple times with different process count to see if that shows a variation?

**Comment by xiongyan21** [comment]
I have repeated the calculation on the two different operating systems, each of which gets the same result.

**Comment by ngovind** [comment]
The results look fine. There is no issue here.

Best,
-Niri
