### ISSUE TITLE
Automatic symmetry detection failure on reasonable input

### ISSUE THREAD

**Issue by glowthrower** [nwchemgit/nwchem#354]
**Describe the bug**

Automatic symmetry detection fails for a reasonable system, and causes the run to halt:

```
                                NWChem Input Module
                                -------------------



 Scaling coordinates for geometry "geometry" by  1.889725989
 (inverse scale =  0.529177249)

 D3D symmetry detected
 ------------------------------------------------------------------------
 geom_input: autosym bug : too many atoms                  14
 ------------------------------------------------------------------------
 ------------------------------------------------------------------------
  current input line : 
    16: end
 ------------------------------------------------------------------------
 ------------------------------------------------------------------------
 There is an error related to the specified geometry
 ------------------------------------------------------------------------
 For more information see the NWChem manual at https://github.com/nwchemgit/nwchem/wiki
```

**Describe settings used**

NWChem 7.0.2, compiled with Intel Parallel Studio 2020, running on Ubuntu. I can replicate the bug on the version of NWChem obtained from apt (NWChem 6.6, OpenMPI), so I don't think the issue is due to compiler settings.

**To Reproduce**

Run the following deck, after inserting valid values for `permanent_dir` and `scratch_dir`.

```
echo
start

permanent_dir /path/to/permanent
scratch_dir /path/to/permanent

geometry units angstrom autosym
 C  -0.306900  -0.434000   0.000000
 C  -0.875300   1.009300   0.000000
 H   0.779292  -0.409001   0.005066
 H  -0.648078  -0.971141   0.880641
 H  -0.639873  -0.967954  -0.885705
 H  -1.961472   0.984434  -0.007998
 H  -0.531865   1.547429  -0.879180
 H  -0.544648   1.542352   0.887140
end

basis
  * library sto-2g
end

task scf energy
```

**Expected behavior**

I would expect that the autosymmetry code would either find a non-trivial symmetry and use it, or decide that no non-trivial symmetry can be applied and use C1.

**Additional context**

The system here is effectively a slight perturbation of a close-to-relaxed ethane molecule. It was autogenerated, but I don't see anything particularly pathological about it.

The expected symmetry of the relaxed ethane would be D3D, to my knowledge. I expect that this issue occurs because the perturbation breaks that symmetry in a way that is close to the tolerance of the symmetry detection algorithm. Indeed, changing the tolerance on the `autosym` directive from the default (i.e. `1.0e-02`) to either `1.0e-01` or `1.0e-03` produces successfully completing runs with detected symmetries of D3D and C3 respectively.

This issue can be worked around by simply turning off automatic symmetry (`noautosym`), but this is unappealing for my use case. I'm running a large number of autogenerated calculations like this, some of which will be able to make use of symmetry and some of which will not. Blanket usage of `noautosym` would incur significant unnecessary computational cost.

**Comment by edoapra** [comment]
Commit https://github.com/nwchemgit/nwchem/commit/37f4fbe046025d064313172655d24c4992a26f4b fixes this bug
