### ISSUE TITLE
Semidirect SCF failure on H2 with minimal basis set and memory-only integral caching

### ISSUE THREAD

**Issue by glowthrower** [nwchemgit/nwchem#355]
**Describe the bug**

Running a semidirect SCF calculation without file caching on an H2 system with STO-2G fails and halts:

```
 ----------------------------------------------
         Quadratically convergent ROHF

 Convergence threshold     :          1.000E-04
 Maximum no. of iterations :           30
 Final Fock-matrix accuracy:          1.000E-07
 ----------------------------------------------

 ------------------------------------------------------------------------
 int2e_test_mem: int2e_file_open failed                   0
 ------------------------------------------------------------------------
 ------------------------------------------------------------------------
  current input line : 
    20: task scf energy
 ------------------------------------------------------------------------
 ------------------------------------------------------------------------
 This error has not yet been assigned to a category
 ------------------------------------------------------------------------
 For more information see the NWChem manual at http://www.nwchem-sw.org/index.php/NWChem_Documentation

```

**Describe settings used**

NWChem 7.0.2, Intel Parallel Studio 2020. The bug is reproducible on NWChem 6.6, gcc, OpenMPI.

**To Reproduce**

Run the following deck, after inserting valid values for `permanent_dir` and `scratch_dir`.

```
echo
start

permanent_dir /path/to/permanent
scratch_dir /path/to/scratch

geometry units angstrom autosym
 H 0.0 0.0 0.0
 H 0.7 0.0 0.0
end

basis
  * library sto-2g
end

scf
  semidirect filesize 0
end

task scf energy
```

**Expected behavior**

The run should not fail.

**Additional context**

The `semidirect` specification here is intended to disable file caching in the scratch directory, and implicitly use the default "available" amount of memory for caching. According to my reading of the [relevant documentation](https://nwchemgit.github.io/Hartree-Fock-Theory-for-Molecules.html#direct-and-semidirect-recomputation-of-integrals), this should be a reasonable thing to do, although please do tell me if I'm making a fundamental error here.

A bit of poking around suggests that the issue is occurring [here](https://github.com/nwchemgit/nwchem/blob/master/src/ddscf/int2e_file.F#L144). I suspect that this might be some kind of corner case due to the fact that the number of integrals required here is almost as low as possible. Note that disabling `autosym` stops this error from occurring.

**Comment by edoapra** [comment]
@glowthrower thanks for submitting this detailed bug report.
Fix https://github.com/nwchemgit/nwchem/commit/eca73c5652f8a6e1165cd5f235024669d7d323eb is under testing. Since it seems to be a corner case, we need to be sure it does not cause more harm than good.

**Comment by glowthrower** [comment]
You're welcome, thanks for getting onto it so fast!

Your fix looks pretty much like what I expected it to be. One point: wouldn't it perhaps be better to use `ceiling(...)` rather than `nint(...)`?

**Comment by edoapra** [comment]
Yes, you are right about rounding for `ceiling()` vs `nint()`
The only issue with `ceiling` appeared only with the _Fortran95_ standard and, unfortunately, we might have NWChem developer using historical compilers ...
Anyhow, beyond the silly joke, I will insert `ceiling`

**Comment by edoapra** [comment]
Tested
