### ISSUE TITLE
nwchem conda package on conda-forge?

### ISSUE THREAD

**Issue by ltalirz** [nwchemgit/nwchem#359]
Hi guys, I was wondering whether there is interest in creating a conda package for nwchem so that people can install nwchem simply using `conda install -c conda-forge nwchem` - starting with linux, but perhaps with the goal of eventually adding support for osx (not sure whether there's a chance for windows as well).

Starting from a [conda recipe](https://github.com/insilichem/conda-recipes/tree/master/nwchem) by @jaimergp I've started to make a PR to conda-forge [here](https://github.com/conda-forge/staged-recipes/pull/14725) but I'm running into an issue:

For some reason, nwchem is [trying to use the (non-existing) `gcc` executable as the C compiler](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=308952&view=logs&j=6f142865-96c3-535c-b7ea-873d86b887bd&t=22b0682d-ab9e-55d7-9c79-49f3c3ba4823&l=11125), despite the [`CC` environment variable being set correctly to `$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-cc`](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=308952&view=logs&j=6f142865-96c3-535c-b7ea-873d86b887bd&t=22b0682d-ab9e-55d7-9c79-49f3c3ba4823&l=652)

Would you mind having a look and helping me tweak the compilation?

**Comment by jaimergp** [comment]
Hey! I wrote that recipe years ago so I am not sure it will work with latest `nwchem`... that said, you can try `cat`ing `nwchem_config.h` to see if the settings there are correct. And you can also try passing CC to `make` directly in the same command just to make sure it's using the right one or... creating a symlink in `BUILD_PREFIX/bin` that points `gcc` to `$CC`. Good luck!

**Comment by ltalirz** [comment]
Thanks!

The content of the `nwchem_config.h` file [seems to be](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=309097&view=logs&j=6f142865-96c3-535c-b7ea-873d86b887bd&t=22b0682d-ab9e-55d7-9c79-49f3c3ba4823&l=792)
```
# This configuration generated automatically on 0783b9d7b72b at Mon Apr 26 14:02:34 UTC 2021
# Request modules from user: all python nwxc
NW_MODULE_SUBDIRS = NWints atomscf ddscf gradients moints nwdft nwxc rimp2 stepper driver optim cphf ccsd vib mcscf prepar esp hessian selci dplot mp2_grad qhop property solvation nwpw fft python analyz nwmd cafe space drdy vscf qmmm qmd etrans tce bq mm cons perfm dntmc dangchang ccca dimqm
NW_MODULE_LIBS = -lccsd -lmcscf -lselci -lmp2 -lmoints -lstepper -ldriver -loptim -lnwdft -lgradients -lcphf -lesp -lddscf -ldangchang -lguess -lhessian -lvib -lnwcutil -lrimp2 -lproperty -lsolvation -lnwints -lprepar -lnwmd -lnwpw -lofpw -lpaw -lpspw -lband -lnwpwlib -lnwxc -lcafe -lspace -lanalyze -lqhop -lpfft -ldplot -lnwpython -ldrdy -lvscf -lqmmm -lqmd -letrans -lpspw -ltce -lbq -lmm -lcons -lperfm -ldntmc -lccca -ldimqm
EXCLUDED_SUBDIRS = develop scfaux rimp2_grad argos diana uccsdt rism geninterface smd nbo leps lucia rdmft
CONFIG_LIBS = 
```
I.e. I don't see any specification of the compiler in here.

I'll try passing the `CC` variable explicitly to `make`, although I thought the effect should be the same as having it in the env vars... perhaps nwchem is looking for a different env var for the c compiler?

**Comment by edoapra** [comment]
@ltalirz  You could you try  following make command
```
make FC=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-gfortran _FC=gfortran CC=CC=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-cc _CC=gcc
```  

I have simply added `_FC=gfortran` and `_CC=gcc` (this is needed for using the correct compiler options, since your compilation log shows that this is not happening)  
  
I would recommend passing `FC`, `_FC`, `CC` and `_CC` as make arguments, since they cannot be ignored by makefile content (while environment variables can be ignored and this might be your case) .

Let me know if these changes are of any help

**Comment by ltalirz** [comment]
thanks for the hint @edoapra !

> I would recommend passing `FC`, `_FC`, `CC` and `_CC` as make arguments, since they cannot be ignored by makefile content (while environment variables can be ignored and this might be your case).

I didn't know that [there was a difference](https://stackoverflow.com/a/2826178/1069467), very good to know!

This indeed fixed the issue - it still prints `gcc` while `make`ing but I guess under the hood it now uses the correct compiler.

It looks to me like compilation goes fine now but when it gets to `make make nwchem.o stubs.o` and starts linking, I get [this error](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=312112&view=logs&j=6f142865-96c3-535c-b7ea-873d86b887bd&t=22b0682d-ab9e-55d7-9c79-49f3c3ba4823&l=96192)
```
make nwchem.o stubs.o
make[1]: Entering directory '$SRC_DIR/src'
$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-gfortran -m64 -ffast-math  -Warray-bounds -std=legacy -fdefault-integer-8 -fno-tree-dominator-opts  -finline-functions -O2 -g  -fno-aggressive-loop-optimizations -fno-tree-dominator-opts  -g -O   -I.  -I$SRC_DIR/src/include -I$SRC_DIR/src/tools/install/include -DGFORTRAN -DCHKUNDFLW -DGCC4 -DGCC46 -DEXT_INT -DLINUX -DLINUX64 -DSCALAPACK -DPARALLEL_DIAG -DCOMPILATION_DATE="'`date +%a_%b_%d_%H:%M:%S_%Y`'" -DCOMPILATION_DIR="'$SRC_DIR'" -DNWCHEM_BRANCH="'7.0.2'"  -c -o nwchem.o nwchem.F
$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-gfortran -m64 -ffast-math  -Warray-bounds -std=legacy -fdefault-integer-8 -fno-tree-dominator-opts  -finline-functions -O2 -g  -fno-aggressive-loop-optimizations -fno-tree-dominator-opts  -g -O   -I.  -I$SRC_DIR/src/include -I$SRC_DIR/src/tools/install/include -DGFORTRAN -DCHKUNDFLW -DGCC4 -DGCC46 -DEXT_INT -DLINUX -DLINUX64 -DSCALAPACK -DPARALLEL_DIAG -DCOMPILATION_DATE="'`date +%a_%b_%d_%H:%M:%S_%Y`'" -DCOMPILATION_DIR="'$SRC_DIR'" -DNWCHEM_BRANCH="'7.0.2'"  -c -o stubs.o stubs.F
make[1]: Leaving directory '$SRC_DIR/src'
$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-gfortran   -L$SRC_DIR/lib/LINUX64 -L$SRC_DIR/src/tools/install/lib  -o $SRC_DIR/bin/LINUX64/nwchem nwchem.o stubs.o -lnwctask -lccsd -lmcscf -lselci -lmp2 -lmoints -lstepper -ldriver -loptim -lnwdft -lgradients -lcphf -lesp -lddscf -ldangchang -lguess -lhessian -lvib -lnwcutil -lrimp2 -lproperty -lsolvation -lnwints -lprepar -lnwmd -lnwpw -lofpw -lpaw -lpspw -lband -lnwpwlib -lnwxc -lcafe -lspace -lanalyze -lqhop -lpfft -ldplot -lnwpython -ldrdy -lvscf -lqmmm -lqmd -letrans -lpspw -ltce -lbq -lmm -lcons -lperfm -ldntmc -lccca -ldimqm -lnwcutil -lga -larmci -lpeigs -lperfm -lcons -lbq -lnwcutil  $PREFIX  -l64to32 -lopenblas -lpthread -lrt  -lopenblas -lnwcblas  -L$PREFIX/lib -L$PREFIX/lib -lmpi_usempif08 -lmpi_usempi_ignore_tkr -lmpi_mpifh -lmpi    -lcomex -lmpi_usempif08 -lmpi_usempi_ignore_tkr -lmpi_mpifh -lmpi -lrt -lpthread -lm -lpthread  -lnwcutil -L$PREFIX/lib/python3.9/config-3.9-x86_64-linux-gnu -L$PREFIX/lib -lpython3.9 -lcrypt -lpthread -ldl  -lutil -lrt -lm -lm   
/home/conda/staged-recipes/build_artifacts/nwchem_1619864976759/_build_env/bin/../lib/gcc/x86_64-conda-linux-gnu/9.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: error: /home/conda/staged-recipes/build_artifacts/nwchem_1619864976759/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac: read: Is a directory
collect2: error: ld returned 1 exit status
```
It's a little hard to read but the main part is:
```
ld: error: /home/conda/staged-recipes/build_artifacts/nwchem_1619864976759/_h_env_placehold..._plac: read: s a directory
```
i.e. it seems to me like one of the files mentioned in the link line (`nwchem` binary? one of the `.o` files?) is actually a directory (and the name of the file is cut off because of the insane length of the directory names in the conda-forge build env).

Any ideas why that might be?

P.S. Here the link to the [build script](https://github.com/conda-forge/staged-recipes/pull/14725/files#diff-8344d54caf45059604f1ec780172b582105879883a879b5e06ddb4b81a2919a4R55)

**Comment by edoapra** [comment]
The link error is probably caused by the ScaLapack settings.
Please unset `USE_SCALAPACK` and `SCALAPACK` and
use `SCALAPACK_LIB` to point to the link option needed to link against ScaLapack libraries
(your current value of `$SCALAPACK` contains a directory name instead of a linking option)
In other words, `SCALAPACK_LIB` should have the format `-L"directory of scalapack library" -l"name of scalapack library` (e.g. `-L/usr/local/lib -lscalapack`)

There are a few more changes you should make

* I would change the make command to

```
make FC=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-gfortran _FC=gfortran CC=CC=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-cc _CC=gcc DEPEND_CC=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-cc V=1
```  
I have added `V=1` to get a verbose output and `DEPEND_CC=$BUILD_PREFIX/bin/x86_64-conda-linux-gnu-cc` to fix some errors are still occurring during the compilations.

* Please do not include the `nwxc` module since it is meant for production runs

* if the `python` command is in your current `PATH`, all the python env. variables you have chosen are ignored, only `PYTHONVERSION` might be needed  
https://nwchemgit.github.io/Compiling-NWChem.html#setting-python-environment-variables  
[Python3 github issue](https://github.com/nwchemgit/nwchem/issues/271)

**Comment by ltalirz** [comment]
Thanks a lot for the hints! Compilation and linking now [succeeded](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=312297&view=logs&j=6f142865-96c3-535c-b7ea-873d86b887bd&t=22b0682d-ab9e-55d7-9c79-49f3c3ba4823&l=53269) - just some dependency issues remain that I should be able to address.

By the way, [this](https://github.com/conda-forge/staged-recipes/blob/2790c46a9a287135331c59b461d5f7c4bee112cb/recipes/nwchem/run_test.sh) is currently the test script - once the build proceeds to that stage I'll see how long this takes.
Let me know if you have any comments on it - ideal would be to run a set of tests with reasonable coverage without taking many hours, taking into account that they will run on a azure runner with limited resources (perhaps not the whole test suite).


> * Please do not include the `nwxc` module since it is meant for production runs

I assume you meant to write that `nwxc` is *not* meant for production runs (?).
I've excluded it now - but if it was meant for production runs I guess I should put it back.

P.S. By the way, if you or someone else from the nwchem team is interested in being a co-maintainer of the `nwchem` conda-forge feedstock, just let me know and I will add you (via the github handle).

**Comment by edoapra** [comment]
Glad to hear you got a successful build. The log file looks shows no obvious issues.
The test script looks good, too.
You are right about the `nwxc` module as well.

**Comment by edoapra** [comment]
I have just noticed that some of the  conda-forge files mention the old NWChem website 
(e.g. line 40 of https://github.com/conda-forge/staged-recipes/blob/44ff829a96b247e6c9ada6701d871486d5db7b9f/recipes/nwchem/meta.yaml).
Please remove any mention of it since it has been taken over by cyber-squatters.   
The URL for the current NWChem website is https://nwchemgit.github.io

**Comment by edoapra** [comment]
The Global Arrays (aka tools) configuration fails at detecting the BLAS libraries.  
The only way to debug this problem is to look at `$NWCHEM_TOP/src/tools/build/config.log`
Could you modify the build script to show the `config.log` content?
```
2021-05-02T11:10:15.1019776Z configure: Checks for BLAS,LAPACK,ScaLAPACK
2021-05-02T11:10:15.1020724Z configure: 
2021-05-02T11:10:15.1717466Z configure: Attempting to locate BLAS library
2021-05-02T11:10:15.2156748Z checking for BLAS with user-supplied flags... no
2021-05-02T11:10:15.2618121Z checking for BLAS in AMD Core Math Library... no
2021-05-02T11:10:15.3082721Z checking for BLAS in Intel Math Kernel Library... no
2021-05-02T11:10:15.3599779Z checking for BLAS in ATLAS... no
2021-05-02T11:10:15.4085187Z checking for BLAS in PhiPACK libraries... no
2021-05-02T11:10:15.4229600Z checking for BLAS in Apple Accelerate.framework... no
2021-05-02T11:10:15.4367393Z checking for BLAS in Apple vecLib.framework... no
2021-05-02T11:10:15.5320973Z checking for BLAS in Alpha CXML library... no
2021-05-02T11:10:15.6451179Z checking for BLAS in Sun Performance Library... no
2021-05-02T11:10:15.6902008Z checking for BLAS in SGI/Cray Scientific Library... no
2021-05-02T11:10:15.7355097Z checking for BLAS in SGIMATH library... no
2021-05-02T11:10:15.8294249Z checking for BLAS in IBM ESSL library... no
2021-05-02T11:10:15.8783666Z checking for BLAS in generic library... no
2021-05-02T11:10:15.8784412Z configure: WARNING: BLAS library not found, using internal BLAS
```

**Comment by edoapra** [comment]
The solution for the openblas issue might be to provide the path to the directory where conda has installed openblas. You could you try the following
```
BLASOPT="-L$PREFIX -lopenblas -lpthread -lrt"
```

**Comment by edoapra** [comment]
Since your QA runs fail to use the very long name (stored in `nwchemrc`) of the directory where the basis libraries are stored, you might want to try the patch derived by the commit I have just made
https://github.com/edoapra/nwchem/commit/78c3689b262369b1e0ab379d4df30e060c121678.patch

**Comment by ltalirz** [comment]
thanks a lot @edoapra for the thorough checks!

Just to catch up - website link fixed; fixed blas link linke which [did solve the problem at the configure stage](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=312793&view=logs&j=6f142865-96c3-535c-b7ea-873d86b887bd&t=22b0682d-ab9e-55d7-9c79-49f3c3ba4823&l=7609); fixed linking issue

Thanks for the patch for the tests - if that is indeed the reason that would have taken me some time to figure out...
let's see whether that fixes it!

I'm not entirely sure it will - E.g. the nwchemrc part was not written by me and I'm not 100% sure that this will actually take effect when entering the test environment in the conda-forge build.
If not, there may be a different way to fix it - namely to take the `NWCHEM_BASIS_LIBRARY` from the `$SRC_DIR` instead of from the `$PREFIX`.

Let's see

**Comment by edoapra** [comment]
The previous patch was not covering all the cases yet.
Please add this second patch 
https://github.com/edoapra/nwchem/commit/f2a713e447ea2a9b1010022cf81f5a5cea17ba29.patch

**Comment by ltalirz** [comment]
Thanks to patient hands-on support by @edoapra , a conda package for nwchem is now available (see [feedstock](https://github.com/conda-forge/nwchem-feedstock) ).

A build for MacOS was just merged as well, i.e. in a couple of hours users should be able to `conda install -c conda-forge nwchem` on linux and macos.

Each build is tested with [doafewqmtests.mpi](https://github.com/nwchemgit/nwchem/blob/master/QA/doafewqmtests.mpi), so the basics should work.
Perhaps a little more testing might be useful before mentioning this installation route in the nwchem docs.
