### ISSUE TITLE
SMD generic input always assumes aqueous solvent

### ISSUE THREAD

**Issue by edoapra** [nwchemgit/nwchem#363]
**Describe the bug**
When using the SMD generic input  (that is without providing the `solvent` keyword), the output always shows that an  aqueous solvent is used. More details at 
https://groups.google.com/g/nwchem-forum/c/5osD1_yRle4
A workaround is to supply a solvent keyword for a non existing solvent (e.g. `solvent mysol`)

**Attach log files**
Input and output files showing that the solvent is considered aqueous
[smd_bug.nw.txt](https://github.com/nwchemgit/nwchem/files/6423299/smd_bug.nw.txt)
[smd_bug.out.txt](https://github.com/nwchemgit/nwchem/files/6423300/smd_bug.out.txt)

**Expected behavior**
The output file (as in the cases when  either `solvent mysol`, followed by explicit SMD parameters, or `solvent dmf` are used) reports a non-aqueous solvent
[smd_dmf.nw.txt](https://github.com/nwchemgit/nwchem/files/6423313/smd_dmf.nw.txt)
[smd_dmf.out.txt](https://github.com/nwchemgit/nwchem/files/6423314/smd_dmf.out.txt)

**Comment by xiongyan21** [comment]
I can surely reproduce your results with your inputs by NWChem7.0.2.
