### ISSUE TITLE
Warnings when using NWChem Molden output in JANPA

### ISSUE THREAD

**Issue by nkl311** [nwchemgit/nwchem#37]
Using NWCHEM6.8 molden file output through JANPA, a series of errors has come up.

Molden2molden with cart2pure flag is used to convert NWChem molden file to an acceptable input to JANPA

The new molden file is then run through JANPA with -ignorefock flag. The resulting JANPA file has 3 internal warnings:

WARNING: molecular orbital normalization problem! This may spoil MO occupancies…
Maximum absolute value of off-diagonal MO overlap element: 5.221E-01 (< MO  378 | MO  394 >)
WARNING: molecular orbitals seem to be non-orthogonal ?!
WARNING: input data seems to be improper!

The last issue is that the total number of calculated electrons in the molecule is a float value (179.114112 in this case), making the sum of electrons charges and the nuclei charges = -1.11411. Perhaps this is related to the large off-diagonal overlap?

[nwchem_molden.zip](https://github.com/nwchemgit/nwchem/files/1968548/nwchem_molden.zip)

**Comment by nkl311** [comment]
Attached. Thank you!

[nw_run.zip](https://github.com/nwchemgit/nwchem/files/1968597/nw_run.zip)

**Comment by edoapra** [comment]
Dumb question: why are you using a cartesian basis sets in the NWChem input?
Spherical basis are more numerical stable and would not require the extra cart2pure Janpa step ...

**Comment by edoapra** [comment]
I had a quick look at Janpa's code dealing with cart2pure transformation (SphericalHarmonics.java).
This code is not meant to work with NWChem's definition of cartesian basis.
The comments in the source code SphericalHarmonics.java describes the different conventions used in NWChem from the one cart2pure is expecting.
Therefore, there isn't anything we can do from the NWChem side.
I believe you have two options to get your NPA done

1. Use spherical basis in NWChem (this is what I strongly suggest)
2. Modify the Java code for the  cartesian to spherical transformation in Janpa to have a specific argument (and associated code) for dealing with NWChem cartesian convention

**Comment by edoapra** [comment]
Closed to lack of feedback from issue submitter
