### ISSUE TITLE
Whether the Multipole Analysis of the Density Is for Solvation Phase or Gas One

### ISSUE THREAD

**Issue by xiongyan21** [nwchemgit/nwchem#38]
Recently, Lrdev put a topic COSMO directive failing in NWChem Revision 29289 on the NWCHEM Functionality section of  NWCHEM forum.
After 41 steps of the gas phase and 22 steps of the solvation one iterations, NWCHEM6.8 installed under Ubuntu 17.10.2 using six threads when symmetry c1 had been arbitrarily added into the original input provided there finished with the results  identical with those obtained by NWCHEM6.8 precompiled on MAC without the addition of symmetry c1. I wonder whether the multipole analysis of the density is for the gas phase or for the solvation phase.
The other question is when the dielectric constant is 33.58, it is still called water, although the results might not be affected.
The log file is attached.
[rulinux.log](https://github.com/nwchemgit/nwchem/files/1974513/rulinux.log)

**Comment by xiongyan21** [comment]
When "noio" and "direct" are removed from the input, the calculation is much more faster, around 4600 seconds saved.
The log file is attached.
[ruio.log](https://github.com/nwchemgit/nwchem/files/2385289/ruio.log)

**Comment by jeffhammond** [comment]
> When "noio" and "direct" are removed from the input, the calculation is much more faster, around 4600 seconds saved.
> 
It sounds like you have enough memory to store all the integrals or your filesystem is fast relative to computing integrals.

**Comment by xiongyan21** [comment]
You can check the memory allocation I have used.
The HP Z2 MINI Workstation has an I7 6700, 256G NVMe PCle, and 16GB 2400 MHz memeory.

**Comment by jeffhammond** [comment]
I don't have any NVMe SSDs but my understanding is they are very fast relative to spinning disk storage...  

In any case, the NWChem log file indicates a good fraction of the integrals are cached:
` #quartets = 2.049D+08 #integrals = 4.494D+09 #direct = 24.7% #cached = 75.3%` 

This job likely doesn't need anywhere near 7 GB of GA memory, by the way.  You might try increasing the stack to 10G and reducing the GA allocation to 3 GB to see if that allows all the integrals to be cached.

**Comment by xiongyan21** [comment]
Thanks a lot for your extremely helpful advices.
M.2 NVMe SSD seems to be the fastest so far.

**Comment by xiongyan21** [comment]
Deleted
