### ISSUE TITLE
util_blas_set_num_threads crashes the code when using sci_intel on Cori

### ISSUE THREAD

**Issue by hjjvandam** [nwchemgit/nwchem#381]
Relatively recently the code has been extended to allow setting the number of threads for a BLAS library to use. However, the number of BLAS libraries supported is still relatively low, and for unrecognized BLAS libraries the code now crashes with 
```
     util_blas not ready
```
This means that currently the code won't work on Cori for example. I guess the ultimate plan is to allow users to control the number of threads in the BLAS library perhaps versus the number of threads that OpenMP might use (so you can make BLAS calls from OpenMP parallel regions). However, while this is still under development could we just let the code continue for BLAS libraries that are not recognized (maybe just print a warning message so it isn't forgotten that something still needs to be done) rather than kill the job?

**Comment by jeffhammond** [comment]
indeed, i would prefer this not be an error, and that we fallback on omp_set_num_threads if OpenMP is used, and do nothing if it is not.  a diagnostic warning is something we should use in development but seems imprudent to expose to end users, who will not respond to it in a useful way.

**Comment by edoapra** [comment]
* NWChem can be easily installed on Cori by switching either to MKL or to OpenBLAS/ScaLapack by using `BUILD_OPENBLAS`/`BUILD_SCALAPACK`
* the `util_blas not ready` is there for the developers to provide a solution. For the master branch I prefer this other than a fall-back solution

**Comment by edoapra** [comment]
Commit https://github.com/nwchemgit/nwchem/commit/f74ba9d849d2676451285316f638871651aa4701 tested on cori
It can be used with any variation of `BLASOPT=-lsci*` (e.g. `-lsci_intel_mpi_mp`)

**Comment by hjjvandam** [comment]
Thanks for fixing this. I am up and running with it on Cori now.
