### ISSUE TITLE
It seems result of QA test tce_ipccsd_f2 significantly deviating from experimental data 

### ISSUE THREAD

**Issue by xiongyan21** [nwchemgit/nwchem#396]
It seems result of QA test tce_ipccsd-f2 significantly deviates from experimental data, i.e., 15.099 eV of the former compared with 15.686+-0.006 eV in the latter in _Photoionization Mass Spectrometric Study of F 2, HF, and DF_.

I care this because I wish to calculate the mass spectra of pestices for their detections.

By the way,  the DFT calculated Raman spectra oa a pesticide, whose geometry is first optimized by DFT with Nchem7.0.2, have detection lines being able to be compared with those in an article on it published in China,  but in order to match the THz experimental spectra published in  articles, DFT optimized geometry and RHF frequency analysis all with GAMESS are required. The calculation can repeat the usually reported one with lowest frequency, and the second and forth ones. AM1 calculation in an article reproduces the  above latter two. I will try the DFTB Raman, although it cannot converge in DFTB optimization.

The TD-CIS searched energy of the first excited state of a pesticide in a solvent practically can agree with those in references,  which cannot be very strict because of the solvation setting required here, and the osiccilator strength is zero. 
The adiabatic one fails to match. The search perhaps can be accepted because the energy is close to the experimental one.
If a functional is used, it is very difficult to converge and it seems it is the later excited states that will match the experimental data.

Very Best Regards!

**Comment by xiongyan21** [comment]
For the NWCHEM7.0.2 DFT 6-31+G** b3lyp calculated NMR of a pesticide in vacuum after Si(CH3)4 having been considered, the chemical shift of  around 5.3 ppm cannot include two hydrogens, but the experimental data published in two articles in China all report two hydrogens at 4.53 ppm (400MHz) and 4.578 ppm(600MHz) in solvents. Perhaps b3lyp should be changed.

Very Best Regards!

**Comment by edoapra** [comment]
Please use other platforms for this kind of elucubrations
