### ISSUE TITLE
Small bug in xc_tabcd()

### ISSUE THREAD

**Issue by dmejiar** [nwchemgit/nwchem#4]
I've found a small bug in xc_tabcd(). 

Lines 359-360 read

```fortran
                FUNC_MAXJ = rchi_atom(jat)
                if(grad) FUNC_MAXJ = max(rchi_atom(jat),FUNC_MAXJ)
```

It should be

```fortran
                FUNC_MAXJ = rchi_atom(jat)
                if(grad) FUNC_MAXJ = max(rdelchi_atom(jat),FUNC_MAXJ)
```

**Comment by edoapra** [comment]
Checked in as commit b212d1e030abcd29af2e6702d6e4646d7f157200
Daniel, thanks a lot for your contribution!

**Comment by edoapra** [comment]
Checked into release-6-8 as commit 4fad66626163eee21d216a428ccb06aa1cf1bbea
