### ISSUE TITLE
Geometry optimizations get imaginary frequencies

### ISSUE THREAD

**Issue by xiongyan21** [nwchemgit/nwchem#416]
The input is the following for two pesticides, imidacloprid and thiamethoxam,
...
basis "ao basis"
* library "6-31+G**"
end
dft
xc b3lyp
grid fine
convergence energy 1d-9
end
driver
 clear
 tight
 MAXITER 200
end

task dft optimize
dft;grid xfine;end

and the following is got
...
Step       Energy      Delta E   Gmax     Grms     Xrms     Xmax   Walltime
  ---- ---------------- -------- -------- -------- -------- -------- --------
@   26   -1668.57234903 -3.0D-10  0.00000  0.00000  0.00003  0.00006  24398.8
                                     ok       ok       ok       ok  
but when Raman calculation was carried out, the first Hessian analysis had maginary frequencies
----------------------------------------------------------------------------
 Normal Eigenvalue ||    Projected Derivative Dipole Moments (debye/angs)
  Mode   [cm**-1]  ||      [d/dqX]             [d/dqY]           [d/dqZ]
 ------ ---------- || ------------------ ------------------ -----------------
    1      -28.895 ||       0.129              -0.215            -0.104
    2       -0.000 ||      -0.011              -0.029             0.180
    3       -0.000 ||       0.003               0.006            -0.057
    4       -0.000 ||      -0.007              -0.034            -0.023
    5       -0.000 ||       0.006               0.011            -0.131
For the other:
 1      -82.353 ||    0.000386           0.009         0.377       0.087
    2      -61.992 ||    0.004295           0.099         4.187       0.962
    3       -0.000 ||    0.000330           0.008         0.322       0.074
    4       -0.000 ||    0.000415           0.010         0.405       0.093
    5       -0.000 ||    0.001546           0.036         1.507       0.346
    6       -0.000 ||    0.001148           0.026         1.120       0.257
    7       -0.000 ||    0.000027           0.001         0.026       0.006
    8       -0.000 ||    0.000020           0.000         0.019       0.004

Gamess optimizations using b3lyp and 6-311+G(d,p) have no imaginary frequencies. I know perhaps the larger basis sets eliminate such ones, but it is a little time-consuming in the case of NWCHEM7.0.2. Thus, any helps?

Very Best Regards!

**Comment by edoapra** [comment]
Please use the issue template
