### ISSUE TITLE
Atom order in nudged elastic band MEP search

### ISSUE THREAD

**Issue by xiongyan21** [nwchemgit/nwchem#419]
I am repeating  the work of _Nudged elastic band method and density  functional theory calculation for finding a local minimum energy pathway of p-benzoquinone and phenol fragmentation in mass spectroscopy_  in EJMS (2017, 41-44).
 It seems atom order cannot be kept unchanged in this case(even principles of  microreversibility is applied) . It is the case in GAMESS, too. No permisssion of ROHF in NEB?

The error is
...
 neb: NEW NEB CHAIN, INITIALIZING
 neb_initial_path failed                   2
 ------------------------------------------------------------------------
 ------------------------------------------------------------------------
  current input line : 
 neb_initial_path failed                   2
 ------------------------------------------------------------------------
 ------------------------------------------------------------------------
  current input line : 
 ------------------------------------------------------------------------
 neb_initial_path failed                   2
 ------------------------------------------------------------------------
 ------------------------------------------------------------------------
  current input line : 
     0: 
     0: 
 ------------------------------------------------------------------------
 ------------------------------------------------------------------------
 This error has not yet been assigned to a category
 ------------------------------------------------------------------------
...

 Can it be easily to carry out NEB calculations without such requirements?

Very Best Regards!

**Comment by xiongyan21** [comment]
By the way, this may deal with multiple spin states.
Has NWCHEM implemented this, like the reference _Extending nudged elastic band method to reaction pathways involving multiple spin states?_ 

Very Best Regards!

**Comment by edoapra** [comment]
No input file provided
