### ISSUE TITLE
IPCCSD Gave Different Excitation Orbitals

### ISSUE THREAD

**Issue by xiongyan21** [nwchemgit/nwchem#42]
Dr.Faklerus raised a question on the NWCHEM forum, saying failing to run the QA for f2 IP-EOMCCSD calculation.
I find there is no prolem to finish the calculation using the original input to get the results identical with those in QA test.
I have just installed the updates of  the operating system, and have not recompile NWCHEM6.8, and now the calculation gave different excitation orbitals.
...
Excited state root 1

Excitation energy / hartree =        0.554880518711326

                  / eV      =       15.099073582827362

largest EOMCCSD amplitudes: R1 and R2

Singles contributions

    8a   (alpha)       -0.9552531110

Doubles contributions

   10a   (beta )  ---     5a   (alpha)     7a   (beta )       -0.1018834489

   10a   (beta )  ---     6a   (alpha)     7a   (beta )        0.1101299892

Parallel integral file used       4 records with       0 large values

Task  times  cpu:       24.8s     wall:       42.4s

...
Another run gets
...
Singles contributions

    8a   (alpha)        0.2922556835

    9a   (alpha)        0.9094477014

Doubles contributions

   10a   (alpha)  ---     6a   (alpha)     7a   (alpha)       -0.1058335725

   10a   (alpha)  ---     7a   (alpha)     6a   (alpha)        0.1058335725

   10a   (beta )  ---     6a   (alpha)     7a   (beta )       -0.1444066816

I will recompile it and see.
[ip.log](https://github.com/nwchemgit/nwchem/files/2045719/ip.log)
[ip1.log](https://github.com/nwchemgit/nwchem/files/2045720/ip1.log)

[ip2.log](https://github.com/nwchemgit/nwchem/files/2045730/ip2.log)
[ip3.log](https://github.com/nwchemgit/nwchem/files/2045748/ip3.log)
[ip4.log](https://github.com/nwchemgit/nwchem/files/2045771/ip4.log)
[ip5.log](https://github.com/nwchemgit/nwchem/files/2045772/ip5.log)

**Comment by jeffhammond** [comment]
> I have upgraded the operating system to Ubuntu18, and have not recompile NWCHEM6.8, and now the calculation is not stable

Don’t do this. Recompile binaries when you upgrade the OS.

**Comment by xiongyan21** [comment]
On macOS High Sierra, they are also different.
[ip2.log](https://github.com/nwchemgit/nwchem/files/2046554/ip2.log)
[ip3.log](https://github.com/nwchemgit/nwchem/files/2046555/ip3.log)
[ip1.log](https://github.com/nwchemgit/nwchem/files/2046556/ip1.log)
[ip.log](https://github.com/nwchemgit/nwchem/files/2046557/ip.log)

**Comment by xiongyan21** [comment]
Recompilation eliminate the problem.
[ip.log](https://github.com/nwchemgit/nwchem/files/2046809/ip.log)
[ip1.log](https://github.com/nwchemgit/nwchem/files/2046810/ip1.log)
I think NWCHEM6.8 on MAC also needs recompilation, because of the installation of the updates.

**Comment by xiongyan21** [comment]
Can the motivation of the different excitation orbitals be enlightened by the article of Pharm and Prof. Gordon: Can Orbitals Really Be Observed in Scanning Tunneling Microscopy Experiments?

**Comment by xiongyan21** [comment]
GAMESS can directly give IP. Is the first excited root obtained by NWCHEM here the first IP？
Very Best Regards!

**Comment by xiongyan21** [comment]
GAMESS can directly give IP. Is the first excited state root obtained by NWCHEM here the first IP？
Very Best Regards!

**Comment by xiongyan21** [comment]
I can verify the first excitation energy obtained is the first IP using NWCHEM because when I changed the keyword IPCCSD into CCSD, the obtained first excitation energy is much lower, thus the IP obtained by NWCHEM is unsuccessful for F2 when compared with NIST data.
