### ISSUE TITLE
Can different convergence criteria in geometry optimization and Raman calculation cause imaginary frequency

### ISSUE THREAD

**Issue by xiongyan21** [nwchemgit/nwchem#420]
The DFT Hessian analyses in Raman calculation produce imaginary frequencies for  the two pesticides.   Imidacloprid  and     Thiamethoxam. Can it be cuased by the different convergence criteria in Raman calculation and geometry analyses because Gamess DFT Hessian analysis using Gamess DFT optimized geometry has no imaginary frequencies, neither does NWCHEM RHF frequency with GAMESS geometry.

The input for Raman
basis
* library "6-31+G**"
end

dft
xc b3lyp
convergence energy 1d-8 nolevelshifting
end

hessian
thresh 1d-8
profile
end

property
response  1 8.8559E-2
damping 0.007
end

raman
  normal
end

driver
 clear
end

task dft raman

The input for optimization
basis "ao basis"
* library "6-31+G**"
end

dft
xc b3lyp
grid fine
convergence energy 1d-9
end

driver
 clear
 tight
 MAXITER 200
end

task dft optimize
dft;grid xfine;end

6-31G* frequency analysis of 6-31G* b3lyp optimized   Imidacloprid  has two smaller imaginary frequencies.

**What should be omitted or added to make the calculation equivalent regarding to convergence criteria?**

Very Best Regards!

**Comment by xiongyan21** [comment]
BY the way, DFTB3 optimization of  Imidacloprid  is OK without any imginary frequencies and the subsequent DFTB3 Raman calculation gives three detection lines close to those reported in an article published in China.

I wish NWCHEM implemented this in the near future.

Very Best Regards!

**Comment by edoapra** [comment]
Incomplete input file. Geometry section missing
