### ISSUE TITLE
Same convergence criteria in  DFT group in Raman and geometry optimization or geometry optimized from GAMESS cause many NWChem Dynamic CPHF Module calculations

### ISSUE THREAD

**Issue by xiongyan21** [nwchemgit/nwchem#422]
Identical convergence criteria in  DFT group in Raman and geometry optimization or geometry optimized from GAMESS cause many NWChem Dynamic CPHF Module calculations
Geometry optimization
1d-9
Raman
1d-9 nolevelshifting

What is the problem here?

By the way, 6-31G** Raman  calculation using the geometry optimized using 6-31+G**, all  with NWCHEM7.0.2, has no imaginary frequency.  It seems it should be the other way around.

Very Best Reagrtds!

**Comment by edoapra** [comment]
Yet another incomplete issue

**Comment by xiongyan21** [comment]
DFT Geometry of pesticide, now with 6-31G* and tighter convergence criterion , does not produce imaginary frequency in later Hessian analysis.

Very Best Regards!
