### ISSUE TITLE
Optimization steps in TCE

### ISSUE THREAD

**Issue by antoscha** [nwchemgit/nwchem#43]
Dear developers,

I'd like to ask how to get geometries at each optimization step when run the TCE module? This question is corresponding to a topic on the NWChem forum where, unfortunately, no solution is given:
http://www.nwchem-sw.org/index.php/Special:AWCforum/st/id2216/task_tce_optimize.html
If there is no way to do it, the issue can be marked as [FEATURE REQUEST].

Thank you in advance.

**Comment by edoapra** [comment]
Please provide an input and output file showing the problem.
Thanks

**Comment by edoapra** [comment]
No further input provided
