### ISSUE TITLE
Will the current version of NWCHEM not be updated?

### ISSUE THREAD

**Issue by xiongyan21** [nwchemgit/nwchem#430]
Will the current version of NWCHEM not be updated?

There is an article in Chemical Reviews, _From NWChem to NWChemEx: Evolving with the Computational Chemistry Landscape._

Very Best Regards!

**Comment by jeffhammond** [comment]
This is not really an appropriate topic for GitHub, but NWChem and NWChemEx are separate projects, and both are actively developed right now.  Also, since NWChemEx is not generally available, whereas NWChem is on obviously on GitHub with a permissive license, they are not comparable.
