### ISSUE TITLE
Is the calculated DFT Raman strength wrong?

### ISSUE THREAD

**Issue by xiongyan21** [nwchemgit/nwchem#432]
The Raman lines should be strong around 3000 cm-1, but it seems  NWCHEM7.0.2 B3lyp gives questionable strength for methane if I haven't misunderstood the strength expression.

...
of frequencies : 9
freq [ 1/cm] S [Ang**4/amu]

1 ... 4.6943E+06
2 ... 3.5818E+01
3 ... 2.3670E+01
4 ... 6.6062E+00
5 ... 2.6691E+00
6 ... 2.1850E+00
7 ... 8.0499E+00
8 ... 1.1637E+00
9 3127.45 1.6601E+00

...

The geometry optimization input is 
echo

start molecule

title "Title"
charge 0

geometry units angstroms print xyz
 symmetry c1
   C       -2.62799        1.32442        0.00000
   H       -1.55799        1.32442        0.00000
   H       -2.98465        1.11745        0.98735
   H       -2.98465        0.57283       -0.67291
   H       -2.98465        2.28296       -0.31444
end

basis "ao basis"
* library "6-311++G**"
end

dft
xc b3lyp
grid fine
convergence energy 1d-9
end

driver
 clear
 tight
 MAXITER 200
end

task dft optimize
dft;grid xfine;end

The Raman input is with the geometry omitted
start molecule

title "Title"
charge 0

geometry units angstroms print xyz autosym
....
end

basis "ao basis"
* library "6-311++G**"
end

dft
xc b3lyp
convergence energy 1d-8 nolevelshifting
end

hessian
thresh 1d-8
profile
end

property
response  1 w(a frequency)
damping 0.007
end

raman
  normal
end

driver
 clear
end

task dft raman

Very Best Regards!

**Comment by xiongyan21** [comment]
Actually, there is something unusual in the NWchem output
...
(start,last,rmmodes,nfreq,plot,width)=(   1,  15,   9,   1,normal          ,    20.00000000)
rminfo(   1)=(  1341.19475598,***************,  2097.35357166,***************)
rminfo(   2)=(  1341.19525073,    35.81000501,     0.00753700,    35.81754200)
rminfo(   3)=(  1341.19574540,    23.66503856,     0.00448652,    23.66952508)
...
Perhaps, there are problems in the NWCHEM calculation.

Very Best Regards!

**Comment by edoapra** [comment]
Please post the full input file or I will close this issue, too.
Ever heard of [Reproducibility](https://en.wikipedia.org/wiki/Reproducibility)?
