### ISSUE TITLE
License link broken

### ISSUE THREAD

**Issue by ikirker** [nwchemgit/nwchem#45]
This link to the license in `LICENSE.txt` no longer works. (404)
https://github.com/nwchemgit/nwchem/blob/921d5d0556f5b424b4bfe618e2edcfaa4b2b5a9d/LICENSE.TXT#L20

I'd suggest maybe changing it to https://opensource.org/licenses/ECL-2.0 instead.

**Comment by edoapra** [comment]
It seems to work now.

Could you please be more specific?

On 07/20/2018 04:27 AM, Ian Kirker wrote:

This link to the license in LICENSE.txt no longer works. (404)
https://github.com/nwchemgit/nwchem/blob/921d5d0556f5b424b4bfe618e2edcfaa4b2b5a9d/LICENSE.TXT#L20

I'd suggest maybe changing it to https://opensource.org/licenses/ECL-2.0 instead.

**Comment by ikirker** [comment]
Sorry, I wasn't clear: this URL: <http://www.osedu.org/licenses/ECL-2.0> is contained in the text of the license file in this repo. It returns a 404 page for me. (See image.)

![2018-07-20 18_37_55-404 not found _ os edu](https://user-images.githubusercontent.com/479061/43016850-2017a9a2-8c4c-11e8-93f3-9196b5c3fccb.png)

I checked on the Wayback Machine, and it looks like that URL hasn't worked for at least a few years.

**Comment by edoapra** [comment]
I specified the wrong commit in the previous comment
The correct one for the  master branch is https://github.com/nwchemgit/nwchem/commit/8ce850d7b2c49b96bfdd9172d8e6e0a18ff06994
