### ISSUE TITLE
Numerical and Analytical Hessian routines give vastly different answers

### ISSUE THREAD

**Issue by jbecca** [nwchemgit/nwchem#46]
I have attached two output files to this issue. I have the same exact coordinates and input blocks with the only difference being the numerical frequency routine or the analytical routine. The numerical routine finishes with no negative frequencies while the analytical routine comes back with three large negative frequencies. I am unsure if a setting I have is incorrect for the analytical hessian, or if this is a bug. 

Thanks for looking into this. 

[reactant1-geom-num.txt](https://github.com/nwchemgit/nwchem/files/2249804/reactant1-geom-num.txt)
[reactant1-geom.txt](https://github.com/nwchemgit/nwchem/files/2249805/reactant1-geom.txt)

**Comment by edoapra** [comment]
@jbecca You need xfine grid in the hessian input section and you need to be very strict in the geometry optimization. Have a look at the attached input and output files
[fufu.nw.txt](https://github.com/nwchemgit/nwchem/files/2250623/fufu.nw.txt)
[fufu.output.txt](https://github.com/nwchemgit/nwchem/files/2250624/fufu.output.txt)

**Comment by jbecca** [comment]
@edoapra Is the xfine grid something that should always be set for calculating the analytical frequencies? I would have normally assumed that any grid or numerical instability would have shown up first in the finite difference hessian method.

Thanks for the help on this.

**Comment by edoapra** [comment]
@jbecca No, the analytical frequencies are more likely to be affected by numerical issue, both in first determining the minimum and then in evaluating the hessian
