### ISSUE TITLE
Fails to build with OpenMPI: undefined reference to symbol 'ompi_mpi_dblprec'

### ISSUE THREAD

**Issue by yurivict** [nwchemgit/nwchem#470]
**Describe the bug**
In an attempt to switch to OpenMPI I switched Scalapack and ga to OpenMPI. I've put ```mpif90``` from OpenMPI into path. Then nwchem failed:

```
gmake[3]: Leaving directory '/disk-samsung/freebsd-ports/science/nwchem/work/nwchem-7.0.2-release/src'
gfortran10 -m64 -ffast-math  -Warray-bounds -std=legacy -fdefault-integer-8 -O2 -g  -fno-aggressive-loop-optimizations  -I/usr/local/mpi/openmpi/include  -L/disk-samsung/freebsd-ports/science/nwchem/work/nwchem-7.0.2-release/src/../lib/LINUX64 -L/usr/local/lib  -L/usr/local/mpi/openmpi/lib  -o /disk-samsung/freebsd-ports/science/nwchem/work/nwchem-7.0.2-release/src/../bin/LINUX64/nwchem nwchem.o stubs.o -lnwctask -lccsd -lmcscf -lselci -lmp2 -lmoints -lstepper -ldriver -loptim -lnwdft -lgradients -lcphf -lesp -lddscf -ldangchang -lguess -lhessian -lvib -lnwcutil -lrimp2 -lproperty -lsolvation -lnwints -lprepar -lnwmd -lnwpw -lofpw -lpaw -lpspw -lband -lnwpwlib -lcafe -lspace -lanalyze -lqhop -lpfft -ldplot -ldrdy -lvscf -lqmmm -lqmd -letrans -lpspw -ltce -lbq -lmm -lcons -lperfm -ldntmc -lccca -ldimqm -lnwcutil -lga -larmci -lpeigs -lperfm -lcons -lbq -lnwcutil    -l64to32 -lnwclapack  -lnwcblas  -L/usr/local/mpi/openmpi/lib -lmpi_usempi -lmpi_mpifh -lmpi    -lcomex -lblas -lm -L/usr/local/lib -lpthread   
/usr/local/bin/ld: warning: libmpi.so.40, needed by /usr/local/lib/libga.so, may conflict with libmpi.so.12
/usr/local/bin/ld: /disk-samsung/freebsd-ports/science/nwchem/work/nwchem-7.0.2-release/src/../lib/LINUX64/libnwcutil.a(util_mygabcast.o): undefined reference to symbol 'ompi_mpi_dblprec'
/usr/local/bin/ld: /usr/local/mpi/openmpi/lib/libmpi.so.40: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```

The symbol ```ompi_mpi_dblprec``` is defined in the OpenMPI library.

**Describe settings used**
Environment:
```NWCHEM_TOP=/disk-samsung/freebsd-ports/science/nwchem/work/nwchem-7.0.2-release/src/.. NWCHEM_MODULES=all NWCHEM_LONG_PATHS=Y NWCHEM_TARGET=LINUX64 USE_INTERNALBLAS=Y EXTERNAL_GA_PATH=/usr/local  BLAS_SIZE=4 USE_64TO32=y USE_MPI=Y PATH=/usr/local/mpi/openmpi/bin:/disk-samsung/freebsd-ports/science/nwchem/work/.bin:/home/yuri/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin F77="gfortran10" FC="gfortran10" FFLAGS="-O -Wl,-rpath=/usr/local/lib/gcc10" FCFLAGS="-Wl,-rpath=/usr/local/lib/gcc10" PERL_USE_UNSAFE_INC=1 XDG_DATA_HOME=/disk-samsung/freebsd-ports/science/nwchem/work  XDG_CONFIG_HOME=/disk-samsung/freebsd-ports/science/nwchem/work  XDG_CACHE_HOME=/disk-samsung/freebsd-ports/science/nwchem/work/.cache  HOME=/disk-samsung/freebsd-ports/science/nwchem/work NO_PIE=yes MK_DEBUG_FILES=no MK_KERNEL_SYMBOLS=no SHELL=/bin/sh NO_LINT=YES ADDR2LINE="/usr/local/bin/addr2line" AR="/usr/local/bin/ar" AS="/usr/local/bin/as" CPPFILT="/usr/local/bin/c++filt" GPROF="/usr/local/bin/gprof" LD="/usr/local/bin/ld" NM="/usr/local/bin/nm" OBJCOPY="/usr/local/bin/objcopy" OBJDUMP="/usr/local/bin/objdump" RANLIB="/usr/local/bin/ranlib" READELF="/usr/local/bin/readelf" SIZE="/usr/local/bin/size" STRINGS="/usr/local/bin/strings" PREFIX=/usr/local  LOCALBASE=/usr/local  CC="cc" CFLAGS="-O2 -pipe -fno-omit-frame-pointer  -fstack-protector-strong -fno-strict-aliasing "  CPP="cpp" CPPFLAGS="-fno-omit-frame-pointer"  LDFLAGS=" -Wl,-rpath=/usr/local/lib/gcc10  -L/usr/local/lib/gcc10 -B/usr/local/bin -fstack-protector-strong " LIBS=""  CXX="c++" CXXFLAGS="-O2 -pipe -fno-omit-frame-pointer -fstack-protector-strong -fno-strict-aliasing -fno-omit-frame-pointer  "  MANPREFIX="/usr/local" BSD_INSTALL_PROGRAM="install  -s -m 555"  BSD_INSTALL_LIB="install  -s -m 0644"  BSD_INSTALL_SCRIPT="install  -m 555"  BSD_INSTALL_DATA="install  -m 0644"  BSD_INSTALL_MAN="install  -m 444"```

OS: FreeBSD 13

**Comment by edoapra** [comment]
What about submitting cleaner and more readable issues? Could you break the environment line?

**Comment by yurivict** [comment]
Updated.

**Comment by edoapra** [comment]
Do you still have the `mpich`  libraries on the system installed under `/usr/local/lib/`

**Comment by edoapra** [comment]
> Updated.

Do we need captcha to check if there is a human behind the submitter? The output looks still pretty troublesome to decypher. Couldn't you have a single environment variable on each line?

**Comment by edoapra** [comment]
The `ga-5.8` package seems to be built using `mpich`. Therefore you cannot use it with `openmpi`.
```
$ ldd /usr/local/lib/libga.so|grep mpifo
	libmpifort.so.12 => /usr/local/lib/libmpifort.so.12 (0x803319000)
$ pkg list mpich|egrep libmpifort.so.12
/usr/local/lib/libmpifort.so.12
/usr/local/lib/libmpifort.so.12.1.11
```

**Comment by yurivict** [comment]
> Do you still have the mpich libraries on the system installed under /usr/local/lib/?

Yes.

> Do we need captcha to check if there is a human behind the submitter?

I often think this way about developers.

> Couldn't you have a single environment variable on each line?

Ctrl-F doesn't work in your browser?

In the port framework all variables are in one variable and most easily are printed this way.

**Comment by yurivict** [comment]
> The ga-5.8 package seems to be built using mpich. Therefore you cannot use it with openmpi.

**No**, I changed its port option to build with OpenMPI, and same with Scalapack.
