### ISSUE TITLE
Discrepancy between code and docs: D3 and D3(BJ) correction with B2PLYP 

### ISSUE THREAD

**Issue by gibacic** [nwchemgit/nwchem#475]
The [NWChem documentation](https://nwchemgit.github.io/Density-Functional-Theory-for-Molecules.html#disp-empirical-long-range-contribution-vdw) says that Grimme's D3 and D3(BJ) dispersion corrections (`disp vdw 3` and `disp vdw 4`, respectively) are available for B2PLYP, but NWChem complains that they aren't.

NWChem v7.0.2 was installed and configured by Compute Canada on their Cedar cluster. I believe all settings are default. Occurs with serial or parallel execution.

Is there some other way to set the B2PLYP xc functional and get the dispersion corrections? We have [dftd3-lib](https://github.com/dftbplus/dftd3-lib) installed on the cluster, too, if it can be called externally (like in psi4).

The following minimal input  reproduces the problem. Replace `disp vdw 3` with `disp vdw 4` to reproduce with the other correction.
```
start b2plyp_vdw3_test 
memory total 3 gb
charge 0
geometry 
        O       0       0       0
        H       0       1.4     -1.1
        H       0       -1.4    -1.1
end
basis
        * library def2-qzvpp
end
mp2
        freeze atomic
end
dft
        xc HFexch 0.53 becke88 0.47 lyp 0.73 mp2 0.27
        dftmp2
        disp vdw 3
end
title "B2PLYP-D3/def2-QZVPP single-point energy"
task dft
```

**Comment by edoapra** [comment]
Thank for spotting this documentation discrepancy.
A  [fix](https://github.com/nwchemgit/nwchem/commit/52b09da6d9121dfb6d6538f3167d2cae8d9bcb69#diff-007e7182ff0e9538b6c1c9c5b386951346a3c205fb29f8289602536a7a78872d) was committed to the NWChem repository after the 7.0.2 release that allows to run B2PLYP-D3 (and D4) calculations with non standard input options.

Here are the instructions for patching an existing 7.0.2 source
```
cd $NWCHEM_TOP
wget https://github.com/nwchemgit/nwchem/commit/52b09da6d9121dfb6d6538f3167d2cae8d9bcb69.patch
patch -p1 < ./52b09da6d9121dfb6d6538f3167d2cae8d9bcb69.patch
cd src/nwdft/xc
make
cd ../..
make link
```
Here are the input lines required for B2LYP-D3
```
dft
  xc HFexch 0.53 becke88 0.47 lyp 0.73 mp2 0.27
 dftmp2
  disp vdw 3
end
set dft:vdw 0.64
set dft:vdw_sr6 1.427
set dft:vdw_s8 1.022
task dft
```
Here are the input lines required for B2LYP-D4
```
dft
 xc HFexch 0.53 becke88 0.47 lyp 0.73 mp2 0.27
 dftmp2
 disp vdw 4
end
set dft:vdw 0.64
set dft:vdw_s8 0.9147
set dft:vdw_a1 0.3065
set dft:vdw_a2 5.0570
task dft
```

**Comment by gibacic** [comment]
Thank you, Edoardo. That answers my question. I don't think the administrators will patch the code on the cluster with this hotfix, so I'll just have to wait til the next release candidate. 

Meanwhile, I'll just call `dftd3-lib` after a single-point calculation to get the dispersion correction since I'm not doing optimizations at the double-hybrid DFT level.

Just to clarify, `disp vdw 4` tells NWChem to compute the D3(BJ) correction (https://doi.org/10.1002/jcc.21759), not the newer D4 correction (https://doi.org/10.1063/1.5090222), right?

**Comment by edoapra** [comment]
> Just to clarify, `disp vdw 4` tells NWChem to compute the D3(BJ) correction (https://doi.org/10.1002/jcc.21759), _not_ the newer D4 correction (https://doi.org/10.1063/1.5090222), right?
From

https://nwchemgit.github.io/Density-Functional-Theory-for-Molecules.html#disp-empirical-long-range-contribution-vdw

`vdw 4` triggers the DFT-D3BJ dispersion model
