### ISSUE TITLE
30+ QA testcases fail

### ISSUE THREAD

**Issue by yurivict** [nwchemgit/nwchem#476]
**Describe the bug**
30+ QA testcases failed out of 400+ run so far.

**Describe settings used**
```
NWCHEM_TOP=/disk-samsung/freebsd-ports/science/nwchem/work/nwchem-7.0.2-release/src/.. NWCHEM_MODULES=all NWCHEM_LONG_PATHS=Y NWCHEM_TARGET=LINUX64 USE_INTERNALBLAS=Y EXTERNAL_GA_PATH=/usr/local  BLAS_SIZE=4 USE_64TO32=y USE_MPI=Y PYTHONVERSION=3.8 NWCHEM_MODULES="all python" F77="gfortran10" FC="gfortran10" FFLAGS="-O -Wl,-rpath=/usr/local/lib/gcc10" FCFLAGS="-Wl,-rpath=/usr/local/lib/gcc10" PERL_USE_UNSAFE_INC=1 XDG_DATA_HOME=/disk-samsung/freebsd-ports/science/nwchem/work  XDG_CONFIG_HOME=/disk-samsung/freebsd-ports/science/nwchem/work  XDG_CACHE_HOME=/disk-samsung/freebsd-ports/science/nwchem/work/.cache  HOME=/disk-samsung/freebsd-ports/science/nwchem/work PATH=/disk-samsung/freebsd-ports/science/nwchem/work/.bin:/home/yuri/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin NO_PIE=yes MK_DEBUG_FILES=no MK_KERNEL_SYMBOLS=no SHELL=/bin/sh NO_LINT=YES ADDR2LINE="/usr/local/bin/addr2line" AR="/usr/local/bin/ar" AS="/usr/local/bin/as" CPPFILT="/usr/local/bin/c++filt" GPROF="/usr/local/bin/gprof" LD="/usr/local/bin/ld" NM="/usr/local/bin/nm" OBJCOPY="/usr/local/bin/objcopy" OBJDUMP="/usr/local/bin/objdump" RANLIB="/usr/local/bin/ranlib" READELF="/usr/local/bin/readelf" SIZE="/usr/local/bin/size" STRINGS="/usr/local/bin/strings" PREFIX=/usr/local  LOCALBASE=/usr/local  CC="cc" CFLAGS="-O2 -pipe -fno-omit-frame-pointer  -fstack-protector-strong -fno-strict-aliasing "  CPP="cpp" CPPFLAGS="-fno-omit-frame-pointer"  LDFLAGS=" -Wl,-rpath=/usr/local/lib/gcc10  -L/usr/local/lib/gcc10 -B/usr/local/bin -fstack-protector-strong " LIBS=""  CXX="c++" CXXFLAGS="-O2 -pipe -fno-omit-frame-pointer -fstack-protector-strong -fno-strict-aliasing -fno-omit-frame-pointer  "  MANPREFIX="/usr/local" BSD_INSTALL_PROGRAM="install  -s -m 555"  BSD_INSTALL_LIB="install  -s -m 0644"  BSD_INSTALL_SCRIPT="install  -m 555"  BSD_INSTALL_DATA="install  -m 0644"  BSD_INSTALL_MAN="install  -m 444"
```

**Attach log files**
Test [log](https://people.freebsd.org/~yuri/nwchem-7.0.2-test.log)

Version: 7.0.2
Built with mpich. Ran on a single machine.
OS: FreeBSD 13

**Comment by edoapra** [comment]
Could you use the `master` branch instead of 7.0.2?

**Comment by yurivict** [comment]
[Log](https://people.freebsd.org/~yuri/nwchem-7.0.2.20211105-test.log) of today's master.

It also has failures.

I'll update it when the QA run advances.

**Comment by edoapra** [comment]
> [Log](https://people.freebsd.org/~yuri/nwchem-7.0.2.20211105-test.log) of today's master.
> 
> It also has failures.
> 
> I'll update it when the QA run would advance.

Much fewer failures. And some of the failures are on the last digit.

**Comment by edoapra** [comment]
Please update your tree since commit https://github.com/nwchemgit/nwchem/commit/9fcb2bdb8826fd5790eab199cc25c29ef3e534bf should fix most of your `pspw_*_h2o` failures

**Comment by yurivict** [comment]
9fcb2bdb8826fd5790eab199cc25c29ef3e534bf still has similar failures. See the [log](https://people.freebsd.org/~yuri/nwchem-7.0.2.20211109-test.log) that will be updated as the run progresses.

**Comment by edoapra** [comment]
https://github.com/nwchemgit/nwchem/commit/7b21660b82ebd85ef659f6fba7e1e73433b0bd0a addresses the two remaining `out of heap memory` errors.   
All the other failures seem  on the last digit, except for `k6h2o` were you need to setup the `.nwchemrc` file https://nwchemgit.github.io/Getting-Started.html#nwchemrc-for-environment-variables-and-libraries

**Comment by yurivict** [comment]
Rev. 7b21660b82ebd85ef659f6fba7e1e73433b0bd0a still has similar failures, 19 failures in the first 226 testcases, see [log](https://people.freebsd.org/~yuri/nwchem-7.0.2.20211110-test.log).

**Comment by edoapra** [comment]
Could you try a large memory value to see if this works, say
```
memory 2500 mb
```
?

**Comment by yurivict** [comment]
Adding ```memory 2500 mb``` in /usr/local/etc/nwchemrc didn't help tests/pspw_becke97_h2o.

**Comment by edoapra** [comment]
Please add/modify it in the input file
```
$NWCHEM_TOP/QA/tests/pspw_becke97_h2o/pspw_becke97_h2o.nw
```

**Comment by yurivict** [comment]
Adding same into .nw file helps. I guess you need to update failing cases with suitable memory settings.
There are some other failures in the log too.

**Comment by yurivict** [comment]
rev. 857ede32cca29528d3394766eba4c4c61d09a616 from 2021-11-18 still has 22 failures, see [log](https://people.freebsd.org/~yuri/nwchem-test-7.0.2.20211118.txt.)

**Comment by edoapra** [comment]
The new log seems acceptable to me.
All the failures are either on the last digit or from unreliable QA tests (that we should move at the bottom of the list)
