### ISSUE TITLE
Crash in monoatomic UHF calculation with minimal basis set

### ISSUE THREAD

**Issue by glowthrower** [nwchemgit/nwchem#480]
**Describe the bug**

The following monoatomic UHF calculation crashes:

```
echo
start

permanent_dir /path/to/permanent/dir
scratch_dir /path/to/scratch/dir

memory total 2 gb global 1 gb

geometry units angstrom noautoz noautosym
 S   0.0   0.0   0.0
end

basis cartesian
  S library STO-3G
end

scf
  uhf
  nopen 2
end
task scf energy
```

Running on a single MPI process, I see the following output:

```
...

 ----------------------------------------------
         Quadratically convergent UHF

 Convergence threshold     :          1.000E-04
 Maximum no. of iterations :           30
 Integral*density screening:          1.000E-07
 ----------------------------------------------


 #quartets = 1.200D+02 #integrals = 2.640D+02 #direct =  0.0% #cached =100.0%


 Integral file          = /path/to/scratch/dir/deck.aoints.0
 Record size in doubles =    65536    No. of integs per rec  =    43688
 Max. records in memory =        3    Max. records in file   = ********
 No. of bits per label  =        8    No. of bits per value  =       64


              iter       energy          gnorm     gmax       time
             ----- ------------------- --------- --------- --------
                 1     -393.1301816014  2.97D-02  2.10D-02      1.1
0:wrong dimension specified:Received an Error in Communication
Abort(-1) on node 0 (rank 0 in comm 496): application called MPI_Abort(comm=0x84000002, -1) - process 0
```

I would guess that this is related to the fact that this is a minimal basis set. I've tried with all the various STO-nG basis sets and all break. Similar calculations with larger basis sets (cc-pVDZ, etc.) complete successfully. 

I have tried various permutations of integral caching (e.g. `direct` and `semidirect ...` keywords in the `scf` task block), and they all fail.

**Describe settings used**

The output above comes from a fresh build of NWChem from the current head of the repo (commit aa3dfe2e339b). The build uses a recent version of the Intel compiler suite (oneAPI 2021.4). I can reproduce the exact same problem (modulo the precise formulation of the MPI "wrong dimension specified" error message) on several other older versions of NWChem, all built with various incarnations of the Intel compilers.

**To Reproduce**

Run the input deck given above, after modifying paths as appropriate.

**Comment by edoapra** [comment]
@glowthrower thanks for this bug report.
As a way to bypass this bug, you can use the dft code.
```
dft
 xc hfexch
 mult 3
 vectors output dft.mos
end
task dft
scf
  uhf
  nopen 2
  vectors input dft.mos
end
task scf energy
```

**Comment by glowthrower** [comment]
Thanks for the quick response!

Interesting workaround. It's not immediately clear to me what that does -- obviously it's reusing the KS coefficients, but I'm not sure I see how that helps?

**Comment by edoapra** [comment]
The bug is in hessian evaluation of the preconditioner for the conjugate gradient method (CG) used in `task scf` https://nwchemgit.github.io/Hartree-Fock-Theory-for-Molecules.html.  
`task dft` uses DIIS instead of CG.
The input above re-uses the molecular orbital converged in `task dft` as a guess for `task scf`. Since `task scf` detects that the molecular orbitals  are converged, GC is not used.  

The root cause of this problem is that with minimal basis set such as `STO-3G` the number of virtual orbitals is zero. The preconditioner allocates some quantities that are dependent on the size of the virtual orbitals.

Anyhow, a fix is now available (currently under testing) https://github.com/nwchemgit/nwchem/commit/e4843c8fa0cf9d489e0e070a1c67ce9a15018761

**Comment by glowthrower** [comment]
Great, thanks again for the super quick fix. :)

I'll leave this for you to close when you're happy with the fix.
