### ISSUE TITLE
small bug in updated GA

### ISSUE THREAD

**Issue by ebylaska** [nwchemgit/nwchem#489]
**Describe the bug**

The compilation seems to be consistently failing during the CI checking....

./ga-5.8.1/global/src/peigstubs.c:16:8: note: in expansion of macro ‘gai_diag_reuse_’
   16 | extern gai_diag_reuse_(Integer*,Integer*,Integer*,Integer*,DoublePrecision*);
      |        ^~~~~~~~~~~~~~~
  CC     global/src/sclstubs.lo
  CC     global/src/select.lo
  CC     global/src/sparse.lo
  CC     global/src/thread-safe.lo
  PPF77  global/src/complex.lo
  PPF77  global/src/ga_diag_seq.lo
  PPF77  global/src/ga_diag.lo
  PPF77  global/src/scalapack.lo
../ga-5.8.1/global/src/scalapack.F(2454): error #6404: This name does not have a type, and must have an explicit type.   [GA_DEALLOCATE]
      if (.not.ga_deallocate(g_b)) 
---------------^
../ga-5.8.1/global/src/scalapack.F(3125): error #6404: This name does not have a type, and must have an explicit type.   [GA_DEALLOCATE]
           if(.not.ga_deallocate(g_b))
-------------------^
../ga-5.8.1/global/src/scalapack.F(3405): error #6404: This name does not have a type, and must have an explicit type.   [GA_DEALLOCATE]
         if(.not.ga_deallocate(g_b))
-----------------^
compilation aborted for ../ga-5.8.1/global/src/scalapack.F (code 1)
make[4]: *** [Makefile:6851: global/src/scalapack.lo] Error 1
make[3]: *** [Makefile:7344: all-recursive] Error 1
make[2]: *** [Makefile:4066: all] Error 2
make[1]: *** [GNUmakefile:694: build/.libs/libga.a] Error 1
make[1]: Leaving directory '/home/runner/work/nwchem/nwchem/src/tools'
make: *** [GNUmakefile:105: libraries] Error 1
Error: Process completed with exit code 2.

**Comment by edoapra** [comment]
PR https://github.com/nwchemgit/nwchem/pull/490 should bypass this issue
