### ISSUE TITLE
Docs vs wiki?

### ISSUE THREAD

**Issue by ltalirz** [nwchemgit/nwchem#494]
**Is your feature request related to a problem? Please describe.**
Users visiting the nwchem github repository are redirected to the documentation on https://nwchemgit.github.io/.

However, I noticed that the [wiki](https://github.com/nwchemgit/nwchem/wiki) contains some information that is not present in the documentation.
For example, the [documentation on certain settings for printing 2-electron integrals](https://github.com/nwchemgit/nwchem/wiki/Quantum) seems to be present only in the wiki (I searched for `qorb` in the documentation and got 0 results).

I discovered the existence of the wiki only after searching for the term in the github-internal search.

**Describe the solution you'd like**
Some guidance on when to look in the wiki and when to look in the documentation would be useful (or a joining of both resources).

**Comment by jeffhammond** [comment]
I don't think the situation is perfect but it's easy to fix it if you want to contribute the fixes.

**Comment by ltalirz** [comment]
Hi @jeffhammond, thanks for your comment. 
So what is the current policy on what information goes into the wiki and what goes into the documentation? And what are you suggesting as a fix (document the policy?)?

**Comment by jeffhammond** [comment]
I don't know that there is a policy. I suspect each developer has their own intuition/preference on this. It may also depend on the methods of editing each. Editing Wiki online is easier, because it's WYSIWYG, whereas the doc edits may be a two-step process (I don't know for sure - I haven't edited docs in a while).

Anyways, I think the easiest thing to do is add what you think belong to the docs there, copying from the Wiki where appropriate.

**Comment by edoapra** [comment]
At this time, the mkdocs output in nwchemgit.github.io is manually generated. (I should write a github actions to automate it!).
Therefore, once the wiki pages are edited, the changes made it to nwchemgit.github.io only after the appropriate script is executed.

**Comment by edoapra** [comment]
The nwchemgit.github.io website has been updated with the latest changes.  
https://nwchemgit.github.io/Quantum.html

**Comment by ltalirz** [comment]
Thanks a lot, Edoardo, it's all clear now!

Feel free to close the issue, or to keep it open as a reminder until the deployment from the wiki is automated.
If you'd like any help with that, it might be useful to write down the necessary steps here, so perhaps someone else may be able to add the action.

**Comment by edoapra** [comment]
The github action https://github.com/nwchemgit/nwchem/actions/workflows/website_update.yml now runs once a day to deploy the wiki content to https://nwchemgit.github.io  
It is scheduled to run at around 4pm PST
