### ISSUE TITLE
Please add the install target

### ISSUE THREAD

**Issue by yurivict** [nwchemgit/nwchem#52]
I have to consult the ```package()``` procedure from the Arch port https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=nwchem-git

Normally makefile should install the package into ```$(DESTDIR)$(PREFIX)```, so that such question would not arise.

**Comment by edoapra** [comment]
Please provide more details about this issue since I am not sure I can understand it.
A practical example might help

**Comment by yurivict** [comment]
```make install``` should install the project. Currently there is no target ```install```.

**Comment by edoapra** [comment]
Contributions are welcome.

**Comment by jeffhammond** [comment]
We will need `make install` to install not just the binary but the basis set and pseudopotential library folders, although the latter paths are hard-coded into the binary prior to this step, so we need to add a level of indirection or rebuild the relevant object file to know about the installed path and relink the binary.  I've had to solve this problem manually enough times that I will try to work on the solution here.

Perhaps it would be better to deprecate the hard-coded library paths and move to using `nwchemrc` more.  We could put `nwchemrc` in `/usr/share/nwchem/` and have the binary look there first, followed by `~/.nwchemrc`.

**Comment by yurivict** [comment]
> Currently you can install .nwchemrc in /etc/nwchemrc to set this as a system wide default. That might help.

The problem that I observed with this is that ```nwchem``` attempts to open this file in R/W mode, and this can only succeed as root.

**Comment by edoapra** [comment]
@yurivict 
It's hard to believe that NWChem requires W mode for /etc/nwchemrc. Fedora RPMS are built installing /etc/nwchemrc in r--r--r-- mode and they seem to work fine
https://src.fedoraproject.org/rpms/nwchem/blob/master/f/nwchem.spec

**Comment by jeffhammond** [comment]
According to [GCC docs](https://gcc.gnu.org/onlinedocs/gcc-5.4.0/gfortran/Files-opened-without-an-explicit-ACTION_003d-specifier.html):
> The Fortran standard says that if an OPEN statement is executed without an explicit ACTION= specifier, the default value is processor dependent. 
Looking at `src/util/util_nwchemrc.F` line 108,
```fortran
        if (ipass.eq.1) then
          call util_getenv('HOME',home)
          nwchrc=home(1:inp_strlen(home))//'/.nwchemrc '
        elseif (ipass.eq.2) then
          nwchrc="/etc/nwchemrc"
        else
          return
        endif
        open(unit=69,file=nwchrc(1:inp_strlen(nwchrc)),
     +       form='formatted',status='old',err=9999)
```
the action is not specified.  Now, I would expect Linux builds to use GCC and thus succeed on the second attempt (`ACTION='READ'`) but perhaps we need to make it explicit.
