### ISSUE TITLE
nwchem no longer ignores the double definition of the subroutine dgefa

### ISSUE THREAD

**Issue by iswhy** [nwchemgit/nwchem#528]
**Describe the bug**
The subroutine `dgefa` is defined twice, found in `src/vscf/vscf.F` and `src/util/dgefa.f`.

**Describe settings used**
The environment variables for installation are

         export BLASOPT='-mkl'
         export NWCHEM_TARGET=LINUX64
         export NWCHEM_EXECUTABLE="$NWCHEM_TOP/bin/LINUX64/nwchem"
         export USE_MPI=y
         export MPI_F90=mpif90
         export MPI_CC=mpicc 
         export MPI_CXX=mpicxx
         export NWCHEM_MODULES="smallqm nwxc"`

**Attach log files**
The error message during compilation is

         $NWCHEM_TOP/lib/LINUX64/libvscf.a(vscf.o): In function `dgefa_':
         $NWCHEM_TOP/src/vscf/vscf.F:2304: multiple definition of `dgefa_'
         $NWCHEM_TOP/lib/LINUX64/libnwcutil.a(dgefa.o):dgefa.f:(.text+0x0): first defined here
         make: *** [link] Error 1

**Additional context**
I need `dgefa` to evaluate certain determinants for my application. Before I came to the point where I had to call `dgefa`, my nwchem package compiles just fine, i.e. it ignores the double definition of this routine. But now the program seems to always catch this error even after I comment out and exclude the codes that I write where the calls to dgefa are. I am using developer tool `renwc` to compile and install.

**Comment by edoapra** [comment]
You can use the following steps to patch your NWChem source:
```
cd $NWCHEM_TOP
wget https://github.com/nwchemgit/nwchem/commit/95f23e63dafd54194b1bc2b44cffefc85a4f5b49.patch
patch -p1 < 95f23e63dafd54194b1bc2b44cffefc85a4f5b49.patch
```

**Comment by iswhy** [comment]
Thank you for the quick response. My nwchem package now compiles successfully.
