### ISSUE TITLE
Compiling Problem: $NWCHEM_TOP/src/tools/build/config.h: No such file or directory

### ISSUE THREAD

**Issue by DaveIstanto** [nwchemgit/nwchem#55]
Hi, 

I have been trying to install NWCHEM, but after `make >& make.log`, the make.log file yields:
```
cat: /usr/local/apps/bioapps/nwchem/nwchem-6.8-release/src/tools/build/config.h: No such file or directory
NWChem's Performance is degraded by not setting BLASOPT
Please consider using ATLAS, GotoBLAS2, OpenBLAS, Intel MKL,
IBM ESSL, AMD ACML, etc. to improve performance.
If you decide to not use a fast implementation of BLAS/LAPACK,
please define USE_INTERNALBLAS=y and the internal Netlib will be used.
```
For this, I only set the environments as follows:
```
export NWCHEM_TOP=/usr/local/apps/bioapps/nwchem/nwchem-6.8-release
export NWCHEM_TARGET=LINUX64
cd $NWCHEM_TOP/src
export NWCHEM_MODULES=all
make nwchem_config
make >& make.log
``` 
I found a similar problem here: http://www.nwchem-sw.org/index.php/Special:AWCforum/st/id2500/NWChem_6.8_available_for_dowload.html
but the solution there did not work for me.

What is the suitable solution for this?

Thank you very much

**Comment by jeffhammond** [comment]
See https://github.com/nwchemgit/nwchem/wiki/Compiling-NWChem#optimized-math-libraries for how use better BLAS libraries.  If you want more specific assistance, please include your full platform info.

**Comment by jeffhammond** [comment]
OpenBLAS and BLIS are good open-source options for a wide range of processors.  BLIS is better if your processor supports Intel AVX-512 or is IBM Blue Gene.

MKL is free (as in beer) but of course does not support as many processor architectures as the open-source libraries: https://software.intel.com/en-us/articles/free-ipsxe-tools-and-libraries.

Full disclosure: I work for Intel and have a close relationship with the BLIS team.

**Comment by edoapra** [comment]
@DaveIstanto Did you manage to successfully compile NWChem?

**Comment by DaveIstanto** [comment]
@edoapra No I did not manage to successfully compile NWChem, and the installation was handed over to my colleague.

**Comment by edoapra** [comment]
Closed for lack of detailed feedback
