### ISSUE TITLE
NaN result in paw QA test with Intel OneAPI compilers and MKL libraries

### ISSUE THREAD

**Issue by edoapra** [nwchemgit/nwchem#567]
**Describe the bug**
Using either ifort or ifx with MKL libraries produces NaN results in the paw QA test

**Describe settings used**
Intel OneAPI ifort  2021.5.0 Build 20211109_000000 and Version 2022.0.0 Build 20211123.
MKL 2022.0.2.
Reproducible in Ubuntu 18.04 and 20.04. It might be happen on MacOS, too

**Attach log files**
```
Running tests/paw/paw 
 
     cleaning scratch
     copying input and verified output files
     running nwchem (/var/lib/gitlab-runner/builds/PH7zszVW/0/edoapra/nwchem/../binaries/nwchem_ifx)  with 3 processors 
 
     verifying output ... failed
@@@     Comparison of Output Files
@@ -2,6 +2,6 @@
 Total PSPW energy : -16.38760
 Total PAW energy : -75.80490
-Total PAW energy : -75.80490
+Total PAW energy : NaN
 Effective nuclear repulsion energy (a.u.) 8.73
-Total PAW energy : -75.80488
-Total PAW energy : -75.80490
+Total PAW energy : NaN
+Total PAW energy : NaN
 ```

**To Reproduce**
1. Steps to reproduce the behavior:
- compile NWChem with `FC=ifort` or  `FC=ifx` and
```
    BLAS_LIB: "   -lmkl_intel_ilp64 -lmkl_sequential -lmkl_core -lpthread -lm -ldl"
    LAPACK_LIB: " -lmkl_intel_ilp64 -lmkl_sequential -lmkl_core -lpthread -lm -ldl"
    SCALAPACK_LIB: " -lmkl_scalapack_ilp64 -lmkl_intel_ilp64 -lmkl_sequential -lmkl_core -lmkl_blacs_intelmpi_ilp64 -lpthread -lm -ldl"
   NWCHEM_MODULES='all'
```

- run the paw QA test
```
cd $NWCHEM_TOP/QA
./runtests.mpi.unix procs 2 paw
```

**Additional context**
~~Replacing MKL with `BUILD_OPENBLAS=1` seems to fix the problem.~~
Compiling a smaller build with `NWCHEM_MODULES='nwpw nwdft'` seems to fix the problem.

See forum entry
https://groups.google.com/g/nwchem-forum/c/TgnmfrxjS-M

**Comment by edoapra** [comment]
Related to https://github.com/nwchemgit/nwchem/issues/202

**Comment by nitinehpc** [comment]
The Classic Compiler support is still available but the user needs to check if the Xcode compatibility is right. The latest support is against Xcode 13.1 as documented [here](https://www.intel.com/content/www/us/en/developer/articles/system-requirements/oneapi-c-compiler-system-requirements.html).

**Comment by nitinehpc** [comment]
On Linux OS, be it Ubuntu OneAPI compilers work correctly. Please check the installation.

**Comment by edoapra** [comment]
Seems to be fixed with current Ifort and ifx
```
$ ifort -V
Intel(R) Fortran Intel(R) 64 Compiler Classic for applications running on Intel(R) 64, Version 2021.6.0 Build 20220226_000000
Copyright (C) 1985-2022 Intel Corporation.  All rights reserved.
```
  
```
$ ifx -V
Intel(R) Fortran Compiler for applications running on Intel(R) 64, Version 2022.1.0 Build 20220316
Copyright (C) 1985-2022 Intel Corporation. All rights reserved.
```
