### ISSUE TITLE
restart RT-TDDFT

### ISSUE THREAD

**Issue by MCOP47** [nwchemgit/nwchem#57]
Hello,

After running a simple RT-TDDFT simulation (NWChem 6.8) I am not able to continue the dynamics using the restart command. The idea is to use the restart command to extend the simulation time. Here I present a minimal example of the problem.

This is my first input file:

`title "Water TD-PBE0 absorption spectrum"
echo

start water

geometry "system" units angstroms nocenter noautoz noautosym
  O     0.00000000    -0.00001441    -0.34824012
  H    -0.00000000     0.76001092    -0.93285191
  H     0.00000000    -0.75999650    -0.93290797
end

set geometry "system"

basis
 * library 6-31G
end

dft
 xc pbe0
end

task dft energy

unset rt_tddft:*
rt_tddft
  tmax 3.0
  dt 0.2

  tag "kick_x"
  nchecks *
  nrestarts * 
  print * 

  field "kick"
    type delta
    polarization x
    max 0.0001
  end

  excite "system" with "kick"
 end
task dft rt_tddft
`
After running this file the water.db and water.movecs and water.rt_restart are created in the working directory. Then I run the following input file:

`
title "Water TD-PBE0 absorption spectrum"
echo
restart water

rt_tddft
  tmax 10.0
  dt 0.2

  tag "kick_x2"
  nchecks *
  nrestarts * 
  print * 
end

task dft rt_tddft
`
However, inspecting the output (eg dipole moment) it seems that the dynamics do not continue but instead it starts again from the beginning (but without the kick).

I appreciate any help. Thank you.

**Comment by ngovind** [comment]
Hi,  

Basically, for the restart phase, add a load restart in the rt block

rt_tddft
load restart
tmax 10.0
dt 0.2
tag "kick_x2"
nchecks *
nrestarts *
print *
end

Please try this and let me know. Thanks for reporting this. We will document this better.

Best,
-Niri
niri.govind@pnnl.gov

**Comment by MCOP47** [comment]
Thank you, it worked!

**Comment by ngovind** [comment]
closing this
