### ISSUE TITLE
nga_wait tracker

### ISSUE THREAD

**Issue by edoapra** [nwchemgit/nwchem#579]
This issue is to track `nga_wait_internal()` problems.  
Original issue from ga repository https://github.com/GlobalArrays/ga/issues/232
The following appears in the output file
```
nga_wait_internal: GA NB handle 123456789abc inactive slot:
```

### Related code changes
https://github.com/nwchemgit/nwchem/commit/abf8075e65c6ce9f47e7e461d1a1eb6626cc7cdf
https://github.com/nwchemgit/nwchem/commit/43bd44933135042f150207fe52afa15379cb6b84
https://github.com/nwchemgit/nwchem/commit/0ce606aa2f71b73cd240098c4d787c7a2b995995
https://github.com/nwchemgit/nwchem/commit/81c414c33a4fa2616176ff9543aed5ef2b5e6c83

**Comment by edoapra** [comment]
bug report in google forum
https://groups.google.com/g/nwchem-forum/c/z3vbAV4DIiQ/m/P-fyuU79CAAJ

**Comment by jeffhammond** [comment]
I'm 99% certain that's the issue I fixed this week. I think the user is following my recipe for ISC Student Cluster Challenge.

**Comment by edoapra** [comment]
> I'm 99% certain that's the issue I fixed this week. I think the user is following my recipe for ISC Student Cluster Challenge.

It's quite likely.

The idea of this issue is to keep track of this recurring curse.

**Comment by jeffhammond** [comment]
I should add a QA test for the OpenMP CCSD(T) and include a test for the NB wait warning.

**Comment by edoapra** [comment]
> I should add a QA test for the OpenMP CCSD(T) and include a test for the NB wait warning.

Done https://github.com/edoapra/nwchem/commit/60b77cc6fa57a5c1d698889705e1e44d01f32cbf
