### ISSUE TITLE
Problem when running nwchem

### ISSUE THREAD

**Issue by yuq** [nwchemgit/nwchem#62]
Hi,

I'm working on porting nwchem to AMD ROCm stack. But before any real coding, I tried to compile and run nwchem on Ubuntu 18.04 first. My build method:
> export NWCHEM_TOP=/rocm/nwchem-release/nwchem-6.8.1
> export USE_MPI=y
> export NWCHEM_TARGET=LINUX64
> export USE_PYTHONCONFIG=y
> export PYTHONVERSION=2.7
> export PYTHONHOME=/usr
> export BLASOPT="-lopenblas -lpthread -lrt"
> cd $NWCHEM_TOP/src
> make nwchem_config NWCHEM_MODULES="all python"
> make -j8

Then run a test by:
> cd $NWCHEM_TOP/examples/md/ache
> $NWCHEM_TOP/bin/LINUX64/nwchem mache

I got:
> MPI_ABORT was invoked on rank 0 in communicator MPI COMMUNICATOR 3 DUP FROM 0
> with errorcode 9999.

Attach the full output.
[log.txt](https://github.com/nwchemgit/nwchem/files/2430247/log.txt)

and see many new files in this dir:
> ALA.frg_TMP  ASN.frg_TMP  CYX.frg_TMP  GLU.frg_TMP    GLY.frg_TMP  HIE.frg_TMP  IP.frg_TMP  LEU.frg_TMP  mache_md.rst  mache.nw   MET.frg_TMP  PHE.frg_TMP  SER.frg_TMP    THR.frg_TMP  TYR.frg_TMP
> ARG.frg_TMP  ASP.frg_TMP  GLN.frg_TMP  GLU_N.frg_TMP  HID.frg_TMP  ILE.frg_TMP  job.db      LYS.frg_TMP  mache.nam     mache.pdb  out          PRO.frg_TMP  THR_C.frg_TMP  TRP.frg_TMP  VAL.frg_TMP

Anything wrong in my build/run step?

Thanks,
Qiang

**Comment by yuq** [comment]
And sometimes this kind of log:
>   0: pre_mkfrg failed 9999

[log.txt](https://github.com/nwchemgit/nwchem/files/2430254/log.txt)

**Comment by hjjvandam** [comment]
Hi,

Do you have an .nwchemrc file in your home directory. Normally you would get information about the parameter files that are being used for the force field parameters but I don’t see that in the output you provided. You should see some like:

Directories used for fragment and segment files

                                       /home/hvandam/nwchem-1-codar/QA/../src/data/amber_s/
                                       /home/hvandam/nwchem-1-codar/QA/../src/data/amber_x/
                                       /home/hvandam/nwchem-1-codar/QA/../src/data/amber_q/
                                       ./

And I don’t see anything listed below “Directories used for fragment and segment files”. If you don’t have an .nwchemrc file you can automatically generate one by running nwchem/QA/domknwchemrc. You can manually add more directories (if you need to) by looking at what is available under nwchem/src/data.

Best wishes,

     Huub

-----------------------------------------------------------------------------------------------------
Hubertus van Dam, 631-344-6020, hvandam@bnl.gov
Brookhaven National Laboratory

**Comment by hjjvandam** [comment]
Hi,

This error means that some atom types were not found in the force field parameter files. One possible reason for this is not having the .nwchemrc file, another reason might be that you are trying use an atom that is not specified in any of the directories listed in the .nwchemrc (i.e. you may have to add other directories from nwchem/src/data). Another reason might be that your input geometry suggests bonds between atoms that should not have bonds according to the connection definitions in the parameter files. You will have to check each of these possibilities in turn (in this order).

Best wishes,

    Huub

-----------------------------------------------------------------------------------------------------
Hubertus van Dam, 631-344-6020, hvandam@bnl.gov
Brookhaven National Laboratory

**Comment by yuq** [comment]
Hi Huub,

Thanks for your help. I did miss the .nwchemrc. After generating with the nwchem/QA/domknwchemrc, I can run some other test like examples/md/dna. But the examples/md/ache fail with different log:

> 0: Failed to create global array s    0

[log.txt](https://github.com/nwchemgit/nwchem/files/2430334/log.txt)

Thanks,
Qiang

**Comment by Straatsma** [comment]
Hi,

If the .nwchemrc paths are correctly setup, you see this error – as Huub indicated – if you have a molecular fragment that is not part of the database, and the generation of a new fragment file could not be completed because atom types were not found.

In these cases, a file frg_TMP is created with as much as the prepare module was able to define. This file is typically a good starting point to create the fragment file that you need.

Regards,

Dr. T. P. Straatsma
Oak Ridge Leadership Computing Facility
National Center for Computational Sciences
Oak Ridge National Laboratory
P.O.Box 2008, MS 6008
Oak Ridge, TN 37831-6373

Bldg 5600, A325
Tel. (865) 241-5864
Adm. (865) 574-0972
Fax. (865) 241-8484

**Comment by Straatsma** [comment]
Hi Qiang,

This error typically means that you do not have enough memory defined for the global arrays. On the memory card, increase the amount set aside for GA and most times this will resolve the issue.

Regards,

Dr. T. P. Straatsma
Oak Ridge Leadership Computing Facility
National Center for Computational Sciences
Oak Ridge National Laboratory
P.O.Box 2008, MS 6008
Oak Ridge, TN 37831-6373

Bldg 5600, A325
Tel. (865) 241-5864
Adm. (865) 574-0972
Fax. (865) 241-8484

**Comment by yuq** [comment]
Thanks for your info @Straatsma. Previously I run nwchem on a 6G mem PC, now I tried on 256G mem server, same error for examples/md/ache. Do I have to do other config operations to make nwchem to use more memory? And how much memory nwchem need?
