### ISSUE TITLE
Using the contrib getmem.nwchem during installation with non-gnu compiler

### ISSUE THREAD

**Issue by calmip** [nwchemgit/nwchem#623]
Hello

I just compiled nwchem with the intel compiler following the official documentation (see https://nwchemgit.github.io/Compiling-NWChem.html). At the end it is required to execute the contrib getmem.nwchem for fine tuning the memory requirements.

The script did not work because make was initially called with `make FC=ifort CC=icc`, but the getmem.nwchem script calls make without any parameter.

Thus I suggest the following modification to the script:

replace `make` with `make $*` (lines 95 and 97 in the script), and call getmem.nwchem with the same parameters as the previous make:
`../contrib/getmem.nwchem FC=ifort CC=icc`

Cheers,
Emmanuel

**Comment by edoapra** [comment]
@calmip Could you try the following with the unmodified script and see if it works for you?
The major difference is that you need to type the `FC` and `CC` definitions first.
Please use the `bash` shell ( if you are using another shell, just execute `bash`), then type the following
```
cd $NWCHEM_TOP/src
FC=ifort CC=icc ../contrib/getmem.nwchem
```

**Comment by calmip** [comment]
Hi edoapra
Of course it works ! No need to modify the script, just the documentation.

Thanks for your fast answer

Regards,
Emmanuel
