### ISSUE TITLE
Building NWChem on Windows

### ISSUE THREAD

**Issue by soundarthiaga** [nwchemgit/nwchem#643]
I noticed that the 7.0.2 release has a 64 bit windows executable

But I don't find any instructions on how to build it
Can I get the build instructions to reproduce the same executable

**Comment by edoapra** [comment]
I would rather not got through this extremely painful experience another time.
Since nwchem under WSL or docker is much faster, I would strongly recommend using either WSL or docker on recent 64-bit Windows.

**Comment by soundarthiaga** [comment]
But I need it for a specific test, so can you share the build instructions for a windows executable

**Comment by edoapra** [comment]
Could you share why you need a native WIn64 binary and you cannot use either WSL or docker?
