### ISSUE TITLE
d2h breaks fcidump

### ISSUE THREAD

**Issue by dunc-go** [nwchemgit/nwchem#645]
**Describe the bug**

When using FCIDUMP, which I appreciate is experimental, attempting to use a D2h molecule with the fcidump functionality writes:

 moints: MOs are symmetry contaminated                   0

The calculations show no sign of contamination, and converge quite well. Similarly, the FCIDUMP begins to write the file (first two lines), and then it seems to break when it tries to use D2h symmetry with the moints to write a label in the output.  Lower symmetry point groups seem to go through fcidump quite effectively, including adding appropriate irrep numbering. Higher symmetry label calculations also work with fcidump, but the symmetry labels in the .fcidump file are lost. This is reasonable as many codes seem to ignore this symmetry information and fine in my use case. The problem is that for D2h it just breaks. 

**Describe settings used**

Description:    CentOS Linux release 7.9.2009 (Core)
    nwchem branch   = 7.0.0
    nwchem revision = 81399a6

**Attach log files**
output attached 
[diborane_breaking.txt](https://github.com/nwchemgit/nwchem/files/9525288/diborane_breaking.txt)

**To Reproduce**
Run below input on current master branch

echo
start diborane_sym_fcidump

geometry units ang 
B       0.8880800       0.0000000       0.0000000
B       -0.8880800      0.0000000       0.0000000
H       0.0000000       0.0000000       0.9765560
H       0.0000000       0.0000000       -0.9765560
H       1.4621200       1.0430020       0.0000000
H       1.4621200       -1.0430020      0.0000000
H       -1.4621200      1.0430020       0.0000000
H       -1.4621200      -1.0430020      0.0000000
end

basis "ao basis"
 * library sto-3g
end

dft
xc hfexch
end

task dft

fcidump
 orbitals molecular
end

task dft fcidump

**Expected behavior**
It writes an fcidump file either with or without symmetry information

Possible quick fix (as fcidump is experimental), is to add a symmetry (on | off) option in the fcidump block so that it doesn't try to write labels > 1 but you can still use symmetries in the HF calculation to get symmetrised MOs

**Comment by dunc-go** [comment]
Same occurs for C2v symmetric molecules

**Comment by edoapra** [comment]
@dunc-go you can add the line `set fourindex:osym t` to disable symmetry.
```
fcidump
orbitals molecular
end

set fourindex:osym t

task dft fcidump
```

**Comment by dunc-go** [comment]
Hi Edo, thanks for addressing, I saw your commits and have been using this where necessary - all seems to work
