### ISSUE TITLE
Docs on print resolve to home page

### ISSUE THREAD

**Issue by chchang6** [nwchemgit/nwchem#65]
From https://github.com/nwchemgit/nwchem/wiki/Top-level, the PRINT / NOPRINT link just appears to return to the front page https://github.com/nwchemgit/nwchem/wiki.

**Comment by jeffhammond** [comment]
I just submitted a pull request to fix this.

**Comment by edoapra** [comment]
@chchang6 
Thanks for the feedback.
Jeff has fixed the wiki problem
Cheers, Edo
