### ISSUE TITLE
AIMD simulation of CO

### ISSUE THREAD

**Issue by koroki** [nwchemgit/nwchem#650]
I need to do some AIMD simulations of CO. However, it is not possible with nwchem due to an incorrect degree of freedom calculation (I guess). When I tried, this error appear:

`qmd_driver:                     ndeg<=0                   1`

`There is an error related to the specified geometry`

I'm using  the version 7.0.2 of nwchem

**Comment by edoapra** [comment]
You need to supply the `qmd` input option `linear` 
https://nwchemgit.github.io/Gaussian-Basis-AIMD.html#linear-flag-for-linear-molecules
```
qmd
  linear
end
```

**Comment by koroki** [comment]
Thanks!!! I supposed that it goes in that direction, but I did not think that it was an option for it. My mistake. Thanks.
