### ISSUE TITLE
`c240_631g`: configuration error 

### ISSUE THREAD

**Issue by lalith-mcw** [nwchemgit/nwchem#663]
**Bug**
Error with c240_631g configuration with mpi there are errors
When ran without mpi the execution just hangs after this step
`Sum of atomic energies:       -9038.46098946`

**Settings used**
Couldn't find the library in this repo so used, the ao Basis for C (Carbon) from [6-31G(d,p)](https://www.basissetexchange.org/)

**Command used to run the program (Ran in windows)**
`mpiexec.exe -np 64 --map-by l3cache nwchem.exe c240_631gs.nw`

**Attach log files**
[Input_Output.zip](https://github.com/nwchemgit/nwchem/files/9748326/Input_Output.zip)

**Expected behavior**
Want to replicate the output present in `c240_631gs.out` in this repo

**Comment by edoapra** [comment]
You seem to be running the NWCHem Win64 binary, isn't it?
If this is the case, that binary is not intended for production runs.
If you do use  Windows 10/11, please use NWChem from WSL or Docker, instead.
