### ISSUE TITLE
HAM is written at every step in NAMD

### ISSUE THREAD

**Issue by koroki** [nwchemgit/nwchem#671]
As I commented in a previous bug report, I'm working with NAMD.
Using NWChem 7.0.2 in a 64linux machine, the HAM (I suppose the electronic Hamiltonian) is written at every step. For that reason, every NAMD generates a huge files...

Can we have an option to disable this writing?

**Comment by edoapra** [comment]
Could you upload the input file to complete the bug report?

**Comment by koroki** [comment]
The input

```
start NO_MD-02
MEMORY total 24 gb
print low
#geometry units angstrom nocenter noautoz noautosym
geometry units angstrom noautosym
O	-0.00456199	-0.00522688	-1.13891752	0.00000098	0.00000113	0.00012945
N	0.01493104	0.01710294	0.07955290	-0.00000065	-0.00000074	-0.00010848
N	-0.00972016	-0.01113258	1.22209705	-0.00000048	-0.00000055	-0.00003939
end


basis  
 * library 6-31G**
end 

dft
  xc B3LYP
  grid nodisk
#  odft
end

tddft
  nroots 380
#  triplet
  notriplet
  cis
  civecs
  grad
    root 341
  end
end

qmd
  nstep_nucl 5000
  dt_nucl 0.5
  thermostat none
  namd 
    nstates 370
    init_state 341
    dt_elec 0.1
    deco .false.
#    tdks
  end
end

task tddft qmd
```

**Comment by koroki** [comment]
> 

It is the output of the program. It is written just after the gradient.

**Comment by edoapra** [comment]
Commit https://github.com/nwchemgit/nwchem/commit/a78eaf24b29de4b94b0f322c5a5848c36db46bb7 fixes this issue

**Comment by koroki** [comment]
Thanks!
