### ISSUE TITLE
Installation, QA tests

### ISSUE THREAD

**Issue by lachlanbelcher** [nwchemgit/nwchem#672]
**Describe the bug**
Fresh download of NWChem.  Compiled fine with given build_env.  When running doqmtests.mpi, I receive the message "NWChem execution failed" after each test (see doqmtests.log)

**Describe settings used**
Report all the environment variables used.
Report what operating system and distribution you are using.
setenv NWCHEM_EXECUTABLE "~/nwchem/bin/LINUX64/nwchem"
setenv MPIRUN_PATH "/p/app/hpe/mpt-2.21/bin/mpirun"
setenv MPIRUN_NPOPT -np
setenv NWCHEM_TOP "/p/home/lbelcher/nwchem"
setenv NWCHEM_TARGET "LINUX64"

Running on HPE SGI 8600 (Koehr) "Koehr is an HPE SGI 8600 system located at the Navy DSRC. It has 704 standard compute nodes, 16 large-memory nodes, and 32 GPU-accelerated nodes (a total of 752 compute nodes or 36,096 compute cores). It has 154 TB of memory and is rated at 3.05 peak PFLOPS"

**Attach log files**
Attach as many log files as possible.
* stdout/stderr of the NWChem execution
* complete makefile log
* $NWCHEM_TOP/src/tools/build/config.log
* $NWCHEM_TOP/src/tools/build/comex/config.log
* debugging stack
* 
Since .out files are not allowed to be attached, I am renaming one of the test outputs to a .txt file as an example
[doqmtests.log](https://github.com/nwchemgit/nwchem/files/9813540/doqmtests.log)
[my_test_script.txt](https://github.com/nwchemgit/nwchem/files/9813545/my_test_script.txt)
[build_env.txt](https://github.com/nwchemgit/nwchem/files/9813547/build_env.txt)
[5h2o_core.ok.out.txt](https://github.com/nwchemgit/nwchem/files/9813554/5h2o_core.ok.out.txt)
[make_0.log](https://github.com/nwchemgit/nwchem/files/9813576/make_0.log)
[config.log](https://github.com/nwchemgit/nwchem/files/9813573/config.log)
[comex.config.log](https://github.com/nwchemgit/nwchem/files/9813572/comex.config.log)

**To Reproduce**
1. Steps to reproduce the behavior:
execute doqmtests.mpi 1 fast > doqmtests.log (I used my_test_script, attached, but that would only be valid on Koehr)
2. Attach all the input files required to run.

**Expected behavior**
I expected that the tests would pass

**Screenshots**

**Additional context**

**Comment by lachlanbelcher** [comment]
Thanks for the heads up.  I recompiled without python, which seems to have
been the problem.  I have attached the current make log, the build_env
file, and the current doqmtests.log.

**Comment by lachlanbelcher** [comment]
Looking at the latest make log, it appears that there are many "undefined references" to subroutines such as ycopy, ysymv, yaxpy, yscal, iyamax, and ygemv.  Should these be defined somewhere?
[make_0.log](https://github.com/nwchemgit/nwchem/files/9825196/make_0.log)

**Comment by jeffhammond** [comment]
those symbols are required when one does a 64-to-32 build.  see https://nwchemgit.github.io/Compiling-NWChem.html#how-to-deal-with-integer-size-of-linear-algebra-libraries for docs.

**Comment by edoapra** [comment]
> Looking at the latest make log, it appears that there are many "undefined references" to subroutines such as ycopy, ysymv, yaxpy, yscal, iyamax, and ygemv. Should these be defined somewhere? [make_0.log](https://github.com/nwchemgit/nwchem/files/9825196/make_0.log)

Have you typed 
```
make 64_to_32
```
?
This step is not necessary when you are using ILP64 64-bit integer libraries.
Anyhow, the quickest fix for this is to set `USE_64TO32=1` and recompile.
```
export USE_64TO32=1
cd $NWCHEM_TOP/src/64to32
make FC=ifort
cd ..
make FC=ifort link
```

**Comment by lachlanbelcher** [comment]
Ok, thanks.  adding that flag seems to have solved the compilation error for now.
