### ISSUE TITLE
incorrect gradient for pure TDA-TDDFT calculations

### ISSUE THREAD

**Issue by david-mester** [nwchemgit/nwchem#698]
Dear Developers,
I've just found a strange behaviour for TDA-TDDFT gradient calculations. In my opinion, a factor of 2 is missing for the H^+[X] transformation if pure TDDFT functionals are requested. Please find the attached input and output files. The test2.nw input file is tested against Turbomole, and it gives the correct results. 

[tddft_bug.zip](https://github.com/nwchemgit/nwchem/files/10103943/tddft_bug.zip)

**Comment by edoapra** [comment]
@david-mester thanks for the detailed bug report

**Comment by edoapra** [comment]
@david-mester This bug has now been fixed both in the master and releas-7-2-0 branches
