### ISSUE TITLE
moldenfile property bug when symmetry and linear dependencies are present

### ISSUE THREAD

**Issue by edoapra** [nwchemgit/nwchem#7]
When symmetry is present and basis set exhibits linear dependencies, the calculation crashes or computes a wrong molden output. See attached input file.

Workaround: use "molden" keyword in dft section to dump molden file during the dft energy task.

Reproducer input file
```
start ch4_janpa

geometry
 symmetry td
 C     0.000000     0.000000     0.000000
 H    -0.1800000    0.1800000    0.18
end

basis "ao basis" spherical
 * library aug-cc-pvdz
end

task dft

property
  moldenfile
  molden_norm janpa
end
task dft property

```
Workaround input file
```
start ch4_janpa

geometry
 symmetry td
 C     0.000000     0.000000     0.000000
 H    -0.1800000    0.1800000    0.18
end

basis "ao basis" spherical
 * library aug-cc-pvdz
end
dft
 molden
end
set molden:do_norm_janpa t
task dft
```

**Comment by edoapra** [comment]
More testing needed for commit https://github.com/nwchemgit/nwchem/commit/3ad1a3c94a5dea466e3cea8bd5499c6cdec42bd9

**Comment by nwchemgit** [comment]
test files mentioned in the following NWChem forum entry work correctly with hotfix/release-6-8 

http://www.nwchem-sw.org/index.php/Special:AWCforum/st/id2511/

**Comment by edoapra** [comment]
New commit d2b0350177c552e6c39c46f3cbfa2e1dd0e4e28d (pushed to master and hotfix/release-6-8) fixes all my remaining molden test cases
