### ISSUE TITLE
Compile fail: offl_mic_ccsd_t_singles_l_1 not found in offl_ccsd_t_singles_l

### ISSUE THREAD

**Issue by yuq** [nwchemgit/nwchem#70]
offl_mic_ccsd_t_singles_l_1 is build only when USE_OFFLOAD is defined, but offl_ccsd_t_singles_l will call it no matter USE_OFFLOAD is defined. So when USE_OFFLOAD is not defined, linker will report offl_mic_ccsd_t_singles_l_1 is not found.

**Comment by edoapra** [comment]
@yuq  COuld you please add more details to this bug report?
Please report the full log of the compilation error(s) and the env. variables that your have defined

**Comment by yuq** [comment]
Actually I'm porting NWChem to HIP, compile script:
> export NWCHEM_TOP=/home/yuq/nwchem/nwchem
> export USE_MPI=y
> export NWCHEM_TARGET=LINUX64
> export USE_PYTHONCONFIG=y
> export PYTHONVERSION=2.7
> export PYTHONHOME=/usr
> export BLASOPT="-lopenblas -lpthread -lrt"
> export TCE_HIP=y
> export HIP_INCLUDE="-I/opt/rocm/hip/include"
> 
> cd $NWCHEM_TOP/src
> make nwchem_config NWCHEM_MODULES="all python"
> make -j24

My OS is Ubuntu 16.04.

TCE_HIP is equivalent to TCE_CUDA. I meet the link error, then just read the code and find it's related with USE_OFFLOAD as explained above.

Error log:
> /tmp/tmp.uvRsBD3eKJ/libtce.a/offl_ccsd_t_singles_l.o: In function `offl_ccsd_t_singles_l_':
> offl_ccsd_t_singles_l.F:(.text+0x5b6): undefined reference to `offl_mic_ccsd_t_singles_l_1_'
> clang-7: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by jeffhammond** [comment]
@yuq Are you compiling for Intel Xeon Phi x100 series coprocessors?  Which Intel compiler version are you using?

**Comment by edoapra** [comment]
@yuq the current version of the TCE code calls  offl_ccsd_t_singles_l() ONLY when USE_OFFLOAD is defined. 
Please look at file ccsd_t.F at line 412.F
https://github.com/nwchemgit/nwchem/blob/master/src/tce/ccsd_t/ccsd_t.F
That's why we never have a linker failure when USE_OFFLOAD is not defined

**Comment by yuq** [comment]
@jeffhammond I'm compiling using gfortran (5.4.0) and on AMD EPYC processor.

@edoapra so you mean if offl_ccsd_t_singles_l() is not called, it will be dropped when link stage? Seems it depends on the linker, because in my case (use AMD HIP compiler as the linker), it complains the missing of the offl_mic_ccsd_t_singles_l_1 even offl_ccsd_t_singles_l() is not called.

How about fix this by conditionally build offl_ccsd_t_singles_l.F and offl_ccsd_t_singles_l_1.F by USE_OFFLOAD?

**Comment by edoapra** [comment]
@yuq I am really puzzled by the behavior of linker you are using.
Anyhow, you can try to patch your $NWCHEM_TOP/src/tce/ccsd_t/GNUmakefile by trying the attached
[tco.patch.gz](https://github.com/nwchemgit/nwchem/files/2520118/tco.patch.gz)  patch.
To compile, after applying do the following
* cd $NWCHEM_TOP/src/tce/ccsd_t
* make clean
* cd $NWCHEM_TOP
* patch -p1 < tco.patch 
*  cd $NWCHEM_TOP/src/tce/ccsd_t
* make
* cd ../..
* make link
```

**Comment by yuq** [comment]
Thanks, this patch works for me:
[0001-fix-link-time-symbol-not-found.txt](https://github.com/nwchemgit/nwchem/files/2521314/0001-fix-link-time-symbol-not-found.txt)

Can this patch be integrated to upstream NWChem code base?

**Comment by yuq** [comment]
Thanks for fixing this.

**Comment by edoapra** [comment]
@yuq Sure, thanks for your valuable feedback
