### ISSUE TITLE
help for running nwchem

### ISSUE THREAD

**Issue by hnile** [nwchemgit/nwchem#71]
Recently, I compiled nwchem6.8 according to the documentation, and the binnary nwchem was obtained. however, when I ran for a simple test, the problem happened. I don't know what is it because of ,compling or others? 
   the install script  is as follow:
module load intel/composer_xe_2015.2.164
module load mpi/intelmpi/5.0.2.044
export NWCHEM_TOP=/home/hnile/apps/nwchem/nwchem-6.8/gfort_intelmpi_mkl_64
export NWCHEM_TARGET=LINUX64
export ARMCI_NETWORK=MPI-MT

export USE_MPI=y
export USE_MPIF=y
export USE_MPIF4=y
export PATH=/apps/mpi/intelmpi/5.0.2.044/intel64/bin:$PATH
export NWCHEM_MODULES="all python"
export USE_NOFSCHECK=TRUE
export USE_NOIO=TRUE
#export LIB_DEFINES=-DDFLT_TOT_MEM= 
export MRCC_METHODS=TRUE

export PYTHONHOME=/usr
export PYTHONVERSION=2.7
export PYTHONCONFIG=Y
export USE_PYTHON64=y
export PYTHONLIBTYPE=so

export BLASOPT="-L/apps/compiler/intel/composer_xe_2015.2.164/mkl/lib/intel64 -lmkl_lapack95_ilp64 -lmkl_blas95_ilp64 -lmkl_intel_ilp64 -lmkl_intel_thread -lmkl_sequential -lmkl_core -liomp5 -lpthread -lm -ldl"
export USE_SCALAPACK=y
export SCALAPACK="-L/apps/compiler/intel/composer_xe_2015.2.164/mkl/lib/intel64 -lmkl_scalapack_ilp64 -lmkl_intel_ilp64 -lmkl_intel_thread -lmkl_core -lmkl_blacs_intelmpi_ilp64 -liomp5 -lpthread -lm -ldl"

cd $NWCHEM_TOP/src
make realclean
make nwchem_config &> config.log
make &> make.log
 
my input of h2o.nw for a simple test is as follow:
start h2o
 title "Water in 6-31g basis set"

 geometry units au
   O      0.00000000    0.00000000    0.00000000
   H      0.00000000    1.43042809   -1.10715266
   H      0.00000000   -1.43042809   -1.10715266
 end
 basis
   H library 6-31g
   O library 6-31g
 end
 task scf

the error message is as follow:
Forming initial guess at       0.0s

 !! The overlap matrix has   7 vectors deemed linearly dependent with
    eigenvalues:
 0.00D+00 0.00D+00 0.00D+00 2.40-315 9.49-322 4.94-323 9.88-324

      Superposition of Atomic Density Guess
      -------------------------------------

 Sum of atomic energies:         -75.75081731
 ------------------------------------------------------------------------
 ga_orthog: hard zero                   1
 ------------------------------------------------------------------------
 ------------------------------------------------------------------------
  current input line :
    13:  task scf
 ------------------------------------------------------------------------
 ------------------------------------------------------------------------
 This error has not yet been assigned to a category
 ------------------------------------------------------------------------
 For more information see the NWChem manual at http://www.nwchem-sw.org/index.php/NWChem_Documentation

 For further details see manual section: No section for this category 

who could tell me what is the matter ?

**Comment by edoapra** [comment]
you need SCALAPACK_SIZE=8 and BLAS_SIZE=8 since you have chose the ilp64 MKL libraries

**Comment by hnile** [comment]
thanks for your reply. the above problem has been sloved.
