### ISSUE TITLE
Help needed to compile nwchem 7.2.0, without internet access, linking to existing libxc

### ISSUE THREAD

**Issue by marcindulak** [nwchemgit/nwchem#723]
**Is your feature request related to a problem? Please describe.**

Help needed with compiling nwchem without internet access, linking to existing libxc.

I'm trying to build RPMS of the upcoming 7.2.0 version https://github.com/nwchemgit/nwchem/commit/550861dc52e6873f4198564bc6dbfed57957011b for fedora 38.
The official fedora packages:
1. Don't allow for downloading of sources from the internet during the build https://fedoraproject.org/wiki/Packaging:What_Can_Be_Packaged#Packages_which_are_not_useful_without_external_code
2. Discourage bundling of libraries (compiling external libraries during the process of nwchem compilation and linking with them) https://docs.fedoraproject.org/en-US/packaging-guidelines/#bundling

Until now, I encountered problems with:
1. libxc
```
Making all in libxc
make[2]: Entering directory '/builddir/build/BUILD/nwchem-550861dc52e6873f4198564bc6dbfed57957011b/src/libext/libxc'
GNUmakefile:16: warning: overriding recipe for target 'clean'
../../config/makelib.h:310: warning: ignoring old recipe for target 'clean'
./build_libxc.sh
downloading libxc-6.1.0.tar.gz
curl: (6) Could not resolve host: gitlab.com
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
^M  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: github.com
libxc download failed
make[2]: *** [GNUmakefile:9: install/lib/libxc.a] Error 1
make[2]: Leaving directory '/builddir/build/BUILD/nwchem-550861dc52e6873f4198564bc6dbfed57957011b/src/libext/libxc'
```
2. dftd3
```
Compiling nwpwxc_cs00.F...
./build_dftd3a.sh
downloading dftd3.tgz
chchc curl -f -L https://www.chemiebn.uni-bonn.de/pctc/mulliken-center/software/dft-d3//dftd3.tgz -o dftd3.tgz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: www.chemiebn.uni-bonn.de
attempt no. 5
download failed
make[4]: *** [GNUmakefile:36: nwpwxc_vdw3a.F] Error 1
make[4]: Leaving directory '/builddir/build/BUILD/nwchem-550861dc52e6873f4198564bc6dbfed57957011b/src/nwpw/nwpwlib/nwpwxc'
make[3]: *** [../../../config/makelib.h:146: optimized] Error 2
```

Example (failed) attempt:
```
export NWCHEM_TARGET=LINUX64
export CC=gcc
export FC=gfortran
export USE_ARUR=TRUE
export USE_LIBXC=-1
export USE_NOFSCHECK=TRUE
export USE_NOIO=TRUE
export NWCHEM_FSCHECK=N
export LARGE_FILES=TRUE
export MRCC_THEORY=Y
export EACCSD=Y
export IPCCSD=Y
export CCSDTQ=Y
export CCSDTLR=Y
export NWCHEM_LONG_PATHS=Y
export LIBXC_LIB='-L/usr/lib64 -lxc -lxcf90'
export LIBXC_INCLUDE='/usr/include'
export HAS_BLAS=yes
export BLASOPT='-L/usr/lib64 -lflexiblas'
export BLAS_SIZE='4'
export LAPACK_LIB='-L/usr/lib64 -lflexiblas'
export MAKE=/usr/bin/make
export USE_MPI=y
export USE_MPIF=y
export USE_MPIF4=y
export MPIEXEC=/usr/lib64/openmpi/bin/mpiexec
export LD_LIBRARY_PATH=/usr/lib64/openmpi/lib
export EXTERNAL_GA_PATH=/usr/lib64/openmpi
$MAKE nwchem_config NWCHEM_MODULES="all python" 2>&1 | tee ../make_nwchem_config_openmpi.log
$MAKE 64_to_32 2>&1 | tee ../make_64_to_32_openmpi.log
export MAKEOPTS="USE_64TO32=y"
$MAKE ${MAKEOPTS} 2>&1
```

**Describe the solution you'd like**

The build system of nwchem allows compilation without internet access, and linking to libraries already present on the system. Optionally, documentation for the build options to achieve it.

**Describe alternatives you've considered**

Including libxc archive together with nwchem source (bundle libxc).

**Additional context**

This feature requests is similar in nature to https://github.com/nwchemgit/nwchem/issues/28

**Comment by edoapra** [comment]
* The solution for libxc is already there, as described in https://nwchemgit.github.io/Interfaces-with-External-Software.html#libxc
`USE_LIBXC` needs to be unset, while `LIBXC_LIB` and `LIBXC_INCLUDE` needs to point to the location of the libxc header and libraries files, respectively.
* Instead, the only short term solution for dftd3 is to provide the possibility of stubbing the functionality when neither internet connectivity is present nor the dftd3 source is available. We cannot include the dftd3 source in NWChem because of license incompatibility.

**Comment by marcindulak** [comment]
## Remaining issue 1

Using https://github.com/nwchemgit/nwchem/commit/ceeecfa6234a20f0ea2625a5c24d68907bfd90a0.

The `LIBXC_INCLUDE="/usr/include -I/usr/lib64/gfortran/modules"` setting mentioned at https://nwchemgit.github.io/Interfaces-with-External-Software.html#libxc may be incompatible with https://github.com/nwchemgit/nwchem/blob/ceeecfa6234a20f0ea2625a5c24d68907bfd90a0/src/nwdft/libxc/GNUmakefile#L20

I'm getting the following error, also reproduced locally
```
LIBXC_INCLUDE='/usr/include -I/usr/lib64/gfortran/modules'
grep XC_MAJOR_VERSION ${LIBXC_INCLUDE}/xc_version.h |cut -d " " -f 3
grep: invalid option -- '/'
Usage: grep [OPTION]... PATTERNS [FILE]...
Try 'grep --help' for more information.
```

Setting `LIBXC_INCLUDE='/usr/include'` works for that block
```
LIBXC_INCLUDE='/usr/include'
grep XC_MAJOR_VERSION ${LIBXC_INCLUDE}/xc_version.h |cut -d " " -f 3
5
```
but the location of gfortran modules is then unknown, and results in another error
```
make[2]: Entering directory '/builddir/build/BUILD/nwchem-ceeecfa6234a20f0ea2625a5c24d68907bfd90a0/src/nwdft/libxc'
egrep: warning: egrep is obsolescent; using grep -E
Compiling nwchem_libxc_read.F...
nwchem_libxc_read.F:5:10:
    5 |       use xc_f03_lib_m
      |          1
Fatal Error: Cannot open module file 'xc_f03_lib_m.mod' for reading at (1): No such file or directory
compilation terminated.
```

```
ls /usr/lib64/gfortran/modules/
mpich  openmpi  xc_f03_lib_m.mod  xc_f90_lib_m.mod
```

## Potential issue 2

Another issue arises in the fork https://github.com/edoapra/nwchem/commit/ec34b971e179bf9f7c5d9db2b00786c5b721fe3a as compared to https://github.com/nwchemgit/nwchem/commit/ceeecfa6234a20f0ea2625a5c24d68907bfd90a0. The fork contains [src/NWints/sifs](https://github.com/edoapra/nwchem/tree/ec34b971e179bf9f7c5d9db2b00786c5b721fe3a/src/NWints/sifs) directory and produces an error as below. This may become an issue when sifs gets into the main branch.
```
make[2]: Entering directory '/builddir/build/BUILD/nwchem-ec34b971e179bf9f7c5d9db2b00786c5b721fe3a/src/NWints/sifs'
GNUmakefile:38: warning: overriding recipe for target 'cleanF'
../../config/makelib.h:336: warning: ignoring old recipe for target 'cleanF'
./build_sifs.sh
./build_sifs.sh: line 4: wget: command not found
attempt no. 1
./build_sifs.sh: line 4: wget: command not found
attempt no. 2
./build_sifs.sh: line 4: wget: command not found
attempt no. 3
./build_sifs.sh: line 4: wget: command not found
attempt no. 4
./build_sifs.sh: line 4: wget: command not found
attempt no. 5
./build_sifs.sh: line 4: wget: command not found
attempt no. 6
./build_sifs.sh: line 4: wget: command not found
attempt no. 7
./build_sifs.sh: line 4: wget: command not found
attempt no. 8
./build_sifs.sh: line 4: wget: command not found
attempt no. 9
./build_sifs.sh: line 4: wget: command not found
attempt no. 10
tar (child): columbus-master.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
find: 'columbus-master*s': No such file or directory
mv: missing destination file operand after '.'
Try 'mv --help' for more information.
```

**Comment by edoapra** [comment]
I will try to address the first issue.
Issue #2 exists only in the master branch. Please stick to the release-7-2-0. The release 7-2-0 branch now contains the fix for nwpwxc/dftd3

**Comment by edoapra** [comment]
Please use the latest `release-7-2-0` branch and the following settings
```
    unset USE_LIBXC
    export LIBXC_LIB=/usr/lib64
    export LIBXC_INCLUDE=/usr/include 
    export LIBXC_MODDIR=/usr/lib64/gfortran/modules
```
