### ISSUE TITLE
Failure of NEB initial structure generation using HASMIDDLE

### ISSUE THREAD

**Issue by baba-hashimoto** [nwchemgit/nwchem#734]
**Describe the bug**
When using HASMIDDLE in the NEB, the calculation fails in the generation of the initial structure and the calculation terminates abnormally.

**Describe settings used**
    source          = /home/nwchem-7.0.2
    nwchem branch   = 7.0.2
    nwchem revision = N/A
    ga revision     = 5.7.2
    use scalapack   = T
    input           = NEB_anti.nw
    prefix          = NEB_anti.
    data base       = ./NEB_anti.db
    status          = startup
    nproc           =        1
    time left       =     -1s

           Memory information
           ------------------

    heap     =   26214400 doubles =    200.0 Mbytes
    stack    =   26214397 doubles =    200.0 Mbytes
    global   =   52428800 doubles =    400.0 Mbytes (distinct from heap & stack)
    total    =  104857597 doubles =    800.0 Mbytes
    verify   = yes
    hardfail = no

**Attach log files**
Attach as many log files as possible.
NEB_anti.tar.gz

**To Reproduce**

source /raidx/intel/v2023/setvars.sh
export LANG=C
date
pwd

mpirun -n 2 /home/nwchem-7.0.2/install_dir/bin/nwchem NEB_anti.nw  > NEB_anti.out 2>&1

**Expected behavior**
The third coordinate in NEB_anti.neb_intial.xyz describes the coordinates listed in midgeom.

[NEB_anti.tar.gz](https://github.com/nwchemgit/nwchem/files/10681653/NEB_anti.tar.gz)

**Comment by edoapra** [comment]
Could you specify which output file  contains the error message relative to the abnormal termination?
What is the the specific error message?

**Comment by baba-hashimoto** [comment]
Sorry, maybe I did not express myself properly.
There is an IMAGE in NEB_anti.out that has Infinity energy. Details are as follows.
  convergence    iter        energy       DeltaE   RMS-Dens  Diis-err    time
 ---------------- ----- ----------------- --------- --------- ---------  ------
 d= 0,ls=0.0,diis     1          Infinity -5.66D+03  2.59D-13  3.16D-01   106.5
 Grid integrated density:       9.876253358098
 Requested integration accuracy:   0.10E-05

You can see why Energy becomes Infinity by looking at the coordinate data in NEB_anti.neb_intial.xyz.

                    20
 energy=  0.000000000000000E+000
N          -0.000000    0.000000    0.000000
C           0.000000    0.000000    0.000000
C           0.000000   -0.000000    0.000000
H           0.000000    0.000000    0.000000
H           0.000000   -0.000000   -0.000000
H           0.000000    0.000000    0.000000
C           0.000000    0.000000    0.000000
C           0.000000    0.000000    0.000000
C           0.000000   -0.000000    0.000000
C           0.000000   -0.000000    0.000000
C           0.000000    0.000000    0.000000
C           0.000000    0.000000    0.000000
H           0.000000    0.000000    0.000000
H           0.000000    0.000000    0.000000
H           0.000000    0.000000    0.000000
H           0.000000   -0.000000    0.000000
H           0.000000   -0.000000    0.000000
O           0.000000    0.000000    0.000000
H           0.000000    0.000000    0.000000
H          -0.000000    0.000000    0.000000

If midgeom is not used, the NEB_anti.neb_intial.xyz is created normally and the calculation begins. Therefore, I posted this because I thought there might be a bug in the initial structure generation of the NEB.

**Comment by edoapra** [comment]
This seems a bug in NEB.
It you use the [Zero Temperature String Method](https://nwchemgit.github.io/Nudged-Elastic-Band-and-Zero-Temperature-String-Methods.html#zero-temperature-string-method), the job does not generate the crazy geometry of NEB.

**Comment by edoapra** [comment]
I would recommend the use of the Zero Temperature String Method over NEB, anyhow

**Comment by baba-hashimoto** [comment]
Thank you for your comment. I'll try to use Zero Temperature String Method.　I hope the NEB bug will be fixed.
