### ISSUE TITLE
Limited atom labels in nwchem?

### ISSUE THREAD

**Issue by scottwsides** [nwchemgit/nwchem#737]
I want to give each atom in my input file a unique tag eg
start job-tag-3

memory stack 2700 mb heap 225 mb global 1800 mb noverify
scratch_dir .

geometry units angstroms NOCENTER NOAUTOZ NOAUTOSYM
C_1 -0.98953575 -0.04767925 2.99560486
C_2 -0.42286166 1.22679510 2.78225018
C_3 -0.47896498 2.18409490 3.80883676
C_4 -1.08641214 1.88721355 5.02984455
C_5 -1.64519445 0.63049157 5.24022710
C_6 -1.59738329 -0.33127469 4.22992487
C_7 -0.93321712 -1.00463269 1.96880826
C_8 -0.32501227 -0.72027169 0.73431589
C_9 0.24062474 0.55186912 0.52135244
C_10 0.18485548 1.50995856 1.54785123
C_11 -0.26865678 -1.67747251 -0.29280548
C_12 0.33922509 -1.39426739 -1.52757746
C_13 0.90486178 -0.12212648 -1.74054058
C_14 0.84850626 0.83507437 -0.71341953
C_15 0.39499309 -2.35235570 -2.55407749
C_16 1.00270731 -2.06919024 -3.78847765
C_17 1.56938145 -0.79471595 -4.00183125
C_18 1.51306525 0.16223580 -2.97503307
C_19 1.05880842 -3.02648789 -4.81506638
C_20 1.66625431 -2.72960506 -6.03607481
C_21 2.22503522 -1.47288226 -6.24645671
C_22 2.17722597 -0.51111828 -5.23615216
H_23 -0.04780659 3.17206083 3.66346234

But when I get to tag '41' I get the error

For further details see manual section:
bas_add_utag: too many tags 41
bas_input_cont: bas_add_ucnt0 failed!! 0
input error at line 20: illegal character reading floating point number
H S
*.....
current input line :
20: H S
There is an error in the specified basis set

Why is 41 the magic number? Can I not label atoms above 41?

**Comment by edoapra** [comment]
The 41 value is due to the hard-wired value of 40 in the following header file
https://github.com/nwchemgit/nwchem/blob/f3b57f6be189cea1581361a2ec285bf2ec1ecb05/src/util/nwc_const.fh#L64-L65
If you want to use more than 40 unique atom labels, you can edit to the value of `nw_max_unq_tags` to the new value and recompile NWChem.

May I ask you the reason why you need to use this many different atomic labels?

**Comment by edoapra** [comment]
Closing since we did not get further details from the issue submitter

**Comment by scottwsides** [comment]
Sorry about that... I found a workaround. At any rate, not that many labels are needed... but it is a weird landmine to run into. Thanks!!
