### ISSUE TITLE
Inform about libraries not found ....

### ISSUE THREAD

**Issue by miroi** [nwchemgit/nwchem#765]
Hello,

on one cluster I loaded modules:
~~~
31) ELPA/2021.11.001-foss-2022a
32) ScaLAPACK/2.2.0-gompi-2022a-fb
~~~
but NWChem configuration still stays

~~~
configure: WARNING: ScaLAPACK library not found, interfaces won't be defined
configure: WARNING: ELPA library not found, interfaces won't be defined
configure: WARNING: ELPA 2015 library not found, interfaces won't be defined
configure: WARNING: ELPA 2016 library not found, interfaces won't be defined
configure: WARNING: ELPA 2017 library not found, interfaces won't be defined
~~~

I would welcome some more info printed why are these libraries not accepted....

**Comment by edoapra** [comment]
Using the command  `make V=1` gives you a more verbose log.
Anyhow, all the information you are looking for about the ScaLapack linking failure can be found in `$NWCHEM_TOP/src/tools/build/config.log`

Could we continue this conversation in the google forum since this is an installation issue?
