### ISSUE TITLE
Custom dielectric constant is ignored in COSMO calculations

### ISSUE THREAD

**Issue by rpseng** [nwchemgit/nwchem#776]
**Describe the bug**
If a COSMO calculation is requested with a custom dielectric constant (but no solvent name set), this option is ignored and the value for water is used instead.

**Additional context**
At this line the default `dielec` value is initialized :
https://github.com/nwchemgit/nwchem/blob/d681ac3cc4741fb5e80555be69f6b0696306e5a2/src/solvation/cosmo_initialize.F?plain=1#L255

Then a few lines below there is this conditional:
https://github.com/nwchemgit/nwchem/blob/d681ac3cc4741fb5e80555be69f6b0696306e5a2/src/solvation/cosmo_initialize.F?plain=1#L283

The above conditional will always be true and then a solvent name is internally set, even though the user have not provided a solvent name:
https://github.com/nwchemgit/nwchem/blob/d681ac3cc4741fb5e80555be69f6b0696306e5a2/src/solvation/cosmo_initialize.F?plain=1#L284

By this, the logic on the line below will skip the section that should get the `dielec` custom value, since a *solvent name was set*:
https://github.com/nwchemgit/nwchem/blob/d681ac3cc4741fb5e80555be69f6b0696306e5a2/src/solvation/cosmo_initialize.F?plain=1#L342

I can work on a fix and provide a PR for this, please let me know if that is desirable.

**Comment by edoapra** [comment]
@rpseng what version of NWChem have you been using?

**Comment by rpseng** [comment]
@edoapra thanks for reaching out. I compiled from source, from git master branch.

**Comment by edoapra** [comment]
@rpseng As a temporary workaround, could you try the following solvation input section (where you should replace 33d0 with the value of the dielectric constance you want to use)
```
cosmo
 dielec 33d0
 solvent unkn
end

```

**Comment by edoapra** [comment]
fix available in the master branch

**Comment by edoapra** [comment]
latest commits seems to cause a QA test to fail

```
20May2023 14:29:34  Running tests/CH3OH2pWat_SMD_M062X_opt/CH3OH2pWat_SMD_M062X_opt
20May2023 14:29:34
20May2023 14:29:34      cleaning scratch
20May2023 14:29:34      copying input and verified output files
20May2023 14:29:34      running nwchem (singularity exec /big_scratch/nwchems.img nwchem )  with 54 processors
20May2023 14:29:34
20May2023 14:29:38      NWChem execution failed
20May2023 14:29:38
20May2023 14:29:38
20May2023 14:29:38
20May2023 14:29:38
20May2023 14:29:38  Summary of "ao basis" -> "ao basis" (cartesian)
20May2023 14:29:38  ------------------------------------------------------------------------------
20May2023 14:29:38        Tag                 Description            Shells   Functions and Types
20May2023 14:29:38  ---------------- ------------------------------  ------  ---------------------
20May2023 14:29:38  H                           6-31G*                  2        2   2s
20May2023 14:29:38  C                           6-31G*                  6       15   3s2p1d
20May2023 14:29:38  O                           6-31G*                  6       15   3s2p1d
20May2023 14:29:38
20May2023 14:29:38
20May2023 14:29:38  in cosmo_initialize ...
20May2023 14:29:38
20May2023 14:29:38  solvent parameters
20May2023 14:29:38  solvname_short: h2o
20May2023 14:29:38  solvname_long:  water
20May2023 14:29:38  dielec:       78.4000
20May2023 14:29:38  dielecinf:     1.7769
20May2023 14:29:38  icds:          *
20May2023 14:29:38  ------------------------------------------------------------------------
20May2023 14:29:38  cosmo_initialize: illegal value for icds                   0
20May2023 14:29:38  ------------------------------------------------------------------------
20May2023 14:29:38  ------------------------------------------------------------------------
20May2023 17:26:13 ompi41x
```

**Comment by drew-parsons** [comment]
The ch4-scf-dft-prop.nw  and ch4-dft-scf-prop QA tests in nwchem 7.2.0 suffer from this issue.  Do the patches cited above fix the issue?  Should 7.2.1 be released?  I think it's dangerous to have the software silently ignoring dielec input settings, even if a workaround (adding solvent unkn) is available.

**Comment by edoapra** [comment]
@drew-parsons please refrain from judgmental statements such as _"...  I think it's dangerous to have the software silently ignoring ..._" that are neither useful nor conducive to a positive collaboration

**Comment by drew-parsons** [comment]
I hear you, and I apologise that my choice of words conveyed the wrong nuance.  I didn't mean it pejoratively, but functionally, in the sense that users might not notice that their dielectric constant was not applied, and might proceed using energies calculated for water solvent rather than the organic solvent they meant to use, without seeing the discrepancy.

**Comment by edoapra** [comment]
fixes for this issue available in master and hotfix/release-7-2-0
