### ISSUE TITLE
Warning: Type mismatch in argument 'tmp1' at (1); passed COMPLEX(8) to REAL(8)

### ISSUE THREAD

**Issue by yurivict** [nwchemgit/nwchem#78]
All builds print these and many other warnings:
```
C3dB-mpi.F:2892:72:

      >                          dcpl_mb(tmp2(1)))  !*** map1to3 operation ***
                                                                        1
Warning: Type mismatch in argument 'tmp1' at (1); passed COMPLEX(8) to REAL(8) [-Wargument-mismatch]
C3dB-mpi.F:433:0:

       integer i,nnfft3d

Warning: 'nnfft3d' may be used uninitialized in this function [-Wmaybe-uninitialized]
C3dB-mpi.F:617:0:

       integer i,nnfft3d

Warning: 'nnfft3d' may be used uninitialized in this function [-Wmaybe-uninitialized]
```

It seems to be indicative of real problems when complex is passed as real, or uninitialized values are used.

See here: http://package21.nyi.freebsd.org/data/112amd64-default-qat/484370/logs/nwchem-6.8.1.r.144.log

**Comment by edoapra** [comment]
@yurivict please provide a reproducer (input and output file) showing this failure

**Comment by jeffhammond** [comment]
This is an innocuous warning caused by MA using a double as the base pointer for MT_DBL but using it for complex double allocations since we know with absolutely certainty that a complex double is two doubles in contiguous memory.

I’m not sure afar the best way to fix this in NWPW.
