### ISSUE TITLE
fails to run, **ONENTRYTO GAL_DSYEVPARAMETER NUMBER 8HADANILLEGALVALUE

### ISSUE THREAD

**Issue by ckoe-bccms** [nwchemgit/nwchem#790]
**Describe the bug**

The binary compiled from nwchem-7.2.0-release.revision-d0d141fd-src.2023-03-10.tar.bz2 fails with the error message given in the title. This is the error message reported in https://github.com/GlobalArrays/ga/issues/142. However I have LAPACK_LIB set. Still GA appears, see make.out, to compile its own lapack ?

I would like to note that I also noticed that "make 64_to_32" was not executed when using the source exactly as extracted from the archive. This might be unrelated, but I believe this is also not working as intended ? Eventual cause for the "make 64_to_32" behaviour:

The nwchem-7.2.0/src  directory, as contained in the archive, contains an empty file nwchem-7.2.0/src/64_to_32 .
With this fie present "make 64_to_32" decides that 64_to_32 is up to date and will never do any changes.
After deleting the file nwchem-7.2.0/src/64_to_32 the "make 64_to_32" step modifies files as expected. However, the binary still fails in GA with the same error message.

**Describe settings used**

Rocky 9.1, gcc 13.1.0, mkl, openmpi 4.1.5, scalapack 2.2.0

NWCHEM_TARGET=LINUX64
NWCHEM_MODULES=qm python
PYTHONVERSION=3.9
NWCHEM_TOP=/backup1/build_temp/nwchem-7.2.0
BLAS_SIZE=4
BLAS_LIB=-Wl,--start-group /cluster/intel/oneapi/2023.1.0/mkl/2023.1.0//lib/intel64/libmkl_gf_lp64.a /cluster/intel/oneapi/2023.1.0/mkl/2023.1.0//lib/intel64/libmkl_sequential.a /cluster/intel/oneapi/2023.1.0/mkl/2023.1.0//lib/intel64/libmkl_core.a -Wl,--end-group -lpthread -lm -ldl
BLASOPT=-Wl,--start-group /cluster/intel/oneapi/2023.1.0/mkl/2023.1.0//lib/intel64/libmkl_gf_lp64.a /cluster/intel/oneapi/2023.1.0/mkl/2023.1.0//lib/intel64/libmkl_sequential.a /cluster/intel/oneapi/2023.1.0/mkl/2023.1.0//lib/intel64/libmkl_core.a -Wl,--end-group -lpthread -lm -ldl
SCALAPACK_SIZE=4
LAPACK_LIB=-Wl,--start-group /cluster/intel/oneapi/2023.1.0/mkl/2023.1.0//lib/intel64/libmkl_gf_lp64.a /cluster/intel/oneapi/2023.1.0/mkl/2023.1.0//lib/intel64/libmkl_sequential.a /cluster/intel/oneapi/2023.1.0/mkl/2023.1.0//lib/intel64/libmkl_core.a -Wl,--end-group -lpthread -lm -ldl
SCALAPACK=-L/cluster/libraries/netlib-scalapack/2.2.0/gcc-13.1.0/openmpi-4.1.5/lib/ -lscalapack
ARMCI_NETWORK=MPI-TS
USE_MPI=y
USE_MPIF4=y
USE_MPIF=y

**Attach log files**

Stdout of make attached. 
[make.out.gz](https://github.com/nwchemgit/nwchem/files/11646493/make.out.gz)

**To Reproduce**

extract
set variables
make clean 
make 64_to_32
       receive message "make: '64_to_32' is up to date."
FC=gfortran CC=gcc USE_64TO32=y  BLAS_SIZE=4 make  -j 48 >& make.out 2>&1

mpirun -n 2 ../bin/LINUX64/nwchem h2o-b3lyp-disp.nw
...
...
          s6 scale factor :        1.050000000000
              vdW contrib :       -0.000037459116

**ONENTRYTO GAL_DSYEVPARAMETER NUMBER 8HADANILLEGALVALUE
--------------------------------------------------------------------------
mpirun has exited due to process rank 0 with PID 0 on
node admin exiting improperly. There are three reasons this could occur:

**Expected behavior**

- make 64_to_32 should run if BLAS_SIZE=4 and actually print the expected conversions, for example
"converting gw_analytic.F to 32-bit integers for BLAS/LAPACK"
- The resulting binary should not fail.

I am aware that I could build with 64 bit integers (BLAS_SIZE=8) by linking with ilp64 instead, but I have not tested that yet.

**Comment by edoapra** [comment]
1. `make 64_to_32` is not needed on the release tarballs (including the one you are using)
2. what is the output of the command `ldd /backup1/build_temp/t/nwchem-7.2.0/bin/LINUX64` ?
3. Pre-compiled NWChem binaries are available from a variety of sources https://nwchemgit.github.io/Download.html, you might want to try one of those installation options

**Comment by ckoe-bccms** [comment]
1. Please update the documentation https://nwchemgit.github.io/Compiling-NWChem.html#how-to-deal-with-integer-size-of-linear-algebra-libraries then !

2. # ldd bin/LINUX64/nwchem 
        linux-vdso.so.1 (0x00007ffffff98000)
        libscalapack.so => /cluster/libraries/netlib-scalapack/2.2.0/gcc-13.1.0/openmpi-4.1.5/lib/libscalapack.so (0x0000151348d38000)
        libgfortran.so.5 => /cluster/gcc/13.1.0/lib64/libgfortran.so.5 (0x0000151348a60000)
        libm.so.6 => /lib64/libm.so.6 (0x0000151348978000)
        libmvec.so.1 => /lib64/libmvec.so.1 (0x000015134894c000)
        libmpi_usempif08.so.40 => /cluster/mpi/openmpi/4.1.5/gcc-13.1.0/lib/libmpi_usempif08.so.40 (0x0000151348909000)
        libmpi_usempi_ignore_tkr.so.40 => /cluster/mpi/openmpi/4.1.5/gcc-13.1.0/lib/libmpi_usempi_ignore_tkr.so.40 (0x00001513488f9000)
        libmpi_mpifh.so.40 => /cluster/mpi/openmpi/4.1.5/gcc-13.1.0/lib/libmpi_mpifh.so.40 (0x000015134888a000)
        libmpi.so.40 => /cluster/mpi/openmpi/4.1.5/gcc-13.1.0/lib/libmpi.so.40 (0x000015134874b000)
        libhwloc.so.15 => /lib64/libhwloc.so.15 (0x00001513486f2000)
        libpython3.9.so.1.0 => /lib64/libpython3.9.so.1.0 (0x0000151348392000)
        libcrypt.so.2 => /lib64/libcrypt.so.2 (0x0000151348356000)
        libgcc_s.so.1 => /cluster/gcc/13.1.0/lib64/libgcc_s.so.1 (0x0000151348330000)
        libc.so.6 => /lib64/libc.so.6 (0x0000151348127000)
        libgomp.so.1 => /cluster/gcc/13.1.0/lib64/libgomp.so.1 (0x00001513480d7000)
        /lib64/ld-linux-x86-64.so.2 (0x00001513496a3000)
        libopen-rte.so.40 => /cluster/mpi/openmpi/4.1.5/gcc-13.1.0/lib/libopen-rte.so.40 (0x000015134801b000)
        libopen-pal.so.40 => /cluster/mpi/openmpi/4.1.5/gcc-13.1.0/lib/libopen-pal.so.40 (0x0000151347f62000)
        libz.so.1 => /lib64/libz.so.1 (0x0000151347f48000)
        libevent_core-2.1.so.7 => /lib64/libevent_core-2.1.so.7 (0x0000151347f0f000)
        libevent_pthreads-2.1.so.7 => /lib64/libevent_pthreads-2.1.so.7 (0x0000151347f0a000)
        libquadmath.so.0 => /cluster/gcc/13.1.0/lib/../lib64/libquadmath.so.0 (0x0000151347ec2000)

3. I cannot see a pre-built version which would support a Cornelis Omni-Path network (requires openmpi 4.1.5 with psm2 or libfabric support) or an Rocky Linux 9.1 (aka RHEL 9.1). Or did I miss something ?

I opened a new bug report concerning the unfortunate choice of the h2o-b3lyp-disp.nw test. Attached is the ouput of running the h2o.nw test 
[h2o.txt](https://github.com/nwchemgit/nwchem/files/11654985/h2o.txt)
showing the same error.

**Comment by edoapra** [comment]
> 1. Please update the documentation https://nwchemgit.github.io/Compiling-NWChem.html#how-to-deal-with-integer-size-of-linear-algebra-libraries then 

NWChem is a collaborative effort. You can help us by suggesting changed to the documentation. Your detailed and specific contribution would be much appreciated. One way to provide a detailed feedback is the click the edit icon that will send you to 
https://github.com/nwchemgit/nwchem-wiki/edit/master/Compiling-NWChem.md

**Comment by ckoe-bccms** [comment]
I will do that, now that I am aware of a change in the development process only  known to the developers before.

**Comment by edoapra** [comment]
> I cannot see a pre-built version which would support a Cornelis Omni-Path network (requires openmpi 4.1.5 with psm2 or libfabric support) or an Rocky Linux 9.1 (aka RHEL 9.1). Or did I miss something ?  

NWChem builds using the `ARMCI_NETWORK=MPI-PR` https://nwchemgit.github.io/ARMCI.html#overview should be the best choice for your hardware (caveat: This port will use one processes on each node for communication, therefore subtracting one process (again on each node) for NWChem. Therefore, when executing on a single node (i.e. the case of desktop execution) you would need to ask for n+1 processes; in other words, a serial execution would require the following mpirun invocation mpirun -np 2 ...)    

MPI-PR builds are now available from conda-forge  (this is not documented yet since the packages were built just a week ago)
Here is how to install, once conda and/or micromamba, are installed
`micromamba install -c conda-forge nwchem=*=*mpi_pr*`

**Comment by ckoe-bccms** [comment]
How would this support internode communication on an actual high performance network ? The MPI needs to have the right transport and libraries to be linked in ? I do not understand the reference to ARMCI, is there a plugin architecture in the AMRCI provided with nwchem where we can insert our MPIs in some way into the conda forge ? I am completely confused by your answer. How would I do that ? Is there documentation of that ?

I do not understand how any of this would be a solution. Therefore, I am quite surprised by your suggestion of conda forge. To clarify, the target system is a 4000 core cluster, and not a desktop computer. We need the nwchem  to match the MPI and the process manager/launcher (slurm).

**Comment by edoapra** [comment]
I was not aware that this is a large cluster. I agree with you that a conda based installation is not a good choice.
As a first installation, that you could later refine, I would suggest you install BLAS/Lapack (OpenBLAS) and Scalapack from the NWChem builtin script(s) that would be triggered by the following settings:
```
unset BLASOPT
unset BLAS_LIB
unset LAPACK_LIB
unset LAPACK_LIB
unset SCALAPACK
export BUILD_OPENBLAS=1
export BUILD_SCALAPACK=1
export ARMCI_NETWORK=MPI-PR
```

**Comment by dmejiar** [comment]
> How would this support internode communication on an actual high performance network ? The MPI needs to have the right transport and libraries to be linked in ? I do not understand the reference to ARMCI, is there a plugin architecture in the AMRCI provided with nwchem where we can insert our MPIs in some way into the conda forge binary or built process ? I am completely confused by your answer. How would I do that ? Is there documentation of that ?

Even though conda forge is not the best way to go, there seems to be a way to do exactly make it work: https://conda-forge.org/docs/user/tipsandtricks.html#using-external-message-passing-interface-mpi-libraries .

**Comment by ckoe-bccms** [comment]
OK, thank you for the suggestions.

First, I should probably point out that the 64 bit integer version (mkl with ilp64) works for me, except for the oddity with one test es reported in 791 which leaves an open questions.  I am happy to use the 64 bit integer build.

Now, back to the 32 bit integer version. I extracted fresh sources to make sure that this was not the problem. Then I compiled two binaries (without scalapack) with these scripts.

[compile_nwchem_internal.sh.txt](https://github.com/nwchemgit/nwchem/files/11657522/compile_nwchem_internal.sh.txt)
[compile_nwchem_external.sh.txt](https://github.com/nwchemgit/nwchem/files/11657523/compile_nwchem_external.sh.txt)
(Sorry, apparently I have to rename everything to txt to be able to upload to github. I hope I mess nothing up in the process.)

The external build is with the lp64 version of the mkl (which works great with cp2k or pwscf with gcc 13.1) and the internal build with the openblas generated by nwchem as suggested.

The stdout of the make step together with the output of env (see scripts) is
[make_external.out.txt](https://github.com/nwchemgit/nwchem/files/11657574/make_external.out.txt)
[make_internal.out.txt](https://github.com/nwchemgit/nwchem/files/11657575/make_internal.out.txt)

I also attach the files 
```
./src/tools/build/tools/ga-config
./src/tools/build/comex/tools/comex-config
./src/tools/build/comex/tools/armci-config
./src/tools/build/armci/tools/armci-config
```
of each build in two archives in the hope that this catches the relevant information about the GA configuration.
[configs_external.tar.gz](https://github.com/nwchemgit/nwchem/files/11657605/configs_external.tar.gz)
[configs_internal.tar.gz](https://github.com/nwchemgit/nwchem/files/11657606/configs_internal.tar.gz)

The built with external LAPACK/BLAS fails to run the h2o.nw test input, while the built with the internal openblas, which I assume uses 64 bit integers anyway, works (no surprise ?). Output:
[h2o_external.out.txt](https://github.com/nwchemgit/nwchem/files/11657615/h2o_external.out.txt)
[h2o_internal.out.txt](https://github.com/nwchemgit/nwchem/files/11657616/h2o_internal.out.txt)

I also provide the ldd output for each binary
[ldd_internal.out.txt](https://github.com/nwchemgit/nwchem/files/11657631/ldd_internal.out.txt)
[ldd_external.out.txt](https://github.com/nwchemgit/nwchem/files/11657632/ldd_external.out.txt)

Looking at ga.config one can see the actual linking ? The interesting fact is that the ga.config for the external build shows 
```
libs="-lga    /cluster/intel/oneapi/2023.1.0/mkl/2023.1.0//lib/intel64/libmkl_gf_ilp64.a /cluster/intel/oneapi/2023.1.0/mkl/2023.1.0//lib/i
ntel64/libmkl_sequential.a /cluster/intel/oneapi/2023.1.0/mkl/2023.1.0//lib/intel64/libmkl_core.a -lpthread -lm -ldl $dep_libs "
```
This is the ilp64 version, while the build script specifies lp64. Does configure try to pick up the correct version automatically based in LAPACK_LIB ? Or where does this come from ? In theory this should work if GA wants an 8 Byte integer version of LAPCK ? Interesting.


> ARMCI is a library that uses MPI. When you build NWChem, it will build ARMCI against the specified MPI.

(OK, properly quoting previous replies simply does not work for me for whatever reason ... Sorry.)

I have general understanding where ARMCI sits in the software stack. My confusion was about mentioning ARMCI_NETWORK=MPI-PR in connection with conda forge. Probably this are two different topics. I understand the MPI-PR is recommended for Omni-Path. The Cornelis Omni-Path now moves away from psm2 and will switch to the ofi fi_opx provider. We will see what that means I assume. However, due to the fact that we waste a full Core on the progress rank I tend to build MPI-TS. Perhaps that is a stupid idea ? But it works inter-node on the cluster we are retiring now, which has an Intel Omni-Path using psm2.

But this confirms that I cannot simply switch MPIs in ARMCI after building, no plugin mechanism at that point. However, it might be that conda forge would be able to automatically pick up MPI and eventually correct linear algebra libraries from the loaded modules ? In that case  rebuilding would be as much effort as starting a new build in spack (which, due to other concerns, I did not try for nwchem, assuming it is included) ? That said, experiences with mpi4py and similar on the cluster we are retiring were quite discouraging. So conda is a bit questionable  by association :-)

**Comment by edoapra** [comment]
I will try again to answer the `ARMCI_NETWORK=MPI-PR` question.  
First of all, if you did not have the time yet to do it, please read the related information in https://nwchemgit.github.io/ARMCI.html
One aspect not covered in the documentation above is that most of the current NWChem installations at large computing centers do use the compile time setting `ARMCI_NETWORK=MPI-PR` for reasons of performance and reliability.  
This `ARMCI_NETWORK=MPI-PR` topic  is completely orthogonal to the conda distribution (we simply distribute two different variants of NWChem with conda, one (default) built with `ARMCI_NETWORK=MPI-TS` and a second one built with `ARMCI_NETWORK=MPI-PR` . If you are not interested in using conda, I don't see any point to continue a conda related discussion.  

As far as large computing centers' installations, the other options you could have is to use containers (e.g. Docker, Singularity or Shifter)

**Comment by edoapra** [comment]
> of each build in two archives in the hope that this catches the relevant information about the GA configuration.
[configs_external.tar.gz](https://github.com/nwchemgit/nwchem/files/11657605/configs_external.tar.gz)
[configs_internal.tar.gz](https://github.com/nwchemgit/nwchem/files/11657606/configs_internal.tar.gz)

These files are not so easy to analyze.    
The following ones are what we typically look at  
```
$NWCHEM_TOP/src/tools/build/config.log
$NWCHEM_TOP/src/tools/build/comex/config.log
```

**Comment by edoapra** [comment]
These are the MKL settings we routinely use to test NWChem under Github Actions for ILP64.
LP64 should simply to replace ilp64/lp64 
```
export BLASOPT="-L$MKLROOT/lib/intel64 -lmkl_intel_ilp64 -lmkl_sequential -lmkl_core  -lpthread -lm -ldl"
export LAPACK_LIB=$BLASOPT
export SCALAPACK_LIB="-L$MKLROOT/lib/intel64 -lmkl_scalapack_ilp64 -lmkl_blacs_intelmpi_ilp64 -lpthread -lm -ldl"
```

**Comment by ckoe-bccms** [comment]
> One aspect not covered in the documentation above is that most of the current NWChem installations at large computing centers do use the compile time setting `ARMCI_NETWORK=MPI-PR` for reasons of performance and reliability.

You know these details much better,  I will switch to MPI-PR exclusively in the future. Once I figure out how to prepare a PR for the documentation I will try to suggest a change about a general preference for MPI-PR if necessary. Considering that modern nodes have much more cores than nodes had 10 years ago, a single progress rank really does not matter too much any more.

We plan to offer apptainer for workflows with complicated python dependencies. I will check out shifter, thank you for the suggestion.

I attach the logs you requested (hopefully the right ones)
[configs_external_requested.tar.gz](https://github.com/nwchemgit/nwchem/files/11661374/configs_external_requested.tar.gz)
[configs_internal_requested.tar.gz](https://github.com/nwchemgit/nwchem/files/11661375/configs_internal_requested.tar.gz)

> These are the MKL settings we routinely use to test NWChem under Github Actions for ILP64.
> LP64 should simply to replace ilp64/lp64

I checked the build script again. I have been using (please excuse the long paths, I copied that in from the environment and expanded $MKLROOT in the process):
```
export BLAS_LIB="-Wl,--start-group /cluster/intel/oneapi/2023.1.0/mkl/2023.1.0//lib/intel64/libmkl_gf_lp64.a /cluster/intel/oneapi/2023.1.0/mkl/2023.1.0//lib/intel64/libmkl_sequential.a /cluster/intel/oneapi/2023.1.0/mkl/2023.1.0//lib/intel64/libmkl_core.a -Wl,--end-group -lpthread -lm -ldl"
export BLASOPT="-Wl,--start-group /cluster/intel/oneapi/2023.1.0/mkl/2023.1.0//lib/intel64/libmkl_gf_lp64.a /cluster/intel/oneapi/2023.1.0/mkl/2023.1.0//lib/intel64/libmkl_sequential.a /cluster/intel/oneapi/2023.1.0/mkl/2023.1.0//lib/intel64/libmkl_core.a -Wl,--end-group -lpthread -lm -ldl"
export LAPACK_LIB="-Wl,--start-group /cluster/intel/oneapi/2023.1.0/mkl/2023.1.0//lib/intel64/libmkl_gf_lp64.a /cluster/intel/oneapi/2023.1.0/mkl/2023.1.0//lib/intel64/libmkl_sequential.a /cluster/intel/oneapi/2023.1.0/mkl/2023.1.0//lib/intel64/libmkl_core.a -Wl,--end-group -lpthread -lm -ldl"
```

These are in fact the correct 4 Byte integer lp64 libraries for a 4 Byte integer build (without scalapack) I believe. But please note:
1. This is statically linked, you suggest dynamic linking
2. BLAS_LIB is set, which is not set in your suggestion

To test if static linking is the problem I  modified my build script to include exactly the dynamical linking you suggested like this
```
#!/bin/bash
export NWCHEM_TOP=$PWD
export NWCHEM_TARGET=LINUX64
export NWCHEM_MODULES="qm python"
export PYTHONVERSION=3.9
export BLAS_SIZE=4
export USE_NOFSCHECK=TRUE
export USE_NOIO=TRUE
export BLASOPT="-L$MKLROOT/lib/intel64 -lmkl_intel_ilp64 -lmkl_sequential -lmkl_core  -lpthread -lm -ldl"
export LAPACK_LIB=$BLASOPT
export ARMCI_NETWORK=MPI-PR
export USE_MPI=y
export USE_MPIF4=y
export USE_MPIF=y
cd $NWCHEM_TOP/src
env > make_external.out 2>&1
make -j 48 clean 
make -j 48  64_to_32 >> make_external.out 2>&1
FC=gfortran CC=gcc USE_64TO32=y  BLAS_SIZE=4 make  -j 48 >> make_external.out 2>&1
```

The binary then completes the h2o.nw test successfully. 

So apparently static linking causes problems in the 32 bit build. Note that the successfull 64 bit integer build is also statically linked, it does not cause problems there.

I attach the two log files you specifically requested for this dynamic build
[configs_dynamically_requested.tar.gz](https://github.com/nwchemgit/nwchem/files/11662120/configs_dynamically_requested.tar.gz)

I also give the ldd output
```
ldd bin/LINUX64/nwchem 
        linux-vdso.so.1 (0x00007ffc8f9ca000)
        libmkl_intel_lp64.so.2 => /cluster/intel/oneapi/2023.1.0/mkl/2023.1.0/lib/intel64/libmkl_intel_lp64.so.2 (0x000015378d65e000)
        libmkl_sequential.so.2 => /cluster/intel/oneapi/2023.1.0/mkl/2023.1.0/lib/intel64/libmkl_sequential.so.2 (0x000015378bc52000)
        libmkl_core.so.2 => /cluster/intel/oneapi/2023.1.0/mkl/2023.1.0/lib/intel64/libmkl_core.so.2 (0x0000153787871000)
        libgfortran.so.5 => /cluster/gcc/13.1.0/lib64/libgfortran.so.5 (0x0000153787599000)
        libm.so.6 => /lib64/libm.so.6 (0x00001537874af000)
        libmvec.so.1 => /lib64/libmvec.so.1 (0x0000153787483000)
        libmpi_usempif08.so.40 => /cluster/mpi/openmpi/4.1.5/gcc-13.1.0/lib/libmpi_usempif08.so.40 (0x0000153787442000)
        libmpi_usempi_ignore_tkr.so.40 => /cluster/mpi/openmpi/4.1.5/gcc-13.1.0/lib/libmpi_usempi_ignore_tkr.so.40 (0x0000153787432000)
        libmpi_mpifh.so.40 => /cluster/mpi/openmpi/4.1.5/gcc-13.1.0/lib/libmpi_mpifh.so.40 (0x00001537873c3000)
        libmpi.so.40 => /cluster/mpi/openmpi/4.1.5/gcc-13.1.0/lib/libmpi.so.40 (0x0000153787284000)
        libhwloc.so.15 => /lib64/libhwloc.so.15 (0x0000153787229000)
        libmkl_intel_ilp64.so.2 => /cluster/intel/oneapi/2023.1.0/mkl/2023.1.0/lib/intel64/libmkl_intel_ilp64.so.2 (0x0000153786361000)
        libpython3.9.so.1.0 => /lib64/libpython3.9.so.1.0 (0x0000153786001000)
        libcrypt.so.2 => /lib64/libcrypt.so.2 (0x0000153785fc7000)
        libgcc_s.so.1 => /cluster/gcc/13.1.0/lib64/libgcc_s.so.1 (0x0000153785fa1000)
        libc.so.6 => /lib64/libc.so.6 (0x0000153785d98000)
        libdl.so.2 => /lib64/libdl.so.2 (0x0000153785d91000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x0000153785d8c000)
        /lib64/ld-linux-x86-64.so.2 (0x000015378e89a000)
        libopen-rte.so.40 => /cluster/mpi/openmpi/4.1.5/gcc-13.1.0/lib/libopen-rte.so.40 (0x0000153785cd0000)
        libopen-pal.so.40 => /cluster/mpi/openmpi/4.1.5/gcc-13.1.0/lib/libopen-pal.so.40 (0x0000153785c19000)
        libz.so.1 => /lib64/libz.so.1 (0x0000153785bff000)
        libevent_core-2.1.so.7 => /lib64/libevent_core-2.1.so.7 (0x0000153785bc4000)
        libevent_pthreads-2.1.so.7 => /lib64/libevent_pthreads-2.1.so.7 (0x0000153785bbf000)
        libquadmath.so.0 => /cluster/gcc/13.1.0/lib/../lib64/libquadmath.so.0 (0x0000153785b77000)
```

**Comment by ckoe-bccms** [comment]
OK, I messed the compile script up. I actually had ilp64 first before cancelling the build and starting over. The right settings, as confirmed by the ldd output above, are

```
#!/bin/bash
export NWCHEM_TOP=$PWD
export NWCHEM_TARGET=LINUX64
export NWCHEM_MODULES="qm python"
export PYTHONVERSION=3.9
export BLAS_SIZE=4
export USE_NOFSCHECK=TRUE
export USE_NOIO=TRUE
export BLASOPT="-L$MKLROOT/lib/intel64 -lmkl_intel_lp64 -lmkl_sequential -lmkl_core  -lpthread -lm -ldl"
export LAPACK_LIB=$BLASOPT
export ARMCI_NETWORK=MPI-PR
export USE_MPI=y
export USE_MPIF4=y
export USE_MPIF=y
cd $NWCHEM_TOP/src
env > make_external.out 2>&1
make -j 48 clean 
make -j 48  64_to_32 >> make_external.out 2>&1
FC=gfortran CC=gcc USE_64TO32=y  BLAS_SIZE=4 make  -j 48 >> make_external.out 2>&1
```

**Comment by edoapra** [comment]
> OK, I messed the compile script up. I actually had ilp64 first before cancelling the build and starting over. The right settings, as confirmed by the ldd output above, are
> 

I am assuming now the `GAL_DSYEV` errror has vanished, isn't it?

**Comment by ckoe-bccms** [comment]
Sorry, I should have written that more clearly. With dynamic linking the error `GAL_DSYEV` appears to have indeed vanished, but I only checked with the h2o.nw test at that time. I have now started the fill `doqmtest.mpi` test suite, up to `tests/h2o_dk/h2o_dk` everything is ok.

**Comment by ckoe-bccms** [comment]
Please close.
