### ISSUE TITLE
Compiling Error D3dBs-new.F for 7.2.0

### ISSUE THREAD

**Issue by tvery-idris** [nwchemgit/nwchem#792]
# Describe the bug

The compilation of the version 7.2.0 (https://github.com/nwchemgit/nwchem/releases/download/v7.2.0-release/nwchem-7.2.0-release.revision-d0d141fd-srconly.2023-03-10.tar.bz2) fails because there is an undefined variable pslans at line 500 of  D3dBs-new.F.

From what I understand of the code this should be splans?

# Environment 

Compilation with spack using intel compilers 19.1.3.

**Comment by edoapra** [comment]
Could you provide a more detailed by report by listing all of environmental variables and the full compilation log?
Since we are not familiar this spack, without the information just mentioned, there is not much that NWChem developers can do to help you.

**Comment by edoapra** [comment]
Are you trying to install NWChem with FFTW enabled? My recommendation is use the NWChem builtin FFT and not to enable FFTW.

**Comment by edoapra** [comment]
@tvery-idris Yes, `pslans` needs to replaced by `splans` as in the patch https://github.com/edoapra/nwchem/commit/72563694915bb8e6d77392519dccac1d83fc80c4.patch

However, this compilation problem is a clear indication that this FFTW interface code has never been used and tested.
My recommendation is to use it only after careful testing. Using the default builtin FFT seems a much safer option.

**Comment by ebylaska** [comment]
I’ll take a look.  This is code for running calculations in single precision, which is not really ever used.  I put this in for testing code performance back when people were advocating mix precision numerics.
________________________________

**Comment by edoapra** [comment]
> I’ll take a look. This is code for running calculations in single precision, which is not really ever used. I put this in for testing code performance back when people were advocating mix precision numerics.

On a related note, once this code is used and compiled, the compilation fails at the link stage with the following missing objects:
```
fftw_plan_many_dft_
fftw_plan_many_dft_c2r_
fftw_plan_many_dft_r2c_
fftw_destroy_plan_
fftw_execute_dft_
fftw_execute_dft_c2r_
fftw_execute_dft_r2c_
```
There seem to be no bindings for this object in Fortran only what seem to be single- and double-precision variants, e.g.
`dfftw_plan_many_dft_` or `sfftw_plan_many_dft_`

**Comment by tvery-idris** [comment]
@edoapra Yes the FFTW3 interface was activated. I will deactivate it.

Here are the environment and the compilation log.

[spack-build-env.txt](https://github.com/nwchemgit/nwchem/files/11685754/spack-build-env.txt)
[spack-build-out.txt](https://github.com/nwchemgit/nwchem/files/11685756/spack-build-out.txt)

**Comment by edoapra** [comment]
@ebylaska After renaming the missing object to the single precision variants, I tried a few QA tests and none of them seems to be using the FFTW3 code path ... is there any QA test that stresses this functionality?

Would it make more  sense to disable this FFTW3 code to avoid similar "misunderstandings" in the future?

**Comment by ebylaska** [comment]
if (control_single_precision_on()) callD3dBs_fft_init(nb)

this is where it's initialized

[Eric Bylaska - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=23xnrs)	[23xnrs]

On June 8, 2023 at 20:50 GMT, Edoardo Aprà ***@***.***> wrote:

***@***.***(https://github.com/ebylaska) After renaming the missing object to the single precision variants, I tried a few QA tests and none of them seems to be using the FFTW3 code path ... is there any QA test that stresses this functionality?

Would it make more sense to disable this FFTW3 code to avoid similar "misunderstandings" in the future?

**Comment by ebylaska** [comment]
the environment variable is :. pspw:HFX_single_precision'

[Eric Bylaska - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=23xntl)	[23xntl]

On June 8, 2023 at 20:54 GMT, Eric Bylaska ***@***.***> wrote:

if (control_single_precision_on()) callD3dBs_fft_init(nb)

this is where it's initialized

[Eric Bylaska - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=23xnrs)	[23xnrs]

On June 8, 2023 at 20:50 GMT, Edoardo Aprà ***@***.***> wrote:

***@***.***(https://github.com/ebylaska) After renaming the missing object to the single precision variants, I tried a few QA tests and none of them seems to be using the FFTW3 code path ... is there any QA test that stresses this functionality?

Would it make more sense to disable this FFTW3 code to avoid similar "misunderstandings" in the future?

**Comment by ebylaska** [comment]
It's probably best to keep it since single precision can make things faster for exchange. Can you check in the code you have, and I'll take a look.

[Eric Bylaska - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=23xo0j)	[23xo0j]

On June 8, 2023 at 20:55 GMT, Eric Bylaska ***@***.***> wrote:

the environment variable is :. pspw:HFX_single_precision'

[Eric Bylaska - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=23xntl)	[23xntl]

On June 8, 2023 at 20:54 GMT, Eric Bylaska ***@***.***> wrote:

if (control_single_precision_on()) callD3dBs_fft_init(nb)

this is where it's initialized

[Eric Bylaska - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=23xnrs)	[23xnrs]

On June 8, 2023 at 20:50 GMT, Edoardo Aprà ***@***.***> wrote:

***@***.***(https://github.com/ebylaska) After renaming the missing object to the single precision variants, I tried a few QA tests and none of them seems to be using the FFTW3 code path ... is there any QA test that stresses this functionality?

Would it make more sense to disable this FFTW3 code to avoid similar "misunderstandings" in the future?

**Comment by edoapra** [comment]
The following commits  in the master branch fix this bug
https://github.com/nwchemgit/nwchem/commit/b4ec4ade1af434bc80470d6874aebf6fdcd12489   
https://github.com/nwchemgit/nwchem/commit/376f86f96eb982e83f10514e9dcd994564f973b4  
https://github.com/nwchemgit/nwchem/commit/c89fc9d1eca6689bce12564a63fdea95d962a123  

However, enabling `USE_FFTW3` is not recommended
