### ISSUE TITLE
Do the NMR shielding tensors obtained include solvation effects?

### ISSUE THREAD

**Issue by xiongyan21** [nwchemgit/nwchem#80]
Recently, Dr. Tatrieddy put a topic on NWCHEM Forum, reporting the failure of a case of NMR calculation, whereas Dr. Edoapra said the change of the allocation could make the calculation work.
I found the choice of " memory heap 6000 mb stack 2000 mb global 6000 mb" also makes the calculation finish using NWCHEM6.8 on Ubuntu18.04.1 with four threads, and wonder whether the NMR sheilding tensors obtained include solvations effects. If the answer is yes, I further want to know the way it affects without the gas phase calculation.
The log file is attached, and the repeated calculation gets the same results.
[nmr.log](https://github.com/nwchemgit/nwchem/files/2569480/nmr.log)

**Comment by ngovind** [comment]
Hi Xionguan,

Yes. If you include a solvation environment (implicit or explicit), it will be taken into account. We have examples in our QA suite. For example, check the ch3f_notrans_cosmo test case, which uses cosmo combined with a shielding calculation.

Best,
-Niri
niri.govind@pnnl.gov
