### ISSUE TITLE
7.2.0 fails gradients of bare ecps which <=7.0.2 works

### ISSUE THREAD

**Issue by chemsh** [nwchemgit/nwchem#801]
Dear NWChem Team,

we find a fundamental bug when testing NWChem 7.2.0 for ChemShell. Please see the attached example input and script used for compiling NWChem (both renamed as .txt). This is a test case of gradients on the background point charges which has been stable for many years. With NWChem 7.2.0 it fails with the message, either in serial or parallel:

> 0:cannot locate region: density matrix [0:-1 ,1:15 ]:Received an Error in Communication
> Abort(-999) on node 0 (rank 0 in comm 496): application called MPI_Abort(comm=0x84000002, -999) - process 0

I've traced back to function `hnd_elfcon_0` around line 262 in _property/hnd_elfcon.F_:
`call ga_get(g_dens, bf_lo_i, bf_hi_i, bf_lo_j,` where `bf_lo_i` and `bf_hi_i` became `0` and `-1`, respectively. I think it's a bug in the code because these lines are new in 7.2.0. @dmejiar 

As metal oxide is one of the most common types of simulation in ChemShell, we appreciate if you could take a look at this issue. Thank you very much.

Kind regards,

You

[compile_nwchem_on_ubuntu.txt](https://github.com/nwchemgit/nwchem/files/11792739/compile_nwchem_on_ubuntu.txt)
[mgo_nwchem_bug.txt](https://github.com/nwchemgit/nwchem/files/11792740/mgo_nwchem_bug.txt)

**Comment by edoapra** [comment]
A fix now now available both in the master and hotfix/release-7-2-0 branch
https://github.com/nwchemgit/nwchem/commit/5a45dbf190f068c3fbce28aabb42a684fcb6b68c

**Comment by chemsh** [comment]
Dear Edo,
@edoapra 

thank you so much for the prompt response and hotfix! I can confirm hotfix/release-7-2-0 works for our tests again. I am closing the current Issue now.

Kind regards,

You
