### ISSUE TITLE
elements up to Z=120 wanted in nwchem

### ISSUE THREAD

**Issue by miroi** [nwchemgit/nwchem#821]
Hello !

NWChem has implemented relativistic effects. Nowadays, superheavy elements (SHEs) are an emerging topic of theoretical studies.

I tried TsOH on gold slab with NWChem, https://github.com/miroi/open-collection/tree/master/theoretical_chemistry/projects/adsorbate_on_surface/TsOHonAu28pyramide , but it failed with wrong proton number assigned to Ts, see https://github.com/miroi/open-collection/blob/master/theoretical_chemistry/projects/adsorbate_on_surface/TsOHonAu28pyramide/TsOHAu31.dk2_b3lyp.main_N4_n144_jid4020006.out_SAVED_wrong#L407 .

Please, implement data for SHE's  up to Z=120 or give me hints how to implement this change into the code. Thanks.

PS: Probably this issue should be under feature request, I put it under "bugs" due to wrong assignment of Z for the Ts element...

**Comment by jeffhammond** [comment]
This is the hard-coded limit:
```
geom/geomP.fh:      parameter (nelements     = 112)
```

This is relevant to the tables `symbols` and `elements` in geom/geom.F.

There is a different limit of 105 in the parser code in geom/geom_input.F:
```fortran
DIMENSION ATLBL1(105),ATLBL2(105),ATLBL3(105),ATLBL4(105)
```
These tables are for the different capitalization pairings, which is dumb.  We should have one table and use a upper/lower canonicalization utility, but that's a separate issue.

From this, you should be able to figure out how to add this feature.  It is possible that there are other places where changes are required.

**Comment by jeffhammond** [comment]
please see my pull request.  this was slightly harder than i expected, because of code duplication, which i fixed in the process.

i stopped at Z=118 for the reason listed in the PR.

**Comment by dmejiar** [comment]
@miroi You could also try to go around the current limitations by specifying a different nuclear charge for an already existing element. For example, you could use the following input for Unbinilium (provide a basis set for Unbinilium using the Db tag)

```
start
title superheavy

charge 0

geometry noautosym dubnium
 Db 0.0 0.0 0.0
end

geometry noautosym ekaradium
 Db 0.0 0.0 0.0 charge 120.0 mass 320.0
end

BASIS "ao basis" SPHERICAL PRINT
# define your basis
END

set geometry dubnium
dft
 mult 6
 xc r2scan
 vectors output test.movecs
end

relativistic
 x2c on
end

task dft ignore

set geometry ekaradium
dft 
 odft
 mult 1
 vectors input test.movecs
 grid lebedev 250 14
end

set x2c:noatm t

task dft
```

If you are using DFT, as in the example, it is advisable to define your own grid specification as the one for Db might not be good enough for heavier elements. 

You could also try the same trick for even heavier elements.

**Comment by jeffhammond** [comment]
Resolved by #822

**Comment by jeffhammond** [comment]
I guess we didn't do 119 and 120 yet.

**Comment by jeffhammond** [comment]
https://github.com/nwchemgit/nwchem/pull/824 covers 119 and 120
