### ISSUE TITLE
duplicate copies of geomP.fh in optim

### ISSUE THREAD

**Issue by jeffhammond** [nwchemgit/nwchem#823]
Why do we have these duplicates of geomP.fh in optim?  This seems like a bad idea.

./optim/mepgs/geomP.fh
./optim/tropt/geomP.fh
./geom/geomP.fh

**Comment by edoapra** [comment]
`nvfortran` is now crashing with a segfault in $NWCHEM_TOP/src/geom

https://github.com/nwchemgit/nwchem/actions/runs/5511093015/jobs/10046185487?pr=822

**Comment by edoapra** [comment]
it sounds like the compiler runs out of memory

**Comment by edoapra** [comment]
Addressed by https://github.com/jeffhammond/nwchem/commit/3a2103cc4236d72c6dbda82cb4abbeb8bc30a891
