### ISSUE TITLE
O(10^3) global arrays are created from the property code

### ISSUE THREAD

**Issue by edoapra** [nwchemgit/nwchem#831]
**Describe the bug**
The spin-spin code from `hnd_spinspin()` can create O(10^3)  global arrays when all possible atom pairs are requested.

**Describe settings used**
When using `ARMCI_NETWORK=MPI-PR` this can result in the error `too many open files`  https://github.com/GlobalArrays/ga/issues/257

**To Reproduce**
Input file from https://groups.google.com/g/nwchem-forum/c/LvrAZBMc9fg
```
geometry  noautoz
C  0.000000  0.000000  0.000000
O  1.422300  0.000000  0.000000
C  1.964700  0.000000  1.332700
C  1.674300  -1.244200  2.113000
C  0.887500  -1.395700  3.317000
C  0.138600  -0.336700  4.083700
C  -1.075900  -0.561300  4.697700
C  -1.604100  0.591200  5.367100
C  -2.798600  0.750100  6.114100
C  -3.131700  1.982300  6.697300
C  -4.370100  2.109900  7.533700
C  -2.266000  3.062200  6.544000
C  -1.098900  2.941100  5.782400
O  -0.274900  4.044700  5.682300
C  -0.608100  4.784200  4.507800
C  -0.760400  1.693900  5.215800
S  0.634400  1.276700  4.294200
C  0.891300  -2.745300  3.647100
C  0.472200  -3.581000  4.701300
N  0.371600  -3.154100  6.037000
N  0.300400  -4.917000  4.519800
C  0.823300  -5.433900  3.451700
N  1.499000  -4.826100  2.480700
N  1.502700  -3.396100  2.615600
C  2.071900  -2.529300  1.724300
C  2.868500  -2.975900  0.534400
N  4.262500  -3.335700  0.854100
C  5.025400  -2.231400  1.437900
C  6.401900  -2.753400  1.858300
N  7.106900  -3.398900  0.771800
C  6.426300  -4.140600  -0.163200
O  7.054300  -4.909200  -0.893700
C  4.929800  -3.853600  -0.358500
H  -0.389500  0.833500  0.592700
H  -0.394300  -0.949300  0.373200
H  -0.338400  0.123400  -1.032600
H  1.634000  0.913400  1.824100
H  3.050800  0.098400  1.224700
H  -1.585400  -1.517800  4.659300
H  -3.454200  -0.109300  6.241000
H  -5.160600  1.448200  7.164200
H  -4.761200  3.132300  7.499700
H  -4.148000  1.850600  8.573400
H  -2.489400  4.016200  7.015200
H  -1.625700  5.185000  4.572600
H  -0.495800  4.179900  3.601500
H  0.083400  5.629200  4.437700
H  0.216700  -2.171500  6.177600
H  -0.197000  -3.788900  6.574600
H  0.731100  -6.516200  3.270800
H  2.363200  -3.837800  0.079000
H  2.857100  -2.189700  -0.230700
H  5.134600  -1.408500  0.719900
H  4.543900  -1.832600  2.336600
H  6.303500  -3.490300  2.664100
H  7.031300  -1.934700  2.220700
H  8.062200  -3.696300  0.910400
H  4.848700  -3.142200  -1.189900
H  4.457700  -4.798000  -0.652900
end
basis spherical
 * library 6-31G*
end
dft
 odft
 xc b3lyp
end
property
 spinspin 
end
task dft property

```

**Comment by jeffhammond** [comment]
Instead of N^2 matrices of the same (?) size, can we just create a 3D array where the 3D dimension is the N^2 index?

**Comment by edoapra** [comment]
> Instead of O(N^2) matrices of the same (?) size, can we just create a 3D array where the 3D dimension is the O(N^2) index?
> 
> (I haven't read the code yet. Maybe this is a naive comment.)

That would remove the `too many open files error` for `ARMCI_NETWORK=MPI-PR` https://github.com/GlobalArrays/ga/pull/310, but would not prevent the potentially huge memory requirement.
I am testing a simple fix where I simply cut the number of pairs to a value that does not cause harm (36) https://github.com/edoapra/nwchem/commit/eb2cd07e60389b7e796c3db3828bb26822f75b4a  
A slightly better fix would be to keep the number of atom pairs intact, and add one external loop and process only 36 pairs for each loop.  

The fix you suggested would require some restructuring of the CPHF (and associate Fock/XC build) routines and I am not sure I have the cycles to do in the short term.
