### ISSUE TITLE
gw code not compiling w/ USE_OPENMP and ifort

### ISSUE THREAD

**Issue by ebylaska** [nwchemgit/nwchem#837]
cd $NWCHEM_TOP/src/gwmol
grep MYSIMD *F *fh
make V=1 FC=ifort USE_OPENMP=1 -j 1 -l0.0001

**Comment by edoapra** [comment]
Compiler name and version? Are using the current master branch?

**Comment by edoapra** [comment]
I believe that commit https://github.com/nwchemgit/nwchem/commit/4dfb3a224b6c256b77251fb2e1b420b4b50912da should fix this compiler issue

**Comment by edoapra** [comment]
Same commit is present in the branch hotfix/release-7-2-0, too https://github.com/nwchemgit/nwchem/commit/7dce6cbd4419c1949a768dc0063d3eb146c61b79

**Comment by ebylaska** [comment]
I’m using sunspot
ifort version 2021.9.0

Yes I’m using the master branch


From: Edoardo Aprà ***@***.***>
Date: Friday, July 21, 2023 at 2:51 PM
To: nwchemgit/nwchem ***@***.***>
Cc: Eric Bylaska ***@***.***>, Author ***@***.***>
Subject: Re: [nwchemgit/nwchem] gw code not compiling w/ USE_OPENMP and ifort (Issue #837)

Compiler name and version? Are using the current master branch?

**Comment by ebylaska** [comment]
I also turned of your OPENMP check in src/nwpw/GNUmakefile


From: Eric Bylaska ***@***.***>
Date: Friday, July 21, 2023 at 3:15 PM
To: nwchemgit/nwchem ***@***.***>, nwchemgit/nwchem ***@***.***>
Cc: Author ***@***.***>
Subject: Re: [nwchemgit/nwchem] gw code not compiling w/ USE_OPENMP and ifort (Issue #837)
I’m using sunspot
ifort version 2021.9.0

Yes I’m using the master branch


From: Edoardo Aprà ***@***.***>
Date: Friday, July 21, 2023 at 2:51 PM
To: nwchemgit/nwchem ***@***.***>
Cc: Eric Bylaska ***@***.***>, Author ***@***.***>
Subject: Re: [nwchemgit/nwchem] gw code not compiling w/ USE_OPENMP and ifort (Issue #837)

Compiler name and version? Are using the current master branch?

**Comment by edoapra** [comment]
Could you provide a cleaner bug report instead of this messy postings?
Please post the output of the following commands 
```
cd $NWCHEM_TOP/src/gwmol
grep MYSIMD *F *fh
make V=1 FC=ifort USE_OPENMP=1 -j 1 -l0.0001
```

**Comment by edoapra** [comment]
> I also turned of your OPENMP check in src/nwpw/GNUmakefile 

Why is this relevant for gwmol?

**Comment by ebylaska** [comment]
Shouldn’t be, but you never know.

From: Edoardo Aprà ***@***.***>
Date: Friday, July 21, 2023 at 3:53 PM
To: nwchemgit/nwchem ***@***.***>
Cc: Eric Bylaska ***@***.***>, Author ***@***.***>
Subject: Re: [nwchemgit/nwchem] gw code not compiling w/ USE_OPENMP and ifort (Issue #837)

I also turned of your OPENMP check in src/nwpw/GNUmakefile

Why is this relevant for gwmol?

**Comment by edoapra** [comment]
Closing for lack of feedback
