### ISSUE TITLE
memory printout cannot handle large memory sizes

### ISSUE THREAD

**Issue by ebylaska** [nwchemgit/nwchem#838]
**Describe the bug**

On the newer exascale machines, the amount of memory per node is around 1 TB.  The printout for memory currently only prints in MB.

           Memory information
           ------------------

    heap     = 5368709118 doubles =  40960.0 Mbytes
    stack    = ********** doubles = 122880.0 Mbytes
    global   =     131072 doubles =      1.0 Mbytes (distinct from heap & stack)
    total    = ********** doubles = 163841.0 Mbytes
    verify   = yes
    hardfail = no 

In the above example, I was using the following memory keyword when running with OMP w/ 96 threads/node or threads/mpi rank.

memory heap 40 gb stack 120 gb global 1 mb

**Comment by edoapra** [comment]
fixed by commit https://github.com/nwchemgit/nwchem/pull/839/commits/19e4c0be291dbbdcc50a75e1058bbecd0f97e182
