### ISSUE TITLE
  What is the keyword in NWCHEM to calculate reorganization energies

### ISSUE THREAD

**Issue by xiongyan21** [nwchemgit/nwchem#86]
Dear All
Since 2016 or perhaps 2014, GAMESS has added the function to calculate reorganization energies of ET and proton-coupled ET reactions where one of the two necessary steps may fail on an old cpu in the cases of electrode plus solvent, electrode plus self assembled monolayer and solvent, electrode plus double layer and ionic solution, and homogeneous solvent, respectively, which also has an equivalent Python program. Isn't it fascinating that the electrochemical kinetic parameters can be obtained from the free energies in a solvent though quantum chemical methods, e.g., DFT, without the intricate treatment of electrodes and purification of solvents? These original programs were contributed to GAMESS by Profs. and Drs. previously in the world-wide famous Department of Chemistry of University of Illinois at Urbana-Champaign, and according to the authors' paper on SAM monolayer modified electrodes, they can produce total reorganization energies in good agreement with experimental data for all 12 metal complexes tested in aqueous solution, useful for molecular electrocatalysts electron transfer rate constants calculation.
I am now enjoying it for biochemical applications in aqueous and aprotic solutions.

It is said in the NWCHEM manual that it also can calculate reorganization energies, but I cannot find any keyword or example about this.
How to do it in NWCHEM?
Thanks a lot!

Very Best Regards!

**Comment by rangsimanketkaew** [comment]
As far as I know, the current NWChem version has no module to calculate the solvent (outer-sphere) reorganization energy yet. It has only the module that calculates electron transfer matrix element called [ET module](https://github.com/nwchemgit/nwchem/wiki/Electron-Transfer).

**Comment by xiongyan21** [comment]
Thanks a lot for your answer.
Now I can quanTUM chemically get the ET rate constant from MARCUS's theory using GAMESS and NWCHEM integrately. 
Very Best regards！

**Comment by xiongyan21** [comment]
In the QA tests, qmd_tddft exhibts only final qmd results, but qmd_tddft_h2o_svr gives the result at
around every 0.24 femotoseconds elapsed. **I wish to know whether it is the print level that causes
different outputs of qmd_tddft and qmd_tddft_h2o_svr in the QA test.**
It seems that the TDDFT methods employed in NWCHEM can almost give identical results as
obtained by GAMESS using a same functional without TDA for my subject compound,
which is very amazing. The beginning several successive excited states chosen by me are
in good agreement with the published experimental and my GAMESS cr-eomccsd(t) values,
where eomccsd completely fails. I haven't tried TDA using NWCHEM for it, yet. According to my
previous calculations using GAMESS for it they could fail for some functionals if TDA was used.

Thanks a lot!
Very Best Regards!

**Comment by xiongyan21** [comment]
I am very pleased to find the reorganization energies of TEMPO./TEMPO+ and [Ru(NH3)6]3+/2+, using nonrelativistic 6-31G(d,p) and SPK-DZP basis sets, respectively, in the case of double layer plus electrode in an arbitrarily chosen solvent, whose parameters are not in the GAMESS database and properly approximated by those of another one in the accompaning test example, are in good agreement, i.e., within 0.16 eV, with the experimental outer sphere values in articles indexed by the programmers.
