### ISSUE TITLE
Is it the print level that causes  different outputs of qmd_tddft and qmd_tddft_h2o_svr in the QA test?

### ISSUE THREAD

**Issue by xiongyan21** [nwchemgit/nwchem#88]
In the QA tests, qmd_tddft exhibts only final qmd results, but qmd_tddft_h2o_svr gives the result at
around every 0.24 femotoseconds elapsed. I wish to know whether it is the print level that causes 
different outputs of qmd_tddft and qmd_tddft_h2o_svr in the QA test.

Thanks a lot!
Very Best Regards!

**Comment by safischer** [comment]
What results are your referring to? Both files produce a summary of qmd related results at every time step, e.g. the following set of information is printed at every step in the dynamics for both files:

            QMD Run Information
            -------------------
  Time elapsed (fs) :                     0.241888
  Kin. energy (a.u.):        1            0.000747
  Pot. energy (a.u.):        1          -75.656991
  Tot. energy (a.u.):        1          -75.656245
  Target temp. (K)  :        1               20.00
  Current temp. (K) :        1              157.16
  Dipole (a.u.)     :        1  -4.101790E-15  -2.829312E-02   2.160129E-01

**Comment by xiongyan21** [comment]
Please excuse me for the careless reading of the outputs. Indeed they all print results at 0.24 fs although different.
