### ISSUE TITLE
Testcase tce_cc2_c2 has input file wrong

### ISSUE THREAD

**Issue by mbanck** [nwchemgit/nwchem#89]
The `tce_cc2_c2` test case directory contains a `tce_c2_cc2.nw` which makes the testsuite fail:

```
 Running tests/tce_cc2_c2/tce_cc2_c2 
 
     cleaning scratch
     copying input and verified output files
failed: cannot access tests/tce_cc2_c2/tce_cc2_c2.nw
tail: cannot open '/tmp/autopkgtest.UkRwkj/tree/QA/testoutputs/tce_cc2_c2.out' for reading: No such file or directory
```

**Comment by edoapra** [comment]
@mbanck thanks for the feedback

**Comment by mbanck** [comment]
Thanks - it is actually not the only testcase that cannot be run by `runtests.mpi.unix`, or am I doing some thing wrong?  I guess it'd need more work if there are several input files in the directory, but if there is only one, maybe it could just use that one?

**Comment by edoapra** [comment]
@mbanck The recommended way to run QA tests is by using the script doqmtests.mpi (that uses runtests.mpi.unix to run the individual tests). Test that have not been yet included in doqmtests.mpi might not work (as you have seen in the tce_cc2_c2 case)

**Comment by mbanck** [comment]
I see - `tce_cc2_c2` just seems to be the only testcase exercising the CC2 method (at least on a quick grep), so I wanted to include it to the list of few tests to run while building Debian packages. Good to know I'm not doing something wrong.
