### ISSUE TITLE
Run make clean without options/environment variables

### ISSUE THREAD

**Issue by marcindulak** [nwchemgit/nwchem#903]
**Is your feature request related to a problem? Please describe.**

From time to time the functionality of the "clean" target changes, and requires options/environment variables to be specified in order to execute "make clean". This requires adjusting automated build scripts.

For example, when trying the current master https://github.com/nwchemgit/nwchem/commit/45f057eca7e3bbe85815efe2bbcbbcacc6b95471, another option `BLAS_SIZE` is needed in additon to `USE_INTERNALBLAS` and `USE_MPI`.

```
/usr/bin/make USE_INTERNALBLAS=1 USE_MPI=y clean
***warning MPI_LIB ignored since FORCE_MPI_ENV not set***
***warning MPI_INCLUDE ignored since FORCE_MPI_ENV not set***
You must set
BLAS_SIZE
see https://nwchemgit.github.io/Compiling-NWChem.html#how-to-deal-with-integer-size-of-linear-algebra-libraries
config/makefile.h:4010: *** .  Stop.
```

**Describe the solution you'd like**

If it's feasible to generalize the makefile targets: ability to run "make clean" without options.
This may be difficult if the clean targets share the settings with other targets, but maybe those required options can be somehow hard coded for clean targets?

**Describe alternatives you've considered**

Discover what options "make clean" needs by running it, and add those options.

**Additional context**

**Comment by marcindulak** [comment]
Will a link to this issue appear in a disussion https://github.com/nwchemgit/nwchem/discussions/905?

**Comment by jeffhammond** [comment]
I just do `git clean -dfx` to clean the NWChem source tree without using the build system.
