### ISSUE TITLE
Is perl really needed for build?

### ISSUE THREAD

**Issue by yurivict** [nwchemgit/nwchem#91]
I had perl missing in the VM that's built nwchem package, but the build still succeeded after perl warnings:
```
converting ga_lkain_2cpl3_ext.F to 32-bit integers for BLAS/LAPACK
perl: Command not found.
[1]    Exit 1                        ( $perlexe $perlscript $file )
[3] 63565
[2]    Exit 1                        ( $perlexe $perlscript $file )
converting ga_it2.F to 32-bit integers for BLAS/LAPACK
perl: Command not found.
[4] 63570
[3]    Exit 1                        ( $perlexe $perlscript $file )
perl: Command not found.
[4]    Exit 1                        ( $perlexe $perlscript $file )
Making 64_to_32 in md5
gmake[3]: Entering directory '/wrkdirs/usr/ports/science/nwchem/work-serial/nwchem-master-oct22_2018-71-g3d310890e/src/util/md5'
```

The executable seems to work fine.

Is perl really needed? If yes, missing perl should trigger a build error. If no, it should be removed altogether.

The situation when there are warnings but it still succeeds indicates that it isn't really needed.

**Comment by yurivict** [comment]
Does presence/absence of 64to32 affect performance?

**Comment by jeffhammond** [comment]
Not directly. Some platforms only have optimized 32b BLAS and require 64to32 to use that. If you’re using NWChem internal BLAS or linking ATLAS/OpenBLAS/BLIS that uses 64b integers, you’re fine without it (and thus Perl).

**Comment by jeffhammond** [comment]
I'm going to close this, because the solution is to not use 64to32.  The long-term resolution will be via https://github.com/nwchemgit/nwchem/issues/90.
