### ISSUE TITLE
nwchem builds extremely slowly with gmake-4.4, and doesn't build in parallel

### ISSUE THREAD

**Issue by yurivict** [nwchemgit/nwchem#958]
**Describe the bug**
The build time for the FreeBSD port regressed to many hours from ~1.5 hour for unknown reasons.
It appears to spend a lot of time in bash scripts, and in perl.

Here is the relevant GNU Make issue that I've created: https://savannah.gnu.org/bugs/?65533

It also doesn't build in parallel - make ignores the flag ```-j8```.

Does anybody know why does it build so slowly, and how to make it build in parallel?

Could you please try to build it with gmake-4.4 and see if there's a slowdown?

Version: 7.2.0

**Comment by edoapra** [comment]
This is not a usable bug report. 
Please use the template at https://github.com/nwchemgit/nwchem/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=
