### ISSUE TITLE
Compiling 6.8.1 with Python 2.7.15 and Intel 19 compiler

### ISSUE THREAD

**Issue by hpjeonGIT** [nwchemgit/nwchem#96]
Hi, I am trying to compile nwchem 6.8.1 using python2.7.15 + intel19. In the step of making nwchem.o, following error messages appear. Looks like that it cannot (?) locate python header file  - I tried to add -I/usr/nic/python_da/2.7.15/include but didnt' work. Any comments are appreciated.

Thanks,

BJ

PS1. Error message:
make[1]: Leaving directory `/lstr/applications/atom/src/apps/nwchem/nwchem/src'
ifort -i8 -align -fpp -qopenmp -qno-openmp-offload -fimf-arch-consistency=true -finline-limit=250 -O2 -g -fp-model source  -Wl,--export-dynamic  -L/usr/nic/src/apps/nwchem/nwchem/lib/LINUX64 -L/usr/nic/src/apps/nwchem/nwchem/src/tools/install/lib  -o /usr/nic/src/apps/nwchem/nwchem/bin/LINUX64/nwchem nwchem.o stubs.o -lnwctask -lccsd -lmcscf -lselci -lmp2 -lmoints -lstepper -ldriver -loptim -lnwdft -lgradients -lcphf -lesp -lddscf -ldangchang -lguess -lhessian -lvib -lnwcutil -lrimp2 -lproperty -lsolvation -lnwints -lprepar -lnwmd -lnwpw -lofpw -lpaw -lpspw -lband -lnwpwlib -lcafe -lspace -lanalyze -lqhop -lpfft -ldplot -lnwpython -ldrdy -lvscf -lqmmm -lqmd -letrans -lpspw -ltce -lbq -lmm -lcons -lperfm -ldntmc -lccca -ldimqm -lnwcutil -lga -larmci -lpeigs -lperfm -lcons -lbq -lnwcutil  -L/usr/nic/compiler/intel/19.1/mkl/lib/intel64 -lmkl_scalapack_ilp64 -lmkl_intel_ilp64 -lmkl_intel_thread -lmkl_core -lmkl_blacs_intelmpi_ilp64 -L/usr/nic/compiler/intel/19.1/lib/intel64 -liomp5 -lpthread -lm -ldl -L/usr/nic/compiler/intel/19.1/mkl/lib/intel64 -lmkl_scalapack_ilp64 -lmkl_intel_ilp64 -lmkl_intel_thread -lmkl_core -lmkl_blacs_intelmpi_ilp64 -L/usr/nic/compiler/intel/19.1/lib/intel64 -liomp5 -lpthread -lm -ldl -l64to32 -L/usr/nic/compiler/intel/19.1/mkl/lib/intel64 -lmkl_intel_ilp64 -lmkl_intel_thread -lmkl_core -L/usr/nic/compiler/intel/19.1/lib/intel64 -liomp5 -lpthread -lm -ldl  -L/usr/nic/compiler/intel/19.1/mkl/lib/intel64 -lmkl_intel_ilp64 -lmkl_intel_thread -lmkl_core -L/usr/nic/compiler/intel/19.1/lib/intel64 -liomp5 -lpthread -lm -ldl -lnwcblas   -L/usr/nic/compiler/intel/19.1/impi/2019.1.144/intel64/lib/release_mt -L/usr/nic/compiler/intel/19.1/impi/2019.1.144/intel64/lib -I/usr/nic/compiler/intel/19.1//compilers_and_libraries_2019.1.144/linux/mpi/intel64/include -I/usr/nic/compiler/intel/19.1//compilers_and_libraries_2019.1.144/linux/mpi/intel64/include -L/usr/nic/compiler/intel/19.1//compilers_and_libraries_2019.1.144/linux/mpi/intel64/lib/release -L/usr/nic/compiler/intel/19.1//compilers_and_libraries_2019.1.144/linux/mpi/intel64/lib -Xlinker --enable-new-dtags -Xlinker -rpath -Xlinker /usr/nic/compiler/intel/19.1//compilers_and_libraries_2019.1.144/linux/mpi/intel64/lib/release -Xlinker -rpath -Xlinker /usr/nic/compiler/intel/19.1//compilers_and_libraries_2019.1.144/linux/mpi/intel64/lib -Xlinker -rpath -Xlinker /opt/intel/mpi-rt/2017.0.0/intel64/lib/release -Xlinker -rpath -Xlinker /opt/intel/mpi-rt/2017.0.0/intel64/lib -lmpifort -lmpi -ldl -lrt -lpthread    -lcomex -lmpifort -lmpi -ldl -lrt -lpthread -lmkl_intel_ilp64 -lmkl_intel_thread -lmkl_core -liomp5 -lpthread -lm -ldl -lrt -lpthread -lpthread  -lnwcutil     
/usr/nic/src/apps/nwchem/nwchem/lib/LINUX64/libnwpython.a(task_python.o): In function `task_python_':
/lstr/applications/atom/src/apps/nwchem/nwchem/src/python/task_python.c:29: undefined reference to `Py_SetProgramName'
/lstr/applications/atom/src/apps/nwchem/nwchem/src/python/task_python.c:30: undefined reference to `Py_Initialize'
/lstr/applications/atom/src/apps/nwchem/nwchem/src/python/task_python.c:32: undefined reference to `PyRun_SimpleStringFlags'

PS2: Install steps:
. /usr/nic/compiler/intel/19.1/mkl/bin/mklvars.sh intel64 
. /usr/nic/compiler/intel/19.1/impi/2019.1.144/intel64/bin/mpivars.sh
export NWCHEM_TOP=/usr/nic/src/apps/nwchem/nwchem
export NWCHEM_MODULES="all python"
export NWCHEM_TARGET=LINUX64
export NWCHEM_LONG_PATHS=y
export USE_NOFSCHECK=y
export TCGRSH=/usr/bin/ssh
export LARGE_FILES=y
export PYTHONHOME=/usr/nic/apps/python_da/2.7.15
export PYTHONVERSION=2.7
export PYTHONLIBTYPE=so
export USE_PYTHON64=y
export USE_PYTHONCONFIG=Y 
export USE_MPI=y
export USE_MPIF=y
export USE_MPIF4=y
export MPI_LOC="/usr/nic/compiler/intel/19.1/impi/2019.1.144/intel64"
export MPI_INCLUDE="/usr/nic/compiler/intel/19.1/impi/2019.1.144/intel64/include"
export MPI_LIB="/usr/nic/compiler/intel/19.1/impi/2019.1.144/intel64/lib/release_mt -L/usr/nic/compiler/intel/19.1/impi/2019.1.144/intel64/lib"
export LIBMPI="-I/usr/nic/compiler/intel/19.1//compilers_and_libraries_2019.1.144/linux/mpi/intel64/include -I/usr/nic/compiler/intel/19.1//compilers_and_libraries_2019.1.144/linux/mpi/intel64/include -L/usr/nic/compiler/intel/19.1//compilers_and_libraries_2019.1.144/linux/mpi/intel64/lib/release -L/usr/nic/compiler/intel/19.1//compilers_and_libraries_2019.1.144/linux/mpi/intel64/lib -Xlinker --enable-new-dtags -Xlinker -rpath -Xlinker /usr/nic/compiler/intel/19.1//compilers_and_libraries_2019.1.144/linux/mpi/intel64/lib/release -Xlinker -rpath -Xlinker /usr/nic/compiler/intel/19.1//compilers_and_libraries_2019.1.144/linux/mpi/intel64/lib -Xlinker -rpath -Xlinker /opt/intel/mpi-rt/2017.0.0/intel64/lib/release -Xlinker -rpath -Xlinker /opt/intel/mpi-rt/2017.0.0/intel64/lib -lmpifort -lmpi -ldl -lrt -lpthread"
export USE_OPENMP=y
export MKLROOT=/usr/nic/compiler/intel/19.1/mkl
export MKLLIB="${MKLROOT}/lib/intel64"
export MKLINC="${MKLROOT}/include"
export HAS_BLAS=y
export BLAS_SIZE=8
export BLASOPT="-L${MKLROOT}/lib/intel64 -lmkl_intel_ilp64 -lmkl_intel_thread -lmkl_core -L/usr/nic/compiler/intel/19.1/lib/intel64 -liomp5 -lpthread -lm -ldl"
export LAPACK_SIZE=8
export LAPACK_LIB="$BLASOPT"
export LAPACK_LIBS="$BLASOPT"
export LAPACKOPT="$BLASOPT"
export USE_SCALAPACK=y
export SCALAPACK_SIZE=8
export SCALAPACK="-L${MKLROOT}/lib/intel64 -lmkl_scalapack_ilp64 -lmkl_intel_ilp64 -lmkl_intel_thread -lmkl_core -lmkl_blacs_intelmpi_ilp64 -L/usr/nic/compiler/intel/19.1/lib/intel64 -liomp5 -lpthread -lm -ldl"
export SCALAPACK_LIB="$SCALAPACK"
export SCALAPACK_LIBS="$SCALAPACK"
export CC=icc
export FC=ifort
export USE_64TO32=y
cd $NWCHEM_TOP/src
make realclean
make nwchem_config
make 64_to_32
make CC=icc FC=ifort FOPTIMIZE=-O3

**Comment by hjjvandam** [comment]
Hi,
To me it seems that the build fails to link the Python library, and that is why you get an undefined reference. When I look at your link line I don’t see a Python library appearing there either. I am not sure why the build is not linking against Python though.
Best wishes,
Huub

-----------------------------------------------------------------------------------------------------
Hubertus van Dam, 631-344-6020, hvandam@bnl.gov
Brookhaven National Laboratory

**Comment by edoapra** [comment]
@hpjeonGIT 
What is the output of the following commands on the system you are using for installing NWChem
```
python-config --ldflags
/usr/nic/apps/python_da/2.7.15/bin/python-config --ldflags
```

**Comment by hpjeonGIT** [comment]
Hi hjjvandam and edoapra.
Thanks for the comments. python-config --ldflags didn't show the library of the installed python, and I hard-coded the -L__install_path__ into the python-config script. I just confirmed that nwchem 6.8.1 has been compiled successfully. Thank you again.
