### ISSUE TITLE
dft-3d URL update

### ISSUE THREAD

**Issue by kluophysics** [nwchemgit/nwchem#962]
The URL1 defined in build_dftd3a.sh URL1="https://www.chemiebn.uni-bonn.de/pctc/mulliken-center/software/dft-d3/" seems not to be valid. It fails to download dftd3.tgz tarball file.

Instead, the updated URL "https://www.chemie.uni-bonn.de/grimme/de/software/dft-d3/" is tested to work fine.

Maybe the URL should be updated?

**Comment by edoapra** [comment]
@kluophysics Could you please post the NWChem version you have been using?
Thanks

**Comment by edoapra** [comment]
fix committed
