### ISSUE TITLE
use of fortran90 intrinsic PRESENT in CCSD module

### ISSUE THREAD

**Issue by edoapra** [nwchemgit/nwchem#97]
We have introduced the use of Fortran90 intrinsic PRESENT  and of Fortran90 optional argument attribute since commit 73c244df87d61085b130a31d48d4a6012104cdce for OpenMP code in the CCSD module

Unfortunately, this seems to require the introduction of the Fortran90 subroutine interface on gfortran and xlf.
A simple  reproducer test shows that without a Fortran90 subroutine interface only Intel ifort works correctly.
gfortran has  always PRESENT() returning .true., while xlf  has  always PRESENT() returning .false.

**Comment by jeffhammond** [comment]
Ugh.  Sorry about that.  I should have tested better, but I assumed that everybody supported Fortran 90 properly now.

I only uses present to prevent segfaults if somebody uses the old signature that doesn't have that argument.  If we verify that all uses are correct for the new interface, `PRESENT` isn't required.

**Comment by edoapra** [comment]
@jeffhammond no problem about it. The issue is that the presence of Fortran90 subroutine interface in the caller is only checked when caller and callee are in the same file. In other words, if we would have had caller and callee in the same file, xlf and gfortran would have returned a compilation error.
I am introducing the subroutine interfaces

**Comment by edoapra** [comment]
Fix https://github.com/nwchemgit/nwchem/commit/f9a3235f286e0050dfebd4fbf2f876ed151e6c22 validated on Intel Ifort and IBM XLF
