### ISSUE TITLE
Discrepancy between Energy difference in TDDFT calculations?

### ISSUE THREAD

**Issue by koroki** [nwchemgit/nwchem#973]
I comment that on the forum, but I feel this is a bug or I misunderstood something. 

In TDDFT calculation, nwchem writes the information of the different states in a compact table where appears, between others, the energy difference. I understand that this value is the excitation energy between the ground state and the calculated excited state (an energy difference). 
However, when you put the option "print medium", a part of the compact table, more detailed information of each state is written in the output. In this section appears other value for excitation energy. It is not super different, but usually differs in 0.2~0.5eV and I clearly do not know with is the pattern or the reason of this difference. 

Anyway, the value that nwchem uses for QMD or for the final value is the second one and not the first one.

**Comment by edoapra** [comment]
This sounds more like a misunderstanding of the simulation methods to me.
https://groups.google.com/g/nwchem-forum/c/aCh8jppUrTw

**Comment by koroki** [comment]
Thanks for the information.
